### ISSUE TITLE
Segos.es

### ISSUE THREAD

**Issue by kashkash18** [mbebe/blomqvist#10]
Rzucisz okiem co tam się porobiło ?? Wtyczka nie odpala

**Comment by meserak86** [comment]
potwierdzam... fanfilms egos wlogowywanie niedziala, ani wtyczka z repo phantom ani z teog repo nie trybi

**Comment by mbebe** [comment]
logowanie za cloudflare. poprawka poszla.

**Comment by kashkash18** [comment]
Działa , a możesz jeszcze pomyśleć nad okładkami bo się nie wyświetlają

**Comment by kendo999** [comment]
okładki dobrze  jak by  były
