### ISSUE TITLE
Hejo Tv Alltube

### ISSUE THREAD

**Issue by Maro1982** [mbebe/blomqvist#100]
Dzien dobry czy jest jakis problem z hejo tv I alltube nagle przestaly dzialac

**Comment by kashkash18** [comment]
Poszła aktualizacja w repo mbebe do Hejo i Alltube

**Comment by Maro1982** [comment]
Dziekuje za wiadomosc.Sprawdze wieczorem

**Comment by wisiann** [comment]
w usa alltube dalej nie halo,
nic nie ma w zakladkach :(

**Comment by Maro1982** [comment]
W Dublinie tak samo zaktualizowalo sie do 2.5.9 I zero zaplace know hejo tv orzylo
Ciekawe co z wizja tv od kodivera

**Comment by kashkash18** [comment]
Wysypało się proxy

**Comment by Maro1982** [comment]
Czy komus juz dziala alltube?

**Comment by wisiann** [comment]
bez zmnian ,
trzeba poczekac na mbebe ,

**Comment by Maro1982** [comment]
Wisian moze po 10$ podarujemy do mbebe bedziemy mieli “personalny”support👍

**Comment by Maro1982** [comment]
Ciekawi mnie co z wizja tv sie stalo

**Comment by wisiann** [comment]
#39 issue

**Comment by Maro1982** [comment]
na hejo tv czasami lekko tnie programy ale poki co dziala,informujcie jak alltube ruszy 
dziekuje za pomoc

**Comment by Maro1982** [comment]
Hejo padlo znowu

**Comment by Maro1982** [comment]
Co sie moze dziac ktos cos?nie ma alltube I hejo tv znowu padlo

**Comment by notoco** [comment]
Zmiany na stronie. Cloudflare ma aktualizacje. Pisanie co godzinę nie naprawi problemu

**Comment by Maro1982** [comment]
Witam was przepraszam za posty moja corka dorwala sie do laptopa....Przez te wtyczki mamy jedyny dostep do PL tv
dziekuje za pomoc i wyrozumialosc.Bede grzecznie czekac na aktualizacje wtyczek

**Comment by mbebe** [comment]
sprawdzcie te wersje za granica.
[plugin.video.alltube.tv-2.6.zip](https://github.com/mbebe/blomqvist/files/2997150/plugin.video.alltube.tv-2.6.zip)

**Comment by Maro1982** [comment]
Dzieki sprawdze po pracy I dam znac

**Comment by Huero23** [comment]
HejoTv jescze nie działa.

**Comment by Maro1982** [comment]
U mnie dziala zobaczymy jak dlugo

**Comment by Maro1982** [comment]
Dzwonilem do domu I hejo chodzi alltube sprawdze jak z pracy wroce

**Comment by FXcodi** [comment]
W alltube.pl 2.6 pusto w folderze "filmy nowe" reszta działa poprawnie

**Comment by mbebe** [comment]
dobra, poszla poprawka w repo na wersje 2.6.1.

**Comment by FXcodi** [comment]
Dzięki:), a można prosić o poprawkę do ekino.tv bo tam też blokuje chmura.

**Comment by kashkash18** [comment]
@FXcodi łap :)
[plugin.video.ekinotv-2.3.zip](https://github.com/mbebe/blomqvist/files/2998301/plugin.video.ekinotv-2.3.zip)

**Comment by wisiann** [comment]
@mbebe ..dzieki!!

wszysko bangla ..ale ulga... bez alltube i nasze kino.. za wielka woda troche jest ubogo!

**Comment by wisiann** [comment]
@kashkash18.....👌👍

**Comment by Maro1982** [comment]
Dublin dziala teraz sprawdzilem wizja tv tez wrocila zresetowalem modem box I Cale kodi na nowo powgrywalem zipy jest ok

**Comment by Maro1982** [comment]
mbebe sprawdz paypal
dziekuje za pomoc
Wisian wyskocz z dychy dla Tomka;)

**Comment by wisiann** [comment]
@Mario1982,
chyba jestes tu nowy albo zmnieniles nika,
zwolij troche bo sie przegrzejesz jak kurczak w piekarniku ;)

**Comment by Huero23** [comment]
Czy działa wam już HejkoTv u mine nie (Wersja 1.9.5)

**Comment by kashkash18** [comment]
Działa w wersji 1.9.6

**Comment by kashkash18** [comment]
Na obecną chwilę jest problem z zalogowaniem się na stronę
![1](https://user-images.githubusercontent.com/22107339/54858493-4b98ef80-4d05-11e9-9f4c-c26ff9cd8f88.jpg)

**Comment by Huero23** [comment]
@kaskash18 Mam Cherry TV weszłem do mbebe repo i dalej do HajoTv nie widzę nigdzie 1.9.6 tylko jest jedna opcje 1.9.5...

**Comment by kashkash18** [comment]
No to z Cherry Ci nie pomogę bo nie używam.

**Comment by wisiann** [comment]
@huero23,
sciagnij recznie,
reopo porzebuje czasu na update,

**Comment by Huero23** [comment]
@kashkash18 Ja też miałem problem zalogowaniem wczoraj ale dzisiaj sprawdziłem i byłem zalogowany u mnie wszytko gra z HajoTv. U Ciebie już ok ?

**Comment by kashkash18** [comment]
Dziś wszystko jest ok , hejo miało wczoraj problemy. Przed zgłoszeniem problemu z wtyczka zawsze warto sprawdzić na stronie czy wszystko działa poprawnie.

**Comment by FXcodi** [comment]
Działa u was stream rapidvideo na alltube?
Resolveurl 5.0.27 od mbebe.
U mnie niestety nie działa.

**Comment by mbebe** [comment]
ktos juz zglosil do jsergio - https://github.com/jsergio123/script.module.resolveurl/issues/98
Moze bedzie niedlugo poprawka.

**Comment by FXcodi** [comment]
Serwis Virpe.com został zatakowany przez cloudflare i nie działa w wersji 1.1

**Comment by xxcriticxx** [comment]
@FXcodi virpe sie szatana a virpe.com zacznie dzialac

**Comment by Maro1982** [comment]
Czy hejo znowu na problem?
