### ISSUE TITLE
Sport Premium

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#1018]
Dzień dobry mam taki problem:
przy uruchamianiu się kodi 19.4 win7 oraz anroid(tv) wyskakuje błąd wtyczki(1.7), co dziwne loguje poprawnie natomiast przy włączeniu "na żywo" ponownie wyskakuje błąd wtyczki. Czy dało by się to naprawić? Poniżej log:
https://paste.kodi.tv/icacufuqom
Z góry dziękuję i pozdrawiam
Okazało się że więcej wtyczek tak się zachowuje wyskakuje błąd wtyczki: canalplusVOD(ciągle błąd), cda(loguje i odtwarza prawidłowo), może mopogą nowe logi:
https://paste.kodi.tv/opayurojuj
Pozdrawiam

**Comment by mtr81** [comment]
Co do niedziałających kanałów live należy w liniach 408-411, 419-422 i 605-608 zrobić podmianę identów kolejno na: 1457744, 1457734, 1457736, 1457740

**Comment by mbebe** [comment]
cos tam poaktualizowalem.

**Comment by notoco** [comment]
Super. Dzięki

**Comment by rafalmar1981** [comment]
Dziękuję bardzo za waszą pomoc
