### ISSUE TITLE
segos  - dodaj do zobaczenia:

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#102]
Na stronie segos.es mamy fajną opcję - oznaczoną plusikiem - "Dodaj do zobaczenia" - czy jest możliwość dodania jej w opcji menu podręcznego dla danego filmu we wtyczce?
![obraz](https://user-images.githubusercontent.com/36659110/55058398-26411400-506c-11e9-881a-cd55377efa82.png)

Przykładowy odnośnik: http://segos.es/?page=filmy&acction=view&id=3673&needtosee=true
Dla filmu http://segos.es/?page=filmy&acction=view&id=3673
W połączeniu z opcją dla zalogowanych użytkowników gdzie pojawia im się lista filmów ulubionych po kliknięciu w nazwę usera byłoby to fajne..
Można by też rozważyć od razu opcję usunięcia z "Do obejrzenia" - ale tam już formularzyk wchodzi

**Comment by mbebe** [comment]
Nie moglem znalezc ULUBIONYCH filmow.
Sparwdz te wersje.
Dodano dodawanie do "Do obejrzenia" i usuwanie z niego. Prawy klawisz na filmie lub serialu.

[plugin.video.segos-4.0.4.zip](https://github.com/mbebe/blomqvist/files/3013570/plugin.video.segos-4.0.4.zip)

**Comment by notoco** [comment]
Jako zalogowany użytkownik kliknij w nazwę użytkownika. Przejdziesz do ulubionych/do zobaczenia. W chacie sprawdzę

**Comment by notoco** [comment]
Działa.

**Comment by notoco** [comment]
Tylko taka moja mała sugestia - z komunikatu wywal kolor gold - pozwól żeby to skórka użytkownika określała takie rzeczy.

**Comment by notoco** [comment]
I tak ma być. Jest git.
