### ISSUE TITLE
canalplusvod

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#1020]
Chłopaki z góry przepraszam za kłopot, pojawił się problem z wtyczką jak w temacie. Wyskakuje komunikat przy instalacji  "nieudana instalacja". Log:
https://paste.kodi.tv/ujavukuwav
Sorki jeszcze raz za takie kłopoty.
Pozdrawiam.

**Comment by kopernik1983** [comment]
Z pustego to i Salomon nie naleje Musisz poprosić @mbebe żeby literówkę poprawił w nazwie paczki :P "," - "."
![Screenshot_340](https://github.com/mbebe/blomqvist/assets/33724908/b4327de4-b478-4ac0-abfb-086cddebdeb7)

**Comment by rafalmar1981** [comment]
@kopernik1983  faktycznie instaluje się ale qrcze wywala błąd "niepoprawne dane logowania" :(
taki to log:
https://paste.kodi.tv/jisozafiyi
A już się z "gąską" witałem. Pozdrawiam

**Comment by kopernik1983** [comment]
https://github.com/mbebe/blomqvist/issues/1006#issuecomment-1777854057

**Comment by rafalmar1981** [comment]
O to już magia totalna dla mnie, masakra nie dam rady
