### ISSUE TITLE
Tele Latino HD not working 

### ISSUE THREAD

**Issue by amexpak1** [mbebe/blomqvist#1021]
Hi thanks for all you do. Just wanted to report the add on Tele latino HD is no longer working all channels and links say error. If you could take a look at it when you have a chance thank you very much Happy Holidays.

**Comment by mbebe** [comment]
I can't see any problems with links.
Please show me any errors from log file.

**Comment by amexpak1** [comment]
Actually just checked it again today everything is working fine thank you very much appreciate it.

**Comment by amexpak1** [comment]
Happy Holidays and have a happy New Year!!
