### ISSUE TITLE
virpecom

### ISSUE THREAD

**Issue by oliwer12345** [mbebe/blomqvist#103]
PYTANKO CZY WTYCZKA VIRPECOM DZIALA U WAS

**Comment by FXcodi** [comment]
Trzeba czekać na poprawkę do cloudflare.

**Comment by kashkash18** [comment]
Poszła poprawka wczoraj w nocy , wymuś wyszukiwanie aktualizacji bądź zainstaluj ZIP w wersji 1.2

**Comment by FXcodi** [comment]
Wszystko już gra.
:D

**Comment by wisiann** [comment]
u mnie dalej nie dziala ?
mimo 1.2

**Comment by krotki1** [comment]
U mnie też nie lata

**Comment by wisiann** [comment]
@mbebe,
myslisz ,ze cos sie da z tym zrobic, 
czy to juz martwa sprawa?

**Comment by FXcodi** [comment]
Zaktualizowana wersja do 1.3 też nie działa.

**Comment by kashkash18** [comment]
Zanim zaczniesz pisać że wtyczka nie działa to sprawdź stronę
![](https://i.imgur.com/HDW61GH.png)

**Comment by FXcodi** [comment]
Dzięki:)
Czyli serwis został wyłączony. 
Szkoda!

**Comment by wisiann** [comment]
to kiszka ,fajna byla!

**Comment by kashkash18** [comment]
Serwer wstał więc wtyczka też wróciła do żywych :)

**Comment by wisiann** [comment]
hhmmm?

u mnie dalej pusto w zakladkach?

**Comment by krotki1** [comment]
U mnie też pusto w zakładkach

**Comment by kashkash18** [comment]
Przeglądnięcie wszystkie zakładki i wskoczy

**Comment by krotki1** [comment]
Faktycznie, lata ....

**Comment by wisiann** [comment]
Ale numer!!!
dzieki @kashkash18!   :)

**Comment by kashkash18** [comment]
Trzeba to poprawić przy kolejnej aktualizacji , ale na chwilę obecną taki sposób działa. 
Nie wiem tylko czy po restarcie Kodi znów trzeba przeglądać zakładki czy gada od kopa.

**Comment by wisiann** [comment]
mbebe jeszcze za darmo do wtyczki lamiglowke dorzuca haha !!;)

**Comment by wisiann** [comment]
od kopa

**Comment by wisiann** [comment]
jak jeszcze mozna by bylo okladki dodac, to by fajne bylo....ale sie rozmarzylem ;)

**Comment by FXcodi** [comment]
Virpe.com znowu przestał działać.

**Comment by Bogdan16** [comment]
Witam

Na VirpeCom wyskakoje blad 

Pozdrawiam
