### ISSUE TITLE
CDA.pl + CDA TV

### ISSUE THREAD

**Issue by aprof28** [mbebe/blomqvist#1034]
Witam . Czy można by było do tego dodatku dodać kreatora listy m3u żeby dodać kanały do IPTV Simple Client ? Z góry dziękuję i pozdrawiam mbebe i mtr81 .

**Comment by mtr81** [comment]
Jest taka wersja na forum KWP.

**Comment by aprof28** [comment]
No nic muszę odpuścić. Trzeba się logować . Ok mimo wszystko dzięki.

**Comment by mtr81** [comment]
Generator list M3U zestawia tylko linki pozwalające uruchomić odtwarzanie kanału we wtyczce. Usługa telewizyjna w CDA jest płatna i stąd wymóg logowania.

**Comment by mtr81** [comment]
Dla porządku wrzucam wersję wtyczki bazującą na v1.11 z możliwością wygenerowania listy M3U kanałów TV
[plugin.video.cdaplMB-1.12.zip](https://github.com/mbebe/blomqvist/files/14196841/plugin.video.cdaplMB-1.12.zip)

**Comment by aprof28** [comment]
Serdeczne dzięki;-) Pozdrawiam.

**Comment by aprof28** [comment]
Dziękuję ;-) 
  Dnia 20 lutego 2024 14:18 mtr81   napisał(a):  
 Fix  
 github.com plugin.video.cdaplMB-1.13.zip

**Comment by mtr81** [comment]
[plugin.video.cdaplMB-1.14.zip](https://github.com/user-attachments/files/15592479/plugin.video.cdaplMB-1.14.zip)
