### ISSUE TITLE
Bug: Missing English Language. Polish Only?

### ISSUE THREAD

**Issue by neo-neo1** [mbebe/blomqvist#1035]
Firstly thank you very much for creating a Kick Addon for Kodi, I love it. And use it.

However, I noticed it's only in Polish.
Is it possible to make it in English? Would be much better for everyone.

Thanks for understanding and thanks again for creating this Addon

**Comment by mbebe** [comment]
Yes, that was only in polish, and probably only polish streams were available.

New version - 1.1 is in my repo.
Right now you can change language in addon, and all streams in this language will be available.
All strings in addon will be english or polish.

**Comment by neo-neo1** [comment]
Perfect, thanks for the update.
