### ISSUE TITLE
Segos i hejo padło - again...

### ISSUE THREAD

**Issue by RobinsonPL** [mbebe/blomqvist#104]
Hejo błąd całkowity, Segos nie loguje...truje bo mam tam premium i nie mogę nic obejrzeć :)

PS. Dlaczego to tak często nawala? Kiedyś hulało bez problemów...

**Comment by wisiann** [comment]
nie loguje na stronie?

**Comment by notoco** [comment]
Pewnie cloudflare wywala. Każda zmiana na stronie powoduje zmianę działania wtyczki. A raczej jego brak

**Comment by mbebe** [comment]
Sprawdzcie segosa, czy dziala z ta wersja cloudflare.
[plugin.video.segos-4.0.6.zip](https://github.com/mbebe/blomqvist/files/3027121/plugin.video.segos-4.0.6.zip)

**Comment by kashkash18** [comment]
Działa :)

**Comment by notoco** [comment]
Działa - nie za pierwszym razem ruszyła, kazała mi się przelogować, ale poszło.
