### ISSUE TITLE
Cda.pl

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#1041]
Witam jest jakiś problem z wtyczką;
tu podaję ligi może coś po może:
https://paste.kodi.tv/etutacinob
Pozdrawiam i proszę o pomoc.

**Comment by rafalmar1981** [comment]
@mtr81 Dziękuję za informację...trochę mnie nie było(szpital) ....fajnie działa....dzięki za szybką odpowiedź. Pozdrawiam

**Comment by mbebe** [comment]
@mtr81 - wyszla juz jakas poprawna wersja IA, by moc odtworzyc streamy megogo, bo widzialem, ze dawales tam issue z tym zwiazany?

**Comment by mtr81** [comment]
Problem dotyczy tylko niektórych manifestów MPD. Postęp jest taki, że odtwarzanie się zaczyna, ale wyłącza się po 16 sekundach, czyli moim zdaniem tam dalej jest coś nie halo.

**Comment by mbebe** [comment]
No, bo mam premium w megogo i nie odtwarza kanalow z wyzszych pakietow.

**Comment by mbebe** [comment]
Mam tez logowanie zrobione, ale jak nie idzie dalej to lipa. 
Sprawdzalem ma KODI21 i idzie tylko nascie sekund. Jak cos, to wyslalem ci maila, o ile to byl twoj mail. ;-)
