### ISSUE TITLE
fili.cc błąd logowania

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#106]

**Comment by rafalmar1981** [comment]
jak w temacie od dwóch dni jest problem z zalogowaniem, czy da się to naprawić

**Comment by rafalmar1981** [comment]
na stronie fili.cc logować się można tylko w kodi we wtyczce wyskakuje błąd logowania

**Comment by rafalmar1981** [comment]
kashkash18 witaj da się coś zrobić z logowaniem na fili.cc, nie da się zalogować, wyskakuje błąd logowania od dwóch dni

**Comment by mbebe** [comment]
Proponuje tak z 6-7 razy dziennie ponawiac pytanie. :-)
Sprawdz te wersje.
[plugin.video.filisertv-2.9.1.zip](https://github.com/mbebe/blomqvist/files/3027053/plugin.video.filisertv-2.9.1.zip)

**Comment by kashkash18** [comment]
Jest Git :) można zaktualizować w repo . Dzięki wielkie :)

**Comment by kashkash18** [comment]
@rafalmar1981 nie jestem programista więc ciężko cokolwiek mi z tym zrobić.
Zgłoś problem i czekaj spokojnie aż mbebe dokona korekty w kodzie. 
Pamiętaj że nie wszystko kręci się wokół wtyczek. Mamy pracę , rodziny i inne zainteresowania . Teraz robi się ciepło więc aktualizację będą zdecydowanie rzadziej. 
Ale jak tylko czas i możliwości pozwolą to błędy będą naprawiane :)
Mbebe nie jest robotem , chyba :D 
Zgłoś i czekaj , a jak znajdzie się czas to i aktualizacja wskoczy. 
Pozdrawiam

**Comment by wisiann** [comment]
no niewiem niewiem z tym robotem ;)

**Comment by rafalmar1981** [comment]
mbebe przepraszam membe nie pomyślałem, jeżeli będzie podobna sytuacja to tak zrobię. Sorki wielkie pozdrawiam wszystkich.

**Comment by rafalmar1981** [comment]
niestety wersja plugin.video.filisertv-2.9.1.zip nie działa, nadal błąd logowania

**Comment by mbebe** [comment]
Sprawdz z repo wersje2.9.2

**Comment by rafalmar1981** [comment]
mbebe miodzio elegancko lata mam pytanie czy na alltube jak wyszukuję np gra o tron i wchodzę w zakładkę serialu jest pusto dlaczego?

**Comment by kunraf** [comment]
gdzie znajdę wersję 2.9.2?

**Comment by notoco** [comment]
Czy wy w ogóle czytacie? W repozytorium!

**Comment by kunraf** [comment]
nie ma głupich pytań, są tylko głupie odpowiedzi

**Comment by kunraf** [comment]
w repo nie ma wersji 2 9 2, jest  2 9

**Comment by kashkash18** [comment]
Wymuś wyszukiwanie aktualizacji a się pojawi

**Comment by kunraf** [comment]
a jak to się robi

**Comment by kunraf** [comment]
aktualizacje mam na instaluj automatycznie

**Comment by kashkash18** [comment]
Kodi aktualizację sprawdza raz na 24 godziny.

**Comment by kunraf** [comment]
instaluj automatycznie mam od zawsze

**Comment by notoco** [comment]
To poczekaj 24 h. Musi się zaciągnąć.

**Comment by kashkash18** [comment]
Dodatki -> menadżer dodatków -> opcje -> wyszukaj aktualizacje

**Comment by kunraf** [comment]
w men dodatkow mam tylko
moje dodatki
ostatnio zaktualizowane
zainstal z repo
zainst z zip
szukaj

**Comment by kashkash18** [comment]
Ehhh , na dole masz opcje i wysunie się z lewej strony pasek

**Comment by kunraf** [comment]
dzięki :-)

**Comment by kunraf** [comment]
witam, dziś fili.cc wyświetla przy próbie zalogowania błąd.
Chodzi natomiast bez logowania. Mam pytanie, czy bez zalogowania mamy te same filmy co po zalogowaniu na darmowe konto? Jeśli tak to jaka jest różnica?

**Comment by kunraf** [comment]
oczywiście wersja 2.9.2

**Comment by kashkash18** [comment]
Fili przy logowaniu dodało reCAPTCHA i będzie problem to obejść.
Tak , masz te same filmy . Konto premium po zalogowaniu daje dostęp do dodatkowych serwerów przy danym filmie.

**Comment by kunraf** [comment]
dzięki.
Mam w takim razie inne pytanie.
Czy jest szansa, żeby w przyszłości pojawiła się wtyczka w KODI do nc+ go

**Comment by kashkash18** [comment]
Szanse na taką wtyczkę są prawie zerowe.

**Comment by kunraf** [comment]
szkoda, mam hasło do aplikacji, ale w moim tv z androidem działa odwrócona ponieważ jest stworzona na telefon

**Comment by kashkash18** [comment]
Zainstaluj na TV tą aplikację
https://www.apkmirror.com/apk/eyes-free-project/set-orientation/set-orientation-1-1-4-release/set-orientation-1-1-4-android-apk-download/

https://www.youtube.com/watch?v=S_MKGg7fu5Y
