### ISSUE TITLE
 Possible Use of Aniwave for anime

### ISSUE THREAD

**Issue by mundedesu** [mbebe/blomqvist#1060]
I was looking at the anime one and it didnt have anything other than dragon ball. would it be possible to use aniwaveto since fmovieszto is similar to it? If so how would one go about doing this

**Comment by mbebe** [comment]
Aniwave is available in my repo.

**Comment by mundedesu** [comment]
> Aniwave is available in my repo.

There is an error when playing shows. I cant check the error log as i dont know how but it doesnt seem to open some animes to see the episode

**Comment by mbebe** [comment]
Which animes can't be open?

**Comment by mundedesu** [comment]
none of the jojo ones were opening

**Comment by mbebe** [comment]
Fixed nad updated. Should be good.
direct link >>> [aniwave](https://github.com/mbebe/blomqvist/raw/master/zips/plugin.video.aniwavemb/plugin.video.aniwavemb-1.1.zip)

**Comment by mundedesu** [comment]
Just wondering whether why settings arent used like if you were to click an episode instead of showing the sub dub links it just plays sub automatically and then you can select it from the little settings icon they give you. Wouldnt this make the autoplay kodi feature compatible with it?
