### ISSUE TITLE
Fmovies Servers down

### ISSUE THREAD

**Issue by asavitskii** [mbebe/blomqvist#1069]
After the fmovies domain was fixed, the servers haven’t been working at all, so clicking on any of them there’s an issue displayed. Could you please take a look at this? Thank you :)

**Comment by pitsi** [comment]
No issue here, I watched... 10 minutes of the boys s04e01 a few minutes ago and I tested both mycloud and vidplay.
Maybe the decryption keys needed an update so as to work. If so, that update happened yesterday, June 13th, at 6.58 pm (on gmt+3), which means the addon should work fine after that time.

**Comment by asavitskii** [comment]
Thanks for your reply. I’ve just checked and it works perfectly today :) Perhaps it was indeed an update thing! Have a nice one :)

**Comment by pitsi** [comment]
You are welcome. Please close the issue if you want :)
