### ISSUE TITLE
segos.es - czysty profil, nie działa + brak linków premium + brak wyboru linków

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#107]
Wtyczka segos na czystym profilu nie działa. Problemem jest brak pliku
```
 Error Contents: [Errno 2] No such file or directory: u'/home/tomasz/.kodi/userdata/addon_data/plugin.video.segos/segos.cookie'
                                            Traceback (most recent call last):
                                              File "/home/tomasz/.kodi/addons/plugin.video.segos/main.py", line 324, in <module>
                                                start()
                                              File "/home/tomasz/.kodi/addons/plugin.video.segos/main.py", line 243, in start
                                                logged =  segos.getLogin(u,p)
                                              File "/home/tomasz/.kodi/addons/plugin.video.segos/resources/lib/segos.py", line 70, in getLogin
                                                scraper.cookies.save()
                                              File "/usr/lib/python2.7/_LWPCookieJar.py", line 83, in save
                                                f = open(filename, "w")
                                            IOError: [Errno 2] No such file or directory: u'/home/tomasz/.kodi/userdata/addon_data/plugin.video.segos/segos.cookie'
                                            -->End of Python script error report<--
```
Utworzenie tego pliku powoduje że nie ma problemu i wtyczka działa. Bez tego nie chciała ruszyć.
Poza tym - nie widzi linków premium - te dla zalogowanych widzi - premium nie. I tak - mam premium (jeśli trzeba udostępnię). Na poprzedniej wersji widziało bez problemu linki premium ;(

**Comment by notoco** [comment]
I kolejna rzecz - pobiera tylko jeden link - przykład:
http://segos.es/?page=bajki&acction=view&id=1375&visited=yes
W kodi pokazuje 1 link, w segos jest ich więcej
![obraz](https://user-images.githubusercontent.com/36659110/55349223-6c0d3a80-54b9-11e9-9fd1-4017ef638e74.png)

Dla mnie największą zaletą segos jest duża ilość źródeł 5.1 dla użytkowników premium.. bez tego to tylko kolejna wtyczka

**Comment by notoco** [comment]
https://github.com/mbebe/blomqvist/issues/94#issuecomment-471907887 - czy to nie jest "naleciałość?"

**Comment by mbebe** [comment]
Podeslij premium na maila. Pozniej wieczorem zobacze.

**Comment by notoco** [comment]
A zarzuć mailem bo mi gdzieś zniknął...

**Comment by notoco** [comment]
Poszło.

**Comment by mbebe** [comment]
ok, sprawdz te wersje na czystym jak mozesz.
Do poprawki jeszcze w wyborze zrodel - oznaczenie dla kogo. To juz jutro. ;-)

[plugin.video.segos-4.0.7.zip](https://github.com/mbebe/blomqvist/files/3031619/plugin.video.segos-4.0.7.zip)

**Comment by notoco** [comment]
Na szybko sprawdzane, bo jak pisałeś to u nas już było jutro. Na nieczystym działa. Przydałoby się faktycznie oznaczenie czy linki premium czy dla zalogowanych.

**Comment by notoco** [comment]
na czystym kodi na win 10 działa już wszystko. Ciut szybciej niż 4.0.6 - brakuje tylko oznaczeń zalogowani/premium.
Ale jest git.

**Comment by notoco** [comment]
BTW - nie myślałeś o wrzuceniu zawartości zipów na githuba - łatwiej by było ewentualne poprawki nanosić?

**Comment by kashkash18** [comment]
Chodzi szybciej bo cf w wtyczce nie używa js2py.

**Comment by notoco** [comment]
Wiem, widziałem :) Mbebe to faktycznie chyba automat/robot - ogarnął to dość szybko...

**Comment by mbebe** [comment]
Tu poprawki o ktorych pisalem. ;-)
[plugin.video.segos-4.0.7.zip](https://github.com/mbebe/blomqvist/files/3033544/plugin.video.segos-4.0.7.zip)

**Comment by notoco** [comment]
Więc tak - nadinstalowane na poprzednią wersję - za pierwszym razem mnie nie zalogowało, dopiero za drugim (
Ale... ale działa!
Jeszcze gdyby tylko nie pytało o jakość cda - ale to już kwestia resolvera...

**Comment by kashkash18** [comment]
Akurat pytanie o jakość jest dobre dla "zalogowanych" . Dla mobilnego neta niższa jakość jest przydatna.

**Comment by kashkash18** [comment]
Działa ok , jedyne co to odwrócił bym wybór jakości od najwyższej do najniższej

**Comment by notoco** [comment]
Zerknąłem w kod - wybór wersji cda w tym miejscu: 
![screenshot001](https://user-images.githubusercontent.com/36659110/55399005-33697180-554a-11e9-8fc6-70f4ad3af14a.png)


siedzi w kodzie... a więc jest możliwość dodania opcji dla CDA - wybierz najlepszą jakość ;)
I wtedy by z automatu po wyborze źródła wybierał najlepszą jakość....

**Comment by kashkash18** [comment]
Odwrócona jakość 
cdapl.py
linia 64
srce = re.compile('href="(.*?)"', re.DOTALL).findall(qua[0][1])[::-1]

**Comment by notoco** [comment]
To zawsze coś - a automat z opcji?

**Comment by kashkash18** [comment]
Jeśli tylko da się to opanować przez "opcję" to jak najbardziej :)
Niższa jakość się przydaje przy słabszym necie bądź mobilu.
To nawet wybór jakości może być w opcja a domyślnie najlepsza

**Comment by notoco** [comment]
Dlatego cały czas mówię - jako opcję!
W domyślnych ustawieniach jest tak jak teraz - wyskakuje okienko po wyborze źródła cda z zapytaniem o jakość. A dla chętnych (po zaptaszeniu opcji "Wybieraj zawsze najlepszą jakość CDA") by się wczytywało od razu w maksymalnej - czyli wybor filmu, wybór źródła (cda,premium,zalogowani) i od razu play. Da się to ogarnąć za pomocą if/else - ale mam problem z wypluciem pojedynczego linku z getLinkCda

**Comment by mbebe** [comment]
[plugin.video.segos-4.0.7.zip](https://github.com/mbebe/blomqvist/files/3033973/plugin.video.segos-4.0.7.zip)
Cos jak to? ;-)

**Comment by kashkash18** [comment]
Jeśli chodzi o mnie to jest elegancko .
Wilk syty i owca cała ;)

**Comment by notoco** [comment]
Dzięki. Tak to sobie wyobrażałem. Wszystko działa. Jest super.

**Comment by kunraf** [comment]
czy ta aktualizacja pojawi się automatycznie?

**Comment by notoco** [comment]
Jak zostanie wrzucona do repozytorium, to tak. Na razie jest w fazie testów.

**Comment by notoco** [comment]
Eh - jak ja kocham tę wtyczkę...

**Comment by wisiann** [comment]
w zakladce seriale sa tylko dwie strony?
czy to tyle?
