### ISSUE TITLE
FMovies still broken?

### ISSUE THREAD

**Issue by mavijavi5124** [mbebe/blomqvist#1071]
is FMovies still broken

**Comment by pitsi** [comment]
No. Proof

![screenshot115](https://github.com/mbebe/blomqvist/assets/5880037/fad7e2bd-57ed-44c9-b62b-71395b7f4605)

**Comment by mavijavi5124** [comment]
> No. Proof
> 
> ![screenshot115](https://private-user-images.githubusercontent.com/5880037/339782289-fad7e2bd-57ed-44c9-b62b-71395b7f4605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTg0ODgsIm5iZiI6MTcxODQxODE4OCwicGF0aCI6Ii81ODgwMDM3LzMzOTc4MjI4OS1mYWQ3ZTJiZC01N2VkLTQ0YzktYjYyYi03MTM5NWI3ZjQ2MDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTVUMDIyMzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTgxOGM2ZTc4Njc1Mzk5Y2Y4NzlhMzc2MGEyN2VhMTZiMTZjZGQ2ODJjOTNkNDQzZmJhZWIwZTBlZTgyY2I2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nUdtp77US51XzElTL5PJUUCmlpAnpiPYrRZdTIUAlFI)

guess they fixed it. The addon was broken a few days due to FMovies changing domain from fmoviesz.to to fmovies24.to

**Comment by pitsi** [comment]
Since fmovies is the flagship addon of mbebe's repo and draws the most attention, I think someone should make a sticky issue with warnings etc every time it breaks, e.g. "June 5th: addon broken due to domain change", so that there will be less issue reports about it.
