### ISSUE TITLE
zeriun.cc

### ISSUE THREAD

**Issue by RagnarLodbrok1981** [mbebe/blomqvist#1073]
zeriun.cc tak wiem jest to zmiana nazwy strony z zerion.cc  na właśnie zeriun.cc czy da się to naprawić?
Pozdrawiam

**Comment by pawelbakstosia** [comment]
co w ogóle z polskimi wtyczkami

**Comment by pawelbakstosia** [comment]
§ pytam się jakieś repozytorium
