### ISSUE TITLE
plugin.video.iitv

### ISSUE THREAD

**Issue by RagnarLodbrok1981** [mbebe/blomqvist#1074]
Dzień dobry czy można prosić o aktualizację wtyczki plugin.video.iitv ?
Byłbym wdzięczny(poluję na serial Zabójcze umysły nowy sezon i qrczę nigdzie niema). Pozdrawiam

**Comment by NowyMuzyk** [comment]
Aktualizacja wtyczki zawsze mile widziana. A szukany serial od dawna jest "wszędzie", bo tak to działa. Zacznij od filman cc

**Comment by RagnarLodbrok1981** [comment]
@NowyMuzyk tak zrobiłem, filmany e-kino i tym podobne nie mają nowych odcinków tylko iitv i zeriun

**Comment by NowyMuzyk** [comment]
![Screenshot_2024-07-16_20-40-41](https://github.com/user-attachments/assets/6f61571a-fcd5-4c35-ac5e-b4d3d395e084)
A to co w takim razie jest? Podpowiem odc 1 najnowszego sezonu w filman cc, mam zamiar oglądać tylko czasu brakuje.

**Comment by NowyMuzyk** [comment]
![Screenshot_2024-07-16_21-12-25](https://github.com/user-attachments/assets/6cbd673e-c7ee-46df-9e3c-a1b7dafa3fad)
A tu ten sam w zerion cc (jak napisałem wcześniej- jest wszędzie) tylko z napisami (w sumie wolę napisy i tak). Twoje "nie znalezienie" go w filman wynika pewnie z tego, że tam jest pod innym (nowym) tytułem który jest od poprzedniego sezonu już.

**Comment by RagnarLodbrok1981** [comment]
@NowyMuzyk fakt sorensen jest tak jakpisałeś pod nowym tytułem.Dzięki
