### ISSUE TITLE
Alltube 2.6.2 - brak w repozytorium

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#109]
W repo masz aktualizację do 2.6.2 - ale brak pliku w xip/plugin.video.alltube

**Comment by mbebe** [comment]
pospieszylem sie. ale juz chyba powinno byc.  :-/

**Comment by wisiann** [comment]
@mbebe,

czy w serialach mozna zrobic zakladke , lista wszystkich seriali,
u mnie w usa jest tylko zakladka "seriale nowe" i nic  innego?

**Comment by mbebe** [comment]
Na stronie jest alfabetyczna lista seriali. Nie bedzie jednak okladek. Jestes za tym? ;-)

**Comment by mbebe** [comment]
tu jak cos lista seriali alfabetycznie.
[plugin.video.alltube.tv-2.6.3.zip](https://github.com/mbebe/blomqvist/files/3048739/plugin.video.alltube.tv-2.6.3.zip)

**Comment by wisiann** [comment]
super!!
bardzo mi to odpowiada,

wiele seriali tylko alltube posiada ,
Dziekuje @mbebe!!  :)
