### ISSUE TITLE
Wizja.Tv Premium Nie działa.

### ISSUE THREAD

**Issue by Huero23** [mbebe/blomqvist#110]
@mbebe Hi... Wizja.Tv padła ? Ja jescze miałem 4 miesiące PREMIUM... Masz moze jakieś nowe news na ten temat ? Dziękuję...

**Comment by notoco** [comment]
Padła strona. Mbebe nie ma tu nic do rzeczy...

**Comment by Huero23** [comment]
@notco Tak jusz wiem. Tylko chciałem sie dowiedzieć czy moze @mbebe wie co się stało i czy powróci wizja.tv

**Comment by xxcriticxx** [comment]
Nostradamus mijał wizje ze nie powróci
