### ISSUE TITLE
PasteBin - wersja z filmweb

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#111]
Jak w temacie - bo umknęło chyba to: https://github.com/mbebe/blomqvist/issues/40#issuecomment-480521353, więc podbiłem wersję, dodałem poprawki i śmiga:
[plugin.video.pastebinVID-1.8.zip](https://github.com/mbebe/blomqvist/files/3051332/plugin.video.pastebinVID-1.8.zip)
Wrzuć do repo - kto nie korzysta, nie zauważy. Kto korzysta, będzie wdzięczny.

**Comment by kashkash18** [comment]
Wrzuć jeszcze do zipa nowy fanart

**Comment by kashkash18** [comment]
Tutaj wersja 1.8 od @notoco  z nowym fanartem i wywalonymi plikami .pyo z filmweb
[plugin.video.pastebinVID-1.8.zip](https://github.com/mbebe/blomqvist/files/3051486/plugin.video.pastebinVID-1.8.zip)

**Comment by xxcriticxx** [comment]
to poczatek rewolucji

**Comment by kashkash18** [comment]
Rewolucja trwa ;)

**Comment by notoco** [comment]
A widzisz... Zostawiłem pyo

**Comment by notoco** [comment]
No.
