### ISSUE TITLE
Problem z tvp.vod.pl

### ISSUE THREAD

**Issue by Huero23** [mbebe/blomqvist#112]
@mbebe Log in teraz potrzebny?

**Comment by mbebe** [comment]
ale jaki jest problem?
sprobuj wtyczke - tvpabon 1.2

**Comment by Huero23** [comment]
@mbebe zrobiłem log in i teraz jest ok...TVPABON 1.2 zrobiłem download jak tylko ją zobaczyłem ale to jest premium prawda? Weszłam na seriale i nic nie działa...

**Comment by kashkash18** [comment]
Tak , trzeba mieć dostęp do strefy ABO w TVP

**Comment by mbebe** [comment]
@Huero23  w repo wersja 1.3 - poprawione by odtwarzalo darmowe materialy bez zalogowania.

**Comment by Huero23** [comment]
@mbebe nie wiem dlaczego ale dzisiaj nie widze wtyczki w repo 1.2 i 1.3 tylko 1.1 w CherryTv... Wczoraj byla 1.2 ?

**Comment by wisiann** [comment]
wymus update repozytorium

**Comment by Huero23** [comment]
@mbebe Dobra mam 1.3. Potrzebny do niej VPN tak ? Nie mam servers wsobie jak tvp.vod.pl ? Ale widze nawet z VPN kręci sie kółeczko ale zaden serial nie wchodzi...

**Comment by kashkash18** [comment]
Problemem może być brak zainstalowanego Widevine

**Comment by Huero23** [comment]
@kashkash18 U Ciebie działa ta nowa wtyczka TVPABON 1.3 ?

**Comment by Huero23** [comment]
@kashkash18 U Ciebie działa ta nowa wtyczka TVPABON 1.3 ? Seriale tobie wchodzą?

**Comment by kashkash18** [comment]
Tak , działa wszystko . Trwają prace by puścić wszystko przez Proxy.

**Comment by Huero23** [comment]
@kashkash18 u mnie niestety nie działa. Wersja 1.3 kręci się kułeczko ale nic nie wczhodzi. Zrobiłem z log in i bez log in i VPN I bez VPN. Ale działa vod.pl.pl z proxy to jest ok. Chciałem mieć twie wtyczki wrazie jak jedna by nie działał.... Dziękuję za infromacie @KashKash18

**Comment by Huero23** [comment]
@mbebe zauważyłem ze na vod.tvp.pl jak używasz proxy link na serial jak wybierasz jakość to zaczęło nie wychodzić  wykopuje jak klikniesz bardzie trudno wejść niz poprzednią versją wtyczki...

**Comment by krecik71** [comment]
Witam 
U mnie na wer 1.3 działa co ma działać
podziękowania

**Comment by Huero23** [comment]
@kashkash18 @krecik71 Czy działa u was poprawnie tvp.vod.pl ? Dobrze działa Wiadomość, Teleexpress i Panorama? Bardzo zle mi chodzi cała wtyczka od nowej update...

**Comment by kashkash18** [comment]
U mnie obie wtyczki TVP chodzą dobrze

**Comment by Huero23** [comment]
Kashkash18 Kodi 18.1 ?

**Comment by kashkash18** [comment]
Tak
