### ISSUE TITLE
alltube nie wyświetla strumieni seriali

### ISSUE THREAD

**Issue by andhis2** [mbebe/blomqvist#113]
czy u mnie tylko nie wyświetla alltube strumieni seriali?

**Comment by wisiann** [comment]
cos jest nie tak, 

dosyc slabo z linkami,jakies 20% dziala,

**Comment by FXcodi** [comment]
Trzeba powrócić do wersji 2.6.2.
Tam działa wszystko, ale bez alfabetycznej listy seriali.

**Comment by FXcodi** [comment]
Folder "seriale nowe", nazwy seriali są, ale pusto do stream.

**Comment by mbebe** [comment]
odcinkow tez nie ma?
![fffffffff](https://user-images.githubusercontent.com/30195202/55820067-83bc7280-5afa-11e9-86e6-f19beb578baf.jpg)
tu np. z Dwoch i pol - s12e01

**Comment by FXcodi** [comment]
Odcinki są, ale brak hosta /streamu.

**Comment by mbebe** [comment]
w kazdym?

**Comment by FXcodi** [comment]
W każdym z folderu seriale nowe.
Z listy alfabetycznej seriale odtwarzają się wszystkie.

**Comment by mbebe** [comment]
tu tez poszla poprawka. ;-)
