### ISSUE TITLE
A może by tak...filmy321.pl

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#115]
jak była by ochota i zapotrzebowanie

**Comment by xxcriticxx** [comment]
zeby nie otwierac nowego tematu https://filmdom.fun/

**Comment by mbebe** [comment]
oba dodane do repo

**Comment by rafalmar1981** [comment]
ja pieroszcze aby nie przeklinać ale jaja wtyczka jest WOW i wielkie brawa
