### ISSUE TITLE
Fili.cc oraz ekinomaniak- brak kategorii

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#117]
Nie tyle że brak bo nie działają, ale brak bo we wtyczkach ich nie ma ;( Na stronie działają świetnie;
https://fili.cc/filmy?kat=animacja 
https://ekinomaniak.tv/watch-genres/Animacja

(nie działa segos.es więc grzebię...)

**Comment by mbebe** [comment]
Musze dodac wybor kategorii w tych 2 wtyczkach.

**Comment by notoco** [comment]
No.... musisz.... jak nic musisz... Właśnie dlatego napisałem ;)

**Comment by mbebe** [comment]
fili.cc zaktualizowane ;-)
ekinomaniak po meczach ;-)

**Comment by notoco** [comment]
człowieku - napij się piwa, odpocznij... Ja przecież żartowałem...

**Comment by mbebe** [comment]
daje poprawki gdy mam chwile czasu. :-)

**Comment by xxcriticxx** [comment]
mozna prosic o scraper fili.cc do fanfilma?

**Comment by rafalmar1981** [comment]
co to całe repo padło

**Comment by rafalmar1981** [comment]
mój błąd

**Comment by notoco** [comment]
W fili.cc - pokazuje się okno wyboru kategorii, ale po wybraniu nic się nie dzieje, przenosi do głównego okna wtyczki. W logach czysto.
