### ISSUE TITLE
filmwebbooster

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#120]
w pelni poprawiona wtyczka w repo. wersja 3.0
:-)

**Comment by kashkash18** [comment]
Bajka :)

**Comment by wisiann** [comment]
super!!

**Comment by sky0002** [comment]
Total szacun. Piękna robota. Nie mów, że udało Ci się rozkodować do końca remica :) ? A może jednak jest to Twoja robota od początku, bo stawiam, że mało co po tylu latach było by aktualne? Tak czy siak, naprawdę podziwiam!!!

**Comment by notoco** [comment]
Wielki jesteś!

**Comment by notoco** [comment]
Nie, no działa jak marzenie. Zacząłem używać FanFilmu tylko jedynie dlatego że ta wtyczka nie działała...
Zestaw Filmwebboster + segos + cda u mnie załatwia 80% potrzeb filmowych - reszta Netflix ;)
W sumie jakby dodać nie tylko http://www.filmdb.pl/ jako bazę wyszukiwania tylko dorzucić np moje ulubione segos... to było miodzio...

**Comment by notoco** [comment]
Zauważyłem że jeszcze w 2 plikach choinka lekka: main.py i __init__.py

**Comment by sky0002** [comment]
Notoco chodzi Ci o te 1111111....? Czy coś jeszcze ?

**Comment by notoco** [comment]
Yhm. Wtyczka jest czysta, ale te 1l1l....

**Comment by oliwer12345** [comment]
WITAM PANOWIE WTYCZKA SUPER TYLKO NIE WSZYSTKO OTWIERA PROBOWALEM NIE KTORE FILMY ORAZ SERIALE BRAK ZRODEL .ALE TAK OGOLNIE OK

**Comment by gzenio22** [comment]
Jeszcze tylko wsparcie dla serwisu trakt.tv i jestem w niebie :D

**Comment by notoco** [comment]
To co? Strajk? Ma być wsparcie trakt... I segos? Ma być. I 1000 zł

**Comment by gzenio22** [comment]
@notoco a czy ja to powiedziałem? przystopuj troche nie napisalem ze ta wtyczka jest zla czy ze mi sie nie podoba napisałem tylko ze jeszcze tylko trakt i bede w siodmym niebie nie napisalem MUSI byc trakt

**Comment by notoco** [comment]
Ej - żartowałem przecież :) Ja też widzę straszny potencjał w tej wtyczce - sam byłem jej pomysłodawcą u ramica przecież... Jak człowiek nie napisze ironia to wszyscy biorą słowo pisane na poważne...

**Comment by gzenio22** [comment]
@notoco To ja przepraszam czasem cieżko zrozumieć kontekst słowa pisanego zle odebrałem twoj post 

Szczerze? fajnie by było jak by ktoś stworzył wtyczke podobną do exsodusa nie mam nic do fanfilm ani jego tworcow ale wpienia mnie to ze skupiają sie na polskich zrudłach bo na polskich serwisach sa materiały w cienkiej jakosci majac TV 4K ogladanie materiau w okrojonej jakosci 720P ważący ok 1GB to jest porażka i bol oczu Xd 

Mam też pomysł wtyczki do napisów takiego kombajnu choc nie jestem programistą nie uważasz ze fajnie by było stworzyć kombajn z napisami? Połączyć serwisy typu napi projekt opensubtitles napisy24 i wiele innych serwisow z napisami w jedną dużą wtyczke? wtedy jak np w napisy24 nie bylo by napisow do danego materialu to bez koniecznosci zmiany wyszukiwarki były by napki z innego serwisu myśle że jakaś mądra głowa jak np @mbebe jest w stanie to po składać

**Comment by notoco** [comment]
Ale takich wtyczek jest multum. 13 clowns, seren... Dla angielskich źródeł wymiatają... A fanfilm... Cóż obawiam się że nie mamy aż tylu osób do roboty żeby go solidnie ruszyć. 
Ja się powoli przerzucam na segos z premium i filmwebboster. Czyli ten sam zestaw co za ramica miałem. Plus Phantom do CDA.

**Comment by gzenio22** [comment]
@notoco A co myslisz o tym pomysle z napisami? :P

**Comment by notoco** [comment]
Praktycznie nie używam napisów. Jeśli już, to w opensubtitles zawsze mi znajduje.
