### ISSUE TITLE
ŻYCZENIA ŚWIĄTECZNE

### ISSUE THREAD

**Issue by krecik71** [mbebe/blomqvist#122]
Dziś w dzień Wielkiej Nocy pragnę Wam złożyć życzenia
Smacznego jajeczka i kruchego ciasteczka!
Wesołego, rodzinnego świętowania i biesiadowania.
Pozdrowienia serdeczne - świąteczne!
Podziękowania za pracę!!!!!!

**Comment by sky0002** [comment]
A ja napiszę po świętach. Czemu nikt nie pociągnął życzeń. Wstydzicie się być katolami ? czy Polakami. Nie bardzo rozumiem. A może już inny świat inne wierzenia inne dogmaty, a gdzie czas świąt ? Ludzi naprawdę już tego nie czujecie ? Wesołego Alleluuja hehe nie dajcie się bo coś bo ktoś. I Z BOGIEM :)

**Comment by rysson** [comment]
To ja napiszę w Święta, wszak Oktawa Zmartwychwstania trwa :-D

Może po prostu mało jest wśród młodych (a tacy chyba tutaj przeważają) osób wierzących?
Ale masz rację, to nie powinno powstrzymywać nas choćby przed życzliwością.

Wszystkim zarówno głównemu motorowi polskich wtyczek, u którego gościmy, jak wszystkim testującym, zgłaszającym czy po prostu korzystającym życzę radości i szczęścia. Niech Zmartwychwstały Pan wszystkim błogosławi, nawet jak ktoś w niego nie wierzy. A może wtedy tym bardziej.

Alleluja!

**Comment by notoco** [comment]
To i ja powiem.
Jak dla mnie Github to nie miejsce od tego.... z tego co kojarzę to jest nawet lekko lewacki w poglądach ;)
Natomiast - pamiętamy w tych świętach o jajeczkach, ciasteczkach, świętowaniu, biesiadowaniu... a zapominamy o tym co jest istotą tego wszystkiego. Nadzieja na zbawienie jaką nam daje Chrystus. Że nawet przy wszystkich błędach, upadkach zawsze jest ta nadzieja jaką Chrystus dał Dobremu Łotrowi w ostatnich minutach jego życia.
Alleluja.... i do przodu!
