### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by Janasek** [mbebe/blomqvist#124]
czy jest jakaś mała szansa abyś dorzucił Artworka do swoich wtyczek 

clearart, clearlogo, characterart , te 2 pierwsze niby są w dodatkach ale nie ma atworka chyba powiązanego

**Comment by mbebe** [comment]
A co to ten artwork? :-D

**Comment by Janasek** [comment]
Loga dociąga lub tytuły w graficznej szacie

https://kodi.wiki/view/Artwork
https://kodi.wiki/view/Add-on:Artwork_Downloader

Widziałem w dodatkach ze są nazwy ale nie ma niczego co by to odpalalo 
u Anonka w fanfilm jest takie coś / chyba tylko w filmach Netflix tez to posiada ale tylko tytuly graficzne


<img src="https://i.ibb.co/2dRPrD5/2019-05-06-18h33-03.png"

**Comment by Janasek** [comment]
Loga dociąga lub tytuły w graficznej szacie

https://kodi.wiki/view/Artwork
https://kodi.wiki/view/Add-on:Artwork_Downloader

Widziałem w dodatkach ze są nazwy ale nie ma niczego co by to odpalalo
u Anonka w fanfilm jest takie coś / chyba tylko w filmach Netflix tez to posiada ale tylko tytuly graficzne

<img src="https://i.ibb.co/2dRPrD5/2019-05-06-18h33-03.png">
