### ISSUE TITLE
alltube tv

### ISSUE THREAD

**Issue by firetrap71** [mbebe/blomqvist#125]

**Comment by xxcriticxx** [comment]
![Capture](https://user-images.githubusercontent.com/15007183/57193409-b8102c80-6f08-11e9-94f1-e5062f5c758d.PNG)

**Comment by mbebe** [comment]
zaktualizowane w repo
@xxcriticxx  jakiegos bana masz :-/

**Comment by xxcriticxx** [comment]
@mbebe już puściło cf gryzie
