### ISSUE TITLE
szukajka.tv

### ISSUE THREAD

**Issue by newworks24** [mbebe/blomqvist#126]
Hej padła szukajka.tv przy wyszukiwaniu wyskakują błędy działania

**Comment by mbebe** [comment]
Jaki blad? Co np. wyszukujesz?

**Comment by newworks24** [comment]
wpisujesz obojetnie jakas nazwe filmu wyszukuje pozycje wybieram obojetnie którą - do uruchomienia i wyskakuje komuniukat błąd dodatku, więcej informacji w dzienniku wtyczki, nieudane otwarzanie jednej lub wiecej pozycji na wszystkim tak jest

**Comment by kashkash18** [comment]
U mnie w wersji 1.4.2 wszystko działa poprawnie.

**Comment by newworks24** [comment]
jakby coś wtyczka zainstalowana na kodi 17.4

**Comment by mbebe** [comment]
jakiego masz resolvera?
