### ISSUE TITLE
filmoteka.tv

### ISSUE THREAD

**Issue by xxcriticxx** [mbebe/blomqvist#127]
https://filmoteka.tv/film/leaving-neverland

strona wyglonda na fake zalozy ktos test konto 

ps reklamuje to alltube i szukajka

**Comment by mbebe** [comment]
Fake. Nie korzystac. :-)

Z treści udostępnianych w serwisie można korzystać po utworzeniu indywidualnego konta użytkownika. Korzystanie z serwisu jest odpłatne zgodnie z cennikiem serwisu.

**Comment by xxcriticxx** [comment]
alltube = szukajka = filmoteka
