### ISSUE TITLE
fili.cc

### ISSUE THREAD

**Issue by gzenio22** [mbebe/blomqvist#128]
Hej logowanie do fili nie hula wyskakuje błąd logowania a dane są poprawne

**Comment by mbebe** [comment]
wersja 2.9.5 loguje normalnie - sprawdzane na darmowym.

**Comment by gzenio22** [comment]
na premium nie wpuszcza

**Comment by mbebe** [comment]
nie mam zadnego konta premium :-/

**Comment by kashkash18** [comment]
U mnie wtyczka w wersji 2.9.5 loguje bez problemu zarówno do darmowych kont jak i premium.
