### ISSUE TITLE
TVP.VOD.PL problem. 

### ISSUE THREAD

**Issue by Huero23** [mbebe/blomqvist#129]
Hey... @mbebe Mam znowu problem wejściem na Wiadomość, Teleexpress i Panorama... Pokazuję Błędy. Czy to jest coś nie tak z mojej strony czy wtyczka ? 
![20190506_122500](https://user-images.githubusercontent.com/19337836/57341240-70e39080-70ee-11e9-9342-b6073e091e3a.jpg)

**Comment by mbebe** [comment]
Sprawdz na innym vpnie.
