### ISSUE TITLE
Segos - DO OBEJRZENIA więcej niż 12

### ISSUE THREAD

**Issue by zboina** [mbebe/blomqvist#130]
Witam!
To taka drobnostka i jeśli nie wymaga zbyt wiele pracy to poproszę o nią.
Czy można w zakładce pierwszej DO OBEJRZENIA włączyć paginator czyli możliwość wyświetlenie więcej filmów niż 12? To wydaje się fanaberia ale wrzucam tu filmy ciekawe i lista się powiększa a ja mam nadzieję że kiedyś je obejrzę :-) 
Pozdrawiam i gratuluję super repozytorium! :-)

**Comment by mbebe** [comment]
Poprawka w repo. wersja. 4.1.1

**Comment by zboina** [comment]
Bardzo dziękuję! 
Super że masz tyle zapału i cierpliwości ;-) do tworzenia wtyczek i robienia poprawek!
