### ISSUE TITLE
Błąd Hejo.tv

### ISSUE THREAD

**Issue by RobinsonPL** [mbebe/blomqvist#132]
Stronka działa, ale dodatek wywala błąd :)

**Comment by mbebe** [comment]
wtyczka zaktualizowana.

**Comment by Reddevil19** [comment]
Niby działa ale tylko na chwilę i wywala, da się coś zrobić?

**Comment by mbebe** [comment]
co niby dziala chwile? co i gdzie wywala?

**Comment by Reddevil19** [comment]
Witam, za każdym razem włączam jakiś program to chodzi pięknie jakieś 2 minutki i zatrzymuje sie obraz i wywala z powrotem na główne stronę z kanałami a jak chce włączyć jeszcze raz to pochodzi doslownie chwile zaczyna sie buforowac bardzo wolno  albo i chodzi parę sekund i z powrotem wywala na główną listę programów. Tak od kilku dni.

**Comment by RobinsonPL** [comment]
Może masz jakąś blokadę na Boxie, u dwóch moich znajomych na TX3 mini cieło filmy oraz telewizję po dłuższym użytkowaniu Boxa. U mnie tv chodzi normalnie, myślę że u Ciebie problemem może być box albo dostawca internetu (w Niemczech np niektórzy blokuja streamy). 
  Dnia 19 maja 2019 21:40 Reddevil19   napisał(a):  Witam, za każdym razem włączam jakiś program to chodzi pięknie jakieś 2 minutki i zatrzymuje sie obraz i wywala z powrotem na główne stronę z kanałami a jak chce włączyć jeszcze raz to pochodzi doslownie chwile zaczyna sie buforowac bardzo wolno  albo i chodzi parę sekund i z powrotem wywala na główną listę programów. Tak od kilku dni.

**Comment by Reddevil19** [comment]
No sam nie wiem, używam amazon fire stick w UK od dawna i nigdy czegoś takiego nie miałem, mam stick drugi na piętrze w domu i to samo się dzieje... do tej pory było ok tylko po tym jak zaktualizowałeś wytyczne tak się dzieje. Wyczyscilem nawet pamięć kodi i zainstalowałem jeszcze raz wczoraj ale bez zmian. Tak czy owak dzięki za odpowiedź a czy wtyczka Internetowa działa poprawnie ?

**Comment by RobinsonPL** [comment]
Mi działa, moim znajomym też, Gold Tv czasem tnie ale z Hejo nie miałem problemów, spróbuj ściągnąć jeśli masz WBMC (jest na androida) lub Vavoo, to bliźniacze aplikacje na których też zainstalujesz hejo, działają jak Kodi, zwlaszcza WBMC jest klonem Kodi, może nie będzie zacinać. 
  Dnia 19 maja 2019 23:01 Reddevil19   napisał(a):  No sam nie wiem, używam amazon fire stick w UK od dawna i nigdy czegoś takiego nie miałem, mam stick drugi na piętrze w domu i to samo się dzieje... do tej pory było ok tylko po tym jak zaktualizowałeś wytyczne tak się dzieje. Wyczyscilem nawet pamięć kodi i zainstalowałem jeszcze raz wczoraj ale bez zmian. Tak czy owak dzięki za odpowiedź a czy wtyczka Internetowa działa poprawnie ?

**Comment by Reddevil19** [comment]
Dzięki wielkie, spróbuje powalczyć z tym, nie jestem wielkim specem ale będzie git.

**Comment by Reddevil19** [comment]
Hej Robinson, zrobiłem tak jak mówiłeś i ściągnąłem sobie WBMC ale nic nie dało nawet chyba hejo tv przestało w ogóle chodzić. Zrobiłem sobie konto na Internetowa TV i to samo. Pochodzi chwilkę i wyskakuje " nieudane odtwarzanie jednej lub kilku pozycji.." Wczoraj włączyłem sobie bezpłatną Sportowa i praktycznie bez problemu oglądałem, tylko nie mam pojęcia co jest z kontami premium ?

**Comment by rebeliant1956** [comment]
poszukuje wtyczki do alltube

**Comment by notoco** [comment]
Lenistwo na maxa. Przecież wtyczka jest w repo. Nazywa się......uwaga... Ciężko będzie.... Alltube

**Comment by mbebe** [comment]
Tam juz pytal i twierdzi, ze nie ma tutaj takiej wtyczki. :-)

**Comment by notoco** [comment]
@mbebe - wiem że tam pytał... dostał wszystko co potrzebne. Ale na kwp.pl są poradniki.
Zresztą - czemu autor wtyczki mu jej po prostu nie zainstaluje ;)
