### ISSUE TITLE
Filmbooster - wyszukiwanie w bazie filmów i seriali

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#133]
Nie działa wyszukiwaniew bazie filmów i seriali, np:
Data produkcji 2010-2020
Gatunek: Animacja
wyrzuca do pustego katalogu

W logach nic nie ma ;(

**Comment by wisiann** [comment]
no nie dziala ;(

**Comment by notoco** [comment]
No wiem - a to siła tej wtyczki - kryminały lata 50 szwecja....

**Comment by mbebe** [comment]
Dziwne. Sprawdzilem. Wyszukuje. Dramaty z lat 50 tez. Dajcie najpierw Ustawienia domyslne i wtedy zobaczcie.

**Comment by notoco** [comment]
Ok. Działa. Miałem ustawione na minimalną ocenę 4 - i chyba nic z tego co wyszukiwałem nie było powyżej tej oceny ...
@mbebe - zerknij na wersję z ikonkami...
