### ISSUE TITLE
Filmbooster - wersja z ikonkami :)

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#134]
Wersja z dodanymi ikonkami dla głównych pozycji menu. W przyszłości pozostałe zagłębienia w menu
[plugin.video.filmbooster-3.1.zip](https://github.com/mbebe/blomqvist/files/3170459/plugin.video.filmbooster-3.1.zip)

**Comment by mbebe** [comment]
Jest git. :-)
w Dziś w TV Film i w Dziś w TV Serial zamienilem ikonki :-)

**Comment by notoco** [comment]
Co do kolejności ikonek - przyjąłem te rozwiązania które były w incursion/covenant/exodus/fanfilm - taśma filmowa to film - ekran tv to serial...  Ale chyba przy wpisywaniu mi się pomieszało...
Od razu lepiej wygląda, co ;) ?
