### ISSUE TITLE
cda-tv.pl

### ISSUE THREAD

**Issue by adamibeata** [mbebe/blomqvist#135]
Witam all przy ostatniej aktualizacji nie działa wyszukiwanie , oraz dodałem nową kat. NOWE LINKI gdyby ktoś miał czas na to zerknąć  dzięki i pozdro

**Comment by mbebe** [comment]
poprawione szukanie. wersja 1.3.3 w repo.

**Comment by adamibeata** [comment]
dzięki wielkie a dało by rady dodać kategorie "nowe linki"  bo są kategorie  takie jak  filmy, polecane filmy, filmy HD, filmy FHD,  gatunek, rok   i tym podobne,  czy to już dodanie  tej kat. za dużo roboty z tym jest?

**Comment by mbebe** [comment]
dodane

**Comment by adamibeata** [comment]
Witam jak by ktoś mógł luknąć żadne linki nie działają

**Comment by adamibeata** [comment]
z tego co widze to nawet openload .co przestało działać  :(

**Comment by adamibeata** [comment]
a jak już komuś będzie się chciało reaktywować tą wtyczkę fajnie żeby było też dodane "Naciśnij aby wyczyścić historię" chodzi o pole w wynikach wyszukiwania

**Comment by mbebe** [comment]
prawy klawisz na tym co wyszukiwales - Usun cala historie.
Wtyczka zaktualizowana (1.3.5)  w repo.

**Comment by adamibeata** [comment]
dzięki bardzo :)

**Comment by adamibeata** [comment]
Witam proszę o aktualizację dodane nowe linki   cdaxpl
mixdrop.co / upstream.to / jetload.net / onlystream.tv / gounlimited.to - raz działa raz nie

Dzięki pozdro

**Comment by mbebe** [comment]
https://github.com/mbebe/blomqvist/issues/201
Wina resolvera.
