### ISSUE TITLE
Może czas na CDA...

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#137]
Reaktywowałeś już prawie wszystkie wtyczki ramica... Może czas na tę, od której się wszystko zaczęło. CDA...
Wersja od Phantom jest niezła... Ale używa własnego resolvera. Wersja ramica sprzed apokalipsy była spójna, szybka...

**Comment by notoco** [comment]
No... taka reakcje mi się podoba...

**Comment by mbebe** [comment]
ostatnia wersja cda usuwa pliki jak sa te wtyczki. 
``` bad_addons = ['repository.cherrytv', 'plugin.program.cherrytv'] ```
katalogi sa tez zaciagane od niego i tam je tez aktualizowal, wiec troszke bedzie z tym roboty

**Comment by notoco** [comment]
Katalogi (w znaczeniu root - 2017/2016 z tego co pamiętam) są najmniej potrzebne - nikt z tego nie korzystał... 
To tak jakbyś miał wolny weekend... Chyba że masz rozkodowaną tę wtyczkę - to wtedy mógłbym sam pogrzebać - mi się nie udało ich "rozkodować"

**Comment by mbebe** [comment]
to z czego sie korzystalo? ;-)

**Comment by notoco** [comment]
Ja? Z własnych katalogów wyszukiwań które się tam dało ustawiać... 
A w sumie - może szkoda czasu - wtyczka phantom działa... nie tak jak cda ale dziala,...

**Comment by notoco** [comment]
Mam wersję 1.7.5 sprzed apokalipsy (nie pytaj skąd...), sprzed kodowania.
![screenshot004](https://user-images.githubusercontent.com/36659110/58090008-8bc20480-7bc6-11e9-930a-0b34b8ad89e0.png)
Własny folder jest na pierwszej pozycji...
ustawia się go w opcjach:
![screenshot006](https://user-images.githubusercontent.com/36659110/58090038-a5634c00-7bc6-11e9-86e4-aaa4914f9e70.png)

W sumie wtyczka w wielu elementach działa... więc może się za nią wezmę...

**Comment by mbebe** [comment]
te wersje tez mam. :-)

**Comment by leonzawodowiec12** [comment]
nie ukrywam że chętnie bym przetestował taką wtyczkę :)

**Comment by mbebe** [comment]
CDA juz w repo. :-)

**Comment by leonzawodowiec12** [comment]
Dzięki
