### ISSUE TITLE
FilmwebBooster... małe duże usprawnienie.... [idea].

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#139]
Pojawiła się ostatnio fajna wtyczka: plugin.video.release24 obsługująca stronę release24.pl https://github.com/piotrekcrash/kodi.
Ma jedną ciekawą opcję - umożliwia odtwarzanie filmów przy pomocy FanFilm, **FilmwebBooster**...
Baza katalogowa jest dość uboga... bo i nie do tego ta wtyczka służy
Natomiast - zalet filmweb jako serwisu nie muszę przedstawiać.
FilmwebBooster korzysta tylko z jednego serwisu, znanego nam wszystkim.
A gdyby w opcjach dodać możliwość odtwarzania za pomocą FanFilmu - wystarczy przekierowanie do wyszukiwania w FF, tak jak to jest we wtyczce release24.pl?
Można by w opcjach wtyczki dać wskazanie który serwis ma być domyślny.
I tu nie chodzi o promowanie FanFilmu - ale o to że wtyczka FilmweBooster jest świetnym uzupełnieniem dla każdego maniaka filmowego. A w wielu przypadkach także podstawową wtyczką.

**Comment by xxcriticxx** [comment]
Napewno ściąganie plakatów i opisów o filmie spowolni wtyczkę

**Comment by notoco** [comment]
Ale nic nie trzeba więcej ściągać! Zmienia się tylko odtwarzacz!
W opcjach dodajesz tylko wybór odtwarzania - albo przez filmweb albo przez FF (domyślny filmweb).
Wszystko działa dokładnie tak samo - różnica jest w momencie kliknięcia odtwórz - przy domyślnych ustawieniach przenosi cię tak jak teraz do ona z wyborem źródeł. Przy wybraniu w opcjach FF - otwiera Fanfilma - z wyszukanym danym filmem. Nie ma to wpływu na tempo działania wtyczki - bo nic więcej się nie ściąga - dopiero odpalenie oglądania spowoduje uruchomienie FF. Gdybyśmy chcieli od razu odpalić odtwarzanie w FF to owszem - trzeba by zasysać dane imdb/tmdb

**Comment by notoco** [comment]
Zwróć uwagę jak to jest zrobione w release24.pl - wtyczka sobie scrapuje stronę, a w opcjach masz wybór co ma odtwarzać. 
BTW - w FilmwebBoster przecież się plakaty ściągają... opisy nie - ale plakaty są.

**Comment by xxcriticxx** [comment]
Nie testowalem jeszcze release24 ale napewno lookne na weekendzie 

Czekamy na @mbebe niech poda swoją opinie na ten idea

**Comment by notoco** [comment]
Tak naprawdę - to można dodać opcję do menu wywołującą FF z parametrami:
plugin://plugin.video.fanfilm?action=movieSearchterm?name= i tu nazwa.... i to powinno zadziałać - nie umeim natomiast wywołać z jednego addonu drugiego z parametrami...

**Comment by notoco** [comment]
Dobra... coś się udało - na razie jako dodatkowe menu:
[main.txt](https://github.com/mbebe/blomqvist/files/3216281/main.txt)
Linia 53:
`        out.append(('Odtwórz w FanFilm', 'ActivateWindow(10025,plugin://plugin.video.fanfilm/?name='+name+' ('+infoLabels.get('year')+')&action=movieSearchterm,return))'))
`

Wiecie o czym myślę... segos też posługuje się danymi z filmweb....

**Comment by notoco** [comment]
@mbebe - wrzuć w końcu gdzieś repo w kodzie - coby można robić normalne pull request?

**Comment by notoco** [comment]
Ale... ale wywala błąd przy popularnych filmach:
```
2019-05-24 12:19:50.928 T:1264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cannot concatenate 'str' and 'NoneType' objects
                                            Traceback (most recent call last):
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.filmbooster\main.py", line 631, in <module>
                                                elif mode=='popularnefilmy_show': filmboost().popFILMYseriale(ex_link,page)
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.filmbooster\main.py", line 297, in popFILMYseriale
                                                addLinkItem(name='[COLOR gold]>> następna strona >>[/COLOR]', url=ex_link, mode='__page__:popularnefilmy_show', page=page+1, IsPlayable=False)
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.filmbooster\main.py", line 53, in addLinkItem
                                                out.append(('Odtwórz w FanFilm', 'ActivateWindow(10025,plugin://plugin.video.fanfilm/?name='+name+' ('+infoLabels.get('year')+')&action=movieSearchterm,return))'))
                                            TypeError: cannot concatenate 'str' and 'NoneType' objects
                                            -->End of Python script error report<--
2019-05-24 12:19:50.928 T:1264   DEBUG: CPythonInvoker::onExecutionDone(27, C:\Users\twos\AppData\Roaming\Kodi\addons\plugin.video.filmbooster\main.py)
2019-05-24 12:19:50.940 T:1836   DEBUG: ------ Window Init (DialogNotification.xml) ------
2019-05-24 12:19:51.021 T:1264    INFO: Python interpreter stopped
2019-05-24 12:19:51.021 T:1264   DEBUG: Thread LanguageInvoker 1264 terminating
2019-05-24 12:19:51.025 T:6172   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.filmbooster/?ex_link=%2fajax%2fhome%2fpopular%2ffilm%2f%25d&foldername=Popularne%20Filmy&minfo=%7b%7d&mode=popularnefilmy_show&page=1
2019-05-24 12:19:51.025 T:6172   DEBUG: Thread waiting 6172 terminating
2019-05-24 12:19:51.039 T:1836   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2019-05-24 12:19:51.041 T:1836   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.filmbooster/?ex_link=%2fajax%2fhome%2fpopular%2ffilm%2f%25d&foldername=Popularne%20Filmy&minfo=%7b%7d&mode=popularnefilmy_show&page=1) failed
2019-05-24 12:19:51.041 T:1836   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.filmbooster/)
2019-05-24 12:19:51.041 T:1836   DEBUG:   ParentPath = [plugin://]
2019-05-24 12:19:51.042 T:1836   DEBUG: Loading items: 11, directory: plugin://plugin.video.filmbooster/ sort method: 0, ascending: false
```

**Comment by notoco** [comment]
ok - wywalenie roku poprawiło problem...
Czyli winno być:
Linia 53:
`        out.append(('Odtwórz w FanFilm', 'ActivateWindow(10025,plugin://plugin.video.fanfilm/?name='+name+' &action=movieSearchterm,return))'))
`

**Comment by notoco** [comment]
Działa sprawnie i przyjemnie... Ale trzeba by to podpiąć w opcje i w odtwarzanie z automatu :)

**Comment by notoco** [comment]
Za słaby jestem w te klocki.
Na logikę - trzeba by w opcjach dać domyślne odtwarzanie - jeśli jest FF zainstalowany to dać opcję wyboru - jeśli go nie ma - wtedy zostawić jak jest.
Druga rzecz - zrobiłem tylko dla filmów - ale wyszukiwanie pojawia się zarówno przy serialach/episodach itp - więc to nie tędy droga.
Najłatwiej by to dać tak jak mówiłem powyżej - z rozbiciem czy to serial czy film... ale... ale w ff nie da się wyszukać poszczególnych episodów - wtedy tu w menu serialu nie sezonu/episodu można dodać "odtwarzanie przez fanfilm"
Czyli reasumując mój pomysł:
W opcjach wybór "odtwarzacza" dla filmów - domyślnie jak jest, jeśli jest zainstalowany FF, dodać opcję wyboru.
Dla seriali - ale tylko dla tytułów dać opcję (pod warunkiem że FF jest zainstalowany) "Znajdź w FanFilm"
Dzięki temu - można je odtwarzać tak jak teraz, albo samodzielnie wyszukać w FF.
Cała "idea" nie spowalnia wtyczki, nie zaciąga nic nowego. Sprawdza tylko czy jest FF - jeśli jest - wtedy dodaje dodatkową opcję.

**Comment by kodiwpigulce** [comment]
To może pójść krok dalej i zrobić fork OpenMeta z bazą filmweb i wtedy do każdej wtyczki zrobić json do wyszukiwarki?

**Comment by mbebe** [comment]
Popatrze na tamta wtyczke jak to tam wyglada.

**Comment by notoco** [comment]
Wiesz że daje to potężne możliwości. Połączenie szukania nie tylko z fanfilm, ale przede wszystkim z twoimi wtyczkami... Segos, alltube...

**Comment by mbebe** [comment]
Czasami znajduje w FF inny film lub serial, wiec automatyczne odtwarzanie moze byc bledne.

**Comment by notoco** [comment]
Tak, wiem. Problem polega na tym że nie ma możliwości odpalenia w ff filmu tylko po tytule i roku. Tammkesy dużo więcej parametrów z IMDb/tmdb puszczanych. Chyba że potrafisz to zrobić na zasadzie tytuł +rok w parametrach dla odtwarzania w ff - mi się nie udało...
Ale twoja metoda też jest super. Wystarczy w 100%. W fanfilm ciężko się znajduje szwedzkie kryminały z lat 50...

**Comment by notoco** [comment]
Może lepiej to zmienić na Znajdź w Fanfilm....

**Comment by mbebe** [comment]
dodalem do repo z szukaj w ff.

**Comment by xxcriticxx** [comment]
sorry za off topic

@kodiwpigulce instagram do poprawki strona sie rozlewa

![Capture](https://user-images.githubusercontent.com/15007183/58508019-09ef4f80-8161-11e9-9491-6cb6edb798ea.PNG)

**Comment by notoco** [comment]
I działa super. Świetne uzupełnienie dla źródeł z filmwebboster.

**Comment by notoco** [comment]
@xxcriticxx pisz na forum kwp

**Comment by xxcriticxx** [comment]
@notoco nie posiadam tam full access moge tylko czytac posty
