### ISSUE TITLE
zalukajcom

### ISSUE THREAD

**Issue by krecik71** [mbebe/blomqvist#14]
Witam.
 
Czy u was dziala aktualizacja na 1.8

**Comment by meserak86** [comment]
nie cos jest skopane  i trzeba instalwoac recznie... zassac se zipa i zainstalwoac z paczki

**Comment by krecik71** [comment]
Teraz ok dzięki

**Comment by gzenio22** [comment]
Z uwagi na to że u podpisa zrobilo sie cicho napisze to tez tu 

Był byś w stanie stworzyc dla zalukaj parowanie z traktem? to by sporo ułatwiło

**Comment by mbebe** [comment]
Nigdy nawet nie uzywalem TRAKT. Nie wiem co z czym sie je. ;-)

**Comment by kendo999** [comment]
Czy u was dziala ver   1.8 działa  u mnie wszystko sie wyswietla a filmy nie odpalaja , na ver 1.7.3  wszystko jest OK.

**Comment by kashkash18** [comment]
W wersji 1.8 na koncie VIP wszystko działa jak należy

**Comment by kendo999** [comment]
u mnie na ver 1.8 nic nie działa
