### ISSUE TITLE
Problem z zalukaj

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#143]
Problem z zalukaj, mam konto vip. W zakładkach "najpopularniejsze", "ostatnio dodane" i "ostatnio zaktualizowane"- nie działa żaden link. Wyskakuje "Zalukaj error", pozostałe zakładki "seriale", "szukaj filmu", "ostatnio oglądane" i "film gatunek" działają poprawnie odtwarzane są wszystkie linki.

**Comment by kashkash18** [comment]
![](https://i.imgur.com/eMyJYDt.jpg)![](https://i.imgur.com/rlF2BJu.jpg)

**Comment by mbebe** [comment]
poprawka poszla. wersja 1.9.9.

**Comment by rafalmar1981** [comment]
elegancko tyś to gość

**Comment by rafalmar1981** [comment]
mam pytanie może durne ale ta poprawka zaktualizuje się sama w repo po jakimś czasie?

**Comment by notoco** [comment]
Tak. Ale można wymusić aktualizacje.

**Comment by rafalmar1981** [comment]
a to spoko nic na siłę niema pośpiechu ale dziękuję za szybką odpowiedź i pozdrawiam

**Comment by notoco** [comment]
Najedz na repo mbebe w kodi, wciśnij prawy przycisk (opcji) i wybierz aktualizuj. Powinno zaskoczyć

**Comment by kashkash18** [comment]
Wszystko jest ok . Dzięki 🙂

**Comment by rafalmar1981** [comment]
notoco dzięki za podpowiedź jest jak kashkash18 napisał wszystko oki. Jest jakiś poradnik jak stworzyć własną wtyczkę jak ją się rozkodowuje itp?

**Comment by mbebe** [comment]
@rafalmar1981 zacznij od tego.
https://www.desinerd.co.in/create-kodi-video-addon-kodi-addon-development/
;-)
