### ISSUE TITLE
fili.cc  premium

### ISSUE THREAD

**Issue by xxcriticxx** [mbebe/blomqvist#146]
wyglonda na koniec strony. mozna jeden odcinek serialu/filmu oglondac co 8min albo wykupic konto premium 

![2](https://user-images.githubusercontent.com/15007183/59163692-3b0d3f80-8ad2-11e9-9390-8bc0fd33a937.png)
![1](https://user-images.githubusercontent.com/15007183/59163694-3f395d00-8ad2-11e9-9dfa-ebb6a10c8c7e.png)

**Comment by mbebe** [comment]
Przeklikalem i u mnie sie to nie pojawilo. :-/

**Comment by xxcriticxx** [comment]
Faktycznie dzisiaj tego już nie ma może trafiłem na jakoś test ale jestem pewny ze nie długo się ukaże :(

**Comment by rafalmar1981** [comment]
Witam, wiem, że jest upalnie ale może jest mi ktoś w stanie pomóc. Zainstalowałem ponownie kodi 17,6 i na androidzie i win7 - nie mogę się zalogować na swoje konto we wtyczce fili.cc. Przed odinstalowaniem byłem zalogowany na swoim koncie dodam, że zrobiłem też test kodi 18,2(pobranej z oficjalnej strony kodi). W obu przypadkach i na androidzie i win7 nie mogę się zalogować - wyskakuje komunikat "błąd logowania". Mam jeszcze pytanie czy z kontem premium na fili.cc da się zalogować? Mam i darmowe i premium, w przeglądarce internetowej wszystko działa poprawnie i darmowe oraz premium. Pozdrawiam

**Comment by kashkash18** [comment]
Jeżeli w przeglądarce przy logiwaniu pojawia się recaptcha to błąd logowania będzie się pojawiał.
Fili tak ma że od czasu do czasu uruchamia recaptcha ale nie u wszystkich. Ja na obecną chwilę nie mam problemu z zalogowaniem.

**Comment by rafalmar1981** [comment]
no to już wiem winny recaptcha. Dziękuje

**Comment by xxcriticxx** [comment]
@rafalmar1981 premium wrocilo?

**Comment by kashkash18** [comment]
U mnie premium działa bez problemu , ale jakiś czas temu też syplal błędem logowania. Po czasie wszystko wróciło do normy gdy przestało pytać czy jestem robotem.

**Comment by xxcriticxx** [comment]
@kashkash18 ile kosztuje premium?

**Comment by kashkash18** [comment]
![](https://i.imgur.com/zzW7uxJ.jpg)
