### ISSUE TITLE
Alltube nie wyswietla linkow

### ISSUE THREAD

**Issue by raalek** [mbebe/blomqvist#147]
czy u mnie tylko nie wyświetla alltube linkow do  seriali? po wybraniu tytulu pokazuje pusta strone bez zadnych strumieni

**Comment by xxcriticxx** [comment]
Napewno proxy dead

**Comment by mbebe** [comment]
poprawione - wersja 2.6.6 w repo.

**Comment by FXcodi** [comment]
2.6.6
Nadal nie chce odpalać seriali z folderu "nowe" w kodi 18.2

**Comment by raalek** [comment]
noo u mnie tez, kreci kreci kreci sie koleczko i wywala ....  :( , moze jeszcze da rade cos tam kopnac w repo ?

**Comment by mbebe** [comment]
No tak, wieczorem poprawie. A zobaczcie po wlaczeniu Grupowania w sezony w Opcjach wtyczki, czy wtedy rusza.
