### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#151]
działa wam fili.cc i zalukaj? mi wywala "error"

**Comment by kunraf** [comment]
u mnie działa

**Comment by rafalmar1981** [comment]
kurcze sprawdzę później ale dzięki za info.

**Comment by kashkash18** [comment]
U mnie wszystko śmiga :)

**Comment by rafalmar1981** [comment]
oki działa 
przeinstalowałem kodi i dalej był błąd, po paru godzinach zaczęło samo śmigać...nie wiem co się mogło stać
