### ISSUE TITLE
hejo.tv silne zakłócenia kanałów sportowych

### ISSUE THREAD

**Issue by kunraf** [mbebe/blomqvist#152]

**Comment by kunraf** [comment]
od kilku dni mam duże zakłócenia na kanałach sportowych na hejo.tv a także na internetowa.tv (konta premium)

**Comment by xulek** [comment]
No to pisz do hejo.tv i internetowej.tv. Z tego co wiem to nie prowadzą supportu swojej telewizji w tym repozytorium :P

**Comment by kunraf** [comment]
chodziło mi tylko o potwierdzenie tych problemów przez innych użytkowników.
wtedy będę wiedział gdzie jest problem, u mnie czy u dostawcy?

**Comment by mbebe** [comment]
Ale, ze co? Obraz sniezy? ;-)

**Comment by kunraf** [comment]
internetowa.tv zmienili ustawienia serwera i pomogło
teraz problem został już tylko na polsatach sport premium. 
obraz nie śnieży ;-) raczej zacinają się klatki.
śnieżenie pewnie wróci zimą ;-)
