### ISSUE TITLE
internetowa.tv błąd logowania

### ISSUE THREAD

**Issue by mibox1** [mbebe/blomqvist#153]
Od kilku dni brak możliwości logowanie do internetowa.tv.
Błąd wywala po wpisaniu kodu captcha.

**Comment by mbebe** [comment]
Jaka wersja wtyczki?

**Comment by mibox1** [comment]
Na każdej skończywszy na 1.6.4
Błąd potwierdzony także przez znajomych.

**Comment by mbebe** [comment]
Napisz do mnie maila. Podaj system, wersje kodi i daj tam loga. :-)

**Comment by kashkash18** [comment]
Testowałem dziś wtyczkę na kilku kontach i loguje bez problemu.

**Comment by mibox1** [comment]
Wtyczka sie loguje do czasu kiedy nie prosi o captcha. Nie ma znaczenia jaki sysyem. Debian, windiws, android.
Zaraz napisze majla do mnebe.

**Comment by mibox1** [comment]
Wtyczka sie loguje do czasu kiedy nie prosi o captcha. Nie ma znaczenia jaki sysyem. Debian, windiws, android.
Zaraz napisze majla do mnebe.

**Comment by kashkash18** [comment]
Captcha przechodzi gładko. Testowane na ATV , Windows i RPi3

**Comment by mibox1** [comment]
U mnie nie, po wpisaniu wywala błąd logowania. Do tej pory działało ok.

**Comment by mibox1** [comment]
Reset rutera do ustawień fabrucznych pomógł. Można zamknąć temat. Dzięki
