### ISSUE TITLE
Hejo.tv Błąd przy wyświetlaniu listy kanałów 

### ISSUE THREAD

**Issue by Arkosake** [mbebe/blomqvist#155]
Dzień dobry. Wtyczka do Hejo.tv ma problem z wczytaniem listy kanałów, wczytuje tylko pierwsze 12 i dalej nic. Prawdopodobnie zaszły jakieś zmiany na stronie bo przez przeglądarkę też doczytują się dość topornie.

**Comment by mbebe** [comment]
czy nadal problem wystepuje?

**Comment by kashkash18** [comment]
U mnie pokazuje 77 kanałów.

**Comment by mbebe** [comment]
No wlasnie. U mnie tez. :-)

**Comment by kashkash18** [comment]
Możliwe że Hejo miało wczoraj jakiś problem skoro przez przeglądarkę szło topornie.
Dziś działa dobrze :-)

**Comment by Arkosake** [comment]
Dziś już wszystko działa o dziwo :-)

**Comment by kashkash18** [comment]
@Arkosake można zamknąć temat.
