### ISSUE TITLE
otube.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mbebe/blomqvist#158]
sluchamy opinii klienta

**Comment by krecik71** [comment]
jestem na tak

**Comment by wisiann** [comment]
Jak to wszystko dziala...to wtyczka potrzebana,

Mam wrazenie ze dotychczasowe ( nie wszystkie)
 strony/wtyczki  slabo ostatnio updates robią z nowymi filmami/serialami,

Nie ma co ogladac,

Taki osobiste spostrzezenie!?

**Comment by wisiann** [comment]
Ja nie mam 2 miesiace wakacji ;)

**Comment by xxcriticxx** [comment]
@wisiann to ty nie jestes offisowy?

**Comment by wisiann** [comment]
No niestety nie ....Gdzies te ludzie musza mieszkac w tym chicago

**Comment by xxcriticxx** [comment]
@wisiann dzieki za off topic!

**Comment by leonzawodowiec12** [comment]
myślę że warto dodać
