### ISSUE TITLE
polsatnews

### ISSUE THREAD

**Issue by meserak86** [mbebe/blomqvist#16]
nie odpalaja sie linki na 17 i na 18

**Comment by mbebe** [comment]
u mnie na 16, 17 i 18 odpalaja sie. moze ktos jeszcze sprawdzic?

**Comment by notoco** [comment]
U mnie też działa. Coreelec. @meserak86 wrzuć logi.

**Comment by kashkash18** [comment]
Kodi 17.6 odpala bez najmniejszych problemów.
