### ISSUE TITLE
fili.cc

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#160]
Witam kilka dni się głowię i nie wiem gdzie leży problem, a mianowicie nie odpalają się żadne źródła. Rinstalacja systemów win i android pod kodi 17.6, różne resolvery i lipa. Te sam źródła filmów i seriali na innych wtyczkach działają tylko nie na fili.cc, dodam, że na koncie vip jeżeli jest taka opcja i są dodatkowe źródła premium ale tylko i wyłącznie trzy źródła premium to odpala tylko jedno. Nie wiem dlaczego tak się dzieje, ma ktoś jakieś rozwiązanie? Pozdrawiam

**Comment by rafciu27** [comment]
Mam to samo. Żadnych źródeł.

**Comment by rafalmar1981** [comment]
jest jakaś opcja na pomoc lub wyjaśnienie co z tą wtyczką się porobiło?

**Comment by notoco** [comment]
Wtyczka padła. Jest sezon urlopowy. Trzeba czekać cierpliwie na poprawkę.

**Comment by rafalmar1981** [comment]
dziękuję za odpowiedź, tak przypuszczałem, pozdrawiam

**Comment by kashkash18** [comment]
Możliwe że dziś pojawi się akutalizacja wtyczki lecz Fili coraz częściej wrzuca recaptcha co powoduje błąd logowania. Na tę chwilę jest to nie do przeskoczenia. 
Za to w ustawieniach wtyczki można wyłączyć logowanie i spokojnie korzystać z wtyczki.

**Comment by rafalmar1981** [comment]
dziękuję kashkash18 za informację, utrudniają te serwisy wam pracę ale i tak jest zaje...iście. Pozdrawiam, odezwę się na KWP, bo mam kilka pytań

**Comment by kashkash18** [comment]
Nie nam tylko Mbebe i innym programistą. Teraz wtyczka mnie zalogowała a na stronie nie wyskakuje recaptcha.

**Comment by mbebe** [comment]
zaktualizowana wtyczka w repo? bo nie wiem czy dodalo.

**Comment by kashkash18** [comment]
Zaktualizowana

**Comment by rafalmar1981** [comment]
no no no elegancko

**Comment by rafalmar1981** [comment]
wymusiłem aktualizację i proszę, pięknie, ładnie....dziękuję mbebe.
