### ISSUE TITLE
Wtyczka do storytel

### ISSUE THREAD

**Issue by meserak86** [mbebe/blomqvist#163]
Jak w temacie, storytel daje dostep do audiobookow, konta sa tanie, aktualnie  nie mamy zadnej wtyczki z audiobookami, mysle ze to ciekawy pomysl

**Comment by rafalmar1981** [comment]
zgadzam się, ciekawa propozycja

**Comment by mbebe** [comment]
Probna wersja wtyczki.
[plugin.audio.storytel.zip](https://github.com/mbebe/blomqvist/files/3529811/plugin.audio.storytel.zip)

**Comment by meserak86** [comment]
Nie mam aktualnie konta by sprawdzic

czw., 22 sie 2019, 12:21 użytkownik mbebe <notifications@github.com>
napisał:

**Comment by mbebe** [comment]
na darmowym koncie - 3 min. odtwarzania.

**Comment by meserak86** [comment]
Zona gdzies wsadzila polska karte a karta z uk nie dziala a numeeu pl nie
mam... Nie moge tego darmowego okresu 14 dni wziasc narazie dopuki z zona
sie nie spotkam:D

czw., 22 sie 2019, 13:19 użytkownik mbebe <notifications@github.com>
napisał:
