### ISSUE TITLE
Hejo.tv - błąd dodatku

### ISSUE THREAD

**Issue by Kantel88** [mbebe/blomqvist#167]
Wyrzuca błąd, na stronce wszystko śmiga :)

**Comment by Arek76** [comment]
dokladnie to samo sygnalizuja mi znajomi ktorzy korzystaja z hejo

**Comment by kunraf** [comment]
potwierdzam, wyrzuca błąd

**Comment by mbebe** [comment]
Poprawka w repo. wersja wtyczki 2.0

**Comment by kunraf** [comment]
repo po zaktualizowaniu ma tylko wersje 1.9.9

**Comment by mbebe** [comment]
faktycznie. poprawione.

**Comment by kunraf** [comment]
dzięki

**Comment by kodiwpigulce** [comment]
U mnie błąd wywala... 

`18:27:00.737 T:6820   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "X:\Kodi18\portable_data\addons\plugin.video.hejotv\main.py", line 800, in <module>
                                                home()
                                              File "X:\Kodi18\portable_data\addons\plugin.video.hejotv\main.py", line 78, in home
                                                login()
                                              File "X:\Kodi18\portable_data\addons\plugin.video.hejotv\main.py", line 195, in login
                                                log1=re.findall("""class="fa fa-user" aria-hidden="true"></i>(.+?)</a><div""", html)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--`

**Comment by Kantel88** [comment]
Na stronie hejo od dzisiaj  jest do pobrania wtyczka do Kodi (autorzy chyba repo Podpis) i działa. Pewnie dlatego wtyczka mbebe nie śmiga.

**Comment by mbebe** [comment]
[plugin.video.hejotv-2.1.zip](https://github.com/mbebe/blomqvist/files/3543376/plugin.video.hejotv-2.1.zip)
Sprawdzcie te wersje.
Nie wiem po co hejo.tv kaze instalowac repo podpisa. :-/
Wtyczka tam jest moja.

**Comment by kodiwpigulce** [comment]
Pewnie dlatego, że w twoim repo brakuje zależności i jak instaluje się na czystym Kodi tylko twoje repo plus wtyczkę Hejo to wywala błędy braku paru zależnych wtyczek. 
Teraz przechodzi przez logowanie, pokazuje listę kanałów ale wywala babola przy próbie odpalenia kanału. "Tylko konta premium".

**Comment by mbebe** [comment]
Jak zalatwie sobie premium, to sprawdze. ;-)

**Comment by kodiwpigulce** [comment]
No jak te gamonie nie dają Ci dostępu do premium to weź ich olej i zaraz się znajdzie dostęp premium.

**Comment by Kantel88** [comment]
Mbebe napisz mi swojego e-maila wyśle Ci swoje dane do premium żebyś mógł lepiej operować w hejo :)

**Comment by kunraf** [comment]
tak czy siak, hejo wyrzuca błąd

**Comment by kunraf** [comment]
tak czy siak, hejo nie działa

**Comment by mbebe** [comment]
Zmiany ponowne na stronie. Powrocili do starej strony.
[plugin.video.hejotv-2.1.zip](https://github.com/mbebe/blomqvist/files/3545487/plugin.video.hejotv-2.1.zip)

**Comment by kodiwpigulce** [comment]
Działa :)

**Comment by kunraf** [comment]
Wrzucisz tą wersję do repo?

**Comment by mbebe** [comment]
Jest w repo. Wymus aktualizacje.

**Comment by kunraf** [comment]
próbuje w lapku i telefonie i jest tylko 2.0

**Comment by kunraf** [comment]
nie tylko aktualizuje, próbowałem instalować od nowa i wchadzi v2.0

**Comment by kodiwpigulce** [comment]
zainstaluj ponownie repo

**Comment by kunraf** [comment]
poszło

**Comment by kunraf** [comment]
dziś zauważyłem, że w tv samo się zaktualizowało do wersji 2.1 
teraz jest ok
dzięki

**Comment by japierdziele** [comment]
Witajcie. Od kilku dni mecze sie z hejo.tv na tvboxie. Po zainstalowaniu najnowszej wtyczki ze strony hejo.tv (plugin.video.hejotv-2.2.1.zip. ) i zalogowaniu poczatkowo dziala normalnie. Po kilku minutach jednak z tv wraca na liste kanalow. Czasem wystarczy kliknac dany kanal ponownie i rusza, czasem pokazuje sie komunikat ze tylko konta premium (pomimo ze jestem zalogowany - nie wylogowywuje) W takiej sytuacji musze wylaczyc kodi i od nowa wszystko uruchomic. Pomozecie rada? Dzieki.
