### ISSUE TITLE
Nasze Kino

### ISSUE THREAD

**Issue by KML73** [mbebe/blomqvist#17]
Czy komuś działa Nasze Kino wersja 1.6.5 ? U mnie po wpisaniu kodu nic się nie otwiera.

**Comment by kashkash18** [comment]
U mnie działa , Kodi 17.6

**Comment by krecik71** [comment]
działa kodi 17.6

**Comment by KML73** [comment]
Czy używacie czystego Kodi ? Android czy Windows ?

**Comment by mbebe** [comment]
nie odtwarza filmow, napis o blednej captchy, czy co?

**Comment by KML73** [comment]
Wszytko jest ok do momentu wpisania captcha, chwilę mieli i za każdym razem mam komunikat "Nieudane odtwarzanie jednej lub więcej pozycji". Inne wtyczki w tym najnowsza filmantv chodzą bez problemu. Sprawdzałem na Kodi 17.6 i 18. System operacyjny Win 10.

**Comment by mbebe** [comment]
taki komunikat moze sie pojawic jesli jest brak filmu, blad resolvera itp. Podaj tytul filmu na jakim cie wyrzuca.

**Comment by KML73** [comment]
Na każdym tyule serialu lub filmu np. Wilcze echa, Sami swoi Ucieczka / The Escape (Dział Ostatnio dodane filmy)

**Comment by KML73** [comment]
Dodam, że używam buildu Cherry TV 1.9.5 i mam wgrane Twoje repo.

**Comment by mbebe** [comment]
wybor zrodla sie pojawia po wpisaniu captchy?

**Comment by KML73** [comment]
po wpisaniu captchy i OK jakiś czas nastąpi komunikat o uruchomieniu ... po czym po 10 sek. otrzymuje komunikat  "Nieudane odtwarzanie jednej lub więcej pozycji".

**Comment by kashkash18** [comment]
Android 7.1.2 i 8.0.0 K17.6 , W10 K17.6. Kodi czyste i z wtyczka nie mam nigdzie problemów.

**Comment by KML73** [comment]
Wracam do tematu ... przyczyną moich problemów był użyty resolveurl. Proszę poradźcie, którego używać, tak aby chodziły wszystkie wtyczki. Mój problem dotyczył tylko nasze-kino.pl. W tej chwili używam wersji 5.0.13. Trochę stara wersja.

**Comment by mbebe** [comment]
ja uzywam od jsergio. wersja teraz obowiazujaca to 5.0.16.
