### ISSUE TITLE
serwisy  vod

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#170]
Co myślicie o takiej wtyczce w której były by się znalazły takie serwisy jak Netflix, Showmax i HBO GO, VOD.pl, Player, IPLA i TVP VOD, ale też CDA Premium, WP Video i nc+ GO, u zapewne wiele innych. jedna wtyczka w jednym plugini, oczywiście z możliwością logowania się na nowe plugińy na kotna vip, suę

**Comment by notoco** [comment]
Ciężko by ogarnąć taką wtyczkę. Showmaxa np już od dawna nie ma w ogóle. Każda z tych wtyczek to odrębny kombajn i spięcie tego razem jest IMO nie do ogarnięcia i mija się z celem. Dlaczego? Bo właśnie kodi spina te wszystkie wtyczki w jedną całość.

**Comment by rafalmar1981** [comment]
to może jak na zasadzie co w sd-xbmc by wszystko było w jednym....czy w ten sposób by się dało

**Comment by notoco** [comment]
No to jest sd-xbmc przecież :) a że nie aktualizowane? To pytanie do autorów...

**Comment by rafalmar1981** [comment]
tak wiem ale to słabo wygląda w sd-xbmc, więc pomyślałem jak wyżej by coś takiego stworzyć...

**Comment by notoco** [comment]
To nie lepiej pisać do autorów sd-xbmc żeby nanieśli poprawki żeby było lepiej. Takie wtyczki kombajny to naprawdę koszmar. Brak wspólnego api i często praca po omacku jak z netflixem nie ułatwia roboty.

**Comment by rafalmar1981** [comment]
dobra coś im tam skrobnę, ale pomyślałem skoro mbebe ma prawie wszystko... jak tak to przepraszam i pozdrawiam. Jeszcze jedno pisałem do Pana na KWP odnośnie nieodtwarzających programów w serwisie ipla(mam premium) w m-TVGuide

**Comment by notoco** [comment]
Nie korzystam ani z ipli ani z mtvguide. Oni mają swoje forum mods-kodi.pl tam pytaj o te sprawy

**Comment by notoco** [comment]
I nie pisz mi na pan. W sieci jesteśmy równi bez względu na wiek i inne.

**Comment by rafalmar1981** [comment]
W porządku, miłego wieczora

**Comment by Janasek** [comment]
**sd-xbmc**,nikt nie poprawi chyba ze inne obrazki albo nazwe zmieni,dzialania trwają a efektu żadnego
co to klepania jednej wtyczki all in one to pomysł marny każda powinna byc jako jedna 
**Kodi** robi tą wtyczke już chyba z 1,5 roku ale na to muszą miec zgodę której nie otrzymają chyba ze nieoficjalnie ktoś to zrobi

Wtyczki takie jak IPLA,Player i tym podobne uważam że było by świetnie kto nie chce nie płaci i nie instaluje sprawa prosta,ale wiem ze miały by większą popularność 

Czy Netflix jej nie ma????

@mbebe 
gdybyś zechciał zerknąć chociaż by nawet do sd-xmbc i przegląd zrobił co do logowania ipla player coś więcej może była też wtyczka która oferowała tv z ipla i coś jeszcze nie pamiętam nazwy ale autor to Mrknow
