### ISSUE TITLE
Błąd wtyczki Hejo.tv

### ISSUE THREAD

**Issue by kunraf** [mbebe/blomqvist#171]
od wczoraj Hejo.tv nie działa

**Comment by mbebe** [comment]
wtyczka z wersja 2.0 dziala poprawnie.
w repo wersja 2.1.1

**Comment by kunraf** [comment]
działa, dzięki

**Comment by kunraf** [comment]
problem z wtyczką hejo, nie loguje do konta premium, na stronie działa
