### ISSUE TITLE
Hejo.tv - błąd brak premium

### ISSUE THREAD

**Issue by Kantel88** [mbebe/blomqvist#175]
Wtyczka loguje się na konto ale przy odpaleniu TV wyrzuca błąd premium mimo logowania na koncie premium :)

**Comment by Kantel88** [comment]
Jest już nową wersję na stronkę Hejo,  wrzucisz mbebe do swojego repo żeby ludziom automatycznie zaktualizowalo?

**Comment by kunraf** [comment]
mi się sama zaktualizowała, sprawdź ustawienia

**Comment by notoco** [comment]
Tylko że 3 dni temu nie było tej aktualizacji. Jest od wczoraj...
