### ISSUE TITLE
Hejo.Tv

### ISSUE THREAD

**Issue by Huero23** [mbebe/blomqvist#176]
Błąd wtyczki Hejo.Tv
![20191009_214303](https://user-images.githubusercontent.com/19337836/66539774-30919f80-eade-11e9-9a66-979f96979181.jpg)

**Comment by mbebe** [comment]
Poprawka w repo. ;-)

**Comment by Huero23** [comment]
@mbebe Dziękuje bardzo :)

**Comment by Huero23** [comment]
@mbebe Znowu jakiś błąd :(
