### ISSUE TITLE
co to fili.cc padło

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#177]
co to fili.cc padło....czy coś innego się stało?

**Comment by rafalmar1981** [comment]
pewnie zawracam gitarę ale może taka wtyczka była by dobra jak już fili padło https://www.vodgo.pl/

**Comment by xxcriticxx** [comment]
strona glowna otwiera sie bardzo wolno

**Comment by rafalmar1981** [comment]
siadło a nie wolno się otwiera
