### ISSUE TITLE
Hejo.Tv

### ISSUE THREAD

**Issue by Huero23** [mbebe/blomqvist#178]
@mbebe Znowu jakiś błąd :( 
![15708294130913502667292409544480](https://user-images.githubusercontent.com/19337836/66686253-b07d4e00-ec33-11e9-82a1-eae9ba7b5c96.jpg)

**Comment by Ognistysmall** [comment]
Witam, mam ten sam problem na tv, jakby źle hasło wpisywal na premium i nie wchodzi stronka hejo. Na lapku i mobile normalnie lata. Dodam że korzystam z boxa xiaomi
Pozdrawiam

**Comment by Huero23** [comment]
@Ognistysmall Mbebe ostatnio poprawił ale znowu jakiś błąd... goldvod.tv jest narazie z darmo tylko musisz zrobić konto.

**Comment by Huero23** [comment]
@mbebe Znowu jakiś błąd
