### ISSUE TITLE
A może coś takiego?

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#179]
Skoro fili padło, dobra baza seriali jak i filmów https://3filmy.com/ ,gdyby był czas oczywiście na takie coś

**Comment by xxcriticxx** [comment]
dla mnie nic na tej stronie sie nie laduje

**Comment by rafalmar1981** [comment]
mnie lata

**Comment by rafalmar1981** [comment]
przed chwilą sprawdzałem dla pewności i działa

**Comment by kendo999** [comment]
nie zawracac glowy divixami jakosc 720p to bylo dobre ale 10 lat temu dzis to minimum 1080p z neta  cda i segos ale tam nic ciekawego.

**Comment by rafalmar1981** [comment]
Oj kendo kendo....zwróć uwagę ile jest podobnych w repo mbebe i jak ludzie łapali, gdy szefowi się zechce lub znajdzie czas....albo stwierdzi, że warto/można to tylko się cieszyć. Ja podałem tylko moją propozycję. Pozdrawiam

**Comment by xulek** [comment]
@mbebe jak coś się będziesz bawił to recepta na zdekodowanie linku video:

https://gchq.github.io/CyberChef/#recipe=URL_Decode()XOR(%7B'option':'Hex','string':'5d'%7D,'Standard',false)

**Comment by mbebe** [comment]
Dodane do repo.

**Comment by rafalmar1981** [comment]
Nonono proszę bardzo jaki speedy gonzalez
