### ISSUE TITLE
[NEWS] VOD Site Markowy "Notorious Market" uderza w MPAA

### ISSUE THREAD

**Issue by xxcriticxx** [mbebe/blomqvist#18]
https://torrentfreak.com/vod-site-branded-notorious-market-hits-back-at-the-mpaa-181015/

**Comment by mbebe** [comment]
https://businessinsider.com.pl/wiadomosci/serwis-cdapl-na-liscie-pirackich-stron/hyl859h

**Comment by xxcriticxx** [comment]
![image](https://user-images.githubusercontent.com/15007183/49675529-16151280-fa44-11e8-8aa7-eea8de662c4e.png)
