### ISSUE TITLE
Videopenny

### ISSUE THREAD

**Issue by oliwer12345** [mbebe/blomqvist#183]
Czy ktos cos wie na temat wtyczki videopenny ostatnio cos zeby ogladac to jest normalnie tragedia.

**Comment by leonzawodowiec12** [comment]
Już działa wyszła poprawka

**Comment by oliwer12345** [comment]
DZIEKUJE

**Comment by jointer23** [comment]
fajna wtyczka, tylko u mnie jest problem, że większość linków to error. Działają mi tylko te z videozy i to po kilkukrotnym włączeniu. Na stronce linki śmigają. Ktoś podpowie? wersja 1.5

**Comment by mbebe** [comment]
poprawione. w repo wersja 1.6

**Comment by oliwer12345** [comment]
DZIEKI MBEBE ZA WERSJE 1.6 ALE PRAWIE ZADEN LINK SIE NIE OTWIERA TYLKO CIAGLE ZE BRAK

**Comment by jointer23** [comment]
u mnie to samo tylko te z videozy działają :(

**Comment by mbebe** [comment]
Kolejna poprawka. w repo wersja 1.7

**Comment by oliwer12345** [comment]
Panie kolego Mbebe mozna cos zrobic z ta wtyczka videopenny  po koleniej wersi 1,7 chodzilo az 1 dzien. Teraz nawet niechce otwierac nowych odcinkow seriali albo zaraz po otwarciu wlaczy sie bufor i mozna czekac i czekac.

**Comment by Smerd5** [comment]
Dolaczam sie kolegi oliwera, bufor nie ma konca, czasami nakreci i gra przez 5 sec, i dalej kreci i kreci........

**Comment by justkidding321** [comment]
nie dziala, czy tylko mi nie laduja sie seriale?

**Comment by oliwer12345** [comment]
U mnie w uk nie dziala

**Comment by Bogdan16** [comment]
witam u mnie tesz nie dziala

Pozdrawiam

**Comment by mbebe** [comment]
Ale co nie dziala?
Nie wyswietla zawartosci? Nie odtwarzaja sie linki? Cos innego?
Doprecyzowujcie.

**Comment by justkidding321** [comment]
Nie odtwarzaja sie linki.

**Comment by Bogdan16** [comment]
witam

 

Seriale Nie odtwarzaja sie linki?

 

Pozdrawiam

 

Bogdan16

 

Gesendet: Samstag, 30. November 2019 um 14:06 Uhr
Von: "mbebe" <notifications@github.com>
An: mbebe/blomqvist <blomqvist@noreply.github.com>
Cc: Bogdan16 <Bogdan16@gmx.de>, Comment <comment@noreply.github.com>
Betreff: Re: [mbebe/blomqvist] Videopenny (#183)


Ale co nie dziala?
Nie wyswietla zawartosci? Nie odtwarzaja sie linki? Cos innego?
Doprecyzowujcie.

**Comment by Bogdan16** [comment]
Witam

Nie wyswietla zawartosci? w Ostatnio Dodane i w Seriale jest tylko jedna Strona

Pozdrawiam

**Comment by Bogdan16** [comment]
witam mbebe

Moze bys poprawil w Ostatnio Dodane i w Seriale jest tylko jedna Strona linki sa ale nic sie nie dzieje

**Comment by mbebe** [comment]
[plugin.video.videopenny-1.9.zip](https://github.com/mbebe/blomqvist/files/3935653/plugin.video.videopenny-1.9.zip)
tutaj na razie poprawka.

**Comment by Bogdan16** [comment]
witam 
serdeczne dzieki 
moja moze ogladac na serial Na Wspolnej
Pozdrawiam
