### ISSUE TITLE
cpgo

### ISSUE THREAD

**Issue by Janasek** [mbebe/blomqvist#184]
Nie wiem czy tylko u mnie ,ale tv nie działa natomiast vod działa bezbłednie

**Comment by mbebe** [comment]
Topornie, bo topornie, ale odtwarza tv. :-/

**Comment by Janasek** [comment]
jestem sam na koncie nawet telefon nie podpięty i powiedzmy 1 raz dziennie uda mi się wskoczyć i odpalic tv ale jak wyjde z tv,dodatku to już koniec tylko vod działa nic więcej.

**Comment by mbebe** [comment]
Moglo tak byc. Wersja 1.2 powinna to rozwiazac.

**Comment by Janasek** [comment]
Tak na windows naprawione ,CoreELEC nadal problem pewnie to wina samego systemu

**dzięki za poprawkę !!!**

**Comment by BlackGlassSkin** [comment]
kawałek loga z CoreELEC

https://hastebin.com/ihepoyurec.pl

**Comment by Janasek** [comment]
Kawałek loga z CoreELEC

https://hastebin.com/ihepoyurec.pl

**Comment by mbebe** [comment]
Faktycznie. Wczoraj tez otrzymalem takiego loga. Wina jest epg. W kolejnej wersji w

**Comment by adam2a** [comment]
Identyczny błąd na Androidzie (Mi Box S) jest nadal. Można to jakoś obejść?
