### ISSUE TITLE
vodgo.pl - propozycja....

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#186]
A to widziałeś?
Ilośc linków dość spora...

**Comment by leonzawodowiec12** [comment]
Fajna stronka

**Comment by xxcriticxx** [comment]
duplikat #117

**Comment by notoco** [comment]
Albo już stary jestem, albo źle widzę... ale gdzie masz duplikat?

**Comment by xxcriticxx** [comment]
@notoco bardzo by pasowalo zebym podal dobry numer #177 

![Capture1](https://user-images.githubusercontent.com/15007183/67619290-c4928500-f7c7-11e9-8168-31ab3aceebaa.PNG)

**Comment by mbebe** [comment]
dodane do repo.

**Comment by notoco** [comment]
Dzięki.
