### ISSUE TITLE
wtyczka polsat cyfrowy go

### ISSUE THREAD

**Issue by kunraf** [mbebe/blomqvist#189]
czy ktoś ma podobny problem?
po zalogowaniu się na swoje konto(mam usługę on the go w polsacie) nie ma listy kanałów.
czy komuś ta wtyczka działa?

**Comment by mbebe** [comment]
Niestety kanaly dzialaja. :-/ A dziala Tobie vod?

**Comment by isio831** [comment]
Witam kanaly dzialaja ale nie wiem czy tylko u mnie wystepuje tak ze jak wlacze kanal to dziala chwile potem staje i dopiero po dluzszej chwili idzie dalej i tak wkolko dzieje sie tak na kilku urzadzeniach konto na cp go prywatne.

**Comment by kunraf** [comment]
Po kilku odinstalowywaniach i i ponownych instalowaniach kanały się pojawiły.
Czy to normalne, że kanały oglądane przez wtyczkę mają gorszą jakość niż bezpośrednio przez stronę polsatu?

**Comment by kashkash18** [comment]
Jakość obrazu możesz zmienić w ustawieniach obrazu po odpaleniu danego kanalu![](https://i.imgur.com/bisyTON.jpg)

**Comment by kunraf** [comment]
Tak, ale po zmianie jakości i tak jest słabsza niż ze strony polsatu, dodatkowo potrafi zacinać.
Czy to normalne?, czy to powinno chodzić jak ze strony?
Porównywałem hejo.tv i tam nie widać różnic.
Może przyjdzie czas też czas NC+ go (mam konto)
Mam tv z androidem, obie aplikacje mam zainstalowane, ale trzeba je obsługiwać myszką.

**Comment by kunraf** [comment]
zauważyłem, że np na eleven1 jest jakieś dziwne przesunięcie czasu, nie można tego ustawić żeby było na  żywo
