### ISSUE TITLE
Ekstraklasa

### ISSUE THREAD

**Issue by kashkash18** [mbebe/blomqvist#19]
@mbebe dwie prośby odnośnie tej wtyczki . Czy jest możliwość dodania do ekstraklasa.tv terminarza oraz strzelców ?? Obie zakładki znajdują się na stronie ekstraklasa.tv . Ekstraradar można wyrzucić bo nie jest to już dalej rozwijany.

I jeszcze meczyki.pl , skróty z Pucharu Polski . Tam jest przekierowanie do PS i niestety wtyczka tego nie odpala.

**Comment by kashkash18** [comment]
Tutaj jest wersja z wyłączonym ekstraradarem oraz wyłączyłem Najnowsze i Najpopularniejsze gdyż one też nie są rozwijane. 

[plugin.video.ekstraklasa-3.2.3.zip](https://github.com/mbebe/blomqvist/files/2488565/plugin.video.ekstraklasa-3.2.3.zip)

Zresztą sobie nie poradzę ;)

**Comment by mbebe** [comment]
W glownym menu dodalem terminarz i strzelcow.
sprawdz te wersje. jak cos, to jutro wrzuce do repo.
[plugin.video.ekstraklasa-3.3.zip](https://github.com/mbebe/blomqvist/files/2489601/plugin.video.ekstraklasa-3.3.zip)

**Comment by mbebe** [comment]
sprawdz wersje 3.4 jest w repo.
dodane odtwarzanie ps w meczykach.

**Comment by kashkash18** [comment]
Streme od meczu PP Wisła Kraków - Lechia Gdańsk  się nie odpalają , a wcześniejsze na liście się odpalają.

**Comment by mbebe** [comment]
poszla poprawka

**Comment by kashkash18** [comment]
Wszystko działa jak należy 👍 
Mam jeszcze pytanie o Live , czy jest możliwość użycia f4m proxy lub streamlink proxy by odpalał się Live w PL ?? Może dzięki którejś z tych zależności ruszy. A jeśli nie to obok Live dodać info iż z polskiego IP wymagany jest VPN

**Comment by mbebe** [comment]
Nie odpowiem na to pytanie, bo nie wglebialem sie w to. ;-)  Popatrze w wolnym czasie w weekend jak mecze beda.

**Comment by kashkash18** [comment]
Live idzie 24h na dobe ;) Nie ma jakiegoś wielkiego parcia . Ja sobie radzę przez VPN ale niektórzy ich nie posiadają i jest trochę kiszka. Może akurat się uda . Dzięki za usprawnienia wtyczki.

**Comment by kashkash18** [comment]
@mbebe popatrzysz na meczyki ?? Skróty się wysypały . Działa tylko ekstraklasa

**Comment by mbebe** [comment]
poszla poprawka. w matchat zmienili.

**Comment by kashkash18** [comment]
Działa , dzięki :)

**Comment by kashkash18** [comment]
Lukniesz na Estadios w wolnej chwili ??

**Comment by mbebe** [comment]
poszla poprawka
