### ISSUE TITLE
e-kinotv

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#191]
coś się chyba posypało, od pewnego czasu strasznie dużo materiałów wywalało brak linka itp. Przed chwilą sprawdziłem jednak na necie i tam wszystko śmiga tz. to co nie idzie na kodi

**Comment by FXcodi** [comment]
Potwierdzam,wtyczka nie odpala filmów.
Przydała by się poprawka pod resolveurl bo nie odpala hostów np. onlystream, hqq itd.
Wszystko co tak jeszcze niedawno chodziło zostało ubite przez ACE.

**Comment by mbebe** [comment]
https://github.com/mbebe/blomqvist/issues/201

**Comment by FXcodi** [comment]
No niestety nie pomogło , tak jak w przypadku Allltube.pl.
Do poprawki również Segos.es oraz Virpe.COM.

**Comment by FXcodi** [comment]
No niestety nie pomogło , tak jak w przypadku Alltube.pl.
Coś się wysypało , ponieważ w boxie na E2 tez nie działa, a jeszcze 2 dni temu grało .
