### ISSUE TITLE
Pastebin

### ISSUE THREAD

**Issue by Arek76** [mbebe/blomqvist#193]
Witaj Mbebe , Juz kiedys pisalem ale gdzies to ucieklo i temat pewnie przepadl w otchlani . 
Chodzi o wtyczke Pastebin , Czy jest mozliwosc dodania do wtyczki stron ? Chodzi o to ze mam liste ktora ma ponad 400 pozycji i samo wgrywanie trwa czasem kolo 3 minut , Mysle ze gdyby sie podzielilo na stony mogloby to przyspieszyc dzialanie . Oczywiscie to tylko propozycja i chetnie dowiem sie jak to wyglada z Twojej strony . Dziekuje

**Comment by mbebe** [comment]
wyslij mi na maila te liste lub adres listy i postaram sie zrobic strony.
