### ISSUE TITLE
Vodgo dostało cf

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#196]
Jak w temacie. Vodgo.pl schowało się za cloudflare.

**Comment by xxcriticxx** [comment]
strona wyglonda na dead wszystkie linki prowadza do chili.com albo player.pl

**Comment by notoco** [comment]
Nie... https://vodgo.pl/film/krol-lew/2023 są linki do chili ale są też do vidozy...

**Comment by xxcriticxx** [comment]
@notoco linky dzialaja?

**Comment by notoco** [comment]
Na tym zrzucie pierwsze 2 od góry otworzyło.

**Comment by xxcriticxx** [comment]
u mnie to nie działa zapytam kolegow z innej branzy

**Comment by oliwer12345** [comment]
Witam mi wtyczka Vodgo nic nie otwiera pokazuje blad Vodgo.

**Comment by mbebe** [comment]
juz powinna dzialac. poszla poprawka - wersja 1.2

**Comment by oliwer12345** [comment]
Dziekuje
