### ISSUE TITLE
TVP.vod.pl abo

### ISSUE THREAD

**Issue by Contralege** [mbebe/blomqvist#197]
Od kilku dni nie działa abo... choć jestem zalogowany i prawidłowe opłacone konto. To nie działają filmy w abo oraz w vod np w serialach odcinki prapremierowe Co się stało co mam zrobić

**Comment by Smerd5** [comment]
Mam dokladnie ten sam problem, jestem zalogowany i zadnego nowego odc. serialu nie moge otworzyc, zwyczajnie nie dziala.

**Comment by tete90** [comment]
Na stronie logowanie jest ok i wszystkie treści idą. Natomiast wtyczka wyrzuca komunikat  ,, niepoprawne dane logowania"

**Comment by Contralege** [comment]
jednak nie wszystkie treści idą bo odcinki seriali przedpremierowe nie idą Idą tylko te któe juz były w tvp
a do tej pory szły i przedpremierowe i nie było komunikatu o błędnym logowaniu

**Comment by mbebe** [comment]
Pojawila sie recaptcha na stronie. Na ten moment nie do ominiecia.

**Comment by hevet** [comment]
Nawet dla Ciebie? Może jednak coś poradzisz ;)

**Comment by krecik71** [comment]
https://www.sat-4-all.com/board/topic/257422-plugin-e2iplayer_public/page/75/ może to pomoże

**Comment by mbebe** [comment]
Nie dziala proxy. Wersja testowa. Rzuccie okiem.
[plugin.video.tvpABON-1.5.zip](https://github.com/mbebe/blomqvist/files/3894423/plugin.video.tvpABON-1.5.zip)

**Comment by tete90** [comment]
plugin.video.tvpABON-1.5.zip sprawił że wtyczka działa poprawnie. Ślicznie dziękuje.

**Comment by hevet** [comment]
Działa poprawnie, dzięki.
