### ISSUE TITLE
Zalukaj

### ISSUE THREAD

**Issue by Ahxide** [mbebe/blomqvist#198]
Czy wtyczka Zalukaj dziala? Mam vip konto i za kazdym razem gdy probuje sie zalogowac pisze "Blad wlogowaniu"

**Comment by tomusfl** [comment]
wydaje mi sie ze dodali jakies zabezpieczenie wczoraj - byla przerwa techniczna. Na stronie zalukaj.com da sie zalogowac, we wtczce nie. Raczej niemozliwe, abym sie pomylil w kodziez obrazka 5 razy z rzedu, na stronie zawsze dziala

**Comment by mbebe** [comment]
podeslijcie na maila konto. jedyne jakie mam to takie, gdzie nie pojawia sie captcha. ;-/

**Comment by Ahxide** [comment]
Wyslalem ci na proton

**Comment by mbebe** [comment]
poszla poprawka w repo.

**Comment by Ahxide** [comment]
Wyprobowalem nowa wersje i nadal nie dziala. Teraz captcha sie nie wyswietla podczas logowania. Zaraz po logowaniu pokazuje sie "Blad Logowania", na stronie dziala.

**Comment by tete90** [comment]
U mnie captcha się także nie wyświetla , ale loguje się normalnie i wszystko działa.

**Comment by tomusfl** [comment]
Zainstalowalem wersje2.3 i zadzialalo.
U mnie captcha sie wyswietlilo dla odmiany ale zalogowalo prawidlowo

**Comment by Ahxide** [comment]
dziwne, sprobowalem teraz i dziala...
