### ISSUE TITLE
kreskowkitv

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#20]
Do testow.
[plugin.video.kreskowkitv-1.0.zip](https://github.com/mbebe/blomqvist/files/2496761/plugin.video.kreskowkitv-1.0.zip)

**Comment by kopernik1983** [comment]
losowo potrzaskałem trochę tytułów i wszystko jest Ok. Szukanie też działa.

**Comment by xxcriticxx** [comment]
@kopernik1983 zalozyc nowy temat/issue please

**Comment by krecik71** [comment]
działa na kodi17.6 mam tylko pytanie czy działa wam bolek i lolek obojetnie jaki sezon

**Comment by xxcriticxx** [comment]
@krecik71 bolek i lolek jest nadawany z youtuba. masz plugin do yt zamontowany?

**Comment by krecik71** [comment]
Kol.@xxcriticxx mam.Tu kawałek loga:
08:18:53.344 T:18446744071570471200  NOTICE: [plugin.video.youtube] Running: YouTube (6.1.4) on Krypton (Kodi-17.6) with Python 2.7.12
                                            	Path: /
                                            	Params: {}
08:18:59.584 T:18446744071723551008  NOTICE: [plugin.video.youtube] Running: YouTube (6.1.4) on Krypton (Kodi-17.6) with Python 2.7.12
                                            	Path: /kodion/search/list/
                                            	Params: {}
08:19:03.430 T:18446744071723551008  NOTICE: [plugin.video.youtube] Running: YouTube (6.1.4) on Krypton (Kodi-17.6) with Python 2.7.12
                                            	Path: /kodion/search/input/
                                            	Params: {}
08:20:13.079 T:18446744071564687648  NOTICE: [plugin.video.youtube] Running: YouTube (6.1.4) on Krypton (Kodi-17.6) with Python 2.7.12
                                            	Path: /play/
                                            	Params: {'video_id': 'sjrI1krO_M4'}
08:20:16.401 T:18446744071839254816  NOTICE: VideoPlayer: Opening: https://r8---sn-u2oxu-a01s.googlevideo.com/videoplayback?initcwndbps=545000&gir=yes&source=youtube&pl=24&ratebypass=yes&gcr=pl&c=WEB&mime=video%2Fmp4&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&txp=5431432&fvip=1&ei=nhrMW7-VLp2oyQX6_pKIBQ&key=yt6&ip=79.185.184.8&lmt=1540061538391985&dur=594.570&itag=18&id=o-AJY3aiYjNRpfZLNonACbFjpL_k8PPASM2gD0a-jj0frN&requiressl=yes&mm=31%2C29&mn=sn-u2oxu-a01s%2Csn-4g5ednle&ipbits=0&mt=1540102685&mv=m&clen=33113345&ms=au%2Crdu&expire=1540124414&signature=D817E152E4844D342D5530613F04E266C2F24818.CCBFA4AACCFA26116727B25FD95E7BA907CC6C3E|Cookie=CONSENT%3DWP.272ab6%3B%20GPS%3D1%3B%20PREF%3Df1%3D50000000%3B%20VISITOR_INFO1_LIVE%3DqpyqJMw_oxs%3B%20YSC%3DGe12BSuhwOA%3B%20s_gl%3Dda31afa91505e36f8d5ab291d88e299dcwIAAABQTA%3D%3D%3B
08:20:16.402 T:18446744071839254816 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
08:20:16.556 T:18446744071569930528  NOTICE: Creating InputStream
08:20:16.956 T:18446744071569930528  NOTICE: Creating Demuxer
08:20:17.213 T:18446744071569930528  NOTICE: Opening stream: 0 source: 256
08:20:17.214 T:18446744071569930528  NOTICE: Creating video codec with codec id: 28
08:20:18.935 T:18446744071569930528  NOTICE: Creating video thread
08:20:18.935 T:18446744071569930528  NOTICE: Opening stream: 1 source: 256
08:20:18.935 T:18446744071569930528  NOTICE: Finding audio codec for: 86018
08:20:18.935 T:18446744071564687648  NOTICE: running thread: video_thread
08:20:18.937 T:18446744071569930528  NOTICE: Creating audio thread
08:20:18.937 T:2146957600  NOTICE: running thread: CVideoPlayerAudio::Process()
08:20:18.948 T:2146957600  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
08:20:18.971 T:18446744071828936992  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
08:20:18.975 T:18446744071828936992  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 42528 m_frames: 2658 m_frameSize: 8 channels: 2
08:20:19.060 T:18446744071839254816  NOTICE: Using GL_TEXTURE_2D
08:20:19.060 T:18446744071839254816  NOTICE: GL: Using MediaCodec (Surface) render method
08:20:19.061 T:18446744071839254816  NOTICE: GL: NPOT texture support detected
08:20:22.313 T:18446744071839254816  NOTICE: CVideoPlayer::CloseFile()
08:20:22.313 T:18446744071839254816  NOTICE: VideoPlayer: waiting for threads to exit
08:20:22.315 T:18446744071569930528  NOTICE: CVideoPlayer::OnExit()
08:20:22.315 T:18446744071569930528  NOTICE: Closing stream player 1
08:20:22.315 T:18446744071569930528  NOTICE: Waiting for audio thread to exit
08:20:22.371 T:2146957600  NOTICE: thread end: CVideoPlayerAudio::OnExit()
08:20:22.371 T:18446744071569930528  NOTICE: Closing audio device
08:20:22.432 T:18446744071569930528  NOTICE: Deleting audio codec
08:20:22.432 T:18446744071569930528  NOTICE: Closing stream player 2
08:20:22.432 T:18446744071569930528  NOTICE: waiting for video thread to exit
08:20:22.469 T:18446744071564687648  NOTICE: thread end: video_thread
08:20:22.470 T:18446744071569930528  NOTICE: deleting video codec
08:20:22.718 T:18446744071839254816  NOTICE: VideoPlayer: finished waiting
08:20:22.773 T:18446744071839254816   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
08:20:22.820 T:18446744071839254816  NOTICE: CVideoPlayer::CloseFile()
08:20:22.820 T:18446744071839254816  NOTICE: VideoPlayer: waiting for threads to exit
08:20:22.821 T:18446744071839254816  NOTICE: VideoPlayer: finished waiting
08:20:22.821 T:18446744071839254816  NOTICE: CVideoPlayer::CloseFile()
08:20:22.821 T:18446744071839254816  NOTICE: VideoPlayer: waiting for threads to exit
08:20:22.821 T:18446744071839254816  NOTICE: VideoPlayer: finished waiting
08:20:30.183 T:18446744071839254816   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
08:20:32.008 T:18446744071567288608  NOTICE: ResolveURL: Initializing ResolveURL version: 6.2.1
08:20:47.981 T:18446744071665350944  NOTICE: Previous line repeats 2 times.
08:20:47.981 T:18446744071665350944 WARNING: Attempt to use invalid handle 12
08:20:53.695 T:18446744071665350944  NOTICE: ResolveURL: Initializing ResolveURL version: 6.2.1
08:20:54.908 T:18446744071665350944 WARNING: Attempt to use invalid handle 13
08:21:12.532 T:18446744071665350944  NOTICE: ResolveURL: Initializing ResolveURL version: 6.2.1
08:21:13.228 T:18446744071665350944 WARNING: Attempt to use invalid handle 14
08:21:18.604 T:18446744071665350944  NOTICE: ResolveURL: Initializing ResolveURL version: 6.2.1
08:21:19.408 T:18446744071665350944 WARNING: Attempt to use invalid handle 15
08:21:22.804 T:18446744071664765216  NOTICE: ResolveURL: Initializing ResolveURL version: 6.2.1
08:21:23.604 T:18446744071664765216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kreskowkitv/main.py", line 286, in <module>
                                                getLinks(exlink)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kreskowkitv/main.py", line 209, in getLinks
                                                items = getVideosOk(exlink)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kreskowkitv/main.py", line 241, in getVideosOk
                                                href= parseDOM(link, 'a', ret='href')[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
08:21:23.886 T:18446744071839254816   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.kreskowkitv/?url=https%3A%2F%2Fwww.kreskowki.tv%2Fkreskowka%2Fpokaz%2F19423%2Fs11_bolek_i_lolek_w_europie__odcinek_05__wyscig_renow&mode=getLinks&page=1]
08:21:29.991 T:18446744071664765216  NOTICE: ResolveURL: Initializing ResolveURL version: 6.2.1
08:21:30.747 T:18446744071664765216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kreskowkitv/main.py", line 286, in <module>
                                                getLinks(exlink)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kreskowkitv/main.py", line 209, in getLinks
                                                items = getVideosOk(exlink)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kreskowkitv/main.py", line 241, in getVideosOk
                                                href= parseDOM(link, 'a', ret='href')[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
08:21:31.025 T:18446744071839254816   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.kreskowkitv/?url=https%3A%2F%2Fwww.kreskowki.tv%2Fkreskowka%2Fpokaz%2F19422%2Fs11_bolek_i_lolek_w_europie__odcinek_04__pod_kraterem&mode=getLinks&page=1]
08:21:37.722 T:18446744071665350944  NOTICE: ResolveURL: Initializing ResolveURL version: 6.2.1
08:21:38.490 T:18446744071665350944 WARNING: Attempt to use invalid handle 18
08:21:42.386 T:18446744071664769312  NOTICE: ResolveURL: Initializing ResolveURL version: 6.2.1
08:21:43.240 T:18446744071664769312   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kreskowkitv/main.py", line 286, in <module>
                                                getLinks(exlink)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kreskowkitv/main.py", line 209, in getLinks
                                                items = getVideosOk(exlink)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kreskowkitv/main.py", line 241, in getVideosOk
                                                href= parseDOM(link, 'a', ret='href')[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
08:21:43.505 T:18446744071839254816   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.kreskowkitv/?url=https%3A%2F%2Fwww.kreskowki.tv%2Fkreskowka%2Fpokaz%2F19391%2Fs09_bolek_i_lolek_wsrod_gornikow__odcinek_05__pasowanie_na_gornika&mode=getLinks&page=1]

**Comment by kashkash18** [comment]
Myvi.tv nie odpala , Denver, ostatni dinozaur odcinek 51

**Comment by xxcriticxx** [comment]
@krecik71 dzięki za log :)
