### ISSUE TITLE
Hejo.tv - nie wczytuje kanałów 

### ISSUE THREAD

**Issue by Kantel88** [mbebe/blomqvist#200]
...kreci kółeczko ale nie odpala kanalow. Loguje normalnie,  na stronie śmiga :)

**Comment by mbebe** [comment]
Nie bylo przejsciowych problemow? U mnie jest bez bledu.

**Comment by kunraf** [comment]
Jest podwojone menu, telewizja nie pokazuje ikon kanałów, lista kanałów się powtarza

**Comment by isio831** [comment]
U mnie dziala ok

**Comment by tete90** [comment]
U mnie także działa ok.

**Comment by kunraf** [comment]
problem dalej jest, i na androidzie i na windowsie

**Comment by leonzawodowiec12** [comment]
u mnie to samo brak ikon i lista się powtarza

**Comment by kunraf** [comment]
myśli ktoś żeby to naprawić?
niby nic a pomagało.

**Comment by mbebe** [comment]
poszla aktualizacja

**Comment by kunraf** [comment]
działa, dzięki
