### ISSUE TITLE
Czy dzialaja wam wtyczki od alltube / cda?

### ISSUE THREAD

**Issue by gs188** [mbebe/blomqvist#201]
Alltube mi przestal dzialac tzn nie ma linkow dzialajacych - cos z wtyczka czy u mnie cos trzeba w kodi przestawic?

**Comment by notoco** [comment]
Alltube - Irlandczyk (2019) [pierwszy film jaki mi się wyświetlił] - działa każdy z 4 linków
cda.pl - działa - zarówno normalne jak i premium...

**Comment by gs188** [comment]
sprawdze jeszcze raz ale u mnie ostatnio kazdy film mial tylko jeden link i to nie dzialajacy.  Cos z resolverem moze?

**Comment by FXcodi** [comment]
U mnie też nie działa film Irlandczyk 4x link onlystream , żaden nie działa.

**Comment by notoco** [comment]
Sprawdźcie jaką macie wersję resolvera.

**Comment by FXcodi** [comment]
Można poprosić o link do pobrania?

**Comment by notoco** [comment]
https://github.com/CherryKodi/CHERRY
Tam jest wersja 0.0.1 - sama się zaktualizuje do wersji 0.0.2

**Comment by FXcodi** [comment]
No to teraz gra i buczy , dzięki wielkie.

**Comment by gs188** [comment]
OK a jaka wersja resolvera powinna byc?

**Comment by notoco** [comment]
6.4.83  - to ostatnia w repo ptw.

**Comment by gs188** [comment]
Dzieki za pomoc, sprawdze.

**Comment by gs188** [comment]
Zalozylem te repo i.... nic nie pomoglo.   URL resolver sie sam nie zaktualizowal.  Ale dzieki temu ze kolega notoco podal numer wersji wymaganej w googlach znalazlem i zainstalowalem 'recznie'.  Smiga, dzieki ;)

**Comment by notoco** [comment]
Ręcznie bym nie aktualizował. Z repo się aktualizuje, tylko trzeba wymusić aktualizację. Kodi samo z siebie robi aktualizację raz na 24 h.

**Comment by gs188** [comment]
no wlasnie jakos nie widzialem tej wtyczki (resolver) na liscie wtyczek w repo ptw/polishteam... no i chyba dlatego sam sie nie aktualizowal.  Moze musze skasowac repo kompletnie i zainstalowac od nowa?

**Comment by notoco** [comment]
Tej wtyczki nigdy nie zobaczysz bo jest tylko zależnością. Masz po prostu zaktualizować wtyczki kodi. Nie ręcznie, ale wyszukać aktualizację. Pojawią się wtedy te które mają nowsze wersje.

**Comment by gs188** [comment]
Rozumiem, dzieki jeszcze raz.
