### ISSUE TITLE
Błąd hejo.tv

### ISSUE THREAD

**Issue by kodiwpigulce** [mbebe/blomqvist#208]
`19:43:03.215 T:6956 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.hejotv/?url=&mode=settings&page=1
19:43:03.215 T:6956   ERROR: InputStream: Error opening, plugin://plugin.video.hejotv/?url=&mode=settings&page=1
19:43:19.917 T:8112   ERROR: X:\Kodi18\portable_data\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
19:43:21.109 T:18632   ERROR: Previous line repeats 5 times.
19:43:21.109 T:18632 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.hejotv/?url=&mode=settings&page=1
19:43:21.109 T:18632   ERROR: InputStream: Error opening, plugin://plugin.video.hejotv/?url=&mode=settings&page=1
19:43:21.116 T:19840   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.hejotv/?url=&mode=settings&page=1]
19:43:21.119 T:18632 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.hejotv/?url=&mode=settings&page=1
19:43:21.119 T:18632   ERROR: InputStream: Error opening, plugin://plugin.video.hejotv/?url=&mode=settings&page=1
19:43:24.677 T:1032   ERROR: X:\Kodi18\portable_data\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
19:43:25.600 T:1032   ERROR: Previous line repeats 2 times.
19:43:25.600 T:1032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc4 in position 97: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "X:\Kodi18\portable_data\addons\plugin.video.hejotv\main.py", line 876, in <module>
                                                ListTv(exlink)
                                              File "X:\Kodi18\portable_data\addons\plugin.video.hejotv\main.py", line 337, in ListTv
                                                links= getTV(exlink)
                                              File "X:\Kodi18\portable_data\addons\plugin.video.hejotv\main.py", line 386, in getTV
                                                links = parseDOM(html, 'div', attrs={'class': "col-lg-3 col-md-4 col-sm-6 col-12 p-2"})
                                              File "X:\Kodi18\portable_data\addons\script.module.parsedom\lib\CommonFunctions.py", line 299, in parseDOM
                                                temp = _getDOMContent(item, name, match, ret).strip()
                                              File "X:\Kodi18\portable_data\addons\script.module.parsedom\lib\CommonFunctions.py", line 162, in _getDOMContent
                                                end = html.find(endstr, start)
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 97: ordinal not in range(128)
                                            -->End of Python script error report<--
19:43:25.630 T:11476   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.hejotv/?mode=listtv&page=1&url=https%3a%2f%2fhejo.tv%2f
19:43:25.634 T:19840   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hejotv/?mode=listtv&page=1&url=https%3a%2f%2fhejo.tv%2f) failed
19:43:25.728 T:19572 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.hejotv/?url=&mode=settings&page=1
19:43:25.728 T:19572   ERROR: InputStream: Error opening, plugin://plugin.video.hejotv/?url=&mode=settings&page=1
`

Wywala się jak wchodzi się w zakładkę telewizja.

**Comment by Kantel88** [comment]
Dokładnie, wyskakuje błąd dodatku po zalogowaniu i wejściu w telewizje

**Comment by mbebe** [comment]
poprawilem

**Comment by tete90** [comment]
Dziękujemy ślicznie mistrzu.
