### ISSUE TITLE
Propozycje Wtyczek

### ISSUE THREAD

**Issue by kopernik1983** [mbebe/blomqvist#21]
Można by w wolnej chwili coś z tego wyciągnąć https://serialnet.pl/ niby jest zagłębienie we wtyczce sd-xbmc.org ale działa jak cała wtyczka czyli w zasadzie wcale.

**Comment by mbebe** [comment]
serialnet w repo

**Comment by kopernik1983** [comment]
I już Sprawdzamy :)

**Comment by kopernik1983** [comment]
Parę losowych sprawdzone i działa. Wyszukiwanie tez działa , więc jest jak najbardziej w porządku. Podziękował.

**Comment by edgarok** [comment]
To może AXN player

**Comment by edgarok** [comment]
@mbebe  coś rozwaliło listę możesz zerknąć?
