### ISSUE TITLE
segos.es -> hdseans.pl

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#215]
Segos.es zmieniło swoją stronę, i dodało nowy adres : hdseans.pl
Da się?

**Comment by mbebe** [comment]
Potrzebuje maila, bo mam nicka. :-) Jak cos to na maila. :-)

**Comment by notoco** [comment]
o2.pl

**Comment by mbebe** [comment]
Ok.pozniej lukne.

**Comment by Seico** [comment]
Hejka , kiedy można będzie spodziewać się aktualizacji wtyczki ?

**Comment by Bogdan16** [comment]
witam mbebe
mam znowu problem z logowaniem do hdseans.pl

Pozdrawiam Bogdan16

**Comment by notoco** [comment]
Strona padła, więc nie działa
