### ISSUE TITLE
Wesołych świąt dla mbebe i wielu innych którzy wspomagają

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#219]
Pogodnych, radosnych, zdrowych i szczęśliwych w gronie najbliższych Świąt Bożego Narodzenia.

**Comment by Huero23** [comment]
Merry Christmas & Big Thank You @mbebe without you non of this would be possible very greatful for all your time and huge contributions to all of this and to this Polish Community Thank You as well & Happy Holidays !

**Comment by mbebe** [comment]
Wszystkiego najlepszego. Spokojnych i zdrowych Świąt.

**Comment by Cinek77** [comment]
Życzę Wszystkim Spokojnych Świąt :)
Oraz spełnienia najskrytszych marzeń w Nowym Roku :)

**Comment by notoco** [comment]
To i ja tak skromnie życzę wam +1

**Comment by krecik71** [comment]
Serdeczne życzenia wielu radosnych doznań z okazji Świąt Bożego Narodzenia, wszystkiego co najlepsze w każdym dniu nadchodzącego Nowego Roku!
