### ISSUE TITLE
Segos,

### ISSUE THREAD

**Issue by wisiann** [mbebe/blomqvist#22]
Cos przestal u mnie dzialac od trzech dni,
Tez tak macie?

**Comment by kopernik1983** [comment]
@wisiann jaka wersja dodatku??? U mnie problem jest taki że w repo nie widzi wersji 3.4 i ta działa , musiałem z zipa aktualizować.

**Comment by mbebe** [comment]
poprawka w repo by widzialo wersje 3.4

**Comment by kashkash18** [comment]
@mbebe cda-hd też nie widać w repo

**Comment by kashkash18** [comment]
Segos u mnie odpala filmy poprawnie ale jest problem z okładkami. Kilka sztuk się wyświetla ale w większości brak okładek.

I mała prośba odnośnie Nasze-kino.tv , tam też okładki się nie pokazują i brak opisów. Podpis dodał opcje opisów ale wtyczka wtedy chodzi strasznie wolno. 

Jak by się dało coś z tym zrobić to będę wdzięczny.

**Comment by mbebe** [comment]
Z powodu cloudflare nie pokazuje okladek sciaganych ze strony segos. Opisy mozna dodac, ale faktycznie zwolnia wtyczke.

**Comment by wisiann** [comment]
@kopernik1983,
Masz racje,przy update z wtyczki nie widzi 3.4, tylko 3.3,
Trzeba z poziomu repo to zrobic,dzieki

**Comment by kashkash18** [comment]
@wisiann wejdź w wyszukiwanie aktualizacji a potem w repo mbebe , powinna się pojawić wersja 3.4

**Comment by wisiann** [comment]
Never mind, 
Wszystko bangla,
Zamykam, dzieki

**Comment by kashkash18** [comment]
U mnie działają wtyczki bez problemu. Zainstaluj na nowo kodi i sprawdź , bo wygląda na to że problem nie jest w wtyczkach

**Comment by kendo999** [comment]
dzieki  bede musial postawic kodi na  nowo
W dniu 2018-10-22 20:05:37 użytkownik kashkash18 <notifications@github.com> napisał:
U mnie działają wtyczki bez problemu. Zainstaluj na nowo kodi i sprawdź , bo wygląda na to że problem nie jest w wtyczkach
