### ISSUE TITLE
fili.cc problem

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#23]

**Comment by rafalmar1981** [comment]
UTRresolver ERROR: [Set either url, or host AND media_id. No other combinations are valid.]" mam od kilku ni taki komunikat korzystalem z resolvera od pdpis-u i nagle przestało działać fili.cc próbowałem z resolvera cherry też to samo te same streemy na innych wtyczkach działają jak to rozwiązać

**Comment by mbebe** [comment]
poprawka w repo. wersja 2.3 filicc

**Comment by mbebe** [comment]
przy wlaczonym i wylaczonym proxy w opcjach to samo sie dzieje?

**Comment by kopernik1983** [comment]
Coś tam jest na rzeczy , bez względu na resolver. Nie ma co podawać konkretnego tytułu bo na każdym nie odpala. Sprawdzałem 3 ResolveUrl i na każdym to samo.

**Comment by mbebe** [comment]
https://github.com/mbebe/blomqvist/issues/17 sprawdz czy nie masz podobnego problemu.

**Comment by mbebe** [comment]
Usunalem wpis, bo nie widzialem odp.kopernika. :-)

**Comment by rafalmar1981** [comment]
kurcze jak ja bym umiał takie rzeczy robić to bym sobie poradził za duża magia z tym dlamnie fajnie ze dajesz rade coś kombinować podpis ma urlop czy co tam u nich

**Comment by krecik71** [comment]
Hej.
Coś nie działa 
log.
4:22:34.143 T:9576   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.filisertv/
14:22:34.181 T:9576   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.filisertv/) failed
14:22:38.008 T:8204  NOTICE: [FanFilm] ######################### FANFILM ############################
14:22:38.008 T:8204  NOTICE: [FanFilm] ####### CURRENT FANFILM VERSIONS REPORT ######################
14:22:38.008 T:8204  NOTICE: [FanFilm] ### FANFILM PLUGIN VERSION: 2018.09.01.0 ###
14:22:38.008 T:8204  NOTICE: [FanFilm] ### FANFILM MEDIA VERSION: 2018.07.17.0 ###
14:22:38.008 T:8204  NOTICE: [FanFilm] ###############################################################
14:22:39.514 T:9576   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
14:22:44.460 T:10116  NOTICE: script.grab.fanart: Grab Fanart Service Started
14:23:19.673 T:5336  NOTICE: metahandler: Initializing MetaHandlers version: 3.0.2
14:23:20.643 T:5336  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.10.2
14:23:23.211 T:5336   ERROR: metahandler: Error connecting to TMDB: HTTP Error 403: Forbidden
14:23:23.245 T:5336  NOTICE: metahandler: No SQLite rows requiring update
14:23:23.322 T:120   ERROR: XFILE::CDirectory::GetDirectory - Error getting
14:24:03.041 T:7464  NOTICE: ResolveURL: Initializing ResolveURL version: 6.2.1
14:24:07.627 T:9576  NOTICE: VideoPlayer: Opening:
14:24:07.627 T:9576 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:24:07.678 T:9576   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
14:24:07.678 T:9576   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
14:24:07.679 T:8344  NOTICE: Creating InputStream
14:24:07.976 T:8344   ERROR: perror:
14:24:07.977 T:8344   ERROR: Error on dvdnav_open
14:24:07.977 T:8344   ERROR: CVideoPlayer::OpenInputStream - error opening []
14:24:07.977 T:8344  NOTICE: CVideoPlayer::OnExit()
14:24:07.977 T:9576   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.filisertv/?foldername=Sprzedawca+%C5%9Bmierci&page=1&ex_link=https%3A%2F%2Ffili.cc%2Ffilm%2Fsprzedawca-smierci-1993%2F16279&mode=getLinks]
14:24:07.977 T:9576  NOTICE: CVideoPlayer::CloseFile()
14:24:07.978 T:9576  NOTICE: VideoPlayer: waiting for threads to exit
14:24:07.978 T:9576  NOTICE: VideoPlayer: finished waiting
14:24:07.978 T:9576  NOTICE: CVideoPlayer::CloseFile()
14:24:07.978 T:9576  NOTICE: VideoPlayer: waiting for threads to exit
14:24:07.978 T:9576  NOTICE: VideoPlayer: finished waiting
14:24:14.409 T:4308 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:17648, P:1368, O:15864.
14:24:15.900 T:4436 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Wersja%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DWszystkie%5B%2FCOLOR%5D&page=1&ex_link=&mode=setFiltr%3Af_ver
14:24:15.900 T:4436   ERROR: InputStream: Error opening, plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Wersja%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DWszystkie%5B%2FCOLOR%5D&page=1&ex_link=&mode=setFiltr%3Af_ver
14:24:18.848 T:5496 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DSeriale+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3As_sort
14:24:18.848 T:5496   ERROR: InputStream: Error opening, plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DSeriale+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3As_sort
14:24:18.852 T:5496 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3Af_sort
14:24:18.852 T:5496   ERROR: InputStream: Error opening, plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3Af_sort
14:24:29.268 T:9044 WARNING: Attempt to use invalid handle -1
14:25:04.586 T:2028  NOTICE: ResolveURL: Initializing ResolveURL version: 6.2.1
14:25:36.931 T:9576  NOTICE: VideoPlayer: Opening:
14:25:36.931 T:9576 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:25:36.931 T:9576   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
14:25:36.931 T:9576   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
14:25:36.932 T:6384  NOTICE: Creating InputStream
14:25:36.937 T:6384   ERROR: perror:
14:25:36.937 T:6384   ERROR: Error on dvdnav_open
14:25:36.938 T:6384   ERROR: CVideoPlayer::OpenInputStream - error opening []
14:25:36.938 T:6384  NOTICE: CVideoPlayer::OnExit()
14:25:36.938 T:9576   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.filisertv/?foldername=Na+pla%C5%BCy+Chesil&page=1&ex_link=https%3A%2F%2Ffili.cc%2Ffilm%2Fna-plazy-chesil-2017%2F13292&mode=getLinks]
14:25:36.939 T:9576  NOTICE: CVideoPlayer::CloseFile()
14:25:36.939 T:9576  NOTICE: VideoPlayer: waiting for threads to exit
14:25:36.939 T:9576  NOTICE: VideoPlayer: finished waiting
14:25:36.939 T:9576  NOTICE: CVideoPlayer::CloseFile()
14:25:36.939 T:9576  NOTICE: VideoPlayer: waiting for threads to exit
14:25:36.939 T:9576  NOTICE: VideoPlayer: finished waiting
14:25:42.234 T:8600 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Wersja%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DWszystkie%5B%2FCOLOR%5D&page=1&ex_link=&mode=setFiltr%3Af_ver
14:25:42.234 T:8600   ERROR: InputStream: Error opening, plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Wersja%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DWszystkie%5B%2FCOLOR%5D&page=1&ex_link=&mode=setFiltr%3Af_ver
14:25:42.242 T:2004 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DSeriale+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3As_sort
14:25:42.242 T:2004   ERROR: InputStream: Error opening, plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DSeriale+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3As_sort
14:25:42.252 T:2004 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3Af_sort
14:25:42.252 T:2004   ERROR: InputStream: Error opening, plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3Af_sort
14:25:42.263 T:2004 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Wersja%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DWszystkie%5B%2FCOLOR%5D&page=1&ex_link=&mode=setFiltr%3Af_ver
14:25:42.263 T:2004   ERROR: InputStream: Error opening, plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Wersja%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DWszystkie%5B%2FCOLOR%5D&page=1&ex_link=&mode=setFiltr%3Af_ver
14:25:42.271 T:8600 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DSeriale+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3As_sort
14:25:42.272 T:8600   ERROR: InputStream: Error opening, plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DSeriale+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3As_sort
14:25:42.276 T:4188 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3Af_sort
14:25:42.276 T:4188   ERROR: InputStream: Error opening, plugin://plugin.video.filisertv/?foldername=%5BCOLOR+lightblue%5DFilmy+Sortuj%3A+%5B%2FCOLOR%5D+%5BCOLOR+whilte%5DData+dodania+%28od+najnowszego%29%5B%2FCOLOR%5D&page=1&ex_link=&mode=setSort%3Af_sort
14:26:06.979 T:9940  NOTICE: ResolveURL: Initializing ResolveURL version: 6.2.1
14:26:22.842 T:9576  NOTICE: VideoPlayer: Opening:
14:26:22.842 T:9576 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:26:22.843 T:9576   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
14:26:22.843 T:9576   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
14:26:22.844 T:7500  NOTICE: Creating InputStream
14:26:22.848 T:7500   ERROR: perror:
14:26:22.848 T:7500   ERROR: Error on dvdnav_open
14:26:22.848 T:7500   ERROR: CVideoPlayer::OpenInputStream - error opening []
14:26:22.848 T:7500  NOTICE: CVideoPlayer::OnExit()
14:26:22.849 T:9576   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.filisertv/?foldername=Koniec+naszych+dni&page=1&ex_link=https%3A%2F%2Ffili.cc%2Ffilm%2Fkoniec-naszych-dni-2016%2F15757&mode=getLinks]
14:26:22.850 T:9576  NOTICE: CVideoPlayer::CloseFile()
14:26:22.850 T:9576  NOTICE: VideoPlayer: waiting for threads to exit
14:26:22.850 T:9576  NOTICE: VideoPlayer: finished waiting
14:26:22.850 T:9576  NOTICE: CVideoPlayer::CloseFile()
14:26:22.850 T:9576  NOTICE: VideoPlayer: waiting for threads to exit
14:26:22.850 T:9576  NOTICE: VideoPlayer: finished waiting

**Comment by mbebe** [comment]
poprawka w wersji 2.4 w repo.

**Comment by kashkash18** [comment]
2.4 działa na Androidzie :) Ciekawe jest to że w telefonie mam bookera reklam i wtyka nie widzi filmów :) a na Tv z Androidem idzie bez problemu :)

**Comment by rafalmar1981** [comment]
mbebe tyś jest gość dobra robota a jest jakaś szansa by zrobić coś z fanfilmem wszysko z szukajki mi pomija i ekino i kinomaniak na al tube sie łapie teraz sprawdze czy filiser odpala na fanfilm dodam ze instalowałem trzy wersje fan filmu z  pierwszego wrzesnia ta z 10 czerwca i jakas z  lipca ta kilku resorvelach

**Comment by notoco** [comment]
@rafalmar1981 - fanfilm to nie tutaj - pytaj tutaj: https://github.com/CherryKodi/CHERRY
