### ISSUE TITLE
Videopenny

### ISSUE THREAD

**Issue by oliwer12345** [mbebe/blomqvist#231]
Witam wtyczka videopenny  znowu ma problem z otwieraniem zrodel. Youdbox wogole nie otwiera. Clipwatching tylko kreci i tez nie otwiera.wiekszosc seriali jest tylko w tych 2 zrodlach

**Comment by gadom92** [comment]
U mnie nie ma problemów z odtwarzaniem. Za to nie działa wyszukiwarka. Nie ważne co się wpisze wywala wszystkie filmy i seriale w wynikach wyszukiwania

**Comment by oliwer12345** [comment]
Dzieki wlasnie znalazlem wersje 2.1 i dziala.

**Comment by stalker84** [comment]
witam videopenny w wersji 2.1 nie działa

**Comment by oliwer12345** [comment]
Wlasnie sprawdzilem w uk dziala.

**Comment by Bogdan16** [comment]
witam 

dzisiaj nie dziala 

Pozdrawiam

**Comment by oliwer12345** [comment]
Witam ktos cos wie dlaczego videopenny nic nie pokazuje.
