### ISSUE TITLE
Czy bugatsinho naprawił Sport365?

### ISSUE THREAD

**Issue by kisiel999** [mbebe/blomqvist#237]
Dzień dobry,
ogarnia ktoś, czy bugatsinho naprawił wtyczkę Sport365, bo niby przedwczoraj była aktualizacja, ale coś mi nie działa nadal Sport365? Nie mam logów przed sobą, bo sprawdzałem na Android TV.

**Comment by mbebe** [comment]
Mozesz od nich probowac.
https://github.com/Maniac2017/repository.Maniac/blob/master/repor/plugin.video.1x2/plugin.video.1x2-1.0.27.zip
