### ISSUE TITLE
Boso przez świat 

### ISSUE THREAD

**Issue by timtumturutumtum** [mbebe/blomqvist#24]
@Mbebe nie podjął byś się zrobienia wtyczki "boso przez swiat" ze strony http://www.bosoprzezswiat.kinofabryka.pl/ ? 
Wszystko na stronie ładnie poukładane,  dobrze było by mieć to bezpośrednio w kodi.

**Comment by mbebe** [comment]
to tylko filmy z cejrowskim powinny byc?

**Comment by timtumturutumtum** [comment]
@Mbebe tak to sobie wyobrażam, na stronie są posortowane tematycznie odcinki boso. 
Będę bardzo wdzięczny za wtyczkę, pewnie fani serii (nie koniecznie samego cejrowskiego) też się znajdą i docenią Twoją ciężką pracę nad tym pluginem :)

**Comment by mbebe** [comment]
dodane do repo

**Comment by notoco** [comment]
@mbebe - za szybko działasz i nawet nie zdążyłem podsunąć pomysłu - może ogarnąć całą kinofabryka.pl?

**Comment by mbebe** [comment]
rzuccie okiem, bo wg. mnie duzo zrodel to yt, a tam to filmy juz pousuwane.

**Comment by timtumturutumtum** [comment]
@Mbebe jesteś wielki. Super było by gdyby "białe" linki ze strony boso też się uruchamiały, są one jakoś inaczej dodane,  musiał  byś na to spojrzeć. Mimo wszystko super robota,  jestem mega wdzięczny! 
Samo kinofabryka jest świetne, ale jak napisałeś cześć materiału jest niedostępna, chyba ze zrobić jako wtyczkę na zasadzie,  działa co działa.

**Comment by mbebe** [comment]
poprawka w repo do tych bialych linkow. i tak malo ktore dzialaja.

**Comment by timtumturutumtum** [comment]
@Mbebe spojrzysz co się podzialo? Nic nie wczutuje,  w logach nie znalazłem nic

**Comment by mbebe** [comment]
co tzn. nic nie wczytuje? nie otwiera sie wtyczka? nie odtwarzaja sie linki?
