### ISSUE TITLE
Hejo.tv - filmy i seriale 

### ISSUE THREAD

**Issue by Kantel88** [mbebe/blomqvist#244]
Niestety dział filmy jest pusty a przy serialach jest błąd dodatku, jakby można było poprawić było by super ...;)

**Comment by xxcriticxx** [comment]
@Kantel88 czasem trzeba odwiedzic strone internetowa

Dostęp dla niezarejestrowanych użytkowników został wyłączony. Zarejestruj darmowe konto aby móc swobodnie oglądać materiały w naszym serwisie.

**Comment by Kantel88** [comment]
> @Kantel88 czasem trzeba odwiedzic strone internetowa
> 
> Dostęp dla niezarejestrowanych użytkowników został wyłączony. Zarejestruj darmowe konto aby móc swobodnie oglądać materiały w naszym serwisie.

Ale ja mam Premium kolego I na stronie mi chodzi;)

**Comment by xxcriticxx** [comment]
@Kantel88 maja wlasna wtyczke testowales?

 `https://hejo.tv/plugin.video.hejotv-2.2.6.zip`

**Comment by FXcodi** [comment]
U mnie też pusto w folderach, nawet na wersji 2.2.6 od hejo
Tv działa bez problemu.

**Comment by mbebe** [comment]
poszla poprawka. 2.2.7
