### ISSUE TITLE
Zalukaj.com

### ISSUE THREAD

**Issue by xenixganero** [mbebe/blomqvist#246]
Witam, wtyczka Zalukaj przestała działać w dniu dzisiejszym, chyba są zmiany na stronie, przy próbie zalogowania wywala błąd.

**Comment by rafalmar1981** [comment]
potwierdzam przy logowaniu wywala błąd

**Comment by art8814** [comment]
Tutaj to samo. Bez logowania da się oglądać. Podczas próby zalogowania wywala błąd.

**Comment by Medar1061** [comment]
Dokładnie jak u kolegów, w przeglądarce działa bez zarzutu.

**Comment by mbebe** [comment]
poszla poprawka. wersja 2.3.1 w repo.

**Comment by xenixganero** [comment]
Wielkie dzięki, wtyczka działa już poprawnie. Zamykam temat.

**Comment by Medar1061** [comment]
Poda ktoś link do .zip z poprawką?

**Comment by notoco** [comment]
Jest w repozytorium, wystarczy odświeżyć i zaktualizować
