### ISSUE TITLE
horrortube - nowa wtyczka

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#25]
W repo do sprawdzenia.
W sumie identyczna jak filman, naszekino..

**Comment by krecik71** [comment]
hej 
jak dla mnie działa ok
pozdrowionka

**Comment by xxcriticxx** [comment]
@mbebe thank you

**Comment by wisiann** [comment]
😈

**Comment by kendo999** [comment]
@mbebe wali prezenty  , rozwalił wszystkie hosty w necie,  pozdrawiam
