### ISSUE TITLE
Pastebin

### ISSUE THREAD

**Issue by Arek76** [mbebe/blomqvist#265]
Witam , 
Moglby ktos sprawdzic czy dziala u Was wtyka Pastebin ? Od paru dni wystepuja bledy jakies i nie wiem jak sobie z tym poradzic , Probowalem na tej Paste - RhdnhpkJ  wgralem u mnie i wszystko smiga ale wielu moich znjomych nie moze odpalic bo wystepuje nastepujacy blad : 
https://ibb.co/rGynywm
Niby Kodi 16.8 , Wtyczka najnowsza z repo i lipa , Kombinowalismy i nic nie wyszlo , Reinstalowanie wszystkiego nie pomoglo . Moze jakies sugestie ? 
Dodal bym tu rowniez log ale u mnie wszystko chodzi a ta osoba ktora ma problem nie potrafi wyslac mi Loga . Zreszta u wiekszosci nie dziala ale jest kilka osob u ktorych wszystko smiga az milo . Nie mam pojecia

**Comment by xxcriticxx** [comment]
@Arek76 brakuje tobie spacja pomiędzy `7` i `|`

`https://ebd.cda.pl/805x204/485718817|Ultras|2020|film|2020|` brakuje tobie spacja pomiędzy `7` i `|`

**Comment by Arek76** [comment]
ahh tak sorki , to juz zrobilem , przed chwila kombinowalem i tak zostawilem . Niestety mimo poprawienia nadal nie funkcjonuje ,

**Comment by xxcriticxx** [comment]
na jakim filmie? podaj cos do testow

**Comment by Arek76** [comment]
wpisz sobie pastebin RhdnhpkJ bedziesz mial liste , I na tej liscie u mnie dziala wszystko a u niektorych kompletnie nic .

**Comment by xxcriticxx** [comment]
@Arek76 rozumiem podaj film ktory kompletnie nie dziala.  

probowales bez `|` po filmie?

**Comment by Arek76** [comment]
@xxcriticxx Nie probowalem , Tak jak pisze , u mnie dzialaja wszystkie bez problemu , U mojego Brata ani jeden . Wszedzie wyskakuje ten komunikat , Mimo ze odinstalowal Kodi wtyczki i na nowo zainstalowal najnowsza wersje . Drugi znajomy rowniez , Przeinstalowalismy wszystko i zaden film nie odpala . Ani jeden na przyklad hajter , Nic nie dziala :) Ciekawostka taka dodam ze - Znajomy ma boxa w ktorym zrobilem reinstalke wszystkiego i zadzialalo ale dodatkowo zrobilem mu aktualizacje androida . Nie wiem czy sama wersja Android moze byc za to odpowiedzialna.

**Comment by xxcriticxx** [comment]
@Arek76 ty testujesz na win czy anroid?

**Comment by Arek76** [comment]
Ja mam boxa , Brat ma sony telewizor , Znajomy Sony , Na windowsie nie testowalem Ten co mu naprawilem ma Boxa tez .Ogolnie na boxach tez nie dziala u niektorych :) Smieszna sytuacja . A u Ciebie dziala ?

**Comment by xxcriticxx** [comment]
poczekaj musze androida z szafy wykopac

**Comment by FXcodi** [comment]
Witam, 
U mnie działa na Kodi 18.4/ android 7.0 jeśli to coś pomoże, przy okazji zapytam jak wykopałeś te linki ze strony cda/edb.cda ?

**Comment by Arek76** [comment]
:) wykopie wszystko jak potrzeba :)Niedawno mialem liste ponad 600 filmow ale na vshare i smigalo az milo , Niestety Vshare zdechlo:(

**Comment by xxcriticxx** [comment]
windows dziala android tone updejtow

**Comment by xxcriticxx** [comment]
@mbebe android ma problem:

Moze inny link bendzie dzialal?
ERROR: list index out of range

**Comment by Arek76** [comment]
ooo dzieki @xxcriticxx za wstawke :) ciekawe ze ja tego nie mam

**Comment by xxcriticxx** [comment]
inna wersja androida napewno 

@Arek76 podasz log na pewno znajdziemy cos nowego :)

**Comment by Arek76** [comment]
@xxcriticxx  http://paste.kodi.tv/fagusetunu prosze :)

**Comment by FXcodi** [comment]
Teraz u mnie przestało działać pastebin PlayVid przed chwilą ????

**Comment by xxcriticxx** [comment]
@FXcodi jaki os? android?

**Comment by FXcodi** [comment]
18.5 kodi/android 7

**Comment by Arek76** [comment]
Bedzie trzeba poczekac na Wodza Mbebe :)

**Comment by mbebe** [comment]
Wieczorem spojrze.

**Comment by mbebe** [comment]
@xxcriticxx 

> @mbebe android ma problem:

> Moze inny link bendzie dzialal?
> ERROR: list index out of range

> http://paste.kodi.tv/aciduradew

Blad spowodowany resolverem cda.

**Comment by mbebe** [comment]
[plugin.video.pastebinVID-1.8.3.zip](https://github.com/mbebe/blomqvist/files/4371164/plugin.video.pastebinVID-1.8.3.zip)

Tu dodany resolver cda we wtyczce.

**Comment by Arek76** [comment]
:))) Dziekuje Ci slicznie :) Problem rozwiazany , Ciekawi mnie na jakim resolver u mnie caly czas smiga :) Dzikekuje slicznie

**Comment by xxcriticxx** [comment]
@mbebe linkow do clipwatch tez nie widze. czy jest potrzebny nowy resolver za kazdym razem?

test links:
https://pastebin.com/K7wsEU06

**Comment by mbebe** [comment]
Nowy nie. Aktualizowany tak.
Trzeba prosic autora waszego resolveurl o aktualizacje.
;-)

**Comment by xxcriticxx** [comment]
@notoco poprawi ktoś resolver clipwatching z cherry?

@mbebe liczymy na twoje poprawki do resolvera żeby wszystko było w jednym domku

**Comment by notoco** [comment]
Sprawdzę czy już nie ma...

**Comment by Arek76** [comment]
No i nie dziala znowu , wczoraj poinstalowane wszystko smigalo , Dzis juz niestety nie . U mnie tez juz nie dziala , Mam wtyczke test i mam rowniez 1.8.1 i na nich nie dziala , Odpalam teraz w 1.8.3 iii ? Niestety tez lipa , Widac resolver bo pyta o jakosc odtwarzania niestety po wybraniu zero reakcji :(

**Comment by FXcodi** [comment]
U mnie też to samo 
@mbebe help

**Comment by mbebe** [comment]
Poprawiony CDA:
[plugin.video.pastebinVID-1.8.4.zip](https://github.com/mbebe/blomqvist/files/4381019/plugin.video.pastebinVID-1.8.4.zip)

**Comment by Arek76** [comment]
Wszystko znowu smiga pieknie , Dzieki :) Ale i tak cos zauwazylem , Sprawdzalem linki czy dzialaja , 10 linkow moge kliknac , od 11 linku juz wywala blad dodatku Pastebin :)

**Comment by mbebe** [comment]
Tez na cda?

**Comment by mbebe** [comment]
Jaki link nie dziala z Twojego pastebina?

**Comment by Arek76** [comment]
Juz prawie wszystkie dzialaja , tylko ze klikajac i sprawdzajac po okolo 10 filmach wtyka wywala blad i restartowalem cale kodi jeszcze raz i od nowa . W sumie nikt 10 filmow nie puszcze w ciagu minuty czy dwoch wiec to nie powinien byc problem jednakze takie cos wystepuje :)

**Comment by FXcodi** [comment]
U mnie po aktualizacji wszystko gra ,tylko niektóre filmy nie odtwarza z  powodu usunięcia linków z serwisu CDA

**Comment by mbebe** [comment]
Widze, ze powrzucali tez filmy z DRM.

**Comment by mbebe** [comment]
cda.pl zaktualizowana w repo.
Moglibyscie sprawdzic premium, czy odtwarza te DRMy. :-)

**Comment by notoco** [comment]
Jakiś konkretny przykład. Mi na premium na razie otwiera każdy film

**Comment by mbebe** [comment]
to git :-)
Taxi 5 np. ma DRM

**Comment by Arek76** [comment]
Moze nie bedzie to zbyt profesjonalna odpowiedz ale :) Sprawdzilem Taxi 5 i wyskoczyl mi komunikat o input ..... adaptive czy jakos tak , Kliklnąlem ok i wszystko smiga . Kilka fimow innych tez sprawdzalem i zapindala :)

**Comment by notoco** [comment]
Taxi 5 działa.

**Comment by Arek76** [comment]
Wszystko dzialalo , dzialalo , dzialalo :))) Szalu mozna dostac :) Pastebin znowu mi nie dziala ale tym razem nie wywala bledu , po prostu cisza . Jesli chodzi o linki to w przegladarce dzialaja ale w pastebin playwid niestety juz nie . CDA.pl sprawdzilem i tam wszystko smiga ale mam konto premium tam wpisane . Pomalu zaczyna mnie to denerwowac co wyprawia ten CDA :)))))

**Comment by xxcriticxx** [comment]
@Arek76 

https://github.com/mbebe/blomqvist/issues/270#issuecomment-609020705

**Comment by Arek76** [comment]
@mbebe Niezawodny :) @xxcriticxx dzieki za info
