### ISSUE TITLE
Sport

### ISSUE THREAD

**Issue by kashkash18** [mbebe/blomqvist#27]
www.alantvsport.com
@mbebe jest opcja na wtyczkę ??

**Comment by rafalmar1981** [comment]
o kurcze taka wtyczka rozbiła by sportlive 365 sport devils i jokera, masakra

**Comment by xxcriticxx** [comment]
nie lepjej by linky z reddit na przyklad z https://www.reddit.com/r/soccerstreams/

**Comment by kashkash18** [comment]
AlanTV jest i tyle spoko że ma bardzo dużo wydarzeń sportowych że sporą liczbą linków które działają plynnie

**Comment by xxcriticxx** [comment]
czekamy teraz na black magic od @mbebe
