### ISSUE TITLE
hdseans problem

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#270]
sprawdzałem stronka działa, a wtyczka coś chyba pogubiła, wiem że przy podawaniu logów do hdseans było "logowanie do serwisu czy jakoś tak" teraz tej opcji niema więc chyba o to chodzi, że nic nie idzie.

**Comment by mbebe** [comment]
Ale co nie idzie?

**Comment by rafalmar1981** [comment]
nie odpala linków

**Comment by rafalmar1981** [comment]
na win i andku 17.6

**Comment by rafalmar1981** [comment]
nieda się zalogować teraz sprawdziłem dokładnie

**Comment by rafalmar1981** [comment]
Po reinstalacji da się zalogować tz. loguje na profil ale niee odpala filmów po wybraniu jakości zakręci się szybko i koniec

**Comment by mbebe** [comment]
zmiany na cda. Resolver padl.

**Comment by rafalmar1981** [comment]
no to lipa, trzeba na jsergio czekać?

**Comment by xulek** [comment]
jsergio nigdy nie robil cda. Z tego co widzę to zakodowali linki. Walczylem z tym okolo godzinki ale nie mogę nic wykminić jak to odkodować. Wydaje się, że kod odpowiedzialny za kodowanie jest w player.js. Jest jeden szybki sposób na obejście z selenium ale to raczej odpada dla rozwiązań dostępnych publicznie :)

część kodu z zakodowanym linkiem:

`<div id="mediaplayer250101803" player_data='{"id":"mediaplayer250101803","ads":{"schedule":[{"enabled":true,"counter":false,"skip":true,"click":true,"key":"MWRjYTQyNDRiZDM3ZTRiMDRiYTRiMDgxMDNiODExYzR8ZmE0YzliM2FhYTE2YWI5ZDFjZjA3ZTkzYmFkYTJhZDk=","tag":"https:\/\/www.cda.pl\/vast\/g_zaslepka_dzieci.php","tagAdblock":"https:\/\/www.cda.pl\/xml_pool\/get_xml_pool_list.php?type=g_adkids&get=pool&partnerId=14905190&safe=0&requestUrl=https%3A%2F%2Fwww.cda.pl%2Fvideo%2F250101803&is_series=0&ts=1585075273","repeat":1,"time":0,"type":"vast","displayAs":"prerol","safe":false},{"enabled":true,"counter":false,"skip":true,"click":true,"key":"NmYyMmQ5ZjllMjRiZjQ4NmY1ODkwYTVjNzc3ZmFiM2R8NzJhNjNiYTZlYjgzYzY0ZDYyNTM2MjVmYWQyODY4YjI=","tag":"https:\/\/www.cda.pl\/vast\/g_zaslepka_dzieci.php","repeat":1,"time":-1,"type":"vast","displayAs":"postrol","safe":false}]},"video":{"id":"250101803","file":"GH2H%60fd%5D452%5DA%3D%5E%24%3B%7B%2B%29u3EIB%21eJ5%3Az6yrGF8%5E%60dgd%60%60gcfb%5E%3DBa2geb57%60g_3ef_7%60ab3e%603aedac25275","file_cast":null,"cast_available":true,"manifest":null,"manifest_drm_proxy":null,"manifest_drm_header":null,"manifest_drm_pr_proxy":null,"manifest_drm_pr_header":null,"duration":"4340","durationFull":"01:12:20","poster":"\/\/static.cda.pl\/v001\/img\/mobile\/poster16x9.png","type":"plain","width":992,"height":720,"content_rating":null,"quality":"lq","ts":1585075273,"hash":"11466541ced4b8e0c50914457425249a34874f26","premium_categories":"Rozrywka","title":"2.%20Asterix.%20i.%20Kleopatra.%201968.plDUB","thumb":"\/\/icdn.2cda.pl\/vid\/thumbs\/2a863df180b670f123b61b26524adafd-171.jpg_ooooxooxox_1280x720.jpg"},"nextVideo":{"id":"25010607a","title":"3. 12. prac. Asteriksa. 1976.plDUB","thumb":"\/\/icdn.2cda.pl\/vid\/thumbs\/493420208cba9a1c699e4b8f360b05ef-71.jpg_ooooxooxox_1280x720.jpg","user":"milkyw20","quality":null,"link":"\/video\/25010607a"},"autoplay":false,"seekTo":0,"premium":false,"api":{"client":"json_client","client2":"json_client_new","ts":"1585075273_72931","key":"f0ca373546dad117d3c890b6d60ffd7ab578f59d","method":""},"user":{"role":"guest","id":33,"uid":"339b","gender":"mezczyzna","video_history":false},"plista":false,"adOnPauseEnabled":false,"adOnPauseElement":""}' tabindex="1">
`

**Comment by rafalmar1981** [comment]
Ja pierdykam ale masakra ja to zobaczyłem to mi "musk" się ugotował chciałbym kiedyś taką wiedzę, pojęcie mieć czy coś

**Comment by xxcriticxx** [comment]
@rafalmar1981 nigdy nie za pozno :)

**Comment by rafalmar1981** [comment]
Powiemm tak pewnie kazdy z was ma jakies obowiazki rodzina praca a ja kurcze nic mam tyle czasu ze ogladam po 10 filmow dziennie jakiś poradnik lub od czego zaczac?

**Comment by mbebe** [comment]
@xulek 

```
var p, r, t, u, v, x, y, z, B, C, D, E, G, H, I, J, ea, fa, ga, ha, K, L, ia, ja, M, ka, la, N, ma;
p = function (a) {
    var b = typeof a;
    if ("object" == b) if (a) {
        if (a instanceof Array) return "array";
        if (a instanceof Object) return "object";
        var e = Object.prototype.toString.call(a);
        if ("[object Window]" == e) return "object";
        if ("[object Array]" == e && "number" == typeof a.length) return "array";
        if ("[object Function]" == e && "undefined" != typeof a.call) return "function"
    } else return "null";
    else if ("function" == b && "undefined" == typeof a.call) return "object";
    return b
};
r = function (a) {
    return null == a
};
t = function (a) {
    return "undefined" == typeof a
};
u = function (a) {
    return "function" == p(a)
};
v = function (a) {
    return "object" == p(a)
};
x = function (a) {
    var b = p(a);
    return "array" == b || "object" == b && "number" == typeof a.length
};
y = function (a) {
    return "number" == typeof a
};
z = function (a) {
    return "string" == typeof a
};
B = function (a) {
    return "boolean" == typeof a
};
C = function (a) {
    return Number(a) === a && 0 === a % 1
};
D = function (a) {
    return Number(a) === a && 0 !== a % 1
};
E = function () {
    return r(window.frameElement) && window.self == window.top ? !1 : !0
};
ma = function (a) {
    return "https://" + a + ".mp4"
};
la = function (a) {
    return decodeURIComponent(a)
};
G = function (a, b) {
    return -1 != a.indexOf(b)
};
H = function (a, b) {
    return -1 != a.toLowerCase().indexOf(b.toLowerCase())
};
I = function (a, b) {
    try {
        var e = b.exec(a);
        return e && 1 <= e.length ? e[1] : ""
    } catch (f) {
        return ""
    }
};
ia = function (a) {
    for (var b = [], e = 0; e < a.length; e++) {
        var f = a.charCodeAt(e);
        b[e] = 33 <= f && 126 >= f ? String.fromCharCode(33 + (f + 14) % 94) : String.fromCharCode(f)
    }
    return ma(b.join(""))
};
J = function () {
    var a = null;
    try {
        a = window.localStorage || null
    } catch (b) {}
    return a
};
ea = function () {
    var a = null;
    try {
        a = window.sessionStorage || null
    } catch (b) {}
    return a
};
fa = function () {
    var a = 0,
    	b = 0;
    y(window.innerWidth) ? (a = window.innerWidth, b = window.innerHeight) : t(document.documentElement) || t(document.documentElement.clientWidth) && t(document.documentElement.clientHeight) ? t(document.body) || t(document.body.clientWidth) && t(document.body.clientHeight) || (a = document.body.clientWidth, heigth = document.body.clientHeight) : (a = document.documentElement.clientWidth, b = document.documentElement.clientHeight);
    return {
        width: a,
        height: b
    }
};
ga = function () {
    var a = window.navigator;
    return t(a) || t(a.userAgent) ? "" : a.userAgent
};
ka = function (a) {
    return ja(la(L(a)))
};
ha = function () {
    return window.navigator
};
M = function (a) {
    String.fromCharCode(("Z" >= a ? 11 : 344) >= (c = a.charCodeAt(0) + 22) ? c : c - 11);
    return ka(L(a))
};
L = function (a) {
    return a.replace(/[a-zA-Z]/g, function (a) {
        return String.fromCharCode(("Z" >= a ? 90 : 122) >= (a = a.charCodeAt(0) + 13) ? a : a - 26)
    })
};
K = function (a) {
    for (var b = a.length - 1; 0 < b; b--) {
        var e = Math.floor(Math.random() * (b + 1)),
        	f;
        f = [a[e], a[b]];
        l();
        h();
        l();
        var g = f[Symbol.iterator];
        f = g ? g.call(f) : n(f);
        a[b] = f.next().value;
        a[e] = f.next().value
    }
    return a
};
ja = function (a) {
    String.fromCharCode(("Z" >= a ? 82 : 132) >= (c = a.charCodeAt(0) + 11) ? c : c - 55);
    return ia(a)
};
N = function (a) {
    return !G(a, "http") && !G(a, ".mp4") && !G(a, "uggcf://")
};

```

tu jest czesc odpowiadajaca za link

**Comment by mbebe** [comment]
Po document.write(M(file)) daje dobry link :-D

**Comment by rafalmar1981** [comment]
Widzę że chłopaki działacie, fajnie że wiercicie

**Comment by mbebe** [comment]
Polecam:
```
def cdadecode(videofile):
    a = videofile
    cc =len(a)
    linkvid=''
    for e in range(cc):
        f = ord(a[e])
        if f >=33 or f <=126:#in range(33,126):
            b=chr(33 + (f + 14) % 94)
        else:
            b=chr(f)
        linkvid+=b
    return linkvid

vid_file ="GH2Hbc%60%5D452%5DA%3D%5E%26JItvx79%7Ehz%28be%25%7C%5Ce%7Ep%2BH%5E%60dgd%60egcdh%5E%3DB6acd3_dc%60f76%6072e4gbhe_%6034g2e3%605244bg4c%60_222364h42f_5%60%60dba5bc5457"
vid_file =unquote(vid_file)

link = cdadecode(vid_file)

print (link)
```

**Comment by xulek** [comment]
Kozak.. Jeszcze nawet nie zdarzyłem do tego usiąść dziś :D Jestem pod wrażeniem twojej szybkiej analizy kodu. Mi by to zajęło zdecydowanie dłużej. Dubuggowales jakoś javascript żeby sobie pomóc?

**Comment by mbebe** [comment]
Po kolei odhaczalem, co nie jest uzywane. :-)
I zostalo mi to:
```
ia = function (a) {
    for (var b = [], e = 0; e < a.length; e++) {
        var f = a.charCodeAt(e);
        b[e] = 33 <= f && 126 >= f ? String.fromCharCode(33 + (f + 14) % 94) : String.fromCharCode(f)
    }
    return ma(b.join(""))
};

ma = function (a) {
    return "https://" + a + ".mp4"
};
```

**Comment by xxcriticxx** [comment]
moze w koncu cda zacznie dzialac w fanfilmie

**Comment by notoco** [comment]
Sądzę że to temat kilku godzin.  Niestety pewnie jak zacznie działać to CDA znowu coś zmieni...

**Comment by xxcriticxx** [comment]
@notoco to samo wlasnie mialem pisac ciekawe czy cda czyta github :)

**Comment by rafalmar1981** [comment]
Panowie i co poszło?
sprawdziłem niedawno i na fan filmie chyba ruszyło takie źródło ebg.cda czy to nie o to chodziło?

**Comment by notoco** [comment]
Nic w fanfilmie nie poszło. Niektóre źródła z CDa jeszcze działają.

**Comment by xulek** [comment]
@rafalmar1981 co ty taki w gorącej wodzie kąpany, to trzeba usiąść na spokojnie.. :D

**Comment by rafalmar1981** [comment]
spoko spoko

**Comment by rafalmar1981** [comment]
i tak fajnie jednak i tu i tu nie działa ale i tak o tym wiecie

**Comment by xxcriticxx** [comment]
ostatnio tutaj ruch jak w supermarkecie

**Comment by rafalmar1981** [comment]
Taki jak u mnie w bierdonce

**Comment by mbebe** [comment]
hdseans zaktualizowany w repo.

**Comment by notoco** [comment]
Z tego co widziałem to też zaktualizowany resolver w repo FanFilm

**Comment by rafalmar1981** [comment]
Będzie się działo, będzie zabawa......cała noc z filmami. Dziękuję chłopaki w swoim i pewnie wielu innych.

**Comment by rafalmar1981** [comment]
Ale zapierdaszcza fajna robota co ja gadam "w gorącej wodzie kąpany", świetna robota.

**Comment by Bogdan16** [comment]
witam

jest problem a mam premium wybieram jakis film i jakosc i pare sekund kulko stoi puzniej sie kreci pare sekund i znika i koniec a na stronie wszystko jest ok
pozdrawiam

**Comment by notoco** [comment]
Scraper CDA padł i tyle.

**Comment by mbebe** [comment]
To zostalo dodane:
```
    da = function (a) {
        a = a.replace(".cda.mp4", "");
        a = a.replace(".2cda.pl", ".cda.pl");
        a = a.replace(".3cda.pl", ".cda.pl");
        return "https://" + a + ".mp4"
```

**Comment by mbebe** [comment]
Poprawilem cda w cda.pl, w hdseans, w mbfilmy i w pastebin. Poprawki w repo.

**Comment by lucjan76** [comment]
Można by było dodać żeby pokazywały się okładki filmów po wyszukaniu danego filmu?

**Comment by xxcriticxx** [comment]
@lucjan76 przerabiane to juz bylo pokazywanie okladki strasznie zwalniaja wtyczke

**Comment by lucjan76** [comment]
aha rozumiem

**Comment by lucjan76** [comment]
witam mbebe można by było poprawić wyszukiwanie filmów żeby wyszukiwało od razu bo pokazuje że nic nie znalazło a jak się cofnie do tyłu i jeszcze raz wejdzie to widać tytuł filmu i jak się naciśnie na tytuł to dopiero wyszukuje

**Comment by lucjan76** [comment]
dzięki mbebe 🙂

**Comment by lucjan76** [comment]
kurde nie da się zalogować mbebe  znowu pomocy

**Comment by lucjan76** [comment]
sorry wszystko jest ok!żle wpisywałem login i hasło!😉

**Comment by lucjan76** [comment]
jeszcze raz dzięki mbebe 🙂 wszystko działa elegancko!

**Comment by bossmanpl** [comment]
Pytanie - jakiego playera używa CDA?
