### ISSUE TITLE
bajeczki org - nie da się zainstalować

### ISSUE THREAD

**Issue by vigabi7286** [mbebe/blomqvist#272]
bajeczki org - nie da się zainstalować, inne dodatki się instalują.

1. Robię zainstaluj z repozytorium -> mbabe -> wtyczki wideo -> Bajeczki.org
2. wersja 1.4
3. pojawia się lista zależności -> ok
4. "nieudana instalacja"

Serdecznie proszę o poprawkę, potrzebuję "Psi Patrol" szybko ;)

**Comment by xxcriticxx** [comment]
@vigabi7286 jest wiecej informacji w logu?

**Comment by vigabi7286** [comment]
a gdzie można zobaczyć logi?

**Comment by vigabi7286** [comment]
na ułamek sekundy pojawia się pobieranie 0%.. i jest zaraz błąd. Być może pliki są niedostępne?

**Comment by xxcriticxx** [comment]
https://github.com/mrknow/filmkodi/wiki/Jak-przesłać-logi-z-kodi

**Comment by vigabi7286** [comment]
Właśnie miałem przesłać logi ale instalacja dziś zadziałała. Dziwne, wczoraj próbowałem wielokrotnie i był powyższy błąd.. nic to zamykam issue.
