### ISSUE TITLE
Internetowa.ws blad logowania.

### ISSUE THREAD

**Issue by Mariusz89B** [mbebe/blomqvist#277]
Blad logowania we wtyczce, na stronie moge sie zalogowac.

Kodi (18.6 Git:20200326-4e967666f9). Platform: Windows NT x86 64-bit

```
response = sess.post('https://internetowa.tv/logowanie/#', headers=sess.headers, data=data,allow_redirects=False)	

xbmc.log('Response: {}'.format(response.cookies.get('login')))
```

`DEBUG: Response: None`

**Comment by mbebe** [comment]
Sprawdzilem teraz i loguje. 
A pojawia sie Tobie captcha?

**Comment by kashkash18** [comment]
Testowałem teraz na dwóch różnych kontach inie było problemu z logowaniem.
Captcha się pojawia . Może akurat w serwisie coś poszło nie tak.

**Comment by Mariusz89B** [comment]
Tak pojawia sie capcha mysle ze dobrze wpisuje kod, sprawdze jeszcze raz.

**Comment by Mariusz89B** [comment]
Ok logowanie dzisiaj dziala poprawnie.

**Comment by Mariusz89B** [comment]
Ok domyslam sie w czym tkwi problem, przez VPN (PL) logowanie dziala poprawnie jednak bez to sess.get('https://internetowa.tv/konto/', cookies=sess.cookies).content odp. jest pusta (resp = []). Mieszkam za granica.

**Comment by mbebe** [comment]
Wyslalem Tobie maila. :-)

**Comment by Mariusz89B** [comment]
@mbebe Dzieki!, teraz wszystko jasne. :)
