### ISSUE TITLE
pytanie z d....

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#278]

**Comment by rafalmar1981** [comment]
mam okazje kupić dwie pary okularów 3d czy te okulary beda działaly na filmach z repo mbebe niepamiętam dokładnie jaka to byla wtyczka ale gdy włączyłem taki film to miałem ekran podzielony na pół. Czy jest szansa  że kupując model master image będą działały?

**Comment by notoco** [comment]
A telewizor 3d masz?

**Comment by rafalmar1981** [comment]
nie

**Comment by notoco** [comment]
No to nie poogladasz...

**Comment by Arek76** [comment]
faktycznie z dupy :)
