### ISSUE TITLE
problemy

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#28]
nie które wtyczki wywalają błąd, więc tak EKINO - playerbox i uovid nie działają, hause of card- pisze brak linków, na niektórych serialach tez sprawdzałem, orange is the new black - każdy odcinek "proszę czekać" i nic się nie dzieje. Kinonet próbowałem na filmach w różnych kategoriach i też to samo, wywala błąd dodatku kinonet. Czy jest możliwość tego naprawienia? wyślę to również do krecik71 podać log?

**Comment by mbebe** [comment]
po 1 sprawdz na stronie ekino czy house of cards posiada linki.  wiekszosc zostalo usuniete. 
playerbox nie ma w resolverze, upvid te.
w kinonet dodane upvid i tam z upvid dziala. do kinonet bedzie poprawka, bo faktycznie wyrzuca blad.

**Comment by rafalmar1981** [comment]
dziękuję mbebe to jest robota sprawdziłem miałeś racje a linki są openload i vshare w tym serialu
