### ISSUE TITLE
ResolveURL

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#286]
Dziwna sprawa od dwóch dni miałem dostępną aktualizację ResolveURL6.4.111, nie mogłem tego zrobić  wyskakiwał błąd "próba aktualizacji nie powiodła się". Miałem wcześniejszą wersję nie jestem pewien ale chyba wersję ResolveURL6.4.110, dziś zaktualizował mi się ResolveURL do wersji6.4.111, niestety objaw był taki, iż wtyczka hdseans przestała działać, moim ponownym krokiem było wykonanie aktualizacji z PTWCollection do wersji ResolveURL6.4.92 i wtyczka zaczęła prawidłowo działać. Piszę gdyż może jest jakiś problem z tą wersją ResolveURL6.4.111. Pozdrawiam

**Comment by xulek** [comment]
resolveurl 6.4.111 dziala prawidłowo wlasnie sprawdzilem, jak coś jest nie tak to z wtyczką hdseans albo samym hdseans

**Comment by FXcodi** [comment]
U mnie jest to samo, ale oprócz problemu z HDseans, nie działa ekinotv oraz nie odpadają filmy z serwisów typu cda.pl czy cdax.

**Comment by rafalmar1981** [comment]
xulek teras sprawdzałem i na ResolveURL6.4.111  jak chcesz wyczyścić reset function cache to wywala błąd ResolveURL. Posprawdzałem na innych wtyczkach tj hdseans, alltube błąd dodatku. 3filmy, fanfilm, hejo i serialnet działają i odtwarzają filmy. Gdy zmienię na ResolveURL6.4.92 błędy wtyczek hdseans, alltube znikają da się normalnie zalogować na hd seans ale filmu już się nie zobaczy - można najdalej wybrać jakość  niby zakręci się dwa razy zaskoczy jakby i się wyłącza. Alltube działa czyli chyba coś z ResolveURL6.4.111 jednak. Pozdrawiam,

**Comment by xulek** [comment]
podaj jakie urządzenie, wersja kodi i wklej log

**Comment by rafalmar1981** [comment]
tv smart android kodi18,6,  a logów nie potrafię wkleić tz. nie wiem jak to się robi(zielony).

**Comment by rafalmar1981** [comment]
Kodi Logfile Uploade chyba oto chodziło? To zaraz zainstaluje przejdę na ResolveURL6.4.111, zrestartuję kodi 18.6 i zobaczymy co się wydarzy.

**Comment by rafalmar1981** [comment]
pierwsze co chciałem odpalić to alltube, hdseans błąd dodatku,następnie ,zalukaj- błąd dodatku(dane do logowania są wszędzie poprawne). Działają serialnet, hejo, 3filmy, fanfilm. Przy przywróceniu ResolveURL6.4.92 działa wszystko tylko hdseans jak pisałem wcześniej "można najdalej wybrać jakość niby zakręci się dwa razy zaskoczy jakby i się wyłącza". Pozdrawiam

**Comment by rafalmar1981** [comment]
i h... w d... wyskoczył mi komunikat error posting kodi.log file. This file is too large. Max size is 1MB. Nie Wiem nie znam się ale może wyślę gdyby się dało przez ten program EZmaintance czy coś, już mi się nie chce od nowa przeinstalowywać.

**Comment by xulek** [comment]
Bez loga jedyne co mogę zrobić to napisać "u mnie działa" :P 

Sprobuj wykonać następujące kroki (z resolverem 111) i tylko te:
Odpal Kodi
Odpal wtyczkę hdseans (ma wywalic błąd)
Odpal Kodi Logfile Uploader i wyslij log

Wtedy log powinien byc mniejszy bo jest tworzony na nowo przy starcie Kodi

**Comment by Mariusz89B** [comment]
> i h... w d... wyskoczył mi komunikat error posting kodi.log file. This file is too large. Max size is 1MB. Nie Wiem nie znam się ale może wyślę gdyby się dało przez ten program EZmaintance czy coś, już mi się nie chce od nowa przeinstalowywać.

Sprobuj zrestartowac Kodi i wyslac log gdy problem sie pojawi wtedy plik nie bedzie az taki duzy. W m-TVGuide masz wbudowany log uploader.

**Comment by kodiwpigulce** [comment]
Wszystkie wtyczki ze źródłami z CDA jak pastebin, hdseans itp nie korzystają z Resolvera, a teraz znów padły. Więc tymczasowym rozwiązaniem zanim jakieś aktualizację się pojawią wystarczy zmiana w kodzie aby hdseans uruchamiało źródła CDA poprzez Resolvera. Pewnie dlatego @rafalmar1981 ma problem w tych wtyczkach, a w fanfilm nie.

Nieeleganckie ale jak ktoś potrzebuje to wystarczy zakomentować te linijkę w pliku main.py:
`elif 'cda.pl' in hrefSEG:`
Czyli dodajemy "#": `#elif 'cda.pl' in hrefSEG:`

**Comment by xxcriticxx** [comment]
poszukajcie nowego serwisu do uploadowanie filmow widac ze cda walczy z nami

**Comment by Arek76** [comment]
Tez tak uwazam , ze to CDA sie wzielo za robote i zaczyna mnie to troszke draznic , Co drugi  dzien problem ze wtyczkami :)Juz az glupio prosic Mbebe o aktualizacje :) Tylko gdzie mozna uploadowac :) Oto pytanie .

**Comment by notoco** [comment]
Większość nie uploaduje. Większość ogląda. A stety niestety na CDA pełno filmów.

**Comment by mbebe** [comment]
> Juz az glupio prosic Mbebe o aktualizacje :)
Bo od tego oni są, od tego są oni. :-)))

**Comment by xxcriticxx** [comment]
@Arek76 torrenty

@mbebe polski scraper do syreny by sie przydal :)

**Comment by Arek76** [comment]
hmmm moglbym sie zajac i zorganizowac fajna nasz videoteke ale gdzie ?? Prosze Ich o jakis pomysl ?:)

**Comment by rafalmar1981** [comment]
Ja po prostu od instaluje kodi, zainstaluje ponownie i prześle te logi z błędami ale po wpisach widzę, że już wiadomo co się stało. Dziękuję wszystkim za pomoc za angażowanie i życzę udanych ŚWIĄT

**Comment by mbebe** [comment]
poszly aktulizacje zawierajace cdapl

**Comment by rafalmar1981** [comment]
mbebe zapierdzielasz z tymi jajkami :) Jak nic nie napisze to gra gitara i ŚWIĘTA, jajkami do góry. Pozdrawiam

**Comment by Arek76** [comment]
cos u mnie nie poszlo , dalej lipa http://paste.kodi.tv/siwifusume

**Comment by mbebe** [comment]
Jaki film sprawdzales na swoim pastebin?

**Comment by xulek** [comment]
@mbebe wygląda na to, ze ten: https://ebd.cda.pl/805x204/49700607f?wersja=1080p

**Comment by xulek** [comment]
> 
> 
> cos u mnie nie poszlo , dalej lipa http://paste.kodi.tv/siwifusume

sprawdzilem ten link (https://ebd.cda.pl/805x204/49700607f?wersja=1080p) na tym samym resolverze co ty (111) i u mnie działa prawidłowo.. ciekawe

**Comment by mbebe** [comment]
u mnie tez teraz sprawdzilem. dziala.

**Comment by mbebe** [comment]
@Arek76 zaktualizuj wtyczke. Jak widze korzystales z 1.8.9. Nowa to 1.8.10.

**Comment by Arek76** [comment]
deinstaluje cale kodi , Wszystkie wtyczki wyrzuce i na nowo , Moze faktycznie zbyt wiele tergo mialem a i tak nie potrzebne , świateczne porzadki zrobie na boxie swym i zaraz dam znac

**Comment by kodiwpigulce** [comment]
Potwierdzam, działa wyśmienicie. 👍

**Comment by kodiwpigulce** [comment]
> hmmm moglbym sie zajac i zorganizowac fajna nasz videoteke ale gdzie ?? Prosze Ich o jakis pomysl ?:)

odezwij się do mnie na kodiwpigulce@gmail.com 📧

**Comment by Arek76** [comment]
Ok Deinstal poszedl , Świeze Kodi i wtyka smiga az milo :) Dziekuje Mbebe jak zwykle i lece szybko do tematu #39 Juz do Ciebie pisze Kodiwpigulce

**Comment by rafalmar1981** [comment]
zalukaj hdseans alltube bład dodatku nowa instalacja resolve 6.4.113 Kodi Logfile Uploade chciałem wysłać jakiśerror mi wyskoczył kody z oficjalnej strony oczywiście

**Comment by xulek** [comment]
> 
> 
> zalukaj hdseans alltube bład dodatku nowa instalacja resolve 6.4.113 Kodi Logfile Uploade chciałem wysłać jakiśerror mi wyskoczył kody z oficjalnej strony oczywiście

no to ja rozkładam ręce bez loga. Tu masz sciezki do pliku log, mozesz probować ręcznie go gdzieś wyslać https://kodi.wiki/view/Log_file/Easy punkt 3.3

**Comment by rafalmar1981** [comment]
przy 6.4.92 działa wsio tz. zalukaj, hejo hdseans, serialnet 3filmy tylko alltube nie wczytuje żadnego linku ale co tam próbowałem wysłać log ponownie to mi kod qr wyskoczył

**Comment by xulek** [comment]
w 6.4.92 na bank nie dziala cda. A kod QR to wlasnie link do pliku log ktory wyslales, a obok niego w opisie masz wypisany link

**Comment by rafalmar1981** [comment]
nawet nie będę robić instalacji innych wtyczek bo znów coś się pochrzani, a nie jest źle czy przez EZMaintenance+ można wysłać

**Comment by mbebe** [comment]
@xxcriticxx 

> @mbebe polski scraper do syreny by sie przydal :)

Ale jak je robic? Dodawac do jakichs scraperow? Np. do 4kscrapers, czy jak? ;-)

**Comment by xulek** [comment]
masz oficjalny Kodi Logfile Uploader w oficjalnym repozytorium to po co korzystać z jakiegoś syfu typu EZMaintenance+ do ktorego nie wiadomo kto i co wpakował?

**Comment by rafalmar1981** [comment]
przecież siedziałem i sprawdzałem przed chwilą na hdseans  i działa

**Comment by rafalmar1981** [comment]
https://paste.kodi.tv/woqaxoqene coś takiego mam

**Comment by rafalmar1981** [comment]
oto chodziło?

**Comment by mbebe** [comment]
Tak, O to chodzilo. :-)

**Comment by xulek** [comment]
bardzo dobrze tylko wrzuciłeś log z script.module.resolveurl v6.4.92 a mialeś z wersją 111 wrzucić

**Comment by mbebe** [comment]
:-))))))

**Comment by rafalmar1981** [comment]
dobra zaktualizuje

**Comment by kashkash18** [comment]
Co za ruch tutaj heheh
Jak nigdy 😁

**Comment by mbebe** [comment]
Ale bedzie usuwania :-)

**Comment by xulek** [comment]
> 
> 
> dobra zaktualizuje

po aktualizacji sprobuj powtorzyć błąd przed wysłaniem logu

**Comment by kashkash18** [comment]
A jajek nie ma komu malować 🙃

**Comment by rafalmar1981** [comment]
tylko mam do wyboru ptw 6.4.113 i 5.0.34mbebe i tą co wysłałem

**Comment by xulek** [comment]
tak jak napisalem wczesniej, instaluj 111 albo wyższą

**Comment by mbebe** [comment]
Ale jaki w sumie jest blad? Nie odtwarza tylko?
Serwery sa przeciazone.
![over](https://user-images.githubusercontent.com/30195202/79047412-a524d280-7c16-11ea-888c-8429c32128c4.jpg)
To np. gounlimited.

**Comment by xulek** [comment]
> 
> 
> Ale jaki w sumie jest blad? Nie odtwarza tylko?
> Serwery sa przeciazone.
> ![over](https://user-images.githubusercontent.com/30195202/79047412-a524d280-7c16-11ea-888c-8429c32128c4.jpg)
> To np. gounlimited.

myślę, że jeszcze okolo 20 komentarzy i się dowiemy :P juz finiszujemy

**Comment by mbebe** [comment]
hahahahahahaa

**Comment by rafalmar1981** [comment]
to113 poszła
bład alltube hdseans zalukaj
hejo serialnet 3filmy działaja poprawnie

**Comment by xulek** [comment]
log

**Comment by rafalmar1981** [comment]
https://paste.kodi.tv/xegagiwujo

**Comment by mbebe** [comment]
Blad podczas odtwarzania? Blad podczas wyswietlania filmow, seriali? Blad logowania? Kiedy wystepuje blad?

**Comment by rafalmar1981** [comment]
podczas uruchomienia wtyczek tych trzech

**Comment by xulek** [comment]
no i juz wszystko jasne, brakuje modułu six, poczekaj trochę, a pewnie za niedługo się pojawi poprawka w resolverze. Jestem pewien ze autor czyta ten wątek :)

Jak nie chcesz czekac to doinstaluj ręcznie script.module.six

**Comment by rafalmar1981** [comment]
to jakim cudem u innych działa?

**Comment by mbebe** [comment]
Hurra. :-)

**Comment by xulek** [comment]
bo inni mają ten moduł zainstalowany pewnie z jakąś inną wtyczką

**Comment by rafalmar1981** [comment]
np?
z fanfilmem?

**Comment by mbebe** [comment]
https://mirrors.kodi.tv/addons/krypton/script.module.six/script.module.six-1.13.0.zip

**Comment by notoco** [comment]
Inni pewnie z jakimiś innymi zależnościami mają ten moduł zainstalowany. Jeśli autor resolvera to czyta, to ... Wesołych Świąt mu życzę.

**Comment by xulek** [comment]
> 
> 
> np?
> z fanfilmem?

moze i z fanfilmem, nie wnikam jaka wtyczka go wymaga do zainstalowania

**Comment by kashkash18** [comment]
Alleluja 😁

**Comment by rafalmar1981** [comment]
mam z fan filmem do zainstalowania script.module.six1.11.0 o to biega?

**Comment by rafalmar1981** [comment]
nie niestety to nie oto chodziło z fanfilmem zainstaluje to co mbebe mi podał  i zobaczymy

**Comment by rafalmar1981** [comment]
niestety  to samo zainstalowałem od mbebe i dokładnie to samo

**Comment by rafalmar1981** [comment]
na 6492 chodzi tylko jaj juz był wpis alltube pewnie przeciązone

**Comment by rafalmar1981** [comment]
Dziękuję wszystkim za pomoc, cierpliwość i wyrozumiałość za moje wcześniejsze nieporadne tłumaczenie lub nieudolne wysyłanie logów, dzięki jeszcze raz. Pozdrawiam i świetnych świąt.

**Comment by mbebe** [comment]
rafalmar - jak tobie nie poszlo, to zrob tak:
1. zainstaluj moje repo (mam nadzieje, ze masz)
2. zainstaluj te wtyczke(i tak nie dziala) - https://github.com/mbebe/blomqvist/raw/master/zips/plugin.video.movies365/plugin.video.movies365-2.3.zip 
ona powinna zassac wszystkie potrzebne zaleznosci.
3. sprobuj teraz zaktualizowac resolveurl do wersji 111 lub wyzszej
i podaj czy sa jakies efekty.

**Comment by rafalmar1981** [comment]
mbebe pobrałem na kompa, a już nie chcę mi się wpinać i wypinać pena, jutro napiszę czy będzie efekt. Dzięki za poradę

**Comment by rafalmar1981** [comment]
resolveur 6.4.113 ale na kompie na win7 i kodi 17,6 zainstalowałem to co napisałeś efekt ten sam. Ale jak dałem 6492 to leci jak pisałem wcześniej, nie kłopocz się wszystko gra, odpoczywaj, świętuj

**Comment by xxcriticxx** [comment]
> @xxcriticxx
> 
> > @mbebe polski scraper do syreny by sie przydal :)
> 
> Ale jak je robic? Dodawac do jakichs scraperow? Np. do 4kscrapers, czy jak? ;-)

@mbebe cos na podstawie 4kscrapers ale musi byc oddzielny zip zeby mozna bylo to zamontowac w syrenie

**Comment by xulek** [comment]
> resolveur 6.4.113 ale na kompie na win7 i kodi 17,6 zainstalowałem to co napisałeś efekt ten sam. Ale jak dałem 6492 to leci jak pisałem wcześniej, nie kłopocz się wszystko gra, odpoczywaj, świętuj

Coś robisz zle, zainstalowałem czyste kodi, repozytorium mbebe, repo z resolverem 113, script.module.six następnie wtyczkę hdseans i wszystko działa poprawnie.

I kodi 17 to staroć, zmień to na kodi 18

**Comment by rafalmar1981** [comment]
czyste kodi 18.6(android) mbebe-cherry-instaluje z repo mbebe zalukaj,serialnet,alltube,3filmy,hejo,hdseans,następnie z ptw fanfilm przechodzę do dodatki repozytoriów w ptw instaluje repo kwp z programów wybieram EZmaitance(czy jakoś tak). Sprawdzam że jest dostępna aktualizacja na resolveur 6.4.113(aktualizuję) wyłączam kodi uruchamiam ponownie i jak pisałem wcześniej błąd hdseans,zalukaj,alltube(naciskam na wtyczkę prawy dolny róg "błąd hdseans" itd. reszta chodzi. Nie wiem, opisałem najdokładniej jak mogę co robię.

**Comment by kodiwpigulce** [comment]
Czysta instalacja, Kodi 18.6, zainstalowane tylko repozytorium mbebe, wtyczka hdseans działa, alltube się uruchamia ale nie odtwarza  bo resolver z repozytorium stary, serialnet się uruchamia jednak też nie odpala filmów, 3 filmy też działa bez problemu.
Po instalacji repo FanFilm i zaktualizowaniu resolvera serialnet uruchamia wideo, natomiast alltube się nie uruchamia, Wystarczyło doinstalować https://mirrors.kodi.tv/addons/krypton/script.module.six/script.module.six-1.13.0.zip i alltube działa.

**Comment by mbebe** [comment]
Tez kiedys mialem ten problem z js2py, tez z six.
Teraz na czystym kodi na telefonie mam identyczny problem z tym six.
Zrobilem to tak jak w movies365.
Usuniete sa z resolveurl js2py oraz pyjsparser i uzywane ze scriptow.
```
        <import addon="script.module.js2py" />
        <import addon="script.module.six" />
        <import addon="script.module.pyjsparser" />
        <import addon="script.module.tzlocal" />
```
scripty sa na https://github.com/Proximus2000/mb-support/tree/master/zips
Tylko wtedy mialem mozliwosc uzywania tego nowego resolveurl.
Rzuccie okiem.
[script.module.resolveurl-6.4.114.zip](https://github.com/mbebe/blomqvist/files/4467143/script.module.resolveurl-6.4.114.zip)

**Comment by rafalmar1981** [comment]
Guzik się na tym znam ale chyba mbebe daje do myślenia, poprzednim postom np. dlaczego mnie to nie działa

**Comment by xxcriticxx** [comment]
@rafalmar1981 wyrzuc tego androida przez okno na pewno zacznie dzialac

**Comment by rafalmar1981** [comment]
xxcriticxx tak bym zrobił, ale niestety serwis na innego androida mi nie pozwala wgrać, jutro jeszcze zerknę na sposób kodiwpigulce ale to już robiłem może w innej kolejności zobaczymy. Ciekawi mnie dlaczego nie napisali ze po zaktualizowaniu resolveurl czy działa hd seans zalukaj. Zobaczymy jutro pozdrawiam

**Comment by xxcriticxx** [comment]
@rafalmar1981  mbebe podal tobie nowy script.module.resolveurl-6.4.114.zip testowales?

**Comment by rafalmar1981** [comment]
dzisiaj bede testował wszystko jeszcze raz i na piszę o efektach

**Comment by rafalmar1981** [comment]
dobra wygląda to tak przy sposobie kwp resolveURL 6.4.116 wszystko działa tylko to altube mnie wku..ale to im coś się chyba popierniczyło bo tylko videospace mi chodzi ale i tak jest nieźle, natomiast przy próbie instalacji script.module.resolveurl-6.4.114.zip zasysa mi
<import addon="script.module.js2py" />
<import addon="script.module.six" />
<import addon="script.module.pyjsparser" />
<import addon="script.module.tzlocal" /> i kończy się na 45 % dwie próby druga 15min..
Tak ze chyba wszystko dobrze jest :) sprawdzę jeszcze tak z ciekawości ekino bo z tym zawsze miałem problemy....aha takie pytanie czy macie problem w hdseans z opcją "szukaj" mi zawsze wyskakuje brak materiału czy coś

**Comment by xxcriticxx** [comment]
@rafalmar1981 rekomenduje wykupjenie real debrid serwisu + torrenty

**Comment by notoco** [comment]
> Tez kiedys mialem ten problem z js2py, tez z six.
> Teraz na czystym kodi na telefonie mam identyczny problem z tym six.
> Zrobilem to tak jak w movies365.
> Usuniete sa z resolveurl js2py oraz pyjsparser i uzywane ze scriptow.
> 
> ```
>         <import addon="script.module.js2py" />
>         <import addon="script.module.six" />
>         <import addon="script.module.pyjsparser" />
>         <import addon="script.module.tzlocal" />
> ```
> 
> scripty sa na https://github.com/Proximus2000/mb-support/tree/master/zips (stad tez sa sciagane po zainstalowaniu mojego repo)
> Tylko wtedy mialem mozliwosc uzywania tego nowego resolveurl.
> Rzuccie okiem.
> [script.module.resolveurl-6.4.114.zip](https://github.com/mbebe/blomqvist/files/4467143/script.module.resolveurl-6.4.114.zip)

U mnie na nowy 116 było dość długie ładowanie - do prawie 10 sekund w FF przed oknem przygotowywanie źródeł. Po zastosowaniu się do porady - 4 sekundy. Zgłoszone gdzie trzeba

**Comment by rafalmar1981** [comment]
@notoco nie rozumiem to było do mnie?

**Comment by notoco** [comment]
A odpowiadałem na twój post czy na post mbebe? Po to go zacytowałem żeby było wiadomo.

**Comment by rafalmar1981** [comment]
notoco oki przepraszam

**Comment by notoco** [comment]
@mbebe nowy resolver (118) stosuje się do tych wskazówek. Niestety wiele twoich wtyczek sypie błędami...
Fanfilm dostał kopa z nowym resolverem bez tych katalogów. Wcześniej od 114 do 116 mulił.

**Comment by xxcriticxx** [comment]
@notoco wow dobre nowiny

**Comment by notoco** [comment]
No tak. Ale inne wtyczki od mbebe wymagają poprawek.

**Comment by xxcriticxx** [comment]
dawno przerzuciłem sie na torrenty + newsgroupy. teraz czekam kiedy @mbebe napisze scraper do syreny.

**Comment by notoco** [comment]
Co to syreny? Z tymi błędami jest różnie. U mjw sypie. U mnie nie.

**Comment by xxcriticxx** [comment]
@notoco mjw?

**Comment by kashkash18** [comment]
@notoco a w jakich wtyczkach sypie błędami po aktualizacji . Testowałem teraz kilka i działają. Hejo się tylko wysypało z odpalaniem filmów ale to raczej ich wina

**Comment by notoco** [comment]
Mjw->kodiwpigulce. Ja nie mam problemu. U niego sypie błędami.

**Comment by xxcriticxx** [comment]
@notoco na pewno testuje na androidzie a ty jedziesz na linuxie

**Comment by kodiwpigulce** [comment]
Testuje na Androidzie, Android TV, CoreELEC, Win10 i na Macu.

**Comment by xxcriticxx** [comment]
@kodiwpigulce i najwiecej sypie na jakim os?

**Comment by kodiwpigulce** [comment]
@xxcriticxx nie było zależności, na którym systemie był lub nie był problem. Ale z tego co widzę boska ręka zrobiła poprawkę :) w script.module.pyjsparser i teraz jest miód malina. 👍 

Także jak ktoś będzie miał problem z nieruchomieniem jakiejś wtyczki typu hdseans, alltube itp to zainstalować repozytorium fanfilm i zrobi się update script.module.pyjsparser co u mnie pomogło jak się okazuje.
