### ISSUE TITLE
jeden resolver

### ISSUE THREAD

**Issue by xxcriticxx** [mbebe/blomqvist#29]
Nie można dodać pl zmian do jsergia resolvera tak zeby byl tylko jeden?

zapytajmy specjalistów:

@mbebe / @notoco  / @xulek / @rysson / @grzebzi

**Comment by mbebe** [comment]
np ktore?

**Comment by notoco** [comment]
Obecnie w cherry są uwzględnione zmiany od jsergio...
Namieszało się z tym po sytuacji z ramicspa i mrknow i jakoś nie możemy dojść do "porozumienia"

**Comment by rysson** [comment]
Też o to pytałem kiedyś. Mamy jakieś specyficzne zmiany ale nie patrzyłem jakie.
Generalnie opcja, że wszystko jest w jsergio, a my tylko paczkujemy i wrzucamy poprawki do niego wydaje mi się najlepsza.
Opcja druga to mamy bliski klon, z naszymi poprawkami, ale cały czas )codziennie!) synchronizowany. Pozwala to mieć zmiany, których nie chce jsergio, ale wymaga więcej pracy.

Porządkowanie trwa i pewnie i do tego dojdziemy :)
Swoją drogą mamy bałagan w wersjach. W Cherry jest 6.3.4 a u jsergio jest 5.0.17.

**Comment by xxcriticxx** [comment]
@notoco dokładnie dlatego proponuje dodać pl zmiany do jsergia repo

**Comment by xxcriticxx** [comment]
@rysson chery jest większa versia żeby się updatowal sam. Tylko problem ze cały czas gubię RD i muszę się parować.

**Comment by rysson** [comment]
Ale jakby to były tylko poprawki do jsergio to można by dodwać kolejną liczbę i mielibyśmy 6.3.4.1
Co prawda w zaleceniach jest „x.y.z”, ale jak widziałem więcej liczb nie przeszkadza Kodi.

**Comment by xxcriticxx** [comment]
@rysson a czemu by jsergio nie przyjął pl zmian? Nikt z tego nie bendzie korzystał chyba ze ma polskie wtyczki.

**Comment by rysson** [comment]
@xxcriticxx, tylko na wypadek gdyby nasza grupa chciała coś specyficznego inieakceptowalnego. Należy unikać takich wsadów. Ale jak chłopaki wyjaśnią, ze ma to sens, to wtedy mamy opcję drugą. Jak nie to trzeba dążyć pełną parą do opcji pierwszej (całość u jsergio).

Sprawdziłem w źródłach Kodi (wyjąłem funkcję i ją skompilowłem), wersja porównywana jest w sposób debianowy. Można dodawać tekst, a liczby dalej mają koleność numeryczną, np.:
```
1.2.3-cherry2.4 < 1.2.3-cherry11
1.2.3-cherry2.4 < 1.2.4
```

**Comment by notoco** [comment]
Jak dla mnie można by w końcu wstrzyknąć do jsergio poprawki z cherry, ale i tak będziemy mieli bałagan z tymi wersjami. Tu wchodzimy w podstawę tego problemu - czyli fakt iż w pewnym repo które już nie istnieje pewna osoba zawsze chciała być pierwsza i zaczęła zabawę z podbijaniem.
Drugim rozwiązaniem jest wspólna akcja mbebe/podpis/cherry/phantom i praca nad polską wersją resolvera z numeracją 6.x.x - wtedy zwykły user nie będzie miał problemów.
Ale tu jest konieczne porozumienie między autorami i obranie wspólnego frontu - IMO nie powinniśmy robić każdy pod inną wersję resolvera tylko pod jedną - wszak to dla zwykłego usera. Po zniknięciu ramicspa/mrknow powstał problem który do dziś nam siedzi na plecach.
Także apel @mbebe @podpis @all - pracujmy nad jednym resolverem, tym od cherry - @xulek - wydzielmy je do odrębnego repozytorium, co by inni twórcy mogli je podłączać w swoich repozytoriach.

**Comment by xxcriticxx** [comment]
@rysson co kolwiek aby parowania real derbid nie tracic

**Comment by xxcriticxx** [comment]
@notoco byle o aby password nie trzeba wprowadzac co nowa versie

**Comment by xxcriticxx** [comment]
Może niech @mbebe / @grzebzi zapyta czy jserio przyjmie polskie zmiany do resolvera

**Comment by notoco** [comment]
> Moim zdaniem wszystkie wtyczki powinny być rozdzielone do osobnych repo. I tak cherry-dev jest lepsze od samych ZIP-ów, ale podział na osobne repo daje pełne pole manewru. Bardzo silnie oddzieliłbym wtyczki (utrzymywane w źródłach) od repo czyli binarnych zestawów wtyczek.

Nie, nie powinny być oddzielnie. Jeden autor - jedno repo. Jak sobie wyobrażasz 40 repozytoriów i aktualizację, szukanie w repozytoriach.... Jak dla mnie twórczość autora winna być w jednym miejscu.

**Comment by rysson** [comment]
@notoco, no właśnie problem jest, że to nie do końca jeden autor. Niektóre wtyczki są dev, niektórych nie ma, mimo, że w Cherry są. A jak ktoś chce spaczkować jedną, dwie wtyczki to po co mu całe repo. 

Zobacz jaki problem jest z utrzymaniem zmian w resolverze. Nie możesz po prostu zrobić `git cherry-pick`. Nie wiem jak to aktualizujecie, ale mam nadzieję, że nie ręcznie.

Tego wszystkiego nie ma jak są osobne repa. A jk lubisz mieć porządek w drzewie, to możesz meić wspólne repo i git submodules.

To nie jest niezbędne, ale ułatwia. Zresztą dopuszczam myśl, że część wtyczek może być razem. Nie cieszy mnie ale i nie przeszkadza za bardzo. Za to zewnętrzne (jak resolver) albo ogólne (jak PTW) wyjąłbym do osobnego repo dev.

**Comment by xxcriticxx** [comment]
@notoco ja mam problem ze musze znowu parowac 15 urzadzenie co nowa wersie

**Comment by xxcriticxx** [comment]
Czyli panowie i panie jaki jest plan?

**Comment by rysson** [comment]
Na razie pewnie żaden. Ja proponuję poczekać że dwa tygodnie, zademonstruję wygodniejszy, mam nadzieję, sposób budowania, przykładowe repo i wtedy wznowimy dyskusję jeśli będą chętni. 
Nie ma co się spieszyć a potem odwijać.

**Comment by xulek** [comment]
Z tego co pamiętam to jsergio nie chce u siebie modułu requests, a ja dodałem kilka stronek z użyciem tego modułu. Dodatkowo w Cherry jest autoparowanie openload i dlatego zależy im na tym aby ich wersja była najwyższa. A autoparowania w świat nie możemy puścić z różnych względów, o których nie chcę pisać :)

**Comment by notoco** [comment]
A autoparowanie nie jest tylko w VIP?

**Comment by rysson** [comment]
O! Własnie autoparowanie jest w CHERRY czy w jakiś zamkniętych repo?
Nie dopytuję się o zamknięte (pamiętam naszą rozmowę) tylko o otwarte repo. 
Żeby nie wyciekło jeśli nie powinno.

**Comment by rysson** [comment]
> jsergio nie chce u siebie modułu requests,

A właśnie, @grzebzi musiał wywalać od siebie requests.
No cóż to trochę zmienia. 

A może zrobimy meta-resolver. Taki resolver co używa innych resolverów (w liczbie dowolnej). Wtedy moglibyśmy się skupiać tylko i wyłącznie na łączeniu (proste by to było) i na własnych specyficznych dodatkach, a resztę brać od jsergio i np. z youtube-dl (spaczkowałem go kiedyś).

Niestety wymagałoby to zmiany nazwy i dostosowania naszych wtyczek do korzystania z meta-resolvera.

**Comment by xulek** [comment]
@notoco Jest ale to nie zmienia faktu, że jak wersje będą szły równolegle to będzie im nadpisywać tą autoparowaniem. Wersja publiczna też jest wersją wyższą bo kiedyś autoparowanie było publicznie udostępnione i żeby teraz nie robić problemów z nieaktualizującym się resolverem od jsergio(bo juz pobrali wyższą wersje, która była z openloadem) to publiczna wersja od cherry jest aktualizowana do poprawek jsergio i zwiększana. Autoparowanie na ten moment nie ma możliwości wyciec nawet jakby było w publicznym repo (chyba, że mówimy o tym repo co Ci @rysson wyslałem bo tam jest bez zabezpieczeń :P) Trochę zamieszałem ale mam nadzieje, że mój komentarz jest zrozumiały :D

**Comment by rysson** [comment]
>  mówimy o tym repo co [...] wyslałem  
Dlatego pisałem, że pamiętam. Możesz wyciąć to z komentarza, żeby nie budzić emocji :)

Tak, autoparowanie nie jest dostępne w publicznym CHERRY i to mnie uspokaja.

A co z pomysłem zmiany nazwy? Jest to bolesne, ale jakbyśmy to dobrze przemyśleli, to może ta bolesna zmiana (dotykająca użytkowników) byłaby jednokrotna.
Tylko musimy rozważyć wszystkie scenariusze.
Np.
- można ogłosić, że trzeba instalować nowe;
- można do naszych wtyczek dodać zależności;
- można dodać pakiet tranzytowy (resolverurl), który będzie wymagał naszego meta-resolvera; dzięki temu u userów zainstaluje się samo;
- można zostawić w tranzytowym dodatku API jak jest teraz, to nawet obce wtyczki będą działać.
Itd.

**Comment by grzebzi** [comment]
jsergio nie przyjmie do siebie nic co ma requests, musiałem skorzystać z metod, które są w jego net.py,
odrzucił też bitporno, twierdząc, że został przeniesiony do xxx, chociaż niektóre linki z raptu przekierowują właśnie na bitporno

Przepychanie wszystkiego do jsergio miałoby jakiś sens, gdyby wersje się zgadzały, ale w CHERRY jest wyższa, więc dla większości coś co się nie zaktualizuje z automatu będzie bezużyteczne. 
Można by z nim pogadać i może jakoś kupą zrobić jedną wielką aktualizację, ale trzeba by wszystko przepisać bez requests.
Szczerze mówiąc nie porównywałem różnic między CHERRY i jsergio, ale podejrzewam, że rozjechane jest grubo i roboty byłaby kupa. 
Myślę że najlepszą opcją byłoby utrzymywanie oddzielnej wersji resolvera i ew. dodawanie nowych wtyczek od jsergio.

**Comment by rysson** [comment]
@grzebzi, no właśnie tylko to generuje dużo pracy.
Dlatego zaproponowałem właśnie co wymyślony meta-resolver. Taki, który by przepytywał inne resolvery. Nie musielibyśmy śledzić jsergio. Problemem jest numer wersji a jeszcze bardziej nazwa.

Im dłużej nad tym myślę, tym bardziej jestem za zmianą nazwy. Wtedy jest to w naszych rękach i nie musimy przepakowywać jego roboty (co generuje zamieszanie).

Tylko trzeba przeanalizować wszystkie skutki.

**Comment by notoco** [comment]
@rysson - to może teraz ja, jako kompletny laik w programowaniu, ale z pewną wiedzą zwykłego usera.
Z tego co rozumiem ideałem byłoby zrobienie takiej wtyczki która by łączyła w sobie ten od jsergio, który by się aktualizował zgodnie z jsergio sam, oraz nasze/wasze/polskie poprawki które by były odrębne. Nowa nazwa+ nowa numeracja - na zasadzie np: meta-resolveurl-6.4-jsergio5.0.17. Dorzucone jako nowa zależność do polskich wtyczek.
Wtedy wymusza to utworzenie odrębnego repozytorium kodi dla "meta-resolveurl" co by inni mogli je łatwo włączyć do siebie.
I teraz tak:
> można ogłosić, że trzeba instalować nowe;

Nie zda to egzaminu - ty, ja, xxcritixx to zrobimy, posiadacze buildów dostaną w kolejnej aktualizacji, ale wiele osób w ogóle nie skojarzy o co chodzi.

> można do naszych wtyczek dodać zależności;

to w połączeniu z tym 

>można dodać pakiet tranzytowy (resolverurl), który będzie wymagał naszego meta-resolvera; dzięki temu u userów zainstaluje się samo;

zda egzamin dla zwykłego usera - nie zauważy nic - poza koniecznością ewentualnego parowania z realdebrid

> można zostawić w tranzytowym dodatku API jak jest teraz, to nawet obce wtyczki będą działać.
Itd.

nie rozumiem i podejrzewam że zwykły user też nie...

Tylko jest tu jedna rzecz którą by musieli wszyscy spełnić - przyjąć we wtyczkach mbebe/podpis/cherry/grzebzi jedną zasadę że stosuje się ten jeden resolver jako zależność - odrębne repo to ułatwi.

**Comment by rysson** [comment]
@notoco, dzięki, o to mi chodziło. To dopiero początek analizy.

#### Wyjaśnienie
Najpierw wyjaśnię
> można zostawić w tranzytowym dodatku API jak jest teraz,

Chodzi o to, żeby meta-resolver (a nie tranzytowy, przepraszam) był widziany nawet przez obecne wtyczki tak samo jak obecny resolveurl (czyli punkt wejścia lib.resolveurl). Dzięki temu wtyczki, których nie mamy w naszych łapach też będą działać.


#### Meta-resolver
Teraz dalej, zrodzony wczoraj pomysł meta resolvera to tylko pośrednik do właściwych resolverów. Z zewnętrznymi regułami priorytetów (to pomysł z dzisiaj). 

Oryginalny resolveurl od jsergio paczkujemy jako script.module.resolveurl.jsergio (5.0.17).
Dodatkowo zmieniamy punkt wejścia (nazwę lib.resolveurl na lib.resolveurl-jsergio albo coś podobnego).

resolveurl-6.4-jsergio5.0.17  (*to jest właściwy pakiet tranzytowy*)
↳meta-resolveurl-0.1.0      (*wymaga*¹)
↳resolveurl.jsergio-5.0.17  (*wymaga*¹)
↳(*wymaga¹ jakiegoś naszego pakietu z preferencjami, patrz dalej*)

meta-resolveurl-0.1.0              (*to on ma główny punkt wejścia: `lib.resolverurl`)
↳ resolveurl.jsergio-5.0.17     (*łączy się*²)
↳ resolveurl.pl 0.1.0               (*łączy się*²)
↳ resolveurl.youtubedl-0.1.0  (*łączy się*²)
↳ ...

resolveurl.youtubedl-0.1.0
↳ youtubedl-2018.10.05.0  (*wymaga*¹, *to tylko biblioteka*)

... (*itd.*)

Tak jak wsponiał @notoco, wszyscy powinnismy przejść (w zależnościach) na meta-resolver.
Z tym, że jak ktoś się zagapi to też będzie działać (zainstaluje się meta-resolver + resolveurl.jsergio).

Podział na repozytoria popieram. Choć z powyższym podziałem na pakiety powinno się to dać upchnąć nawet w pojedynczym binarnym repo.

¹) Wymaga, czyli jest w zależnościach (`requires/import`)
²) Łączy się, czyli nie ma w zależnościach ale jest zainstalowany to używa. Innymi słowy przeszukuje zainstalowane dodatki pod kątem sub-resolv


#### Paczki preferencji
Do tych wszystkich naszych resolverów (pl, youdubedl itd.) można dodać jakąś klasę bazową (rodzaj wzorca), dzięki czemu pisanie ich będzie banalne. To już szczegół techniczny, choć może się wtedy pojawić zależność od powiedzmy script.module.resolveurl.api.
erów.

Dodatkowo, wspomniany dzisiaj pomysł, to zbiór reguł dla meta-resolvera, których resolverów dla którch linków używać najlepiej. Czyli lista preferencji. Oczywiście w meta-resolverze będzie domyślna, a poza tym jak mu jeden sposób zawiedzie (sub-resolver się podda), to będzie brał następny.
Preferencje widzę, poza wpisywaniem w oknie konfiguracji meta-resolvera (co nie jest najwygodniejsze) jako dodatkowe paczki, które mogą być polecane na stronach. Wtedy w meta-resolwerze będzie można wybrać, który zestaw ma obowiązywać (jak user zainstaluje ich pare). 

Czyli np.

script.module.resolverurl-pref.cherry
↳ meta-resolveurl     (*wymaga*¹)
↳ resolveurl.jsergio   (*wymaga*¹)
↳ resolveurl.pl           (*wymaga*¹)
↳ *plus reguły, od którego z powyższych sub-resolverów zaczynać dla szukanego linku*


#### Podsumowanie
Wygląda na przekombinowane, ale daje spore możliwości. Przy paczkach preferencji się nie upieram ale i one ułatwią userom działanie, a jednocześnie nie zablokują możliwości dostosowania.

Co to daje (albo mi się wydaje, że daje – proszę o krytykę):
* płynna przesiadka (dzięki zależnościom),
* stary kod (bez przeróbek), też powinien zadziałać,
* kod jsergio bez dodatkowego czasu, nawet z numerem wersji (wadą jest ingerencja we źródła, ale to powinien załatwić nowy builder z automatu),
* dowolna ilość nowych resolverów.

Chciałem na koniec zaznaczyć, że wszystkie ogólne zmiany i tak powinniśmy się starać wpychać do jsergio, wtedy więcej osób to ma i to testuje. Ale dzięki podziałowi nie wszystko musi tam trafić a i z pozostałymi zmianami nie musimy się spieszyć (np. z usuwaniem requests).

Mam nadzieję, że choć trochę zrozumiale napisałem.

**Comment by notoco** [comment]
No teraz to rozumiem.

**Comment by xxcriticxx** [comment]
@notoco cos takie jak lambda scrapers
