### ISSUE TITLE
zalukaj error

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#297]
sprawdzane na kodi17.6(win7) i 18.6(android) na trzech wersjach ResolveURL, zastosowanie się do porady w ostatnim poście kodiwpigulce z temetu głównego ResolveURL nie pomaga. wtyczki ekino, alltube, hdseans, hejo, 3filmy, fanfilm, efilmy działają prawidłowo. Pozdrawiam

**Comment by mbebe** [comment]
resolveurl jest tylko do odtwarzania. Jaki error wychodzi? Przy odtwarzaniu wlasnie? Czy co?

**Comment by xxcriticxx** [comment]
@rafalmar1981 posiadasz konto VIP?

Duze obciazenie! Tylko uzytkownicy z kontem VIP maja dostep do strony. Zaloguj sie lub Zarejestruj

**Comment by rafalmar1981** [comment]
mam konto vip, a resolveurl  6.4.118, przy próbie wejścia w wtyczkę(teraz na androidzie błąd zalukaj).
log:  https://paste.kodi.tv/jodamiqifu

**Comment by mbebe** [comment]
poszla poprawka

**Comment by rafalmar1981** [comment]
Dziękuję

**Comment by FXcodi** [comment]
Zalukaj.vip z MB filmy też przestało działać.

**Comment by xxcriticxx** [comment]
@FXcodi Jeśli nie dostałeś konta premium to napisz na email admin@zalukaj.vip , chwilowo brak wolnych kont premium, nowe dojdą dopiero we wtorek :)

Filmy i seriale dostępne tylko dla osób z wykupionym dostępem.
Zaloguj się lub Zarejestruj i wybierz plan, aby uzyskać dostęp Premium!

**Comment by kodiwpigulce** [comment]
Tak z ciekawości ile trzeb zapłacić pirackim złodziejom za konto premium? :D

**Comment by xxcriticxx** [comment]
@kodiwpigulce moze bys zrobil tabele u siebie ile kto bierze za serwise to sie posimiejemy troche :)

**Comment by kodiwpigulce** [comment]
Nie rozumiem? Płaciłeś coś korzystając z mojej strony czy forum? Zapytałem ile sobie życzą za konto premium.

**Comment by xxcriticxx** [comment]
zrob tabele ile kosztuja konto premium na innych serwisach

**Comment by kodiwpigulce** [comment]
aaa ok w każdym razie już sprawdziłem

**Comment by xxcriticxx** [comment]
ile?

**Comment by kodiwpigulce** [comment]
ktoś mi napisał, że niby 20 pln ale ile w tym prawdy :)

**Comment by xxcriticxx** [comment]
strata pieniędzy

**Comment by leonzawodowiec12** [comment]
zalukaj chyba padło

**Comment by mbebe** [comment]
hej @kodiwpigulce wlozyliscie tu reklame? ;-)
![6565656565](https://user-images.githubusercontent.com/30195202/81591617-ff9f8300-93bc-11ea-80c5-8ecae69a2cd2.jpg)

**Comment by xxcriticxx** [comment]
kodiwpigulce = zalukaj na pewno

**Comment by notoco** [comment]
Ta... Ukrywał. Się.

**Comment by kodiwpigulce** [comment]
@mbebe już od dawna tam wisi z niewiadomej przyczyny. 😏 
@xxcriticxx na pewno 😱

**Comment by xxcriticxx** [comment]
@kodiwpigulce poprawki naniesione

**kodiwpigulce **≠** zalukaj**
