### ISSUE TITLE
Kontakt 

### ISSUE THREAD

**Issue by vTneilA** [mbebe/blomqvist#30]
Siema można dostać jakiś kontakt na email ?

**Comment by mbebe** [comment]
Napisz ogolnie w czym rzecz.

**Comment by vTneilA** [comment]
Chce wysłać dotację

**Comment by mbebe** [comment]
LOL

**Comment by xxcriticxx** [comment]
@vTneilA https://www.pajacyk.pl/

**Comment by vTneilA** [comment]
Spoko. . Mam wrażenie że jestem w cyrku. Pozdrawiam

**Comment by mbebe** [comment]
mbebeGIT (at) gmail.com

tu napisz  . za chwile usuwam ;-)

**Comment by vTneilA** [comment]
Ok poszło

**Comment by mbebe** [comment]
Nie bedzie problemu.

**Comment by xxcriticxx** [comment]
@vTneilA dobrze powiedziane
