### ISSUE TITLE
Altube problem z resolve_url

### ISSUE THREAD

**Issue by FXcodi** [mbebe/blomqvist#306]
Jaki potrzeba resolver_URL aby odtworzyć filmy z np: clipwatching, upstream, easyload bez otworzenia z tych streamów można przyjąć, że wtyczka "alltube"prawie nie działa.

**Comment by notoco** [comment]
clipwatching działa,upstream też działa... easyload nie chce mi działać (ale nie wiem czy to nie martwe źródła). Resolver - jak zawsze dla polskich wtyczek- najnowszy z repo FanFilm

**Comment by FXcodi** [comment]
Po wyczyszczenie pamięci z Kodi i ponownym zainstalowaniu repo mbebe oraz fanfilm clipwatching ruszył.

**Comment by wisiann** [comment]
Zamkinji topik  jak mozesz
