### ISSUE TITLE
wtyczka do seriale.co

### ISSUE THREAD

**Issue by xxcriticxx** [mbebe/blomqvist#31]
slucham waszych opini krytyka mile widziana

**Comment by rafalmar1981** [comment]
gdzie ta wtyczka jes  i ta druga

**Comment by mbebe** [comment]
@rafalmar1981  @xxcriticxx  poprosil o opinie strony seriale.co i czy warto by bylo utworzyc do niej wtyczke. ;-) a ty jakis w goracej wodzie kapany. chcialbys juz, teraz, za chwile :-)

**Comment by xxcriticxx** [comment]
za duzo red bulla

**Comment by rafalmar1981** [comment]
dobbre dobre przejrze strony rano i  dam opinie sorry za wczesniej

**Comment by mbebe** [comment]
jutro dodam seriale.co

**Comment by mbebe** [comment]
dodane do repo

**Comment by xxcriticxx** [comment]
dzieki

**Comment by kashkash18** [comment]
Wtyczka przyjemna ale w liście seriali brak okladek

**Comment by mbebe** [comment]
mocno zwolni wtyczke. zobacz na stronie spis seriali po lewej stronie. po najechaniu nie ma zdjec. a tak by musialo otwierac linka, pobierac obrazek itp.

**Comment by mbebe** [comment]
ja na miejscu wlasciciela serwisu, gdyby za kazdym wejsciem na strone bylo przez jednego uzytkownika wysylanych ponad 200 odpytan, bo tyle jest seriali na liscie, bym uzytkownika zbanowal. :-D
wiec wole takiego czegos uniknac. 
Kiedys filmwebooster o takim zachowaniu pisal we wtyczce ramica :-)
dlatego uwazam, ze taka opcja moze tylko zaszkodzic i spowodowac zablokowanie korzystania z tej strony .

**Comment by xxcriticxx** [comment]
@mbebe mozesz sparowac z zewnetrznego serwisu filmweb.pl? 

https://github.com/Regss/metadata.filmweb.pl

**Comment by mbebe** [comment]
w repo aktualizacja 1.1 
w ustawieniach wtyczki wyszukiwanie z filmweb opisu i okladki.

**Comment by kashkash18** [comment]
A czy ten myk z Filmweb jesteś w stanie zastosować do Nasze - Kino ??

**Comment by kashkash18** [comment]
Tak , teraz jest ok . Temat można zamknąć.

**Comment by xxcriticxx** [comment]
testowalem dlugo zajmuje lepiej jest bez okladek
