### ISSUE TITLE
VirpeCOM Problem

### ISSUE THREAD

**Issue by Bogdan16** [mbebe/blomqvist#313]
witam mbebe

jest mozliwosc poprawienia VirpeCOM  bo caly czas sie kreci

Pozdrawiam

**Comment by Contralege** [comment]
Pod Androidem w dalszym ciągu ten sam problem cały czas się kręci i nic nie wchodzi

**Comment by Mariusz89B** [comment]
Ktos poda log?

**Comment by sky0002** [comment]
Proszę 
https://paste.kodi.tv/oxivarilem

**Comment by Smerd1233** [comment]
Na Fire stick apka tez tylko kreci i nic sie nie dzieje dalej, ale to sprawa nie sprzed tygodnia ale prawie ponad miesiaca,wiele osob pisalo, prosilo i jakos nie udalo sie tego poprawic......moze teraz sie uda ???

**Comment by Mariusz89B** [comment]
Blad get url.

**Comment by Smerd1233** [comment]
Mozna to poprawic Panie Mariuszu ???

**Comment by Mariusz89B** [comment]
> Mozna to poprawic Panie Mariuszu ???

Niewiem jutro sprawdze.

**Comment by Mariusz89B** [comment]
Wyglada na to ze trzeba chyba dodac cloudflare, niestety nie robilem tego wczesniej.
