### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by leonzawodowiec12** [mbebe/blomqvist#315]
@mbebe 

1. ArenaParty 1.0 nie działa
2. Boso Przez świat 1.3 błąd dodatku 
3. cda-hd 1.7.0 błąd dodatku
4. cda-tv 1.3.7 linki nie działają 
5. darmowatv 1.7.7 nie działa
6. efilmy 1.27 nie działa
7. ekino-tv 2.6.3 nie działa
8. filman.cc 2.1 nie działa
9. Filmdom.fun nie działa
10. Filmwebbooster nie działa
11. freedisc 1.5 linki nie działają 
12. Horrortubepl 1.5 błąd dodatku
13. Hulkstream 2.2.1 błąd dodatku
14. iitv-seriale 2.8 nie działa 
15. filmeria.co pusto wszędzie
16. filmninja.ws linki nie działają
17. serialnet.pl 1.1 linki nie działają
18 Szukajka.tv 1.4.3 nie działa
19. TVP.pl 2.2.4 wiadomości nie działają 
20. Vider 1.8 nie działa
21. Virpecom 1.9.2  nie działa 

Do usunięcia:

1. Kreskówkitv strona padła
2. segos strona padła
3. Zalukaj strona padła 

Do dodania:

1. zobacz.ws
2. filmynadzis.pl
3. cda-tv.online
4. playerek.pl
5. exdb.net
6. zerion.cc
7. govod.tv
8. darmowe-filmy.online

**Comment by xxcriticxx** [comment]
@leonzawodowiec12 zajebista robota dzięki!

**Comment by Huero23** [comment]
@leonzawodowiec12 U mnie TVP.PL WIADOMOŚĆ NA VOD ODBIERA OK... Używam NordVpn z Los Angeles.

**Comment by sky0002** [comment]
Tu bardzie chodzi o
bastek6 napisał(a):
Problemem jest wtyczka inputstream.adaptive  usuń nową i zainstaluj wersje 2.4.2.1 U mnie pomogło, tylko pamiętaj żeby wyłączyć automatyczną aktualizacje.
Dla CoreELEC https://relkai.coreelec.org/?dir=addons/9.2/Amlogic/arm/inputstream.adaptive i potwierdzam prawidłowe działania rozwiązania. Nie trzeba obniżać wersji Kodi. Cyfrowy Polsat go także odzyskuje dźwięk

**Comment by leonzawodowiec12** [comment]
https://zerion.cc

**Comment by telewizortcl** [comment]
Ciekawie wygląda strona http://filmynadzis.pl - może dałoby się zrobić do niej plugin w kodi?

**Comment by xxcriticxx** [comment]
filmynadzis czyli jutro tej strony juz nie bedzie

**Comment by telewizortcl** [comment]
A dlaczego ma niby tej strony nie być?

**Comment by mbebe** [comment]
co nie dziala np. w arenaparty?

**Comment by leonzawodowiec12** [comment]
ok jednak działa :) ale nie działało mi sorry za zamieszanie

**Comment by leonzawodowiec12** [comment]
@mbebe dodasz https://telewizja.cc i http://tv-swirtvteam.info

**Comment by adamibeata** [comment]
Witam jeśli oczywiście to dodacie to dajcie link do pobrania   pozdro

**Comment by mbebe** [comment]
@leonzawodowiec12  `@mbebe dodasz https://telewizja.cc i http://tv-swirtvteam.info`
   -dodane do darmowatv - wersja 1.7.8
@telewizortcl  `Ciekawie wygląda strona http://filmynadzis.pl - może dałoby się zrobić do niej plugin w kodi?`
   -dodane do mbfilmy
https://github.com/mbebe/blomqvist/issues/331#issuecomment-650806305  `A jak sytuacja wygląda z https://dudeplayer.com/ - może by się udało dodać do repo`
   -dodane do mbfilmy

**Comment by leonzawodowiec12** [comment]
@mbebe dzięki wielkie już przetestowane działa super

**Comment by adamibeata** [comment]
Cześć wszystkim  nie wiem czy to tak tylko u mnie jest  że nie można a raczej nie działa tv-swirtvteam.info  co prawda tak jest od samego początku :(   A wiadomo co się dzieje z telewizja.cc  ? 
A czy jest może jeszcze jakaś inna wtyczka  tv dostępna  czy tylko ta jedyna  "darmowatv"
Podzro dla wszystkich

**Comment by leonzawodowiec12** [comment]
@mbebe dodasz w wolnej chwili http://darmowatv.ws z góry dziękuję

**Comment by mbebe** [comment]
@leonzawodowiec12 - dodane w wersji 1.7.9

**Comment by adamibeata** [comment]
Witam @mbebe   jest możliwość aktualizacji wtyczki   darmowa nie odpala  a i to samo z SwirTeamTK pozdro dzięki

**Comment by adamibeata** [comment]
Prośba i zaktualizowanie darmowatv.ws   dzieki  (wtyczka nie widzi brak wszystkich programów )

**Comment by mbebe** [comment]
a ten swirteam ruszyl?

**Comment by mbebe** [comment]
darmowa zaktualizowana w repo.

**Comment by adamibeata** [comment]
Dzięki za aktualizacje  a napisze tak  swirteam  jak stoi tak stał czyli zero reakcji na cokolwiek oczywiście lista programów jest pokazana ale brak reakcji 
a darmowatv.ws  pokazała się lista lecz programów działających  to zaledwie około 10%  a reszta  kręci kreci i kręci a po chwili wywala czyli wcale nie reaguje  po prostu nie włączają się :(

**Comment by mbebe** [comment]
wymagane jest zainstalowanie f4mtester 
Zainstaluj 
[repository.proximSupp-0.0.6.zip](https://github.com/mbebe/blomqvist/files/5246046/repository.proximSupp-0.0.6.zip)
Pozniej z niego f4mtester i wtedy swirteam ruszy.

**Comment by mbebe** [comment]
I napisz jakie nie dzialaja w darmowej, bym nie musial szukac.

**Comment by mbebe** [comment]
Sprobuj wiec te wersje.
[plugin.video.darmowatv-1.8.1.zip](https://github.com/mbebe/blomqvist/files/5246897/plugin.video.darmowatv-1.8.1.zip)

**Comment by adamibeata** [comment]
Dzieki a raczej napisze co działa ok w nowej czyli 1.8.1
tvp1, tvp2, tvn-7, polsat puls, tvp-info, eurosport1, tvp-sport, canalfamily, canalseriale, canalfilm, alekino, comedy-central, polsat-film, discovery-channel, ID, planete, TLC, nat-geo-channel, tvn-turbo, hgtv,  reszta nie ruszyła
Co do swirteam to faktycznie ruszyło kilka działa a kilka nie  jak co to napisze  bo jest ich sporo tam

**Comment by adamibeata** [comment]
Nie wiem czy dobrze rozumiem f4mtester jak tam wchodzę nie widzę swirteam   jedynie co można zrobić i włączyć cokolwiek muszę iść do do wtyczki darmowatv i tam uruchomić swirteam ale z tego co przeglądam to jedynie kilka kanałów można ruszyć a reszta no raczej nie odpalają się  te które działają jest to kilka z samej góry a później już nici z tego

**Comment by mbebe** [comment]
Ok. Tu powinna byc jakas poprawa.
[plugin.video.darmowatv-1.8.2.zip](https://github.com/mbebe/blomqvist/files/5248155/plugin.video.darmowatv-1.8.2.zip)
A f4mtester - nic tam nie ruszaj. Ma byc po prostu zainstalowane, bo za jego pomoca sa odtwarzane w wiekszosci kanaly. :-D

**Comment by adamibeata** [comment]
Tam myślałem zainstalowałem te trzy dodatki co tam były f4mTester LiveStreamsPro F4mProxy wraz z dodatkami zależnymi  bo jak nawet coś chciałem wyjść to nic się nie działo  tak własnie przeglądam co tam działa co nie  w swirteam jest kilka programów co działają ale większość  albo błąd albo kręci i i i dalej nici z tego
Ps zaraz luknę na 1.8.2

**Comment by adamibeata** [comment]
Tak jak przeglądam w swirteam nie działa około 90% kanałów :(

**Comment by adamibeata** [comment]
A dało by rady ruszyć z hbo i canal bo wcale nie dają o sobie znać zero odzewu

**Comment by mbebe** [comment]
kolejna wersja.
Powinny dzialac te, ktore dzialaja na stronie.
Czasami u mnie zaskakuja za 2 razem.
[plugin.video.darmowatv-1.8.3.zip](https://github.com/mbebe/blomqvist/files/5249342/plugin.video.darmowatv-1.8.3.zip)

**Comment by adamibeata** [comment]
Większość kanałów ruszyła :) na swirteam lecz jest dzieje się tak ze niekiedy po 1min. samoczynnie się wyłączają kanały  później znowu uruchamiają się i za około min. znowu się wyłączają  i tak w kółko :(

**Comment by mbebe** [comment]
Dzieki za info. Teraz powinno byc juz ok. ;-)
[plugin.video.darmowatv-1.8.4.zip](https://github.com/mbebe/blomqvist/files/5250169/plugin.video.darmowatv-1.8.4.zip)

**Comment by adamibeata** [comment]
Czy jest możliwe jakoś inaczej z Tobą pisać przykładowa priv?

**Comment by mbebe** [comment]
Pisz maila.

**Comment by adamibeata** [comment]
Już nie wiem albo ja coś źle robię bo raczej nic to nie pomaga w tej ostatniej wersji jest bez zmian program a raczej kanał się włączy ale i tak wywala się wyłącza się i to trwa niekiedy 1min a niekiedy 30s. :(

**Comment by Janasek** [comment]
świrteam chyba nie mają własnego serwara i nie udostępniają własnych źródeł, wywala bo lista która jest tam gdzieś na ftp jest lisą dla xxx użytkowników rano może 20 wieczór może 1000 ,to tak samo,jak z pvr dodasz listę znalezioną w sieci to urywa połaczenie po kilkudziesięciu sekundach jak jest możliwość w addonie czy prv zrobić reconect true to odpali ten kanał ponownie ale jak ktoś gdzieś tam odpali addon czy listę w pvr to tobie znów przerwie i tak w kółko.

**Comment by adamibeata** [comment]
Hmm to trochę bezsens  bo skoro już odpalisz dany kanał  i leci kilkadziesiąt sekund czy  minut to czemu wywala raczej nie powinno tak mi się wydaje

**Comment by notoco** [comment]
I w tym momencie do listy dobija się kolejne dziesięć osób, serwer robi restart połączeń bo "przeciążony" i zaczyna obowiązywać zasada kto pierwszy ten lepszy - czyli im niższy ping itp

**Comment by adamibeata** [comment]
a dało by rady ruszyć z darmowatv.ws i hbo  canal , bo nie reagują wcale  dzięki

**Comment by mbebe** [comment]
Ok. w repo wersja 1.8.5. w swirteam powinny dzialac, w darmowa canal powinien dzialac, a hbo czasem rusza (tak samo na stronie).

**Comment by notoco** [comment]
No ale tu dodatek nic nie zrobi. To wina serwerów.

**Comment by adamibeata** [comment]
3 euro to jak za darmo daj namiar

**Comment by notoco** [comment]
Teleevidenie. W weekendy mają często otwartą rejestrację. Minimalna wpłata 9e, ale lista kosztuje 3e.

**Comment by adamibeata** [comment]
A jakiś konkretny adres ?  bo szukając w ciemno to jakieś wysypiska nieznane

**Comment by notoco** [comment]
https://my.teleelevidenie.com/signin

**Comment by adamibeata** [comment]
Z tego coo widzę jest tylko logowanie nic więcej :(

**Comment by notoco** [comment]
Będzie rejestracja dostępna to się pojawi opcja rejestracji. Trzeba obserwować. Na shoutbox kwp pojawiają się informacje kiedy jest otwarta

**Comment by adamibeata** [comment]
Brak listy nie ma nic ale zaraz...   jest :) 9ojro do zapłaty ale za co ?

**Comment by notoco** [comment]
Za 3 miesiące. Wybierasz sobie listę pl i opłacasz. Na kwp w którymś z tematów jest z obrazkami krok po kroku

**Comment by adamibeata** [comment]
Trochę przeszukałem temat  Na kwp i nic nie znalazłem  a szkoda  -  ale moim zdaniem powinno być pokazane co kupujesz w Teleevidenie bo to jakbyś kupował kota w worku płacisz ale nie wiesz za co to powinni oni udostępniać 
PS.
Coś się popsuło  w swirteam "( od 24 do 201 ) te pozycje nie działają nie odpalają się wcale mbebe  zerkniesz  dzięki.

**Comment by notoco** [comment]
jak nie widać? Poklikałeś tam chociaż troszkę?
Pakiety usług - tu sobie możesz zobaczyć co, i zerknąć jakie kanały w jakim pakiecie.
![screenshot-my teleelevidenie com-2020 10 18-20_34_22](https://user-images.githubusercontent.com/36659110/96376808-5df93a80-1181-11eb-900b-06060b63ca09.png)
Zamówienie serwisowe - tu sobie kupujesz...
![screenshot-my teleelevidenie com-2020 10 18-20_35_49](https://user-images.githubusercontent.com/36659110/96376836-87b26180-1181-11eb-9bc2-10ca8f2ef6a2.png)
Ale wcześniej musisz mieć wpłacone 9E - za miesiąc PL płacisz 3E, ale wpłaty mogą być jedynie >9E
I to robisz tu:
![screenshot-my teleelevidenie com-2020 10 18-20_37_06](https://user-images.githubusercontent.com/36659110/96376870-ba5c5a00-1181-11eb-977d-9f7ee59ce2d6.png)
Jak chcesz innej formy płatności - np. paypal, to pisz do ichniego supportu...

**Comment by notoco** [comment]
@mbebe - sorki za bałagan ;)

**Comment by adamibeata** [comment]
Cześć jeśli można to poproszę o dodanie http://darmowa-tv.ws

**Comment by Sonic198** [comment]
@mbebe czy przypadkiem darmowatv.ws z wtyczki darmowaTV nie powinno prowadzic do http://darmowa-tv.ws? Jak dla mnie linki w darmowatv.ws nie dzialają.

**Comment by mbebe** [comment]
@sonic , @adamibeata  w repo nowa wersja 1.8.6, dodalem tez jakies zagraniczne.

**Comment by telewizortcl** [comment]
Mam pytanie: w darmowatv nie działa we wtyczce kanał HGTV choć na stronie działa, co może być przyczyną?
W logi kodi tylko takie coś: 
2020-11-10 17:36:36.461 T:2504  NOTICE: @#@htmlhtml: ['http://darmowa-tv.ws/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp', 'https://shidurlive.com/embed.js', '//st.chatango.com/js/gz/emb.js', '//waust.at/d.js', 'http://darmowa-tv.ws/wp-content/plugins/contact-form-7/includes/js/scripts.js?ver=5.3', 'http://darmowa-tv.ws/wp-content/themes/jetblack/js/skip-link-focus-fix.min.js?ver=20201013-111955', 'http://darmowa-tv.ws/wp-content/themes/jetblack/js/keyboard-image-navigation.min.js?ver=20201013-111955', 'http://darmowa-tv.ws/wp-includes/js/imagesloaded.min.js?ver=4.1.4', 'http://darmowa-tv.ws/wp-includes/js/masonry.min.js?ver=4.2.2', 'http://darmowa-tv.ws/wp-content/themes/jetblack/js/functions.min.js?ver=20201013-111955', 'http://darmowa-tv.ws/wp-includes/js/wp-embed.min.js?ver=5.5.3']
2020-11-10 17:36:36.487 T:5328  NOTICE: VideoPlayer::OpenFile: TODO
2020-11-10 17:36:36.493 T:5724  NOTICE: Creating InputStream
2020-11-10 17:36:36.493 T:5724   ERROR: CVideoPlayer::OpenInputStream - error opening [TODO]
2020-11-10 17:36:36.493 T:5724  NOTICE: CVideoPlayer::OnExit()
2020-11-10 17:36:36.624 T:5328  NOTICE: CVideoPlayer::CloseFile()
2020-11-10 17:36:36.624 T:5328  NOTICE: VideoPlayer: waiting for threads to exit
2020-11-10 17:36:36.624 T:5328  NOTICE: VideoPlayer: finished waiting
link do kanału na stronie: http://darmowa-tv.ws/hgtv

**Comment by mbebe** [comment]
Bo nie ma dodanego shidurlive w mydecode.

**Comment by telewizortcl** [comment]
Dziękuję za odpowiedź, jednak nic mi ona nie mówi. 
Czy w związku z tym będzie aktualizacja wtyczki, czy nie jest to możliwe?

**Comment by mbebe** [comment]
Widze, ze wiekszosc juz padla.

**Comment by mbebe** [comment]
Ok. Poszla poprawka 1.8.7

**Comment by telewizortcl** [comment]
Dziękuję, faktycznie ten kanał już działa.
Ale nie chce ANIMAL-CHANNEL - komunikat "Brak działającego streama" choć ze strony internetowej działa http://darmowa-tv.ws/animal-channel/
Z góry dziękuję za kolejną poprawkę.

**Comment by mbebe** [comment]
Wczoraj poprawione.

**Comment by telewizortcl** [comment]
serwis "darmowa-tv.ws" dodał jakieś zabezpieczenie anty-ddos cloudfire sprawdzające przeglądarkę i chyba przez to nie działa plugin w KODI. Nie wiem na czym to polega, ale w przeglądarce tak jakby trzeba poczekać kilka sekund i dopiero wpuszcza.

W logach takie coś:
2020-12-11 17:40:45.689 T:4912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.darmowatv\maintv.py", line 1270, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.darmowatv\maintv.py", line 1246, in router
                                                getDarmowaws()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.darmowatv\maintv.py", line 169, in getDarmowaws
                                                result = parseDOM(html, 'div', attrs={'class': "entry-content"})[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-12-11 17:40:45.720 T:5136   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.darmowatv/?image=C%3a%5cUsers%5cuser%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.darmowatv%2fresources%2fdarm.png&mode=darmowatvws&title=darmowatv.ws&url=http%3a%2f%2fdarmowa-tv.ws
2020-12-11 17:40:45.722 T:3940   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.darmowatv/?image=C%3a%5cUsers%5cuser%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.darmowatv%2fresources%2fdarm.png&mode=darmowatvws&title=darmowatv.ws&url=http%3a%2f%2fdarmowa-tv.ws) failed
