### ISSUE TITLE
IPLA-BŁĄD 

### ISSUE THREAD

**Issue by Huero23** [mbebe/blomqvist#319]
Ipla->Vod->Seriale->Bład 
![IMG_22361](https://user-images.githubusercontent.com/19337836/83202623-d0974a00-a0fc-11ea-82f3-4da6d5097632.jpg)

**Comment by kashkash18** [comment]
Wyloguj się z wtyczki i zrestattuj Kodi . Wejdź we wtyczkę i zaloguj ponownie.

**Comment by Huero23** [comment]
@kashkash18 Dziękuje wszytko teraz działa... 👍
