### ISSUE TITLE
wtyczka do virpe.com

### ISSUE THREAD

**Issue by xxcriticxx** [mbebe/blomqvist#32]
meserak86 kiedys podawał taka strone

slucham waszych opini krytyka mile widziana

**Comment by krecik71** [comment]
nawet fajna

**Comment by xxcriticxx** [comment]
slabe te wasze opinie wtyczki nie bedzie

**Comment by rafalmar1981** [comment]
wiec ju po ptakach, strona jest dpbra  czytelna  i duzzo seriali ja jestem na tak

**Comment by timtumturutumtum** [comment]
Pozwolę dopisać swoją opinię teraz,  chodź może ona już nic nie wnieść do tematu. 
Sam serwis posiada bogatą kolekcje i dobrze było by mieć ją po ręką w jednym miejscu,  żona była by zadowolona bo seriale które oglada ma w jednym miejscu,  a ja mam spokój :) 
Niestety część materiału nie działa, może tylko u mnie (np.  Alternatywy 4), ale to można przeżyć. 
W mojej opinii jeżeli @Mbebe miał by chęć zrobić wtyczkę to spora część userów będzie bardzo zadowolona.

**Comment by mbebe** [comment]
virpecom w moim repo :-D

**Comment by kashkash18** [comment]
Nie widać w repo i odepnij debuggera bo sypie błędami.

**Comment by mbebe** [comment]
poprawione

**Comment by Contralege** [comment]
Wtyczka virpe po aktualizacji 1.9.2 nie otwiera się pod Androidem natomiast pod Windows jest wszystko ok

**Comment by kashkash18** [comment]
Na Androidzie występuje problem z Cloudflare. Trzeba czekać na rozwiązanie
