### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Bogdan16** [mbebe/blomqvist#327]
Witam

Alltube nie dziala jak sie cos wybierze to wywala blad Alltube

Pozdrawiam

**Comment by xxcriticxx** [comment]
@Bogdan16 najlepiej szybko sprawdzic na stronie co sie dzieje

Lista linków
Tylko zalogowani użytkownicy mają dostęp do linków.

**Comment by Bogdan16** [comment]
witam

Jestem zalogowany na stronie wszystko dziala a na Kodi wywala Blad Alltube

**Comment by notoco** [comment]
Ten alltube plus to przekręt. Wyszukują tylko linków do serwisów takich jak Netflix HBO Ipla. Nie oferują nic.

**Comment by rafalmar1981** [comment]
@notoco święta racja

**Comment by notoco** [comment]
@rafalmar1981 - wiem. Jak zawsze. Od lat ten sam i bez zmian.

**Comment by Bogdan16** [comment]
witam
na alltube bedzie poprawiony blad

Pozdrawiam

**Comment by notoco** [comment]
No jak poprawisz to będzie....
Ja tu nie jestem programistą. Jeśli mbebe ogarnie temat to będzie poprawione. Jeśli nie, to może ktoś inny ogarnie.

**Comment by xxcriticxx** [comment]
@notoco i senior taki jak ja dal sie wyciulac.  Trzeba dodac to do KAD host na pihole.

**Comment by notoco** [comment]
Ulala... No po tobie się tego nie spodziewałem. Zawiodłeś mnie młody padawanie.

**Comment by mbebe** [comment]
@Bogdan16 jaki material do odtworzenia wymaga zalogowania na stronie http://alltube.pl?

**Comment by mbebe** [comment]
Poszla poprawka, ktora poprawnie odtwarza seriale.

**Comment by Bogdan16** [comment]
mbebe witam

bardzo dziekuje za poprawke wszystko dziala

Pozdrawiam

**Comment by kopernik1983** [comment]
Wszystko ze strony głównej na Alltube tam cię przeniesie , filmów szukaj po kategoriach , a nie ze strony głównej 
![ice_screenshot_20200619-052638](https://user-images.githubusercontent.com/33724908/85093910-c04f2800-b1ed-11ea-95f7-b79246ed681b.jpeg)
![ice_screenshot_20200619-052708](https://user-images.githubusercontent.com/33724908/85093920-c80ecc80-b1ed-11ea-9b98-3d5fa098a617.jpeg)

**Comment by mbebe** [comment]
@Bogdan16 tu jest opisane, ze to przekret z tym przeniesieniem https://github.com/mbebe/blomqvist/issues/327#issuecomment-645523061 wiec nie zakladaj tam konta. :-D

**Comment by Bogdan16** [comment]
Witam mbebe

Alltube nie dziala znowu jak sie cos wybierze to wywala blad Alltube

Pozdrawiam
