### ISSUE TITLE
www.alantvsport.com

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#33]
a co z tą stroną, udało by się zrobić wtyczkę?

**Comment by xxcriticxx** [comment]
@rafalmar1981 zapytaj ladnie prezesa

**Comment by kashkash18** [comment]
@mbebe daj znać czy jest jakakolwiek szansa na wtyczkę z tej strony. Duża ilość wydarzeń oraz dużs liczba linków a do tego streamy stabilne . Wiem że roboty przy tym jest od groma, ale jak nie ma na nią opcji to zamykamy i zapominamy o temacie. Poprzedni temat zamykam już teraz bo kolega zamiast napisać w już otwartym , otworzył nowy. 

Osobiście uważam że wtyczka z tej strony by się bardzo przydała .

**Comment by Zorish** [comment]
xxcriticxx  Proszę. Nie używaj słowa Prezes.

**Comment by mbebe** [comment]
Bede nad nia pracowal...

**Comment by kashkash18** [comment]
To zajebiście dobra informacja :)

**Comment by xxcriticxx** [comment]
@Zorish roger

**Comment by Zorish** [comment]
xxcriticxx  Husar.
