### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#331]
Witam mam pytanie co sądzicie o deltamediaplayer.com czy warto by było pochylić się nad tą stroną? I czy można by zrobić taką wtyczkę? Pozdrawiam

**Comment by kashkash18** [comment]
Pamiętaj że jest to P2P , więc VPN to podstawa przy użytkowaniu tego typu wynalazków

**Comment by rafalmar1981** [comment]
no proszę dziękuje za informację

**Comment by FXcodi** [comment]
A jak sytuacja wygląda z https://dudeplayer.com/ - może by się udało dodać do reopo
