### ISSUE TITLE
Alltube

### ISSUE THREAD

**Issue by Bogdan16** [mbebe/blomqvist#332]
Witam mbebe

Alltube Kodi 18.7 na Kompie lata bez problemu ale Alltube Kodi 18.7 na Android to wywala blad Alltube
jest mozliwosc poprawke zrobic na Kodi 18.7 Androida

Pozdrawiam

**Comment by FXcodi** [comment]
U mnie bez problemów na 18.7 android.

**Comment by notoco** [comment]
Dokładnie to samo u mnie. Działa. Może wrzuć logi: www.kodiwpigulce.pl/logi
