### ISSUE TITLE
Ipla

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#336]
Witam, wykupiłem seriale w ipli na stronie ipli chodzi,  a na 18.6(android) zakręci się chwile i koniec. Jakieś pomysły Panowie i Panie??

**Comment by Mariusz89B** [comment]
Jaka masz wersje inputstream.adaptive?

**Comment by rafalmar1981** [comment]
@Mariusz89B dzięki za zainteresowanie ale zresetowałem wszystko i poszło. Pozdrawiam
