### ISSUE TITLE
serialnet,pl

### ISSUE THREAD

**Issue by Bogdan16** [mbebe/blomqvist#339]
witam mbebe

od 3 dni na serialnet.pl jest blad jest mozliwosc poprawic ten blad

Pozdrawiam

**Comment by kopernik1983** [comment]
Nie ma takiej możliwości , wystarczy kliknąć w link , żeby dowiedzieć się dlaczego . https://serialnet.pl/

**Comment by rafalmar1981** [comment]
Dlatego zawsze najlepiej sprawdzić stronę czy działa, a jeżeli tak to po włączać kilka linków i jak na stronie np. działa, wtedy pytać o możliwość poprawki. Poco zawracać głowę i czas. Pozdrawiam
