### ISSUE TITLE
filman.cc

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#341]
Pierwszy raz udało mi się zalogować do serwisu, natomiast oprócz zakładek "filmy i dla dzieci - odtwarza filmy/bajki ale nie wszystkie na wielu pozycjach zakręci się chwile i koniec, na stronie serwisu te same pozycje działają " we wszystkich pozostałych wywala błąd na kodi 17,6(win7) i kodi18,6(android). Log z 17,6(win7) - https://paste.kodi.tv/tiyacilena

**Comment by notoco** [comment]
Coś dziwny ten log - okrojony - nie widać wersji wtyczek, więc ciężko powiedzieć gdzie jest problem. Zerknij tutaj jak prawiłowo wykonać log: http://kodiwpigulce.pl/logi

**Comment by rafalmar1981** [comment]
dokładnie tak zrobiłem ale dam log z kodi 18,6 na androidzie https://paste.kodi.tv/oyazocabef
Teraz dobrze?

**Comment by mbebe** [comment]
Jakie sie kreca i nie odtwarza a na stronie odtwarza?

**Comment by rafalmar1981** [comment]
tak dokładnie na stronie serwisu odtwarza

**Comment by rafalmar1981** [comment]
Dziękuję  za poprawkę wtyczki wszystko zapiernicza jak lala i mbfilmy też. Dzięki

**Comment by lucjan76** [comment]
dałoby radę mbebe zrobić tą wtyczkę dla premium bo mam i loguję się a pisze że darmowe!? mbebe podaj mejla na który mam ci wysłać ewentualnie dane logowania

**Comment by mbebe** [comment]
Pokazuje darmowe, ale i tak nie odtwarza?
Mail - 
![mmmmm](https://user-images.githubusercontent.com/30195202/93248256-e86c0a00-f78f-11ea-9a7f-ad1b4ee1b5db.jpg)

**Comment by lucjan76** [comment]
Odtwarza ale bez linku premium, zaraz wyślę ci mbebe dane do logowania

**Comment by lucjan76** [comment]
i da się coś zrobić mbebe żeby było premium i odtwarzało linki premium?

**Comment by mbebe** [comment]
Sprawdzam, spokojnie.
Logowanie juz mam poprawione. Teraz linki. :-D

**Comment by mbebe** [comment]
Ok, poprawilem. Wersja 2.5 w repo.

**Comment by lucjan76** [comment]
dzięki mbebe po pracy sprawdzę🙂

**Comment by lucjan76** [comment]
działa elegancko,na piwko poszło😉

**Comment by Mikolajek344** [comment]
Prosziłbym o pomoc, bo gdy uruchamiam wtyczke filman.cc na kodi 19.3 to mi wywala błąd, jak bym mógł go naprawić?
