### ISSUE TITLE
Pilna PROSBA. Wazne. :-/

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#346]
### W zwiazku z tym, ze mialo miejsce _spustoszenie_ w moim sprzecie, bardzo bym prosil o lekkie wsparcie.

![rere](https://user-images.githubusercontent.com/30195202/87985201-7ce12580-cadb-11ea-981e-65f3a18e240b.jpg)

Dane do jakichs wplat - https://github.com/mbebe/blomqvist/issues/39
Kazda pomoc mile widziana.
### Z gory dzieki. 
:-/

**Comment by notoco** [comment]
Coś tam puszczę. A jak jesteś w pl to polecam kompre.pl z poleasingowcami. Tanie a dobre. I naprawdę mają sztuki igła

**Comment by marcinkramek13** [comment]
Sprawdź PP nie majątek ale browarek będzie ;-)

**Comment by p3t3n3t** [comment]
:) grosze, ale jak się każdy dorzuci to damy radę :)

**Comment by Mariusz89B** [comment]
Hej,

Sprawdz czy doszla kasa, paypalem wyslalem. :)

**Comment by Matheusz93** [comment]
Poszło na PayPal. Pozdro.

**Comment by Matheusz93** [comment]
Poszło na PayPal. Pozdro. :-)

**Comment by oliwer12345** [comment]
Prosze dane na paypal

**Comment by Matheusz93** [comment]
Jakie dane? Moje? Kto pisze?

wt., 21 lip 2020, 19:38 użytkownik oliwer12345 <notifications@github.com>
napisał:

**Comment by oliwer12345** [comment]
dzieki juz znalazlem

**Comment by sniochu** [comment]
wysłałem ile mogłem powodzenia :)

**Comment by oliwer12345** [comment]
Poszlo na PayPal tylko sprawdz czy dobrze wyslalem

**Comment by Huero23** [comment]
Done. 💰✔ Dziękuje bardzo za wszystko co robisz.

**Comment by sky0002** [comment]
I moje 13 groszy. :)

**Comment by mbebe** [comment]
Dziekuje.

https://github.com/mbebe/blomqvist/issues/348
