### ISSUE TITLE
Sportowa-SportsBay: Kodi cannot play basketball links

### ISSUE THREAD

**Issue by galex3125** [mbebe/blomqvist#353]
Hi @mbebe,

Thank you for a great app!

This past week Kodi cannot play any of the Basketball links resolved by SportsBay.

Can you please take a look on this when you have time?

**Comment by mbebe** [comment]
Version 1.9.7 should be ok. ;-)

**Comment by galex3125** [comment]
It sure fixed it! :-)
Thank you so much!
