### ISSUE TITLE
Hejo.tv

### ISSUE THREAD

**Issue by kashkash18** [mbebe/blomqvist#36]
@mbebe jesteś w stanie poprawić wtyczkę ? Filmy działają bez problemu , przy TV wyskakuje komunikat "Tylko konta premium" mimo zalogowania się do konta z wykupionym premium. Na stronie pojawiły się jeszcze wydarzenia sportowe które można by dodać.

**Comment by mbebe** [comment]
Pozycz premium na godzine ;-)

mbebegit (at) protonmail.com  ;-)

**Comment by kashkash18** [comment]
Poszlo :)

**Comment by kashkash18** [comment]
Część kanałów się nie odpala ale jest to wina nadawcy , na stronie też nie gadają. 
Szkoda tych wydarzeń sportowych bo jest to fajnie zrobione. Może jeszcze uda Ci się coś z tym zrobić :) 
I jeszcze jedno , czy jesteś w stanie zrobić tak by po najechaniu na kanał , pod ikonka pisało co teraz leci ?? Albo zaciągało epg np na 3 godziny ??

**Comment by kashkash18** [comment]
Dzięki wielkie za wydarzenia sportowe :) Możesz jeszcze dorobić epg pod ikonami kanałów ?? Wystarczy info o tym co w danej chwili leci. I po wejściu w kategorie kanałów no dla dzieci można by dorobić ikony.

**Comment by kashkash18** [comment]
Wszystko działa jak należy :) Dzięki wielkie , zamykam temat.
