### ISSUE TITLE
Problemy

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#363]
Witam mam jakiś problem z mbfilmy z pluginem wideo.site wyskakuje błąd mb filmy(podczas próby wejścia w jakikolwiek serial, by zobaczyć listę sezonów), oraz w hejo.tv gdy wchodzę w zakładki kategorie filmów jest pusto(tylko u góry napis następna strona). Kodi 18.6 android oto log https://paste.kodi.tv/tiwiyubafa
Sprawdzałem na stronach hejo i wideo.site tam działa poprawnie. Pozdrawiam magików gandalfa(mbebe)

**Comment by rafalmar1981** [comment]
o pardon na oglądaj.to na wszystkich filmach przy próbie odtworzenia go wyskakuje komunikat "link nie działa" natomiast na stronie uruchamia się poprawnie. Log https://paste.kodi.tv/uqiharalez...i znów pozdrawiam.

**Comment by mbebe** [comment]
Na ogladaj.to   - 
![fdfdfdfd](https://user-images.githubusercontent.com/30195202/91635838-03065b00-e9fc-11ea-8be5-a302da43d809.jpg)

**Comment by kendo999** [comment]
a host filmy na dzis to  dzialaja

**Comment by rafalmar1981** [comment]
spoko da się zrobić opcję logowania w oglądaj.to w mbfilmy?

**Comment by mbebe** [comment]
@kendo999  dzialaja.

**Comment by mbebe** [comment]
@rafalmar1981 w nowej wersji w ustawieniach wtyczki wpisz dane logowania w ogladaj.to i bedzie ok.
Poszla poprawka mbfilmy, jak i hejo.

**Comment by kendo999** [comment]
wielkie dzieki

**Comment by rafalmar1981** [comment]
@mbebe dobra dziękuję sensej bardzo

**Comment by rafalmar1981** [comment]
wszystko śmiga @mbebe  udanego wieczoru

**Comment by FXcodi** [comment]
U mnie filmynadzis nie działa, komunikat "link nie działa"

**Comment by mbebe** [comment]
Jaka masz wersje resolveurl? Bo wymagana jest poprawka dla gounlimited.

**Comment by FXcodi** [comment]
Niestety nie umiem tego nadpisac, resolveurl to 6.4.139 z fanfilmu

**Comment by notoco** [comment]
> Jaka masz wersje resolveurl? Bo wymagana jest poprawka dla gounlimited.
> Jak umiesz to nadpisz ten plik https://anonfiles.com/reYbk6Q8o7/gounlimited_py
> w ..\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins

Ale ta poprawka jest już od dawna w resolverze FanFilmowym... - od 2 miesięcy?

**Comment by FXcodi** [comment]
To nie wszystko wszystko grało,  jeszcze jakieś parę dni temu.
Teraz linki nie działają.

**Comment by FXcodi** [comment]
Wszystko grało, jeszcze jakieś parę dni temu.
Teraz linki nie działają.

**Comment by mbebe** [comment]
@notoco - w wersji  6.4.139 nie jest ten resolver poprawiony - w sobote dalem pull requests dla jsergio.
tu @FXcodi poprawione - 
[script.module.resolveurl-6.4.139.zip](https://github.com/mbebe/blomqvist/files/5149484/script.module.resolveurl-6.4.139.zip)

**Comment by FXcodi** [comment]
No teraz jest OK.
Problem jeszcze mam z dudeplayer http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
 http://paste.kodi.tv/wovularela.kodi

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela

**Comment by FXcodi** [comment]
Teraz jest OK.
Problem jeszcze mam z dudeplayer
http://paste.kodi.tv/wovularela.kodi

**Comment by notoco** [comment]
@mbebe kurcze...to co ja sprawdzałem...

**Comment by notoco** [comment]
Ok - za dużo wersji miałem w folderze testowym i porównałem tę twoją z tą z pr u jsergio... więc to oczywiste że było to to samo... 
Z tego co się dowiedziałem poprawka do resolvera w ff już idzie

**Comment by mbebe** [comment]
@fxkodi - nowa wersja w repo.  
- poprawiony dudeplayer i filmninja (zamiana w mojseansik)

**Comment by FXcodi** [comment]
dziękuje bardzo!

**Comment by FXcodi** [comment]
dziękuje bardzo!

**Comment by FXcodi** [comment]
dziękuje bardzo!

**Comment by FXcodi** [comment]
dziękuje bardzo!

**Comment by notoco** [comment]
Zaktualizowali resolver fanfilm

**Comment by notoco** [comment]
Mbebe coś znowu resolver padł. Nie działa zarówno ten od fanfilm gdzie była twoja poprawka, jak też ten od jsergio gdzie też były poprawki, ale inne...
