### ISSUE TITLE
nc go pytanie

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#364]
A mianowicie zainstalowałem kodi u kumpla 18.6 na win7 wszystko orginalne, przy próbie włączenia kanałów tv jest komunikat że muszę zainstalować input streem adaptive, zgadzam się wciskam oki i wyskakuje mi komunikat nieudana instalacja dodatku. Zrobiłem inaczej w repo kodi znalazlem ten dodatek ale efekt ten sam, wcześniej zainstalowałem fanfilm i kilka wtyczek od mbebe np. hejo działa. W  czym może być problem?

**Comment by notoco** [comment]
Dlaczego zainstalowałeś mu 18.6 a nie 18.8? Skąd instalowałeś? Ze sklepu windows czy ze strony kodi.tv? To wtyczka binarna, i najprawdopodobniej dostępna jest dla danego systemu tylko dla aktualnej wersji kodi

**Comment by rafalmar1981** [comment]
kodi.tv

**Comment by rafalmar1981** [comment]
kurcze mi na 18.6 wszystko hula ale co prawda to na androidzie

**Comment by notoco** [comment]
To dlaczego pobrałeś starą wersję?

**Comment by notoco** [comment]
Ale android to inna bajka - tam wtyczki binarne są wbudowane w apk

**Comment by rafalmar1981** [comment]
pomyslalem skoro mi dziala to jemu tez powinno

**Comment by notoco** [comment]
No. Sąsiad ma auto na LPG i leje gaz na stacji. A u mnie w dieslu to nie chce działać.
I bzdurą jest pozostawanie na starszych wersjach, przynajmniej nie przy głównych zmianach linii - czyli k18/k19 - zmiany w obrębie k18.x są tylko poprawkami nie działających rzeczy. Nie wprowadzają istotnych nowości

**Comment by rafalmar1981** [comment]
jak patrzylem na system to ma 64bit wiec to pobralem z rozszezrzniem exe

**Comment by rafalmar1981** [comment]
oki teraz rozumiem

**Comment by notoco** [comment]
To nie ma znaczenia czy wersję 64 czy 32 pobrałeś. Ważne jest to że zadałeś sobie trudu żeby pobrać starszą wersję niż od razu pobrać najnowszą stabilną. Link na stronie kodi.tv prowadzi do wersji 18.8 - musiałeś sam szukać, to teraz sam naprawiaj.

**Comment by rafalmar1981** [comment]
hahaha poradzę sobie teraz

**Comment by rafalmar1981** [comment]
dzięki za pomoc i wytłumaczenie

**Comment by rafalmar1981** [comment]
mam nadzieje ze to pojdzie mu bo tak zachwalałem kodi i wkoncu sie strasznie napalil

**Comment by notoco** [comment]
Przy normalnej instalacji ze strony kodi.tv, bez kombinowania z wyszukiwaniem starszych wersji zawsze działa.

**Comment by rafalmar1981** [comment]
to po co w starszych wersjach są do wyboro wersje 32 64bit? skoro pisałes ze bez różnicy

**Comment by notoco** [comment]
Bo kiedyś były procki 32 i 64 bit. Teoretycznie 64 bit powinno być bardziej wydajne ale w rzeczywistości często jest na odwrót (coś tam z zarządzaniem pamięcią jest). Na niektórych systemach nie ma możliwości instalacji wersji 32 bit, niektórzy nie chcą dublować bibliotek i dla tego są oddzielne wersję.

**Comment by rafalmar1981** [comment]
dobra to mu walne 18.8 jak pisałeś i dziękuję za poświęcony czas oraz wyjaśnienie kilku tematów

**Comment by notoco** [comment]
Używałem wielu skrótów myślowych

**Comment by rafalmar1981** [comment]
to za te skróty myślowe dziękuję
