### ISSUE TITLE
Netflix za free

### ISSUE THREAD

**Issue by FXcodi** [mbebe/blomqvist#365]
Jakby się udało, to można by było dodać, ten serwis do repo, ponieważ z poziomu przeglądarki na urządzeniach na Androidzie działa słabo. 

https://www.netflix.com/pl/watch-free

**Comment by notoco** [comment]
Ale wiesz że to tylko po kilka odcinków jest i oferta czasowa...

**Comment by FXcodi** [comment]
Właśnie zauważyłem, chciałem dodać do pastebin , ale nie odtwarza z tego poziomu.

**Comment by notoco** [comment]
Nie odtworzy bo zabezpieczone DRM. Poza tym tam są ponoć loterie co do jakości. Szkoda czasu imo... Jak ktoś ma Netflix to korzysta już z wtyczki. Jak nie ma i chce tylko zerknąć to może okres testowy założyć i wtyczka działa. A ten serwis to taki pokaz, reklamówka czy jak to zwał. Demo...
