### ISSUE TITLE
Zalukaj.vip

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#368]
Tak sobie przeglądam tę stronę i jest ciekawa.. może dlatego, że wykupiłem premium. Ciekawe propozycje dosyć szybko dodawane pozycje i dobry kontakt ze stroną...może warto?

**Comment by zaganiacz** [comment]
Już była w MBfilm dodana został tylko ślad w ustawienich wtyczki. 
![Capture+_2020-09-10-13-26-56](https://user-images.githubusercontent.com/71075312/92723905-0c7fb380-f36a-11ea-880e-d7ff2292c567.png)

**Comment by mbebe** [comment]
Wpisz dane we wtyczce i sprobuj te wersje. Ja nie mam subskrypcji, robilem na sucho, w ciemno.
Jak bedzie ok, to w porzadku, jesli nie, to wyslij mi na maila na chwile jakis login z subskrypcja, to wtedy poprawie.
[plugin.video.mbfilm-1.3.23.zip](https://github.com/mbebe/blomqvist/files/5203066/plugin.video.mbfilm-1.3.23.zip)

**Comment by rafalmar1981** [comment]
wyskakuje link nie działa na wszystkim a na stronie jedzie przesyłam na meila

**Comment by mbebe** [comment]
Ok. Sprawdz te wersje.
[plugin.video.mbfilm-1.3.23.zip](https://github.com/mbebe/blomqvist/files/5203799/plugin.video.mbfilm-1.3.23.zip)

**Comment by rafalmar1981** [comment]
Nie stety nadal wyskakuje "link nie działa"

**Comment by mbebe** [comment]
Na kazdym linku? Uzywasz konta premium?
Na czystym kodi sprawdzalem i jest ok.

**Comment by rafalmar1981** [comment]
Hula, hejo ja ta lala jak pobrałem tą wersję  plugin.video.mbfilm-1.3.24.zip....bardzo, bardzo  dziękuję. Pozdrawiam

**Comment by rafalmar1981** [comment]
@mbebe kurcze nie sprawdzałem do dziś w serialach wyskakuje komunikat brak materiałów do wyświetlenia czy seriali, po prostu wcześniej nie zaglądałem tam... gdy znajdziesz chwilę to zerknij jak możesz logi do premium wysłałem Ci ostatnio

**Comment by mbebe** [comment]
Poszla aktualizacja.

**Comment by rafalmar1981** [comment]
Sprawdzę ale to pewnie tylko formalność skoro piszesz że jest poprawka to pewnie tak jest...

**Comment by rafalmar1981** [comment]
Tak jaj pisałem wszystko zapiernicza idealnie...dziękuję jesteś mistrzem. Pozdrawiam

**Comment by rafalmar1981** [comment]
@mbebe wiem truje d..pe zobaczyłem, że w zakładkach seriali gdy wybiera się np. Lucyfer, Gomorra to sprawdzałem jest tylko pierwszy sezon, na stronie są odpowiednio 5 i 4 sezon.
