### ISSUE TITLE
Sportowa-Spor_ts_Bay: MLB problem

### ISSUE THREAD

**Issue by sviet2k** [mbebe/blomqvist#373]
Hi mbebe,

I have a strange problem:
For MLB match, Sportowa just plays the "MLB.tv: The event will begin shortly" and stop after some seconds.
The same MLB match can be seen in the sports bay page.

Thanks in advance to take time to investigate on this.

**Comment by mbebe** [comment]
Hi, please check this.
[plugin.video.PLsportowo-2.0.2.zip](https://github.com/mbebe/blomqvist/files/5241688/plugin.video.PLsportowo-2.0.2.zip)

**Comment by sviet2k** [comment]
Thanks a lot. It's working. 👍 
You are a genius.
