### ISSUE TITLE
Darmowa tv

### ISSUE THREAD

**Issue by krecik71** [mbebe/blomqvist#38]
@mbebe czy zerkniesz co się dzieje

**Comment by edgarok** [comment]
Strona padła

**Comment by mbebe** [comment]
Widzialem. Zaczynam patrzec.

**Comment by mbebe** [comment]
poszla poprawka.
tak z grubsza poprawilem.

**Comment by edgarok** [comment]
Dzięki

**Comment by wisiann** [comment]
Poprawka jest do wersji 1.5.2? Poniewasz nie widze innej

**Comment by Zorish** [comment]
wisiann. Otwórz zips i tam jest 1.5.3

**Comment by wisiann** [comment]
Ok

**Comment by adamibeata** [comment]
ja też tego szukam no nie ma 1.5.3  jest tylko 1.5.2   http://prntscr.com/lgqooc

**Comment by Zorish** [comment]
adamibeata. Na dole masz zips. Otwórz go. 7 od góry masz plugin.video.darmowatv. Klik i masz 
plugin.video.darmowatv-1.5.3.zip. I jeszcze jedno. Internetowa.ws już jest płatna więc nie będzie już działać. Trzeba wykupić premium.

**Comment by adamibeata** [comment]
dzięki już mam 
Internetowa.ws  no to długo nie pociągnie  ale życzę mu powodzenia

**Comment by adamibeata** [comment]
potrzebna aktualizacja bo admin stronki darmowa-telewizja.online znowu coś skopał

**Comment by mbebe** [comment]
update poszedl

**Comment by adamibeata** [comment]
dzięki
 powiedz którą ścieżkę/plik  edytujesz  aby poprawić ?

**Comment by mbebe** [comment]
plik jest jeden ;-) maintv.py ;-)

**Comment by wisiann** [comment]
Mi zadne.programy  nie dzalaja,
Ale to chyba przez to ze w US,

**Comment by mbebe** [comment]
w tej ostat. wersji 1.5.4?  z zadnej zakladki?

**Comment by wisiann** [comment]
Teraz niekture sie wlaczaja,
To jest chyba wina pory dnia,i przeciazenia,

**Comment by Zorish** [comment]
Wszystko działa super. Dzięki mbebe!

**Comment by Zorish** [comment]
danielson17 . U mnie działają. Na darmowa-telewizja.online zmienili serwer oraz playera i nie wszystkie kanały już działają. Ale pracują nad tym i mbebe nic tu nie zrobi.

**Comment by danielson17** [comment]
Aha, dzięki za informację.

**Comment by piteroli** [comment]
Witam. Czy można poprosić o zip? mistrzu mbebe?

**Comment by wisiann** [comment]
@piteroli ,

Zip..zip,💤

**Comment by piteroli** [comment]
Dzięki mistrzu 🍻

**Comment by piteroli** [comment]
Mbebe pomóż😀 darmowa.tv z Twojego repo wersja 1.5.5 działa ale przycina się obraz i buforuje co chwilkę. Może coś trzeba ustawić w kodi? Pomóż😃

**Comment by Zorish** [comment]
mbebe. Na stronie http://tele-wizja.ru jest komunikat: UWAGA!!! zmiana playerów na niektórych kanałach Pon Gru 10. Jakbyś miał ochotę w wolnej chwili zerknąć to będzie super! Dzięki.

**Comment by mbebe** [comment]
Poszedl update na to, co wylapalem.

**Comment by Zorish** [comment]
mbebe! Jesteś WIELKI. Te co nie chodzą w pluginie to też nie chodzą na ich stronie. To tak dla innych.

**Comment by piteroli** [comment]
Potwierdzam Mistrz. Wszystko gra. Dzięki Mbebe🍻

**Comment by xxcriticxx** [comment]
@mbebe mozesz dodac do darmowej 

https://kraisfilm.pl/telewizja-online
https://darballek.pl.tl/
http://polim-tv.blogspot.com/2018/12/telewizja-online-za-darmo.html

**Comment by ToxicAvenger** [comment]
Hej. 
Nie działa tele-wizja.ru. Zmienili playera. 
Zmieniłem u siebie metodę def _wlivetv(data,url):
`def _wlivetv(data,url):
	
	video_url=''
	url_main = ''
	feed = re.compile('fid=["\'](.*?)["\']; v_width=(.*?); v_height=(.*?);').findall(data)
	if not feed:
		feed = re.compile('live=(.*?)\&').findall(data)
		url_main = 'http://www.wlive.tv/cricsp.php?player=desktop&live=%s&vw=660&vh=420' % feed[0]

	if feed:
		
		header = {'User-Agent':UA,'Referer': url}

		if not url_main:
			if data.find('wlive.tv/embedra.js')>0:
				url_main='http://www.wlive.tv/embedra.php?player=desktop&live=%s&vw=660&vh=420'%feed[0][0]
			else:
				url_main='http://www.wlive.tv/embedhd.php?player=desktop&live=%s&vw=660&vh=420'%feed[0][0]

		contentVideo = requests.get(url_main,headers=header).content
		#web_pdb.set_trace()
		pi = re.findall('return\\((.*?)\\);',contentVideo)
		pi=pi[0]
		if pi:		
			join = re.findall('(\\[.*?\\]).join',pi)
			el_id = re.findall('(\\w+).join',pi)
			aa = re.findall('document.getElementById\\("(.*?)"',pi)
			if join:
				join = ''.join(eval(join[0])).replace('\\','')
			if el_id:
				tmp = re.findall('var %s\\s*=\\s*(\\[.*?\\])'%el_id[0],contentVideo)
				el_id = ''.join(eval(tmp[0])) if tmp else ''
			if aa:
				aa = re.findall('%s\\s*>(.*?)<'%aa[0],contentVideo)
				aa = aa[0] if aa else ''
				video_url = 'http:' + join + el_id + aa +'|User-Agent='+UA+'&Referer='+url
		return video_url
`

i teraz działa.
Moja zmiana nie będzie kompatybilna z resztą, bo zależało mi tylko na tele-wizja.ru. Nie jestem też devem pythona.
Możesz na to rzucić okiem?

**Comment by mbebe** [comment]
dalem poprawke :-D
