### ISSUE TITLE
MB Filmy 

### ISSUE THREAD

**Issue by Katapulta** [mbebe/blomqvist#380]
Siema. Tak do info - padło wideo.site , zapewne zgon na amen i już nie wstanie. Dodatkowo w zaluknij.xyz porobiły się jakieś "krzaczory" przy opisach :P :P w wolnej chwili... :) 
![kodi_opTzLwuun4](https://user-images.githubusercontent.com/26973858/94827320-97534b80-0408-11eb-8844-570e874eca40.png)

**Comment by mbebe** [comment]
Nadal wystepuja takie dziwne opisy? ;-)

**Comment by Katapulta** [comment]
Nie już jest git :D
