### ISSUE TITLE
Wtyczka hejo.tv przestala dzialac

### ISSUE THREAD

**Issue by penguinspl** [mbebe/blomqvist#391]
Dzisiaj rano po wlaczeniu tv wtyczka hejo.tv przestala dzialac mozna w nia wejsc i ukazuje sie menu jak telwizja filmy szukaj itp ale zadna z tych funkcji nie dziala po kliknieciu.

**Comment by rafalmar1981** [comment]
U mnie działa

**Comment by penguinspl** [comment]
Sprawdzilem u siebie na drugim telewizorze  tv i dziala i to jest teraz dopiero ciekawostka
