### ISSUE TITLE
vider

### ISSUE THREAD

**Issue by endrju800** [mbebe/blomqvist#394]
We wtyczce vider nie pokazuje kolejnych stron nie ma nawet możliwości przejścia. Przykładowo wyszukuje serial castle pokazuje mi kilka tylko wyników a na stronie jest wszystkie 8 sezonów.

**Comment by endrju800** [comment]
Ponawiam pytanie. Czy to jest błąd wtyczki i da się coś z tym zrobić czy niestety nic.

**Comment by mbebe** [comment]
Poszla poprawka do vider. Dodane sa strony po wyszukaniu.

**Comment by endrju800** [comment]
Dzięki wielkie. Pozdrawiam.
