### ISSUE TITLE
Pastebin wtyczka 1.9.3

### ISSUE THREAD

**Issue by Jigsaw20** [mbebe/blomqvist#396]
Dzien Dobry...

Chyba wtyczka już nie działa.. Wpisuje link od pastebin z https://pastebin.com/raw/.... Pokazuje mi zródła ale niechce Odtwarzać... Wpisywałem bez /raw/ i to samo.. Zainstalowałem 1.9.3 wersja...

**Comment by xxcriticxx** [comment]
jak dobrze pamietam to linky mialy byc bez `RAW`

example link: `https://pastebin.com/LYHSKP3b` trzeba wpisac tylko koncowke `LYHSKP3b` wtyczka zrobi reszte

**Comment by mbebe** [comment]
Skad zrodla?

**Comment by Jigsaw20** [comment]
Servus mbebe.. 
Zródło n.p. stąd.. jak wpisuje link bez /raw/  https://pastebin.com/5Qy8EhGL to wtyczka pokazuje zródła.. Ale jak nacisnie to wcale nie odtwarza.. nawet jak kolega pisał wpisać koncuwke to jest to samo..

**Comment by Jigsaw20** [comment]
> Skad zrodla?

Servus mbebe..
Zródło n.p. stąd.. jak wpisuje link bez /raw/ https://pastebin.com/5Qy8EhGL to wtyczka pokazuje zródła.. Ale jak nacisnie to wcale nie odtwarza.. nawet jak kolega pisał wpisać koncuwke to jest to samo..

**Comment by mbebe** [comment]
Nie zauwazylem skad te zrodla, mozesz wyslac jeszcze raz? Lub na maila wyslij jaki link sie nie odtwarza.

**Comment by Jigsaw20** [comment]
> 
> 
> Nie zauwazylem skad te zrodla, mozesz wyslac jeszcze raz? Lub na maila wyslij jaki link sie nie odtwarza.

https://pastebin.com/5Qy8EhGL               https://pastebin.com/raw/5Qy8EhGL

**Comment by mbebe** [comment]
Pokaz logi na maila, albo tu.

**Comment by Arek76** [comment]
hej Mbebe , Znowu cos nie tak , kompletnie nic nie wczytuje pastebin. Moglbys rzucic okiem eksperta?:) Dzieki

**Comment by mbebe** [comment]
Co tam sie popsulo?
Dalem jakas aktualizacje. Sprawdz i daj znac.

**Comment by Arek76** [comment]
Witaj milo. Nie działała w ogóle wywala błąd . Teraz 1.9.5 wczytuję już i
odpala . Dziękuję . Od wczoraj działa ale i tak jest problem z okładkami i
opisami . Wszystko czyste wczytuje. Zmieniły się jakoś linki do Filmweb?

niedz., 29 lis 2020, 15:16 użytkownik mbebe <notifications@github.com>
napisał:

**Comment by mbebe** [comment]
Tak. Zmienilo sie w filmwebie. Musze przepisac wyciaganie opisow i okladek.

**Comment by Arek76** [comment]
No to ja juz wyczekuje i w wolnej chwili iide na PP :)))

**Comment by mbebe** [comment]
[plugin.video.pastebinVID-1.9.8.zip](https://github.com/mbebe/blomqvist/files/5639370/plugin.video.pastebinVID-1.9.8.zip)
Mozna sprawdzic.
