### ISSUE TITLE
video playlist loader 

### ISSUE THREAD

**Issue by xxcriticxx** [mbebe/blomqvist#40]
@mbebe dasz radę napisać plugin tak aby czytało listę linków video naprzyklad z pastebina/url shortner odtwarzało to w kodi?

**Comment by mbebe** [comment]
nie probowales tego - https://github.com/tvaddonsco/tva-release-repo/tree/master/plugin.video.playlistLoader   ?

**Comment by xxcriticxx** [comment]
@mbebe  chciałem oglondac linky z ok.ru przetestujesz?

**Comment by xxcriticxx** [comment]
`https://pastebin.com/kQ2sz06P`

**Comment by mbebe** [comment]
Wersja 1.0 do pastebin.
[plugin.video.pastebinVID-1.0.zip](https://github.com/mbebe/blomqvist/files/2573059/plugin.video.pastebinVID-1.0.zip)

**Comment by notoco** [comment]
Tak na szybko - Rewelacja - naprawdę super ...
Mały pomysł do wersji 1.1 - możliwość dodania tytułu - po linku, po spacji - coś jak tu:
https://pastebin.com/azbhk6BJ
A następnie do wersji 1.5 - podłączenie do jakiegoś scrapera coby okładki zaciągał...

**Comment by notoco** [comment]
Sam sobie odpowiadam:

> możliwość dodania tytułu - po linku, po spacji - coś jak tu:

linia 99-100
`		tytul=aser.partition(' ')[2]
		out.append({ 'href'  : link,'title' : tytul,'img': imag})	`
[plugin.video.pastebinVID-1.1.zip](https://github.com/mbebe/blomqvist/files/2575291/plugin.video.pastebinVID-1.1.zip)

**Comment by xxcriticxx** [comment]
@mbebe thank you!
@notoco gratuluje kodowania

**Comment by notoco** [comment]
@mbebe więc tak - z rzeczy które IMO wymagają poprawki...
Muszę wpisywać pełen adres tzn: http://pastebin.com/XXXXXXXX - czy nie lepiej zrobić żeby wpisywać samo XXXXXXX? Zawsze mniej klikania...
A druga rzecz - jakiś pomysł na freedisc? Wklejenie linku, nawet w takiej postaci https://stream.freedisc.pl/video/8141023/odc-01-no-to-mamy-kopacza.mp4 nic nie daje... Patrzyłem w twoją wtyczkę do freedisci i znalazłem ten fragment:
```
def getVideoLink(url):

    out=''
    if not '/embed/' in url:
        content = getUrl(url)
        vid_id = re.compile('<iframe\\s+src="(http://freedisc.pl/embed/video/.*?)"').findall(content)
        if vid_id:
            url = vid_id[0]
    content = getUrl(url)
    data = re.compile('<link rel="video_src" .+? href=["\'](.*)["\'] />').findall(content)
    if data:
        data = data[0]
        file = re.search('file=(http(s)*://[^"\']+)',data)
        if file:
            out=file.group(1)+'|Referer='+url +' swfUrl=http://http://freedisc.pl/static/player/v58/player.swf'
            out=file.group(1)+'|Referer={}&User-Agent={}'.format(url,UA)
    return out
```
Ale nie wiem jak to spiąć razem... Wieczorem pomyślę może po prostu do resolvera to jakoś zapiąć...

**Comment by notoco** [comment]
@mbebe - może zamiast wpisywać cały url (http://pastebin.com/XXXXXX) wpisywać tylko końcówkę?
```
	elif mode =='SzukajNowe':
		d = xbmcgui.Dialog().input(u'Podaj adres PASTEBIN.com', type=xbmcgui.INPUT_ALPHANUM)
		d = 'https://pastebin.com/'+d
```
Łatwiej, szybciej i przyjemniej.
BTW. Z freedisc nie działa... Mam linki pobrane na tej zasadzie:
https://pastebin.com/JDzVCgzR
Wykorzystuję skryptozakładkę do ich generowania (kiedyś miałem skrypt w bashu który mi zasysał na dysk seriale)  i wypluwa mi listę linków całego folderu. We wtyczce freedisc w części:
```
def getVideoLink(url):

    out=''
    if not '/embed/' in url:
        content = getUrl(url)
        vid_id = re.compile('<iframe\\s+src="(http://freedisc.pl/embed/video/.*?)"').findall(content)
        if vid_id:
            url = vid_id[0]
    content = getUrl(url)
    data = re.compile('<link rel="video_src" .+? href=["\'](.*)["\'] />').findall(content)
    if data:
        data = data[0]
        file = re.search('file=(http(s)*://[^"\']+)',data)
        if file:
            out=file.group(1)+'|Referer='+url +' swfUrl=http://http://freedisc.pl/static/player/v58/player.swf'
            out=file.group(1)+'|Referer={}&User-Agent={}'.format(url,UA)
    return out
```

Widzę że obrabiasz ten link. Natomiast nie leci to przez standardowego resolvera chyba...

**Comment by xxcriticxx** [comment]
@notoco tych zakladek jest chyba troche wiecej? kiedys by player jak pamietam 

freedisc ma przejabana graffiti captcha

**Comment by notoco** [comment]
Dlatego że freedisc ma te captha wolałbym sobie sam zasysać przez kodi.

**Comment by xxcriticxx** [comment]
@notoco te zakladki dzialaja w kodi?

**Comment by mbebe** [comment]
1.2 ;-)

[plugin.video.pastebinVID-1.2.zip](https://github.com/mbebe/blomqvist/files/2576814/plugin.video.pastebinVID-1.2.zip)
przy dodawaniu listy wpisujemy nazwe :-D

**Comment by notoco** [comment]
@xxcriticxx - nie to skryptozakładki do przeglądarki - w sumie praktycznie nie używam - poza freedisc ;(
@mbebe - super - jeszcze tylko ten freedisc "rozwiązać"

**Comment by notoco** [comment]
@mbebe - niestety - errory
```
16:15:47.668 T:3297465200   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.pastebinVID/main.py", line 163, in <module>
                                                dalej()
                                              File "/storage/.kodi/addons/plugin.video.pastebinVID/main.py", line 80, in dalej
                                                add_item(entryok[0],entryok[1], '', True, "pastebin", contextmenu=contextmenu)
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
16:15:48.043 T:3289072496   ERROR: GetDirectory - Error getting plugin://plugin.video.pastebinVID/
16:15:48.070 T:4088751712   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pastebinVID/) failed
```

**Comment by mbebe** [comment]
tak na szybko. wersja 1,3
mozliwosc wpisywania koncowki pastebin pastebin.com/XXXXXXX
freedisc tu tez odtworzy ;-)
[plugin.video.pastebinVID-1.3.zip](https://github.com/mbebe/blomqvist/files/2576976/plugin.video.pastebinVID-1.3.zip)

**Comment by notoco** [comment]
No i git. Fajna wtyczka.

**Comment by xxcriticxx** [comment]
panowie zajebista sprawa

**Comment by notoco** [comment]
To dla fanów/zmuszonych do freedisc.
Skryptozakładka (obejmuje też kilka innych serwisów, ale od dawna z nich nie korzystałem, więc nie wiem czy działa). https://pastebin.com/siBDVNkY
Przykład działania na freedisc 
- pojedyncze video:
https://freedisc.pl/grazyna1833,f-8141023,odc-01-no-to-mamy-kopacza-avi
wypluje: 
http://stream.freedisc.pl/video/8141023/odc.01.no.to.mamy.kopacza.avi

- katalog z filmami:
https://freedisc.pl/grazyna1833,d-2274283,sezon-4
wypluje:
```
http://stream.freedisc.pl/video/8141023/odc.01.no.to.mamy.kopacza.avi Odc.01 - No to mamy kopacza
http://stream.freedisc.pl/video/8141025/odc.02.gry.wojenne.avi Odc.02 - Gry wojenne
http://stream.freedisc.pl/video/8141031/odc.03.ameryka.na.nowo.odkryta.avi Odc.03 - Ameryka na nowo odkryta
http://stream.freedisc.pl/video/8141029/odc.04.zapadlisko.avi Odc.04 - Zapadlisko
http://stream.freedisc.pl/video/8141021/odc.05.szkolna.fuzja.avi Odc.05 - Szkolna fuzja
http://stream.freedisc.pl/video/8141033/odc.06.mike.doradza.mandy.avi Odc.06 - Mike doradza Mandy
http://stream.freedisc.pl/video/8141039/odc.07.cika.artyleria.avi Odc.07 - Ciężka artyleria
http://stream.freedisc.pl/video/8141056/odc.08.ryzykowne.zachowanie.avi Odc.08 - Ryzykowne zachowanie
http://stream.freedisc.pl/video/8141058/odc.09.wymiana.arwek.avi Odc.09 - Wymiana żarówek
http://stream.freedisc.pl/video/8141049/odc.10.nowa.restauracja.avi Odc.10 - Nowa restauracja
http://stream.freedisc.pl/video/8158293/odc.11.weselne.plany.avi Odc.11 - Weselne plany
http://stream.freedisc.pl/video/8158323/odc.12.ssiadka.avi Odc.12 - Sąsiadka
http://stream.freedisc.pl/video/8159763/odc.13.mike.zatrudnia.chucka.avi Odc.13 - Mike zatrudnia Chucka
http://stream.freedisc.pl/video/8159776/odc.14.eve.zrywa.z.chopakiem.avi Odc.14 - Eve zrywa z chłopakiem
http://stream.freedisc.pl/video/8160031/odc.15.wielki.brat.avi Odc.15 - Wielki brat
http://stream.freedisc.pl/video/8160156/odc.16.trzy.niedziele.avi Odc.16 - Trzy niedziele
http://stream.freedisc.pl/video/8160676/odc.17.przyjaciel.kylea.avi Odc.17 - Przyjaciel Kylea
http://stream.freedisc.pl/video/8160681/odc.18.impreza.mandy.avi Odc.18 - Impreza Mandy
http://stream.freedisc.pl/video/8181525/odc.19.letni.sta.avi Odc.19 - Letni staż
http://stream.freedisc.pl/video/8181529/odc.20.otwarcie.restauracji.avi Odc.20 - Otwarcie restauracji
http://stream.freedisc.pl/video/8181535/odc.21.vanessa.swata.eve.avi Odc.21 - Vanessa swata Eve
http://stream.freedisc.pl/video/8181542/odc.22.najdroszy.tatko.avi Odc.22 - Najdroższy tatko
```

**Comment by xxcriticxx** [comment]
@mbebe / @notoco skryptozakladki

https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod/code

**Comment by xxcriticxx** [comment]
@mbebe da sie to jakos wykorzystac pod kodi?

**Comment by notoco** [comment]
Teoretycznie tak - w postaci poszczególnych wtyczek :) - które już są...
Ale jeśli w przeglądarce wyciągnie ci linka... to wiesz co masz z nim zrobić....

**Comment by xxcriticxx** [comment]
@notoco chodzi zeby to dzialalo automatycznie ale to i9dea na nowa wtyczke

**Comment by xxcriticxx** [comment]
@mbebe plugin.video.skryptozakladka-1.0.zip :)

**Comment by notoco** [comment]
@mbebe - ale coś nie chce teraz nic działać. Zainstalowana wersja 1.3
https://pastebin.com/HbHG3V87 - lista filmów
I nic nie wczytuje.... nawet się lista na liście list nie pokazuje
Lista, która działała z wersją 1.1/1.2 - https://pastebin.com/JDzVCgzR - też się nie wczytuje...

**Comment by kashkash18** [comment]
@notoco u mnie w wersji 1.3 obie te listy się wyświetlają i startują bez problemów

**Comment by notoco** [comment]
a u mnie nie... na wersji 1.1 wczytuje listę i nawet odtwarza (po lekkiej zmianie skryptu) - ale na 1.3 w ogóle nie pokazuje list. w logach czysto.
Coś jest nie tak - może za bardzo "grzebałem" w wersjach?

**Comment by kashkash18** [comment]
Może tak być , ja teraz zainstalowałem wersję 1.3 z repo Mbebe , dodałem twoje listy i obie chodzą. @mbebe mógł byś dodać opcje edycji nazwy listy ??

**Comment by notoco** [comment]
Tak podejrzewam - pracowałem na wersji od mbebe, sam tworzyłem swoje itp itd - wtyczka nie operuje na podstawowej formie zapisu danych w plikach, tylko zapisuje w bazie, więc pewnie tu jest problem... namieszałem...

**Comment by notoco** [comment]
@kashkash18 - jakie masz kodi? Ja mam 18b4

**Comment by kashkash18** [comment]
Gołe 17.6

**Comment by notoco** [comment]
@mbebe - może jednak standardowo zapisywać te listy w katalogu userdata? Łatwiejby było przenosić podczas backupu.

**Comment by notoco** [comment]
Najlepsze jest to że na 1.1 działa :) I nawet na zmodyfikowanym przeze mnie żeby freedisc działa... ale nie na 1.3 - i potem się sypie wszysttko

**Comment by mbebe** [comment]
u mnie dziala ta tez https://pastebin.com/HbHG3V87
![assssss](https://user-images.githubusercontent.com/30195202/48437122-cdd63d80-e780-11e8-9bf8-0aa04495ffdf.jpg)
usun listy w nowej wersji. i dodaj od nowa

**Comment by notoco** [comment]
Ok - przywrócony profil (od czasów ramica codziennie robię kopię automatycznie) - i wszystko działa.
Podejrzewam że przy zabawach moich i mbebe coś baza się sypła. Nie mogłę nawet usunąć list, bo się nie pokazywały. Ale już jest OK - taki los betatestera.
Dzięki wielkie...
Mój ulubiony serial... 5 sezonów....

**Comment by notoco** [comment]
https://pastebin.com/raw/sr03s7m5
Z tego linka wczytuje mi jako jedną linię... - i odtwarza tylko pierwszy link
https://pastebin.com/raw/sr03s7m5 - z tego normalnie

**Comment by notoco** [comment]
i ciekawostka - ta sama lista, skopiowana i wklejona raz jeszcze w pastebin wyskoczyła normalnie... coś pewnie ze znacznikami końca lini było...

**Comment by xxcriticxx** [comment]
@notoco bo jest xtr space po miedzy avi i 01

http://stream.freedisc.pl/video/7955323/01.last.man.standing.s02e01.pl.web.dl.xvid.death.avi 01. Last.Man.Standing.S02E01.PL.WEB-DL.XviD-Death

**Comment by notoco** [comment]
Nie - to chyba znaczniki końca linii - dodaję na nowo i teraz jest ok... ale nie korzystam z dodatku do chrome pastebin tylko ręcznie.

**Comment by xxcriticxx** [comment]
token sie skonczyl czy freedisk padl?

**Comment by xxcriticxx** [comment]
w przegladarce tez mi sie nie otwieraja

**Comment by notoco** [comment]
Nie - działa wszystko - znaczniki końca lini chyba były złe... ale bangla
@mbebe - koniecznie - zmiana nazwy listy....

**Comment by notoco** [comment]
W przeglądarce freedisc często pada, ale te linki raz zdobyte działają... latami (wierz mi że właśnie tworzę listy dla kodi z seriali które oglądałem ściągając je z freedisc na dysk zanim poznałem kodi.)

**Comment by xxcriticxx** [comment]
@notoco czyli w przeglondarce(mam tylko biala strone) nie dzalaja a w kodi sie odpalaja bez problemu?

![capture](https://user-images.githubusercontent.com/15007183/48441584-e54e0000-e759-11e8-99b4-1bd049ec744e.PNG)

**Comment by kashkash18** [comment]
>wierz mi że właśnie tworzę listy dla kodi z seriali które oglądałem ściągając je z freedisc na dysk zanim poznałem kodi.

notoco a podzielisz się tymi listami ?? :D

**Comment by xxcriticxx** [comment]
@notoco gdzie ta sekret lista bolka i lolka?

**Comment by notoco** [comment]
Dostaliście wędkę w postaci skryptozakladki. Wystarczy robić kopiuj wklej....
Wiecie że nie daję gotowców... Większość seriali jest na innych serwisach, teraz przeglądam listy i w sumie tylko kilka znalazłem na freedisc. Ale wtyczka i tak ma powera że hej.

**Comment by notoco** [comment]
> @notoco czyli w przeglondarce(mam tylko biala strone) nie dzalaja a w kodi sie odpalaja bez problemu?
> 


Dokładnie. W przeglądarce trzeba by w nagłówku ustawić odpowiedni referer - a mbebe wrzucił to do wtyczki.
Na freedisc jakość zawsze jest słaba - ale LMS jest tylko tam (i na vider chyba)

**Comment by notoco** [comment]
To co... może zabawa w wyzwania...
Pastebin jest fajne... ale ja chyba bardziej wolę dropboxa...
https://www.dropbox.com/s/7xdyhaqvzgq5ain/lista_drop.txt?dl=1
Na przykład coś takiego... Wadą jest to, że nie można sobie linka na boxie skopiować gdzieś w opcje, tak jak jest w dodatkach posiadających ustawienia zapisane w plikach tekstowych.

**Comment by mbebe** [comment]
wersja 1.4  na podstawie URLResolver Link Tester - Echo Coder
[plugin.video.pastebinVID-1.4.zip](https://github.com/mbebe/blomqvist/files/2580196/plugin.video.pastebinVID-1.4.zip)

zapisywanie do pliku. do userdata addon_data plugin.video.pastebinVID links linki.txt
zmiana nazwy.

**Comment by notoco** [comment]
I jest super - ale przy przepisaniu wtyczki umknęła wpisywanie tylko końcówki od pastebin.com/XXXXXX
Po linii 242 dodaj:
```
	if 'pastebin.com' in new_link:
		new_link=new_link
	else:
		new_link='https://pastebin.com/'+new_link
```

**Comment by notoco** [comment]
@xxcriticxx - spoko :) ja z własnej wygody - znasz mnie nie od dziś pod tym względem - mam skrypt co mi na routerze różne cuda robi i wrzuca na dropbox, ale już go przerabiam co by robił to samo na pastebin (chociaż nie wiem czy niełatwiej będzie przerobić sobie wtyczkę)

**Comment by xxcriticxx** [comment]
@notoco dalej czekamy na twoja tajna liste bolka i lolka

**Comment by notoco** [comment]
Tajna lista Bolka źle mi się kojarzy :)
https://pastebin.com/fv15RFLF

**Comment by notoco** [comment]
I odpowiadając samemu sobie.
Linia 137
jest:
`	ass=html.split('\r\n')
`winno być:
`	ass=html.split('\n')`

Dzięki temu wszystkie listy są wczytywane prawidłowo.
Sprawdzane na windows - w domu zerknę na boxie z coreelec

**Comment by rysson** [comment]
A może zostawić to Pythonowi?

```python
ass = html.splitlines()
```

**Comment by notoco** [comment]
@rysson - ale wiesz że ja z pythona to noga jestem.... jak widzisz małymi kroczkami coś tam sobie dłubię i stukam... ale to amatorka...
Na razie kombinuję jak to wszystko zaciągnąć jakikolwiek img coby ładniej było.

**Comment by xxcriticxx** [comment]
@rysson witamy dasz radę dozucic coś dobrego to tego plugin?

**Comment by notoco** [comment]
Jedyne czego brakuje to możliwość ustawienia własnego obrazka dla listy :)

**Comment by Janasek** [comment]
developer + skin maker notoso ,mb DOGADAMY SIĘ?

**Comment by notoco** [comment]
> @mbebe,notoco co wy na to

No propozycja ciekawa, możliwa do wdrożenia, ale czy się sprawdzi? Czy tego naprawdę chcemy? LOL

**Comment by rysson** [comment]
@notoco, i bardzo dobrze, że dłubiesz, idzie do przodu.
@xxcriticxx, coraz bardziej tego pragnę, ogranicza mnie w sumie tylko czas, @mbebe, to jakiś sprinter jest, szybciej poprawia niż ja czytam :-)

@Janasek, czekaj, Ty prowadzisz dialog przez edycję? Tak czy inaczej każda pomoc jest mile widziana, o ile mogę się wypowiedzieć. Szczególnie jak będą szczegóły :-P

**Comment by notoco** [comment]
@rysson teraz zauważyłem że @Janasek edytował :) 
Jak widzisz coś tam sobie powoli dłubię ale bez takich rezultatów jak @mbebe rakieta....
@Janasek - czasy wojen PLKodi mamy już za sobą. Teraz tylko współpraca. Jeden warunek jest tylko - to co robimy, jest za free

**Comment by xxcriticxx** [comment]
@notoco ty kazdego znasz z kazdego forum :)

**Comment by notoco** [comment]
Wersja 1.5 z poprawką moją (https://github.com/mbebe/blomqvist/issues/40#issuecomment-438627297 ) i ryssona (https://github.com/mbebe/blomqvist/issues/40#issuecomment-438650371)

**Comment by notoco** [comment]
@xxcriticxx - nie - ale na kilku forach się obijam i kilka osób kojarzę. Nie wszyscy mnie kojarzą, bo są takie fora gdzie jestem zwykłym userem... A @rysson - twoja dokładność kogoś mi przypomina... nie pamiętam czy już pytałem... Z opolszczyzną masz coś wspólnego?

**Comment by xxcriticxx** [comment]
@rysson nikt niema czasu ale dalej jakos tutaj dalej sie spotykamy ;)

**Comment by rysson** [comment]
@notoco, ten mi znany robi w energetyce, a znam go prywatnie. Niewykluczone, że i wspomnianego przez Ciebie spotkałem, ale niestety nikt już się nie przedstawia, jestem Maćko z Bogdańca :-)

**Comment by notoco** [comment]
A bo takie skojarzenia mam... przekrwione oczy, maniak pythona, dokładność ponad wszystko i też siedzi w tej dużej wsi w środku PL... i lubi naleśniki :)

**Comment by rysson** [comment]
:-DDD

Idź mi z tą dokładnością. Zanim rozważę co może być dobre w jednej linijce, to mbebe napisze 3 wtyczki :-P

**Comment by xxcriticxx** [comment]
panowie umowie sie na browara na wieczor i nie robcie mi off topic

**Comment by rysson** [comment]
A sroki, tak się pociągnęło. A już kończąc off-topic, może wszyscy się spotkamy na jakimś zlocie kiedyś?
Dobra, to nie tu, to na forum.

**Comment by xxcriticxx** [comment]
@rysson bys poprawil scrappery w fanfilmie?

**Comment by rysson** [comment]
@xxcriticxx, to w CHERRY? Jeśli tak, to zgłoś błąd i opisz co z nimi jest nie tak. Jest szansa, że zajrzę.

**Comment by xxcriticxx** [comment]
@rysson przewaznie lapie tylko szukajke reszta wyglonda na dead

**Comment by Arek76** [comment]
Jakby ktos mial ochote na kilka filmow to prosze https://pastebin.com/RhdnhpkJ

**Comment by Arek76** [comment]
no i cos padla mi dzis wtyka , zreszta nie tylko mi , Moglbys pojrzec na to co sie tam dzieje ? Dzieki z gory

**Comment by mbebe** [comment]
Jakie objawy?

**Comment by Arek76** [comment]
wywala blad dodatku , i u mnie i u znajomych na mojej Paste czyli jak wyzej RhdnhpkJ

**Comment by mbebe** [comment]
ok, poszla poprawka

**Comment by Arek76** [comment]
Nie wiem ale na kompie nie poszlo :22:37:42.377 T:2688  NOTICE: ResolveURL: Initializing ResolveURL version: 6.3.4
22:37:47.029 T:9108  NOTICE: Previous line repeats 1 times.
22:37:47.029 T:9108   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Test\AppData\Roaming\Kodi\addons\plugin.video.pastebinVID\main.py", line 286, in <module>
                                                ListPastebin(exlink)
                                              File "C:\Users\Test\AppData\Roaming\Kodi\addons\plugin.video.pastebinVID\main.py", line 116, in ListPastebin
                                                lists = getPastebin(exlink)
                                              File "C:\Users\Test\AppData\Roaming\Kodi\addons\plugin.video.pastebinVID\main.py", line 141, in getPastebin
                                                link=re.findall("(http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+)",aser)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
22:37:47.086 T:5172   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.pastebinVID/?mode=pastebin&page=1&url=https%3a%2f%2fpastebin.com%2fRhdnhpkJ
22:37:47.087 T:5172   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pastebinVID/?mode=pastebin&page=1&url=https%3a%2f%2fpastebin.com%2fRhdnhpkJ) failed
22:37:47.904 T:12008  NOTICE: ResolveURL: Initializing ResolveURL version: 6.3.4

**Comment by mbebe** [comment]
wersja 1.6?

**Comment by Arek76** [comment]
nie pokazuje mi w repo 1,6 tylko 1,5:) czyli musze instalowac i zlecic instalacje innym ? czy jakos z repo da sie to z automatu zrobic?

**Comment by mbebe** [comment]
za chwile powinna sie pojawic

**Comment by mbebe** [comment]
tez chwile czekalem. daj poszukaj aktualizacji

**Comment by Arek76** [comment]
tak na kompie juz poszla i jest wszystko ok , dziekuje Ci slicznie Mbebe , czy aktualizacje powinny u znajomych pojsc same czy powienienem zallecic im reczna robote ?:)

**Comment by mbebe** [comment]
powinny pojsc same o ile maja wlaczona automatyczna aktualizacje

**Comment by Arek76** [comment]
aha :d ok dziekuje jeszcze raz , zaraz znajde Paypala Twojego :) dobra robote trzeba doceniac :)

**Comment by Arek76** [comment]
Mbebe , sorki ze tak zakłócam Ci spokój , ale zastanawiałem się czy dało by rade coś zrobić aby jakoś opisy wrzucić z Filmweba do każdego filmu bądź okładkę lub coś w tym stylu :) było by to możliwe ?

**Comment by mbebe** [comment]
Przyspieszyloby dodanie do listy filmow na pastebin poprawnego tytulu filmu (takiego jaki jest na filmweb).

**Comment by mbebe** [comment]
Latwiej wyszukiwaloby poster, opis filmu, serialu z filmweb.
Dodam w kolejnej wersji.

**Comment by Arek76** [comment]
Ja osobiscie moge nawet dodawac link do filmweba obok , tylko zeby dodatek go zczytal :)

**Comment by Arek76** [comment]
No tak to juz jest super :) Tylko nie wiem dlaczego nie wgrywa z mojej paste . z Twojej wgral 3 pozycje i zdjecia itd ale mojej nic

**Comment by mbebe** [comment]
Nie wyswietla zadnej pozycji? A ktora paste wczytujesz?

**Comment by Arek76** [comment]
Jak wczytuje Twoja to sa 3 pozycje jak wczytuje moja czyli tę https://pastebin.com/RhdnhpkJ nie wgrywa nic . Mimo ze format juz zmienilem w kilku filmach

**Comment by mbebe** [comment]
https://pastebin.com/kCW4WQPt

**Comment by Arek76** [comment]
Tak juz do tego doszedlem i wszystko pieknie sie wyswietla . Tylko najlepiej skopiowac tytul filmu z Filmweba i wszystko pieknie sie  wyswietla

**Comment by Arek76** [comment]
Kiedy oficjalnie dorzucisz to do wtyki ?

**Comment by xxcriticxx** [comment]
@Arek76 jutro po 15:00

**Comment by Arek76** [comment]
Mbebe moglbys spojrzec na ten test bo cos nie wczytuje , moglbys ja rowniez dorzucic do repo ? moze pod inna nazwa albo cos

**Comment by frijerz** [comment]
Ogarniam w koncu wtyczkę, ale znalazłem dziwna rzecz: otóż do filmu "Solo" (2018)
http://vshare.io/d/cz6n2k0 |Solo|2018|film|
 wtyczka pokazuje mi plakat i opis filmu "Han Solo: Gwiezdne wojny - historie" (1018)
Dziwne...

**Comment by Arek76** [comment]
Mi rowniez

sob., 26 sty 2019, 17:12: frijerz <notifications@github.com> napisał(a):

**Comment by Arek76** [comment]
Witam , 
Mam dwa pytanka odnośnie tej wtyczki jeszcze . 
Czy dało by się połączyć z ta wtyczka wyszukiwanie z https://www.imdb.com/ ? 
Wiele filmów w szczególności nowych nie ma swojego miejsca jeszcze na filmweb wiec jak sam rozumiesz:)
Drugie pytanie czy można było by wprowadzić strony do Samej wtyczki ? powiedzmy po 30 Filmów na stronie ? Mam już dość spora listę i samo ładowanie na początku trwa około dwóch minut :) a co będzie jak jeszcze dodam .

**Comment by notoco** [comment]
@mbebe a włącz w końcu tę wersję z Filmweb w oficjalne repo... Działa idealnie.
