### ISSUE TITLE
iplatvmb za tępy na to jestem

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#402]
20 godzin siedziałem i zero i na andku i win iplatvmb wywala sprawdzałem na kilku wersjach kodiego http://paste.kodi.tv/otibutuquy        
oooo jeszcze wiele wiele mi brakuję do minimum...jak by kto co....ja padam. Pozdrawiam

**Comment by mbebe** [comment]
poprawione w wersji 1.7

**Comment by rafalmar1981** [comment]
Dziękuję bardzo
