### ISSUE TITLE
oglądaj.to i vider.info

### ISSUE THREAD

**Issue by endrju800** [mbebe/blomqvist#403]
Oglądaj.to nie działa jest szansa na poprawienie. Vider nie wyszukuje nie można nawet wejść w opcje wyszukiwania.

**Comment by mbebe** [comment]
Na najnowszej wersji mbfilmy - 1.3.28?

**Comment by endrju800** [comment]
Tak.

**Comment by mbebe** [comment]
Ale co znaczy nie dziala?

**Comment by endrju800** [comment]
Brak linków po próbie odtworzenia

**Comment by mbebe** [comment]
A wpisales dane logowania?

**Comment by mbebe** [comment]
A w vider co?
Nie mozna wejsc w Szukaj, czy jak?

**Comment by endrju800** [comment]
No właśnie zauważyłem. Powinniście dodać info przy każdej wtyczce że premium tam gdzie to wymagane. Mniej zachodu i komentarzy.

**Comment by endrju800** [comment]
Tak klikając w opcje szukaj nie działa nic nawet nie można wpisać czego szukasz

**Comment by endrju800** [comment]
W ogóle cała ta wtyczka jakoś dziwnie działa. Raz działa raz nie raz captcha się pojawia innym razem nie itd. itp.

**Comment by Katapulta** [comment]
> 
> 
> W ogóle cała ta wtyczka jakoś dziwnie działa. Raz działa raz nie raz captcha się pojawia innym razem nie itd. itp.

Gdzie ty kur*** masz capcha. Używasz - to sie kurna zorientuj czego i co z czym się je a nie jęcz jak zarzynana świnia.

**Comment by endrju800** [comment]
Po pierwsze ogarnij swój język niedojebie umysłowy. Po drugie jeśli nie masz pojęcia o czym piszemy to nie zabieraj głosu. Po trzecie vider już działa jak powinien.
