### ISSUE TITLE
NC + GO - jak zmienić jakość transmisji

### ISSUE THREAD

**Issue by szymon9124** [mbebe/blomqvist#405]
Dzien dobry, od ok. 2 listopada mam problem z wtyczka nc+ go. Mianowicie bardzo długo trwa wczytywanie kanałów, czasem otwiera się kanal po czym wraca do listy kanałów. Większy problem polega na tym, iż po uruchomieniu jakiejkolwiek stacji tv po ok 5-10 minutach kanał się zawiesza. Jako, że posiadam internet mobilny plus wnioskuję, iż moze być to problem obciążenia sieci i łącz. Przeinstalowanie wtyczki jak i repozytorium nie rozwiązuje problemu. Zastanawiam się jak zmienić jakość strumienia (obniżyć) by działało stabilnie - nie mam możliwości zmiany poprzez ustawienia-> ustawienia obrazu mam tylko 1 opcję 
![16060662639128120195203250012734](https://user-images.githubusercontent.com/74872460/99910891-f3439d80-2cf0-11eb-8733-6a907cae6490.jpg)
Proszę o pomoc.
Pozdrawiam Szymon

Android box mi box s4k na android 9, kodi w wersji 18.9,  mbebe 0.5, nc+go 1.2.10.

**Comment by BlackGlassSkin** [comment]
Musisz ustawić to w **inputstream adaptive**

**→**  **Manually select all streams**"

i będziesz mógł wybierać jakość video ...


![test image size](https://i.ibb.co/z6h4hdT/input1.png?raw=true)
![test image size](https://i.ibb.co/PgCqwbt/input2.png?raw=true)
![test image size](https://i.ibb.co/Hq5MbPG/2020-11-29-20h47-28.png?raw=true)

**Comment by szymon9124** [comment]
Dziękuję serdecznie 🙂 Pomogło.
Pozdrawiam
