### ISSUE TITLE
alltube.tv się...... spsuło

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#409]
Drogi mbebe coś z cloudflare z tego co zobaczyłeem

**Comment by rafalmar1981** [comment]
Przepraszam zapomniałem dodać:
https://paste.kodi.tv/licinopivo

**Comment by xxcriticxx** [comment]
@rafalmar1981 update kodi do 18.9 + os 7 na 10 i wykasuj swoje pelne imie z usera windows jak postujesz na pastebin

**Comment by rafalmar1981** [comment]
@xxcriticxx przepraszam... tak zrobię na andku do 18.9, wina zostawię bo tam mam kodi tylko do sprawdzenia wtyczek itp. a jakoś przeboleje...dzięki za dobrą radę z tym userem niby wiesz ale jak ktoś inny Ci o tym powie to już inaczej na to patrzysz

**Comment by zaganiacz** [comment]
> @xxcriticxx przepraszam... tak zrobię na andku do 18.9, wina zostawię bo tam mam kodi tylko do sprawdzenia wtyczek itp. a jakoś przeboleje...dzięki za dobrą radę z tym userem niby wiesz ale jak ktoś inny Ci o tym powie to już inaczej na to patrzysz

Co i tak nie sprawi, że wtyczka alltube nagle zacznie działać. Tylko, że ona nie działa z powodów niezależnych od Mbebe. Zniknie CF, to i wtyczka ożyje.

**Comment by rafalmar1981** [comment]
@zaganiacz dziękuję bardzo za informację już poczytałem troszkę ale mimo to dziękuję za wyjaśnienia

**Comment by xxcriticxx** [comment]
@zaganiacz dokladnie! 

Ale lepjej jest trzymać PC w tym średniowieczu niż byłym :)

**Comment by rafalmar1981** [comment]
@xxcriticxx nie rozumie ale chyba mało istotne

**Comment by xxcriticxx** [comment]
@rafalmar1981 mało istotne :)

**Comment by rafalmar1981** [comment]
@xxcriticxx  tak myślę

**Comment by rafalmar1981** [comment]
@xxcriticxx  mam pytanie w repository.bugatsinho-2.5 jest taka wtyczka kamerki  z całego świata ale za nic nie chcę mi ruszyć, czy potrzeba specjalnych dodatków lub wersji kodi by poszła kiedyś mi śmigała fajnie to była ta wtyczka plugin.video.skylinecctv-0.0.6

**Comment by xxcriticxx** [comment]
@rafalmar1981 jak montujesz plugin to teraz Kodi pokazuje co musi zamontować żeby plugin działał 

PS zagadaj z @mbebe zeby ci taka wtyczkę zakodował

**Comment by rafalmar1981** [comment]
@xxcriticxx wiem wiem instaluje się bez problemu, pobiera tam co musi ale sypie błędem, a to nie wtyczka naszego mbebe to nie podaję żadnych logów, @mbebe ma pewnie swoją robotę by mu d..zawracać czyimiś wtyczkami co nie działają. Ale tak sam dla siebie sprawdzę co tam jest w tym paste.kodi.tv

**Comment by xxcriticxx** [comment]
@rafalmar1981 moze do tej strony internetowej `https://www.webcamera.pl/`

**Comment by rafalmar1981** [comment]
@xxcriticxx fajne to to nawet moje Gliwice są

**Comment by xxcriticxx** [comment]
@rafalmar1981 kupisz dla mbebe kawe i dobrego pączek na pewno napisze plugin

**Comment by mbebe** [comment]
Tu masz ten od bugat poprawione.
[plugin.video.skylinecctv-0.0.7.zip](https://github.com/mbebe/blomqvist/files/5612250/plugin.video.skylinecctv-0.0.7.zip)

**Comment by mbebe** [comment]
a ta nie dziala? https://kodiwpigulce.pl/jak-zainstalowac-wtyczke-leisure-streams-w-kodi-17-poradnik-kamery-na-zywo/
albo ta? https://kodiwpigulce.pl/jak-zainstalowac-wtyczke-cam-kamerki-online-w-kodi-17-poradnik/

**Comment by mbebe** [comment]
Ta druga - https://kodiwpigulce.pl/jak-zainstalowac-wtyczke-cam-kamerki-online-w-kodi-17-poradnik/
 powinna dzialac.
![fdfsdfdsfsdfsd](https://user-images.githubusercontent.com/30195202/100544376-86cb2000-3255-11eb-8446-c37109e76431.jpg)

**Comment by xxcriticxx** [comment]
@rafalmar1981 dzieki za offtopic

@mbebe thank you!

**Comment by rafalmar1981** [comment]
@mbebe @xxcriticxx  ja pierdziele ale jaja zarąbiście oj te kamerki to  fajna rzecz przynajmniej dla mnie bardzo super

**Comment by rafalmar1981** [comment]
@xxcriticxx  sorrensen  za tego offtopica ale wyszło dzięki @mbebe  świetnie

**Comment by rafalmar1981** [comment]
@mbebe nie wiem czy warto to robić ale chyba coś wypadło
w tym offtopicu plugin.video.skylinecctv-0.0.7.zip
https://paste.kodi.tv/xovayasudo

**Comment by mbebe** [comment]
Jaka kamera?

**Comment by xxcriticxx** [comment]
https://www.skylinewebcams.com/en/webcam/italia/lazio/roma/piazza-di-spagna.html

**Comment by rafalmar1981** [comment]
@xxcriticxx żeby nie było nauczyłem się tu na git zanim coś zgłosisz sprawdź czy strona nie padła też tak zrobiłem przed napisaniem postu i wtedy strona szła dlatego napisałem
