### ISSUE TITLE
hejo.tv przestalo dzialac 

### ISSUE THREAD

**Issue by penguinspl** [mbebe/blomqvist#411]
Jak w tytule (sprawdzane na 2  telewizorach) przestala dzialac wtyczka hejo.tv 3 razy wyskakuje error a za 4 5 6 razem blad logowania i tak od rana.

**Comment by mbebe** [comment]
poszla aktualizacja

**Comment by penguinspl** [comment]
> poszla aktualizacja

Jak dlugo trzeba czekac zeby aktualizacja pojawila sie do pobrania bo narazie nic sie nie zmienilo

**Comment by mbebe** [comment]
tu masz bezposredni link: [plugin.video.hejotv-2.2.85.zip](https://github.com/mbebe/blomqvist/files/5612451/plugin.video.hejotv-2.2.85.zip)
Mozna wymusic aktualizacje.

**Comment by penguinspl** [comment]
Super juz dziala zamyka temat
