### ISSUE TITLE
ogladaj.to

### ISSUE THREAD

**Issue by leonzawodowiec12** [mbebe/blomqvist#413]
@mbebe naprawisz ogladaj.to cały czas pisze link nie działa a na stronie działa oczywiście konto premium mam

**Comment by mbebe** [comment]
Przeklikalem teraz kilka linkow i jest ok. Jaki nie dziala?

**Comment by leonzawodowiec12** [comment]
już ok przepraszam za zamieszanie hasło miałem źle wpisane :)
