### ISSUE TITLE
Bajeczki.org

### ISSUE THREAD

**Issue by timtumturutumtum** [mbebe/blomqvist#42]
@Mbebe jest szansa na bajeczki.org?
Najmłodszy fan kodi w moim domu znalazł pewne bajki tylko tam ;)

**Comment by mbebe** [comment]
jest szansa

**Comment by mbebe** [comment]
bajeczkiorg dodane do repo :-)

**Comment by timtumturutumtum** [comment]
Jesteś Wielki. 
"gościu" już ogląda bajki. 
Kazał podziękować Panu który zrobił, że może oglądać Super Wings,  co niniejszym czynię. 
Dziękuję @Mbebe.

**Comment by krecik71** [comment]
podziękowania
