### ISSUE TITLE
ekino i logowanie/premium

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#427]
Witam, czy jest możliwość naprawy logowania w ekino? Czy ktoś sprawdzał czy wtyczka będzie działać z premium u nich?

**Comment by BlackGlassSkin** [comment]
zamień adres logowania w **ekinotv.py** linijka  **83** na ten adres 'https://ekino-tv.pl/login'

**Comment by notoco** [comment]
O cholera - nie zauważyłem tak prostej rzeczy w kodzie!

**Comment by BlackGlassSkin** [comment]
no na to wygląda

**Comment by mbebe** [comment]
Tam chyba cos jeszcze bylo nie halo. :-D
[plugin.video.ekinotv-2.6.4.zip](https://github.com/mbebe/blomqvist/files/5698085/plugin.video.ekinotv-2.6.4.zip)

**Comment by BlackGlassSkin** [comment]
nie wiem pewnie jak sie zmieniło logowanie to i cos mogli z pobieraniem streamu pozmieniac
zresztą zaraz sie dowiem coś tam pozmieniał

**Comment by notoco** [comment]
Działa... Super...

**Comment by notoco** [comment]
Ale w serialach, w spisie alfabetycznym pokazuje tylko 1 stronę

**Comment by mbebe** [comment]
No tak. Puscilem do repo wersje 2.6.5 - raczej to poprawilem.
