### ISSUE TITLE
nie działa 

### ISSUE THREAD

**Issue by leonzawodowiec12** [mbebe/blomqvist#43]
Zalukaj błąd dodatku
CDA HD linki nie działają 
Filmowe.co błąd dodatku 
Filmach.cc linki nie działają

**Comment by kashkash18** [comment]
Zalukaj 1.8 - działa
CDA HD 1.6.1 - działają tylko streamy z openload
Filmowo.co 1.0 - błąd dodatku przy filmach i ciemno w popularnych filmach
Filman.cc 1.0 - dziala

**Comment by kashkash18** [comment]
Jeszcze dorzucę dwa tematy :

eFilmyTv 1.17 - przy serialach wywala błąd dodatku.

Filmwebbooster 2.7 - można by ogarnąć temat Baza filmów / Seriali / Programów. A przy wyborze źródła filmu / serialu dodać wersję językową.

Aha , dobrze by było uwolnić tę wtyczkę od Ramicowych choinek ;)

**Comment by leonzawodowiec12** [comment]
dzięki znalazłem nowe strony: filmowakraina.tv i ekinoman.com jak by coś

**Comment by kashkash18** [comment]
CDA HD 1.6.2 
![](https://i.imgur.com/MqXg8YV.jpg)

**Comment by mbebe** [comment]
no, moj blad. 1.6.3 w repo.

**Comment by kashkash18** [comment]
hqq.tv nie staruje , z tym że na stronie przy próbie odpalenia linku wyskakuje reCaptcha

**Comment by rafalmar1981** [comment]
zalukaj,com błąd dodatku

**Comment by rafalmar1981** [comment]
bład dodatku viperCom

**Comment by mbebe** [comment]
w poniedzialek dopiero bede. ;-)

**Comment by mbebe** [comment]
@rafalmar1981  konkrety podaj co do virpecom

**Comment by leonzawodowiec12** [comment]
@mbebe jak będziesz mieć czas sprawdzisz:

- Livetv.sx linki nie działają 
- kraisfilm.pl telewizja nie działa
- ekinomaniak wymaga poprawki brak okładek 
- segos brak okładek
- virpecom linki nie działają 
- iitv pusto w wszystkie, popularne 
- serialnet.pl brak linków

**Comment by mbebe** [comment]
co do virpecom - jakie linki nie dzialaja ? a na stronie dzialaja?

**Comment by kashkash18** [comment]
Przegląd na K18 RC4 W10

Serialnet.pl [1.0]
Wtyczka działa , problem jest po stronie serwisu gdyż padają materiały na stronie.
Komunikat ze strony "Przepraszamy, wybrany odcinek jest w tej chwili niedostępny."
Zapętlenie po odpaleniu video którego nie ma w serwisie.

iitv-seriale [2.5]
Ostatnio dodane - seriale pokazuje ale przy próbie odpalenia sypie błędem
![iitv](https://user-images.githubusercontent.com/22107339/50904894-baaeb980-1421-11e9-816e-3b5924f29904.jpg)
Popularne - pusto
Wszystkie - pusto

VirpeCOM [1.1]
Wtyczka działa , problem jest po stonie serwisu gdyż padają materiały na stronie.
Zapętlenia przy anulowaniu wyboru streamów
Zapętlenie po odpaleniu video którego nie ma w serwisie.

Segos [3.4]
Brak okładek wg zgłoszenia
Zapętlenia przy anulowaniu wyboru streamów
Zapętlenie po odpaleniu video którego nie ma w serwisie.

eKinomaniak.tv [1.1]
Brak kilku okładek ale jest to wina serwisu , w nim też ichnie widać
Brak opisów filmów
Nie odpalają się filmy z kategorii : Ostatnio dodane, Najwięcej wyświetleń, Najwyżej oceniane [Znaleziony film przez "Szukaj" działa]

KraisFilm [1.1]
Telewizja - błąd dodatku
![kraisfilm](https://user-images.githubusercontent.com/22107339/50904950-e5990d80-1421-11e9-8bba-fa3bdd618dc2.jpg)
Brak opisów filmów w kategoriach , w "Szukaj" opisy są np. Kler

DarmowaTV [1.5.7]
Internetowa.ws  - już za free nie nadaje wiec można się jej pozbyć ( w zamian można by dodać tv z Filman.cc i KraisFilm)
TVmaniak - brak ikonek kanałów
Sport365Live - przestawienie godziny
LiveLooker - działa ale dziś mało streamów
Livetv.sx - w zasadzie to wtyczka pokazuje tylko linki do AliezTV a i tak jest ich niewiele w stosunku do wydarzeń sportowych które są na liście . Nie wiem czy lepiej by nie było zrobić dodatek do samego AliezTV

@leonzawodowiec12  tak opisuj zgłoszenia ;) @mbebe będzie miał łatwiej
