### ISSUE TITLE
Wtyczki od mbebe

### ISSUE THREAD

**Issue by rekin65** [mbebe/blomqvist#430]
Witam, czy wie ktoś coś na temat tego żeby przestały działać niektóre dodatki od mbebe, typu filman, ekino-tv, e-filmy???
Czy problemu szukać w urządzeniu??
Dziękuję za odpowiedź

**Comment by mbebe** [comment]
ekino powinno dzialac - https://github.com/mbebe/blomqvist/issues/427

**Comment by rekin65** [comment]
![Screenshot_2020-12-19-16-04-54-126_org xbmc kodi](https://user-images.githubusercontent.com/25380957/102692508-06745b00-4214-11eb-9b8c-0fd9975d5d85.jpg)

**Comment by rekin65** [comment]
Przeinstalowałem kodi jeszcze raz i problem zniknął dzięki

**Comment by rekin65** [comment]
Całe szczęście wystarczyła tylko ponowna instalacja kodi
