### ISSUE TITLE
Playermb - brak napisów do filmów

### ISSUE THREAD

**Issue by miniworm** [mbebe/blomqvist#439]
Cześć,
Mam problem z napisami do filmów. Nie są dostępne w materiałach, które na WWW i w standardowych aplikacjach mają je. Działa tylko wybór ścieżek dźwiękowych. 
wtyczka w najnowszej wersji - 1.4.

**Comment by mbebe** [comment]
Podaj jakis tytul filmu, na ktorym sa napisy. :-)

**Comment by miniworm** [comment]
Praktycznie wszystkie filmy zagraniczne z kolekcji HBO (np. serial Westworld, filmy z serii James Bond).

**Comment by mbebe** [comment]
Ok. Poszla poprawka. Wersja 1.5 w repo.
Wybor napisow trzeba wlaczyc w opcjach.
![hhhhhhhhh](https://user-images.githubusercontent.com/30195202/103227110-e9cfd580-492d-11eb-9dc6-ecd53dd988ff.jpg)

![hhhhhhhhh2](https://user-images.githubusercontent.com/30195202/103227109-e8061200-492d-11eb-8b6b-8bc8909e7c54.jpg)

**Comment by miniworm** [comment]
Wow, to było szybkie i skuteczne! Dziękuję bardzo! Już dofinansowywałem projekt ale po takiej reakcji na pewno zrobię to znowu :)
