### ISSUE TITLE
Alltube.tv

### ISSUE THREAD

**Issue by Polsk86** [mbebe/blomqvist#459]
Alltube.tv przestało dzialac :(

**Comment by kopernik1983** [comment]
Ale że strona , wtyczka ?? Jest prosta nie pisana zasada. Jeżeli wtyczka nie działa, to sprawdza się stronę w pierwszej kolejności , a potem można przyjść z logiem i założyć issues...... Sprawa wygląda tak , że jeszcze rano było info o pracach konserwacyjnych i przekierowywało na śmiechowe alltube+. Natomiast teraz info już nie ma , przekierowuje od razu. Trzeba poczekać co się wydarzy..
Nie od dzisiaj wiadomo , że pewne rzeczy już wcześniej przekierowywały ( np miniaturki ze strony głównej ) do tego gówna ( wyszukiwarki linków ) alltube +. Jak już wspomniałem , trzeba poczekać chwilę co się wydarzy...

**Comment by Polsk86** [comment]
Wtyczka no i strona widac tez przekierowywana tak jak piszesz. Trudno trzeba czekac pewnie właściciel strony przekierowanie dal.
