### ISSUE TITLE
Alltube

### ISSUE THREAD

**Issue by papulus2** [mbebe/blomqvist#460]
Witam wszystkich, 
Od wczoraj Alltube przestał działać nie wyświetla żadnych linków zarówno jeśli chodzi o filmy jak i seriale. Można by coś z tym zrobić?

**Comment by xxcriticxx** [comment]
mozna polac benzyna i podpalic?

**Comment by notoco** [comment]
Zadać sobie ten trud i sprawdzić stronę alltube która padła

**Comment by Katapulta** [comment]
Padło i poszło papa. Już chyba nie wróci.

**Comment by FXcodi** [comment]
Alltube.tv przestało istnieć , ale jest alltube+/https://alltube.com.pl = coś takiego, tylko wymaga rejestracji.
Jeżeli serwis jest darmowy i działa tak samo, można było go podmienić we wtyczce.
Po filmach widać, że ten serwis ma identyczne filmy oraz seriale , tylko wymaga zalogowania aby uzyskać dostęp do oglądanych materiałów wideo.

**Comment by Katapulta** [comment]
Nie. Nie ma zadnego sensu bo to buble. Trochę  myślcie. Mbebe strzeliłby sobie w kolano robiąc addon do tego syfu. To Strona - kant, która karze ci płacić ... za nic. To tylko wyszukiwarka filmów z innych źródeł premium które i tak nei działają a za oglądanie musisz na tych "źródłach" dodatkowo jeszcze płacić. Płacisz za wyszukiwanie w tym szajsie a później dodatkowo za oglądanie w kolejnym. Jak ktoś nie myśli, i klika w co popadnie to się później zdziwi lekko.

**Comment by notoco** [comment]
> Alltube.tv przestało istnieć , ale jest alltube+/https://alltube.com.pl = coś takiego, tylko wymaga rejestracji.
> Jeżeli serwis jest darmowy i działa tak samo, można było go podmienić we wtyczce.
> Po filmach widać, że ten serwis ma identyczne filmy oraz seriale , tylko wymaga zalogowania aby uzyskać dostęp do oglądanych materiałów wideo.

https://github.com/mbebe/blomqvist/issues/226 - może jeszcze nie opłaciłeś.
