### ISSUE TITLE
Dodatek filman.cc

### ISSUE THREAD

**Issue by rekin65** [mbebe/blomqvist#462]
Czy wiadomo, czemu nie wyświetla się zawartość dodatku filman.cc?

**Comment by rekin65** [comment]
Już działa 😉😉

**Comment by rekin65** [comment]
Znowu nie działa??🤔🤔

**Comment by notoco** [comment]
Filman chowa się za cloudflare/ddos - bardziej lub mniej losowo. Nie da się tego ominąć w kodi tak łatwo, wymagałoby co chwilę zmian we wtyczce - które za 5 minut będą już nieaktualne

**Comment by kodiultimate** [comment]
Filman ostatnio znikł, a teraz powrócił z captcha. Trzeba dwa razy rozwiązać captcha aby strona się wyświetla. Dodatek sypie błędami

**Comment by zaganiacz** [comment]
> Filman ostatnio znikł, a teraz powrócił z captcha. Trzeba dwa razy rozwiązać captcha aby strona się wyświetliła. Dodatek sypie błędami.
> Cloudflare + captcha czyli możemy się pożegnać z serwisem :) ? @mbebe @notoco

Skąd te przypuszczenia? Odpalam teraz wtyczkę w kodi 19 i normalnie działa. Seriale się wyświetlają, filmy się wyświetlają. Bez premium, bez logowania. 
![Screenshot_2021-03-31-14-33-02](https://user-images.githubusercontent.com/71075312/113145849-3e396880-922f-11eb-8094-dbe323be9a8e.png)
![Screenshot_2021-03-31-14-34-29](https://user-images.githubusercontent.com/71075312/113145878-4691a380-922f-11eb-8e4b-61ce8fc986d7.png)
A nawet odpaliłem też film aby tak już calkiem się upewnić.
![Uploading Screenshot_2021-03-31-14-35-29.png…]()

**Comment by kodiultimate** [comment]
Być może to mój dostawca neta z telefonu. Udostępniałem net z telefonu na tablet. Po wejściu na stronę przez przeglądarkę od razu pojawiło sie captcha dwa razy. Stąd moje wnioski. W kodi 19 wywalało błedy.

**Comment by zaganiacz** [comment]
> Być może to mój dostawca neta z telefonu. Udostępniałem net z telefonu na tablet. Po wejściu na stronę przez przeglądarkę od razu pojawiło sie captcha dwa razy. Stąd moje wnioski. W kodi 19 wywalało błedy.

O widzisz. Mnie spotkało coś takiego kiedyś, ze filman w przegladarce mobilnej w tablecie ani w smartfonie w ogóle się nie otwierał, tylko bląd 403 bodajże pokazywał. I już nawet "oglosiłem" gdzieś tam koniec filmana. A pózniej się okazalo, że zmiana dns na te od cloudflare w tablecie "odblokowała" stronę.
