### ISSUE TITLE
cda.pl - dostęp do folderów schowanych za hasłem

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#467]
Obecnie, mając film w swoich ulubionych na cda, można go obejrzeć, nawet jeśli folder jest zabezpieczony hasłem.
Brak jest możliwości natomiast wejścia w katalog (ppm - Folder użytkownika). Wjedzie w owszem w wykaz folderów (jeśli są) - ale już do folderu zabezpieczonego hasłem nie wchodzi... Przydałoby się żeby wyskakiwał monit o hasło.
Jeżeli będą problemy, na pw mogę podesłać taka kombinację wraz hasłem

**Comment by BlackGlassSkin** [comment]
[![ ](https://i.ibb.co/cyPVmJs/12.png)](http://kim.cherrytv.webd.pl/ABT/12.mp4)

- [x]  **Każda wtyczka video**

**Comment by notoco** [comment]
To co pokazałeś rozwiązuje inny mój problem ale nie ten o którym mówię. Ja potrzebuję możliwości wpisania hasła przy wejściu w folder.
Co to za dodatek i skąd go mogę pobrać (ten do generowania strm)

**Comment by notoco** [comment]
Bingo - mam? https://github.com/dandygithub/kodi/tree/master/addons/context.dandy.strm.generator

**Comment by BlackGlassSkin** [comment]
nie odtwarza bo niektóre addony mają **Container.Content(addons)** tam gdzie stream ,kolejne uruchamiają dialog ze streamami zamiast window ,nie można wyciągnąć bezpośrednio jednego stramu

usunąłem już translit stream już się generuje bezpośrednio z addonu dodałem view na true ,teraz pokazuje się wszedzie
pl. settings
plugin://plugin://plugin.video.HDseans/?foldername=

a nie 

plugin://context.dandy.strm.generator + plugin://plugin.video.HDseans/?foldername=
to go wyzwoli i będzie bezpośrednio uruchamiał streamy

ale że nie jestem biegły (prawie wcale nie rozumie pythona) to napotkałem problem 
nie mogę zdekodować bezpośredniego streamu i wychodzi mi coś takiego 

`plugin%3A%2F%2Fplugin%3A%2F%2Fplugin.video.HDseans%2F%3Ffoldername%3DKolekcjoner%2Bko%25C5%259Bci%2B%25281999%2529%26page%3D1%26ex_link%3Dhttps%253A%252F%252Fhdseans.pl%252Ffilmy%252Fkolekcjoner-kosci-1999-694667%2523player%26mode%3DgetLinks`

zamiast

plugin://plugin://plugin.video.HDseans/?foldername=Kolekcjoner+ko%C5%9Bci+%281999%29&page=1&ex_link=https%3A%2F%2Fhdseans.pl%2Ffilmy%2Fkolekcjoner-kosci-1999-694667%23player&mode=getLinks

**Comment by rysson** [comment]
Czołem po przerwie (śledzę Was cały czas).

Musisz użyć `unquote`

```python
from urllib import unquote

s = 'plugin%3A%2F%2Fplugin%3A%2F%2Fplugin.video.HDseans%2F%3Ffoldername%3DKolekcjoner%2Bko%25C5%259Bci%2B%25281999%2529%26page%3D1%26ex_link%3Dhttps%253A%252F%252Fhdseans.pl%252Ffilmy%252Fkolekcjoner-kosci-1999-694667%2523player%26mode%3DgetLinks'

print(unquote(s))
```

Wynik
```
$ python /tmp/a.py 
plugin://plugin://plugin.video.HDseans/?foldername=Kolekcjoner+ko%C5%9Bci+%281999%29&page=1&ex_link=https%3A%2F%2Fhdseans.pl%2Ffilmy%2Fkolekcjoner-kosci-1999-694667%23player&mode=getLinks
```

**Comment by xulek** [comment]
Czołem @rysson, to tak jak ja :-) @BlackGlassSkin to samo rozwiązanie dostałeś ode mnie prywatnie ;)

**Comment by BlackGlassSkin** [comment]
@xulek , @rysson 

mogę wam podesłać to co zrobiłem jak macie chcwile to zaglądnijcie ,ja nie wyrobie przy tym to nie na moje i tak juz słabe nerwy

**Comment by BlackGlassSkin** [comment]
cda jak już robie .strm to bezposrednio z url . wiem ze mało wygodne ale nie ogladam 10 filmów dziennie

**Comment by notoco** [comment]
Gr... Ale problem w tym wątku dotyczy nie robienia strm do biblioteki ale dostępu przez wtyczkę do katalogów za hasłem... 
Strm to inna sprawa. Dużo ogarniam za pomocą add to lib, ale jest cholernie nie wygodne.

**Comment by xxcriticxx** [comment]
No mamy sobie Reunion po latach

**Comment by rysson** [comment]
Czekajcie, jak już wstałem na chwilę z martwych, to się dopytam zanim mnie znów pochłoną otchłanie piek... znaczy projektów.

@notoco, chodzi Ci tylko o popup z hasłem przy wejściu do katalogów w cda?
A drugie pytanie, to jeśli znasz hasło (zakładając, że pytanie o nie się pojawi), to co daje posiadanie ich w ulubionych w cda?
Bo jak rozumiem, możne je oglądać z poziomu ulubionych **bez** wchodzenia w zahasłowany folder.

@BlackGlassSkin, przy okazji co to znaczy „*cda jak już robie .strm to bezposrednio z url*”. Z tych URL z folderów z hasłem?

**Comment by notoco** [comment]
Tak, można je oglądać z poziomu ulubionych - ale jeśli oglądam serial składający się z 57 odcinków to musiałbym mieć każdy w "ulubionych" - nie mogę wejść w folder w którym są, bo jest za hasłem
ja nie chcę mieć folderu w ulubionych - ja chcę mieć przez wtyczkę dostęp do takich folderów jak ten:
https://www.cda.pl/BAJKI__I_SERIALE_KIEDYS_BYLO_FAJNIE_809O_LAT/folder/23408219
Z poziomu strony da się wejść w podfoldery tego folderu bez hasła (!) - np ten:
https://www.cda.pl/BAJKI__I_SERIALE_KIEDYS_BYLO_FAJNIE_809O_LAT/folder/23408420
Ale z poziomu wtyczki mogę wybrać tylko  Folder użytkownika - który prowadzi do głównego folderu danego użytkownika.
Rozwiązaniem by było zamiast wpisywania hasła, przejście do folderu filmu a nie użytkownika.
Ale hasło też by się przydało - rozwiązałoby kompleksowo ten problem

**Comment by rysson** [comment]
@notoco, zdecydowanie rozjaśniłeś. Czyli z zewnątrz można trafić do bajku jak i do folderu z bajkami, ale nadrzędny folder (nie istotne czy po drodze, czy główny) jest z hasłem.
Rozumiem, że hasło jest Ci znane. Rzeczywiście pop up by się przydał.
Jak folder z bajkami jest osiągalny przez www, to można jeszcze trik dołożyć (niezależnie od implementacji pop-upu), w opcjach dać: pokaż folder.

Zaciekawiłeś mnie. I moja żona się ucieszy, bo cda używa. Pocieszę ją po utracie alltube, z którego jakieś seriale oglądała.

Oby tylko starczyło czasu. Dam znać.

**Comment by notoco** [comment]
Hasło do tego folderu jest proste - przewiń na stronie listę folderów na dół i przyjrzyj się dokładnie nazwom folderów. Potem usuń inicjały Hanna Barbera i masz hasło (dla ułatwienia - rok śmierci Leopolda Tyrmanda).
W tym przypadku folder jest osiągalny przez www
Jak już twoja żona tego potrzebuje to masz czas do 22.00 na poprawkę ;) potem idę spać, bo rano trzeba będzie znowu ze śniegiem walczyć.

**Comment by notoco** [comment]
Ba... jakby była opcja zapisania do wybranych nie tylko filmów ale też katalogów to już by było gites...

**Comment by rysson** [comment]
@notoco, hah, żona cda potrzebuje ale tego jeszcze nie zna.

Zapis folderów to musiałby być w cda. Ja proponuję w pierwszym kroku opcję "pokaż folder filmu" (obok pokazywania głównego folderu użytkownika).

Do 22? Kurczę, muszę się chyba zwlec z kanapy :)

**Comment by notoco** [comment]
Co do zapisu folderów - wtyczka sama w sobie zapisuje "wybrane" - nie ulubione ale wybrane
plik favorites.json
```
[
  {
    "code": "", 
    "duration": 719, 
    "img": "https://icdn.2cda.pl/vid/thumbs/da8a84ddc5b50e557d527efadc9578705ec7b49ce29542d2a450522972de2afa-31.jpg_ooooxoooox_192x108.jpg", 
    "new": "", 
    "plot": "Odlotowe wy\u015bcigi - 09 - Ucieczka harcerzy", 
    "title": "Odlotowe wy\u015bcigi - 09 - Ucieczka harcerzy", 
    "url": "https://www.cda.pl/video/2005644dd", 
    "year": ""
  }
]
```
No to biegusiem do roboty a ja idę się kąpać... ;)

**Comment by rysson** [comment]
@notoco, no zpełzłem. I nie pisz mi o śniegu, dzisiaj przed standupem 70 min z łopatą latałem. Ten piękny, k#@$@, buały puszek ;-) Nawet śmiać się nie mogę, tak mnie ciągnie. Nie wiedziałem ile jest w człowieku mięśni, aż je poczułem :-P

@ meritum (nota bene [wiem, po polsku pisze się to razem], że ligatura „@” pochodzi własnie od łacińskiego „ad” czyli do).
> można je oglądać z poziomu ulubionych
Piszesz o „favorites” w Kodi czy ulubionych w CDA, bo się zgubiłem.

Ja od strony użytkownika nie bardzo znam te wtyczki. Nie mogę nawet znaleźć pozycji „ulubione” czy „obejrzyj później”.
Możesz mi tak krok po kroku napisać jak znajdujesz filmy i jak je puszczasz w Kodi? Gdzie dodajesz, jak się poruszasz po dodatku.

Zajrzałem do wtyczki, i o ile @mbebe jest niedościgniony w szybkości reakcji i realizacji naszych pomysłów, to od formatowania źródeł krwawią mi oczy. Wiem, @mbebe pisałeś, że się na tym nie skupiasz, a skuteczny jesteś nieziemsko. Ale choć wolne linie nad `def func()` może? :-)

**Comment by notoco** [comment]
Piszę o **ulubionych w CDA.** ulubione w kodi sa dla mnie troszkę bez sensu - ale to inna sprawa.
Obejrzyj później nie ma we wtyczce CDA. Ulubione są - pod warunkiem że się zalogujesz we wtcyzce, co też ułomnie działa, bo co któreś logowanie CDA chowa się za captcha i nie chce we wtyczce logować. Mi teraz podczas różnych prób wywaliło logowanie na jednym komputerze i już na boxie nie chce się zalogować - trzeba 24h odczekać.
Filmy na cda znajduję na 2 metody. Pierwsza we wtyczce - poprzez szukaj. Jeśli dany film/serial jest ok, to wybieram sobie **ppm - Folder użytkownika** i przeglądam inne, jak chcę sobie "zapisać" to za pomocą LibIntegrationToll (https://forum.kodi.tv/showthread.php?tid=327514) dodaję sobie pojedynczy do biblioteki, albo dodaję do wybranych czyli favorites.json (o którym pisałem we wcześniejszym poście). Z poziomu wtyczki nie da się dodać do "ulubionych w CDA". To się da zrobić na stronie - i tu jest druga metoda znajdowania. Znajduje na stronie, dodaje do ulubionych i jak jestem zalogowany w cda, to wtedy we wtyczce jest dostęp do "Moje cda" gdzie mam m.in ulubione. I znowu mogę "ppm - Folder użytkownika" - i jeśli folder jest zabezpieczony hasłem jak ten z powyższego przykładu to nic się nie dzieje - dostaje .. Wyszukaj sobie we wtyczce "Pies Huckleberry 05" - pierwszy link (ten z radiem) (https://www.cda.pl/video/923043da) prowadzi do katalogu: https://www.cda.pl/BAJKI__I_SERIALE_KIEDYS_BYLO_FAJNIE_809O_LAT/folder/23410151 ale go nie otwiera, bo nad nim jest katalog z hasłem

**Comment by notoco** [comment]
Chociaż zastanawiam się czy to w ogóle o haslo chodzi w tym przypadku... Bo coś mi żadnego folderu u tego użytkownika nie chce pokazać... nawet tych bez haseł...

**Comment by rysson** [comment]
@notoco, chyba mam. Dorobiłem „folder filmu” – ale na Huckleberry nie działa. Powodem jest właśnie blokada dla niezalogowanych. A sama wtyczka ma jakieś pomieszanie z ciasteczkami. Raz używa pliku `cookie.cda` a raz `my_addon.getSetting('loginCookie')`.

W dodatku plik nie jest (przynajmniej czasem) tworzony. A czasem wymagany.

**Comment by notoco** [comment]
Dobra. Uznaje że do 22 zrobiłeś coś tam, więc na dziś odpuszczam ;).  A z logowaniem jest coś mocno spieprzone...

**Comment by rysson** [comment]
@notoco, jeszcze nie ma 22 :-)
Poza tym olana jest druga forma premium, która ma `Premium aktywne` zamiast `Twoje konto...`.

A i w Linuksie wklejanie tekstów do kodi to jakiś koszmar.

**Comment by rysson** [comment]
Dobra, poszło. Muszę to przeczyścić i spaczkować.
„Folder filmu” ma mały sens, jak jesteś w folderze, ale nie będę o tym myślał. Przy wyszukiwaniach się przydaje. Pewnie będzie potrzeba jeszcze dodać pozycję w rodzaju „folder nadrzędny” gdzieś.

![20210209-214754-1752x790](https://user-images.githubusercontent.com/5898312/107426792-f9436080-6b20-11eb-9863-d9649cdde0c0.png)
![20210209-214851-1752x790](https://user-images.githubusercontent.com/5898312/107426804-fd6f7e00-6b20-11eb-84ed-a295a688b886.png)

**Comment by rysson** [comment]
@mbebe, dość istotna poprawka do `cdapl.py` dotycząca konta premium. O ile się nie mylę można podpiąć kartę i wtedy Twój sposób działa, albo zapłacić jednorazowo i to było ignorowane.

Fragment przerobionej funkcji `CDA_login`:
```python
        rodzaj = re.search('Twoje konto:(.+?)</span>|(Premium aktywne)', contents)
        if rodzaj:
            ac.save(COOKIEFILE, ignore_discard=True)
            cookies = ';'.join('%s=%s' % (c.name, c.value) for c in cj)

            if 'darmowe' in rodzaj.group(0):  # whole matched string
                my_addon.setSetting('premka', 'false')
            else:
                my_addon.setSetting('premka', 'true')
```

**Comment by rysson** [comment]
@mbebe, w `addDir()` masz `iconImage = MEDIA + iconImage` a same ikony są w `RESOURCES`.
Nie przenosiłem ikon, na razie dałem zaślepkę:
```python
    elif not iconImage.startswith('http'):
        if not os.path.exists(MEDIA + iconImage) and os.path.exists(RESOURCES + iconImage):
            iconImage = RESOURCES + iconImage
        else:
            iconImage = MEDIA + iconImage
```

**Comment by rysson** [comment]
Poniosło mnie. 

Wymienione wyżej:
- fix logowania premium (przy opłacie z góry)
- fix ikonek
- „folder filmu”

Oprócz tego dodałem listy z CDA (widoczne w „moje cda”):
- ulubione
- do obejrzenia

Listy pokazują pierwszą stronę, później dodam kolejne.


Jest to wersja pre-α (pre-alfa, jakby ktoś nie znał tej literki ;-)).
[plugin.video.cdapl-2.7ry1.zip](https://github.com/mbebe/blomqvist/files/5954973/plugin.video.cdapl-2.7ry1.zip)

@mbebe, jak by Ci się chciało zerknąć, to może byś zassał. Przynajmniej to co Ci się spodoba.

**Comment by BlackGlassSkin** [comment]
<p align="left">
<img src="https://i.ibb.co/6Hw9Crp/2021-02-10-05h48-35.png">
</p>

opcje w wyszukiwarce (czas trwania: powyżej 60min, 20min ) i tak wyświetla filmiki poniżej 60 i 20  minut i trafiają się 2 min, 8min etc.....

**Comment by rysson** [comment]
Zaraz, zaraz, @BlackGlassSkin zaczynamy w jednym zgłoszeniu wszystkim się zajmować.
1. Czy zepsułem to w wersji 2.7ry1, czy wcześniej też ten problem występował?
2. Co to jest multi-search? To jest w kodi czy to inny dodatek? I jak to się integruje z cdapl?
