### ISSUE TITLE
script.module.parsedom

### ISSUE THREAD

**Issue by sky0002** [mbebe/blomqvist#47]
https://github.com/seppius-xbmc-repo/ru/tree/master/script.module.parsedom
Pan Maserak86 zamknął swoje repo więc zdarzają się problemy z instalacją dodatków np. darmowa.Tv

**Comment by xxcriticxx** [comment]
dla pana/pani @sky0002 chodzi o to ze dependency brakuje?

**Comment by mbebe** [comment]
jest dodane chocby w darmowatv
ja nie kumam o co biega ;-)

**Comment by xxcriticxx** [comment]
ja tez nie dlatego pytam

**Comment by mbebe** [comment]
A ten parsedom nie jest automatycznie wraz z kodi?

**Comment by sky0002** [comment]
Tak Panowie, na kodi 18 jest ok, ale na kodi 17,6 pchało na raw/maserak86 naprawdę nie wiem czemu . Postawiłem na androidzie kodi 18 i już jest ok i także zdaje se sprawę że coś nie halo, dlatego to napisałem taką małą pomoc dla zdziwionych jak ja. Pozdrawiam.
