### ISSUE TITLE
Kodi 19 and PlayerPLmb

### ISSUE THREAD

**Issue by Niiph** [mbebe/blomqvist#476]
Is playerPLmb available in Python3?
After autoupgrade on my tv to version 19 kodi doesnt want to run this addon, and I dont see it in repository.

**Comment by kodiwpigulce** [comment]
Downgrade your Kodi to 18.9 and reinstall addon.

**Comment by Mariusz89B** [comment]
@mbebe poprawilem poroblem z logowaniem na kodi v19, podwojne mnozenie (Integer division).

def sprawdzenie1(self):
increment = 100 // time_to_wait

**plugin.video.playermb-1.8.zip**
https://drive.google.com/file/d/1hDoEVLEl0U-Pb187WYXcU-YC2s4iD19b/view?usp=sharing
