### ISSUE TITLE
filmowakraina.tv - nowa wtyczka.

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#48]
[plugin.video.filmowakraina-1.0.zip](https://github.com/mbebe/blomqvist/files/2611840/plugin.video.filmowakraina-1.0.zip)

do testow

**Comment by xxcriticxx** [comment]
Wykup konto Premium aby widzieć Linki Premium - Bez Limitów / Bez Odliczania / Bez Reklam. PREMIUM JUŻ OD 3.00 zł !

**Comment by wisiann** [comment]
U mnie ...bangla,
Fajne poukladane,
👌

**Comment by mbebe** [comment]
Wtyczka nie wymaga logowania i pokazuje wiecej linkow niz na stronie nie odlicza takze ;-)

**Comment by kashkash18** [comment]
Działa , dobra robota :-)

**Comment by leonzawodowiec12** [comment]
Na Kodi 17.6 chodzi fajnie szybko uruchamia linki

**Comment by mbebe** [comment]
poszla poprawka do kodi 18. ale to moj blad byl. :-D

**Comment by mbebe** [comment]
Sprawdzalem na RC1 sciagne b5 i zobacze :-)

**Comment by sky0002** [comment]
Witam Panowie. A któryś z Was próbował na zakładce filmy pójść dalej następna strona? To nie działa, a po aktualizacji nawet filmy kategorie nie można wybrać . LibreELEC 9 rc5 RPi3 platforma testowa. To takie moje małe spostrzeżenia. Pozdrawiam wszystkich.

**Comment by notoco** [comment]
Na coreelec i libreelec ciężko będzie wgrać sobie RC... Zobaczymy przy kolejnej aktualizacji systemów

**Comment by mbebe** [comment]
To nie sa jeszcze stabilne wersje kodi. Ostatnia stabilna i zalecana jest 17.6. Ostatnio wyszla 18 RC1, ta tez moze jeszcze zawierac bugi ;-)

**Comment by mbebe** [comment]
ok. poszla poprawkado wersji 1.2  ;-)

**Comment by sky0002** [comment]
Przedrzymskim chcę bardzo podziękować za twój wkład i pracę w scenie Kodi Pl, bez Twojej pracy PL by bała bardzo uboga. A teraz łyżka dzekću, wiem że moje kodi jest boro hej do przodu ale to jest kodi 18 i beta5 i na tej najnowszej poprawce wszystko działa prósz szukania. Pozdrawiam i jeszcze raz dzięki za Twój wysiłek.

**Comment by mbebe** [comment]
poprawka do szukania w wersji 1.3 . w repo :-D
