### ISSUE TITLE
TVP - nie działa streaming ośrodków regionalnych

### ISSUE THREAD

**Issue by michael112** [mbebe/blomqvist#486]
Witam, moja uwaga dotyczy dodatku TVP.pl.
W zakładce - o skądinąd mylącej - nazwie "TVP Info na żywo" udostępniasz streaming wszystkich kanałów pojawiających się na stronie tvpstream.vod.tvp.pl. Niestety, obecnie nie działa streaming ośrodków regionalnych - tzn. wyświetlają się na liście, jednak po wejściu na nie - nie odtwarzają się.
Po pobieżnej analizie kodu źródłowego oraz API TVP wydaje mi się że przyczyna tego stanu rzeczy leży w tym że jak wejdziesz pod adres: tvp.pl/shared itd. i dokleisz do niego identyfikator streamu któregoś z ośrodków, to w zwróconym JSONie, w obiekcie "formats" jako pierwszy pojawia się stream typu MPD, a dopiero jako drugi M3U8. W przypadku TVP Info, TVP Parlament itd. pierwszym strumieniem jest M3U8 i one działają. Nie działa też TVP Kultura 2 - przypuszczam z tego samego powodu (też MPD jest jako pierwszy).
Wszystkie te strumienie są typu MIME application\/x-mpegurl, a skrypt jest jak widzę tak skonstruowany (metoda playLiveVido) że jak natrafi na strumień tego typu, to już nie sprawdza dalej, tylko bierze. I tutaj jest błąd, najwidoczniej Kodi (przynajmniej u mnie) nie ogarnia streamów MPD, natomiast M3U8 by łyknęło. Trzeba zatem w skrypcie iterować po tych formatach, aż się znajdzie strumień M3U8.
Niepokoi mnie jeszcze dalsza część tej metody, bo przewiduje ona że jak ustawienie "inputstream" jest true (tych ustawień za bardzo nie znam), to skrypt szuka typu MIME application/vnd.ms-ss, a takiego nie ma w tym API TVP (przynajmniej tam gdzie zerkałem).
Ostatnia sprawa - powinieneś zmienić nazwę zakładki, bo sugeruje że tylko TVP Info można oglądać. Może się nazywać TVP Stream - tak jak ich strona na której są strumienie.

**Comment by mbebe** [comment]
Poszla poprawka.

**Comment by hevet** [comment]
Super, działa wszystko, dzięki.

**Comment by michael112** [comment]
Potwierdzam, mi też działa.
Nie wiem tylko, dlaczego dodatek nie mógł się zaktualizować z poziomu samego Kodi (ustawienia dodatku: Aktualizuj, była dalej wersja 2.4.6), musiałem ręcznie pobrać zipa z Githuba i zainstalować z tego zip.
Być może to jest kwestia czasu kiedy on sobie aktualizuje listę dostępnych wersji dodatku, albo coś przeoczyłem.

**Comment by Mariusz89B** [comment]
@michael112 https://www.matthuisman.nz/2019/09/how-to-force-kodi-to-update-add-ons.html

**Comment by EuHadii1** [comment]
Mam takie pytanie, macie może zrobioną listę m3u ze streamów z tej wtyczki, żeby wrzucić np do pvr iptv Simple?
