### ISSUE TITLE
Tvp.pl

### ISSUE THREAD

**Issue by Huero23** [mbebe/blomqvist#487]
Hey @mbebe Nie wiem so się stało seriale na vod działają 💯 Newsy jak Teleexpress, Wiadomość i Panorama nie daję się oglądać. Buforowanie. Archiwum w Teleexpress, Wiadomość i Panorama wywala błąd. Załonczę zdjęcie błędu. Nigdy takiego problem nie miałem że jedno działa a drugie nie. Czy nowa wersja jest tylko na K19 ? Ja używam 18.9... 
![20210301_183356](https://user-images.githubusercontent.com/19337836/109596352-ed690f80-7aca-11eb-903c-935ac6cc22da.jpg)

**Comment by hevet** [comment]
Mam 18.9 i serwisy działają poprawnie.
