### ISSUE TITLE
TVP - poprawienie listowania odcinków z polskimi znakami w Kodi 18

### ISSUE THREAD

**Issue by kszaq** [mbebe/blomqvist#488]
**vodTVPapi.py**

W linijce 217 musi być:
`E['title'] += episode.get('title','') if PY3 else episode.get('title','').encode('utf-8')`
W przeciwnym razie odcinki z polskimi znakami nie listują się.

P.S. Czy jest repo, w którym można robić PR bezpośrednio do kodu wtyczek?

**Comment by notoco** [comment]
No niestety, namawiamy autora do tego od dłuższego czasu... Ale coś uparty jest. https://github.com/kodi-pl - tu masz próby "niezależnych" prac, ale mbebe powiedział że będzie uznawał
@mbebe - może czas faktycznie udostępnić kod...
BTW - ty to ten kszaq? Libreelec dla s905...

**Comment by rysson** [comment]
> mbebe powiedział że będzie uznawał

Więcej, napisał, że zrobi forka. Mam nadzieję, że potem będzie już na nim pracował, a my wszyscy będziemy robili PR-y.

**Comment by notoco** [comment]
@rysson - wrzucę, obiecałem... ale nie mam kiedy siąść i to ogarnąć...

**Comment by kszaq** [comment]
@notoco zgadza się, ale to już (niestety) stare dzieje...

@mbebe Zauważyłem jeszcze jedną rzecz do poprawy: nie rozumiem konieczności filtrowania `sdt-thi` i `sdt-epi` z listy dostępnych formatów - w moim przypadku tokenizer zwraca wyłącznie pliki z serwerów `sdt-thinx` i ich odfiltowanie uniemożliwia otwarcie formatu 1080p. Gdy usunąłem ify filtrujące, 1080p działa bez problemu.

Obie poprawki w załączniku:
[vodTVPapi.zip](https://github.com/mbebe/blomqvist/files/6096318/vodTVPapi.zip)

**Comment by kszaq** [comment]
Dzięki za aktualizację, zamykam. 👍
