### ISSUE TITLE
Telewizja

### ISSUE THREAD

**Issue by leonzawodowiec12** [mbebe/blomqvist#49]
Co myślisz o dodaniu:
- filman.cc została dodana zakładka telewizja 
- http://polim-tv.blogspot.com/
- http://sako-tv.blogspot.com/2017/03/polska-telewizja-online.html
- Goldvod
- Wizja
- weebtv
- wptv

żeby cała telewizja była w jednej wtyczce

**Comment by Zorish** [comment]
leonzawodowiec12  Po co piszesz  Goldvod, Wizja Wptv .Płatne TV. Idź na Cherry. A o sako ja już tu pisałem.
Nie zawracaj głowy mbebe!

**Comment by leonzawodowiec12** [comment]
A czy ktoś cię pytał o zdanie?

**Comment by leonzawodowiec12** [comment]
@mbebe kraisfilm dodało telewizję zrobisz update wtyczki

**Comment by mbebe** [comment]
zupdatowana wtyczka :-)

**Comment by leonzawodowiec12** [comment]
dzięki

**Comment by leonzawodowiec12** [comment]
@mbebe zrobisz ponownie update wtyczki kraisfilm jakieś miany zaszły i tv nie działa :)

**Comment by Zorish** [comment]
@mbebe Telewizja w filman cc  padła Jakbyś zerknął w wolnej chwili. Dzięki za wszystko.

**Comment by Zorish** [comment]
Jesteś wielki! Wszystko śmiga. DZIĘKI!!!

**Comment by RaBr2993** [comment]
Witam, nie wiem czy tutaj mogę zgłosić problem. Otóż we wtyczce Hejo.tv nie działają kanały Polsat Sport, Sport Extra. Wyskakuje okienko tylko konta premium. Oczywiście takie konto mam i w przeglądarce kanały działają. Myślę, że problem może stanowić inny player tych kanałów w serwisie. Czy da się coś z tym zrobić?

**Comment by RaBr2993** [comment]
Wszystko działa! Dobra robota. Dzięki.

**Comment by RaBr2993** [comment]
Po ostatnich problemach z serwisem hejo.tv telewizja we wtyczce przestała działać. Kanał zaczyna się wczytywać i rozłącza.

**Comment by mirsiek** [comment]
do mbebe:
Prośba o poprawkę na filman.cc na Kodi 18 i ew. możliwość logowania

**Comment by mbebe** [comment]
filman.cc zaktualizowane (nie mialem premium) 
logowanie dodane
z darmowym odtwarzalo tv
jak ktos ma checi to niech podesle premium na maila ;-)

**Comment by mirsiek** [comment]
Dzięki za super robotę
Miałem loginy Premium weżne ponad rok, ale jakaś pinda sobie je
zawłaszczyła.


pt., 15 lut 2019 o 21:19 mbebe <notifications@github.com> napisał(a):

**Comment by krecik71** [comment]
Witam 
Czy można dodać do darmowa tv http://twojetv.ws/

**Comment by mbebe** [comment]
@krecik71  https://github.com/mbebe/blomqvist/issues/50#issuecomment-468465517

**Comment by krecik71** [comment]
Ok. Dzieki

**Comment by leonzawodowiec12** [comment]
@mbabe mogę prosić o dodanie 
telewizja-internetowa.pl
televhs.com
Oraz naprawę Filman.cc i Filmbit.ws bo tv nie działa
