### ISSUE TITLE
Generator listy m3u

### ISSUE THREAD

**Issue by irkfine** [mbebe/blomqvist#490]
Czy ktoś może podać adres m3u kanału Novelas+ w NC+ GO? 

Kiedyś wygenerowałem liste m3u używając wtyczki z generatorem od mbebe. Ale teraz jestem już w Kodi 19 i nie widzę jak to zrobić. Przy okazji więc prośba do mbebe o zrobienie wersji wtyczek z generatorem listy do Kodi 19 bo jest to bardzo przydatne gdy pojawiają się nowe kanały.

**Comment by irkfine** [comment]
Wobec braku odpowiedzi postanowiłem sam rozpracować m3u dla Novelas+ w NC+ GO. Najpierw odinstalowałem Kodi 19 i zainstalowałem 18.9 wraz z podaną tu kiedyś starą wtyczką z generatorem m3u którą kiedyś użyłem do generowania listy. Ale ku mojemu zdziwieniu ta wtyczka mi nie działała, nie ściągała listy kanałów a co za tym idzie nie było i listy. Wróciłem więc do zwykłej wtyczki mbebe i analizując jaka mogła być przyczyna tego zauważyłem w logu Kodi podane ścieżki http do strumieni wideo z serwerów. Odszukałem ścieżkę dla Novelas+, ustaliłem format logo dla tego kanału i mam całość na liście tak jak w oryginale. Podaję jeśli ktoś by potrzebował:  

`#EXTINF:0, tvg-id="107" tvg-name="NOVELAS+" tvg-logo="https://ncplusgo.img.rd.insyscd.net/ch-novelas-2/ch-novelas-12.png" group-title="G", NOVELAS+ HD
plugin://plugin.video.ncplusgo/?name=Novelas&moviescount=0&url=novelas-2&movie=True&image=https%3A%2F%2Fncplusgo.img.rd.insyscd.net%2Fch-novelas-2%2Fch-novelas-12.png&mode=playNC&page=1`

**Comment by irkfine** [comment]
Temat jest więc zamknięty.

**Comment by praspp** [comment]
No to go zamknij.

**Comment by praspp** [comment]
> Wobec braku odpowiedzi postanowiłem sam rozpracować m3u dla Novelas+ w NC+ GO. Najpierw odinstalowałem Kodi 19 i zainstalowałem 18.9 wraz z podaną tu kiedyś starą wtyczką z generatorem m3u którą kiedyś użyłem do generowania listy. Ale ku mojemu zdziwieniu ta wtyczka mi nie działała, nie ściągała listy kanałów a co za tym idzie nie było i listy. Wróciłem więc do zwykłej wtyczki mbebe i analizując jaka mogła być przyczyna tego zauważyłem w logu Kodi podane ścieżki http do strumieni wideo z serwerów. Odszukałem ścieżkę dla Novelas+, ustaliłem format logo dla tego kanału i mam całość na liście tak jak w oryginale. Podaję jeśli ktoś by potrzebował:
> 
> `#EXTINF:0, tvg-id="107" tvg-name="NOVELAS+" tvg-logo="https://ncplusgo.img.rd.insyscd.net/ch-novelas-2/ch-novelas-12.png" group-title="G", NOVELAS+ HD plugin://plugin.video.ncplusgo/?name=Novelas&moviescount=0&url=novelas-2&movie=True&image=https%3A%2F%2Fncplusgo.img.rd.insyscd.net%2Fch-novelas-2%2Fch-novelas-12.png&mode=playNC&page=1`

Mogłeś na K19 dodać Novelas+ HD do ulubionych (z poziomu wtyczki) i wyciągnąć linki z pliku favourites.xml. Łatwiej i szybciej.
