### ISSUE TITLE
Darmowa TV

### ISSUE THREAD

**Issue by kwedzina** [mbebe/blomqvist#498]
Cześć. Używałem często wtyczki darmowa tv, jednak wiele streamow nie działa. Chodzi mi głównie o kanały sportowe. Czy da się to jakoś naprawić lub czy są jakieś inne wtyczki z kanałami i streamami sportowymi?
Używam kodi na Xbox X. 
Pozdrawiam

**Comment by kwedzina** [comment]
Dodam ze używam kodi 18.9
Wersja wtyczki darmowa tv 1.8.9

**Comment by mbebe** [comment]
w sportowa powinne byc transmisje.
