### ISSUE TITLE
Aktualizacja repo

### ISSUE THREAD

**Issue by kashkash18** [mbebe/blomqvist#5]
Wywala komunikat o nieudanej aktualizacji 0.1.1

**Comment by notoco** [comment]
Bo nie dałem commita dla samej paczuszki. Zaraz przygotuje wrzucę, a mbebe w wolnej chwili zatwierdzi.

**Comment by kashkash18** [comment]
@mbebe upnij poprawki od @notoco bo ciągle świeci aktualizacja ;)

**Comment by kashkash18** [comment]
Dzięki , zamykam

**Comment by notoco** [comment]
No. To jeszcze pilnować żeby wtyczki wrzucać na bieżąco...
