### ISSUE TITLE
CP Go - poprawki

### ISSUE THREAD

**Issue by kszaq** [mbebe/blomqvist#501]
Cześć @mbebe. Dłubię sobie w CP Go i proponuję poprawki:
- usunięcie *cofaj*, bo powoduje brak dźwięku w kanałach na żywo na *ELEC - nie jestem pewien jaki jest cel tej funkcji, bo przesuwanie w kanałach na żywo nadal mi działa, ale przyznaję, że nie szukałem zbyt mocno
- dostosowanie inputstream pod Kodi 19 - [tu widziałem](https://github.com/xbmc/inputstream.adaptive/issues/608), że już to zrobiłeś u siebie
- usunięcie `verify=False`, bo Kodi w logach marudzi

Poprawki w załącznikach:
[cpgo.kodi19.patch.txt](https://github.com/mbebe/blomqvist/files/6137320/cpgo.kodi19.patch.txt)
[cpgo.urlverify.patch.txt](https://github.com/mbebe/blomqvist/files/6137321/cpgo.urlverify.patch.txt)
[cpgo.usuncofaj.patch.txt](https://github.com/mbebe/blomqvist/files/6137322/cpgo.usuncofaj.patch.txt)

**Comment by mbebe** [comment]
cofaj na poczatku bylo, bo na bank nie odtwarzalo live, tylko z jakims przesunieciem.

**Comment by kszaq** [comment]
Dzięki za wyjaśnienie. Jak na razie nie zauważyłem u siebie zatrzymywania po usunięciu cofania, musiało to zostać poprawione w którymś momencie w IA. Włączę jakiś kanał na noc, żeby sprawdzić stabilność.

Przede wszystkim jednak ogromne dzięki za wielką ilość pracy nad wtyczkami, świetna robota!

**Comment by mpast99** [comment]
Mam pytanie, czy pojawi się cp go na kodi 19 w najbliższym czasie czy lepiej zrobić downgrade do 18.9?

**Comment by kszaq** [comment]
@mpast99 CP Go obecnie nie działa w Kodi 19, bo Inputstream Adaptive w najnowszej wersji ma błąd, który nie pozwala na odtwarzanie materiałów. W zależności od platformy można sobie pobrać lub skompilować patch, który to naprawia. Jeśli działasz na którejś z "oficjalnych" platform, spatchowana wersja jest [do pobrania tutaj](https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-607/1/artifacts/). Aktualizację CP Go może wrzucić @mbebe lub wieczorem mogę spróbować stworzyć odpowiedniego zipa.

**Comment by mbebe** [comment]
Poszla aktualizacja.
Ale tak jak pisal @kszaq trzeba zainstalowac odpowiednia wersje inputstreama.

**Comment by kszaq** [comment]
Dzięki, @mbebe ! Zamykam.
