### ISSUE TITLE
Gonet.TV/Lepsi.TV

### ISSUE THREAD

**Issue by staszek1503** [mbebe/blomqvist#503]
@mbebe 
Da radę napisać wtyczkę do wyżej wymienionego serwisu ?
W razie potrzeby mogę udostępnić konto, mogę również przekazać moje ustalenia co do tego serwisu, proszę tylko ewentualnie wskazać gdzie mam przekazać te informacje

**Comment by mbebe** [comment]
Jak cos, to pisz na maila.

**Comment by staszek1503** [comment]
@mbebe Nie mogę nigdzie znaleźć maila do ciebie, jak możesz odezwij się do mnie staszek1503@onet.pl lub podaj mi tu maila.
Oczywiście pomogę na ile moja wiedza mi pozwala

**Comment by Huero23** [comment]
> @mbebe Nie mogę nigdzie znaleźć maila do ciebie, jak możesz odezwij się do mnie [staszek1503@onet.pl](mailto:staszek1503@onet.pl) lub podaj mi tu maila.
> Oczywiście pomogę na ile moja wiedza mi pozwala

mbebeGIT@protonmail.com
