### ISSUE TITLE
TVP ABO

### ISSUE THREAD

**Issue by rafik121** [mbebe/blomqvist#504]
Witam, nie wiem czy tylko u mnie tak jest, ale po wpisaniu serialu jednego czy drugiego np wspaniałe stulecie na stronie jest 360 odc a we wtyczce 11, albo serial bez tożsamości itp większość seriali ma tylko 11 odc i nie ma żadnego przełącznika dalej itp na drugą stronę np, czy to jest jakiś błąd we wtyczce? Ps: dzięki za twoją pracę mbebe

**Comment by rafik121** [comment]
Można jakieś info?

**Comment by mbebe** [comment]
Poszla jakas aktualizacja.

**Comment by rafik121** [comment]
a skad ja pobrac,nie pisze mi zebym zaaktualizowal? a dalej jest to samo wiekszosc seriali ma po 11 odc:) ?

**Comment by mbebe** [comment]
https://github.com/mbebe/blomqvist/raw/master/zips/plugin.video.tvpABON/plugin.video.tvpABON-1.10.zip

**Comment by rafik121** [comment]
dzieki działa, jesteś mistrzem

**Comment by rafik121** [comment]
jeszcze czasem nie wiem czemu wywala bład przy klikaniu na nastepna strone ale w wiekszosci seriali działa dobrze,
wywala bład np w serialu Bez tożsamości na vod.tvp.pl jest 28 odc a we wtyczce 21 i przy kliknieciu na nastepna strone wywala błąd i nie wchodzi, ale jest dużo lepiej jak było

**Comment by mbebe** [comment]
Kolejna poprawka poszla. Za jakis czas sie zaktualizuje.
tu link bezposredni: 
[plugin.video.tvpABON-1.11.zip](https://github.com/mbebe/blomqvist/files/6177462/plugin.video.tvpABON-1.11.zip)

**Comment by rafik121** [comment]
ok teraz działa juz wszystko
