### ISSUE TITLE
Filman.cc 

### ISSUE THREAD

**Issue by Carviotto** [mbebe/blomqvist#506]
W ostatnich dniach nie działa dodatek filman.cc. Otwiera się ale nie wyszukuje żadnych pozycji.

**Comment by Carviotto** [comment]
Dodam że używam kodi 19

**Comment by mbebe** [comment]
W czym nie wyszukuje?

**Comment by Carviotto** [comment]
W zakładce filmy lub seriale ale zdarza się to czasami. Kolejnego dnia już działało normalnie
