### ISSUE TITLE
filman.cc updt

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#51]
dodana telewizja beta

**Comment by krecik71** [comment]
Hej
jak narazie dziala ok
podziekowania za prace

**Comment by wisiann** [comment]
Bangla az milo 👌

**Comment by xxcriticxx** [comment]
iptv.filman.cc web server is down

**Comment by kashkash18** [comment]
@mbebe a jest opcja dodania opisów ??

**Comment by mbebe** [comment]
Nie ma opisow. 
W kodi 18 wtyczki sie zapetlaja. :-/

**Comment by mbebe** [comment]
dodane opisy w filmach ;-)

**Comment by kashkash18** [comment]
No i gitara 😉

**Comment by sky0002** [comment]
No  ok Panowie.  Filman.tv .Przechodzi bez zgrzytu to widać na git i kodi, to już filman.cc nie widać na stronie git, na kodi w repo jest widoczny ale wiadomo git potrzebuje 24 godz na aktualizację. I teraz pytanie. Czy to ja jestem ślepy czy filman.cc po prostu jest ukryty ??:)

**Comment by wisiann** [comment]
@mbebe,
Telewizja (beta) wyrzuca blad,
Cz to tylko u mnie?
