### ISSUE TITLE
Cyfrowy Polsat GO 

### ISSUE THREAD

**Issue by okcets** [mbebe/blomqvist#514]
Witam. Mam problem z Cyfrowym Polsatem po aktualizacji Kodi. Włącza się lista kanałów i to niestety wszystko co mogę zrobić. Nie jestem w stanie uruchomić żadnego kanału. Proszę o pomoc

**Comment by hevet** [comment]
Zainstaluj ręcznie to https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-607/1/artifacts/

**Comment by okcets** [comment]
Bardzo bardzo dziękuję za szybko reakcję. Po instalacji wszystko działa jak należy
