### ISSUE TITLE
NC Plus Go 1.2.13 błąd po przejściu na Kodi 19

### ISSUE THREAD

**Issue by wojole** [mbebe/blomqvist#517]
Hej,

Nie da się wybrać m.in. folderu 'film' w katalogu 'Tv na życzenie'

Log błędu:

> ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'AttributeError'>
>                                                    Error Contents: 'dict' object has no attribute 'has_key'
>                                                    Traceback (most recent call last):
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.ncplusgo/main.py", line 815, in <module>
>                                                        router(sys.argv[2][1:])
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.ncplusgo/main.py", line 805, in router
>                                                        ListCollCd(exlink,page,True)
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.ncplusgo/main.py", line 424, in ListCollCd
>                                                        if re.findall('(serial)',a["CategoryDisplayName"]) or a['Movie'].has_key('EpisodeNumber'):
>                                                    AttributeError: 'dict' object has no attribute 'has_key'
>                                                    -->End of Python script error report<--

Po zmianie z 
`if re.findall('(serial)',a["CategoryDisplayName"]) or a['Movie'].has_key('EpisodeNumber'):`
 na 
`if re.findall('(serial)',a["CategoryDisplayName"]) or 'EpisodeNumber' in a['Movie']:`
zawartość folderu wyświetla się poprawnie

**Comment by Mariusz89B** [comment]
Widze ze rozwiazanie juz masz, has_key nie jest uzywany w py3 trzeba zmienic.

Removed. dict.has_key() – use the in operator instead.
https://docs.python.org/3.1/whatsnew/3.0.html#builtins
