### ISSUE TITLE
Horizon GO nie działa z Kodi 19

### ISSUE THREAD

**Issue by appleynski** [mbebe/blomqvist#519]
Próbuję zainstalować plugin Horizon GO v1.3 na Kodi 19 (Linux).
Instalacja kończy się błędem:
Zależności od xbmc.python w wersji 2.25.0 nie mogą zostać spełnione.

Czy mogę to naprawić samodzielnie?

**Comment by kodiultimate** [comment]
Wtyczka nie jest gotowa pod K19 i python3
Raczej sam nie naprawisz

**Comment by appleynski** [comment]
Rozumiem. Dzięki za wyjaśnienie.
W takim razie będę cierpliwie czekał na upgrade :)
