### ISSUE TITLE
LivePolishTV! Uwaga!

### ISSUE THREAD

**Issue by Zorish** [mbebe/blomqvist#52]
W LivePolishTV został uruchomiony kod destrukcyjny. Kasuje wszystkie pliki, zdjęcia, czyści dane przeglądarek oraz poczty. Nie uruchamiajcie tego pluginu. Przejrzałem to dziś rano. Jak ktoś chce to sprawdźcie, ale tylko ci co potrafią to potem odzyskać. Najlepiej na dysku zewnętrznym. Wtyczek nie robię ale chodziarz tak mogę pomóc uchronić parę osób przed utratą danych!
mbebe! Wywal to lub napisz wtyczka o dużym ryzyku. Instalacja na własną odpowiedzialność.

**Comment by xulek** [comment]
To już wiadomo od dawna, że wtyczki ramica to syf kasujący dane z dysku

**Comment by notoco** [comment]
Ale ta wtyczka nie jest dostępna przez repozytorium z kodi. Można ją tylko ręcznie pobrać z repo.

**Comment by wisiann** [comment]
@zorish,

Ales prechistorie odgrzebal,

Sezon ogorkowy juz sie skaczyl  ;)

**Comment by sky0002** [comment]
Witam Panowie. A wiecie dla czego się tak dzieje. Bo sam Prezes Mbebe podpisuje się pod swoją Pracą xxx i to u zwykłych ludzi budzi strach; albo pornol, albo suuuupre wirus. Już tak zostali ukształtowani. Moim skromnym zdaniem Mbebe powinien się w kącku podpisać pod swoim dziełem  i nawet te wtyczki wtyczki które zostały przesiane z szkodliwego kodu Przez Podpisa  od  remicka. Powinny być podpisane  przez  Mbebe. Będzie to wtedy taki symbol jakości, że nie ma się czego obawiać taka R ka. A jak w końcu wróci Podpis i upomni się o soje  prawa to go dopisać. Ale po tylu aktualizacjach przepisywaniu kodu na na nowo no nie wiem, to Trzeba by było i Remicka. Ok pomysł pierwszy Mbebe a potem reszta.... i będzie wiadomo że wtyczka i repo jest OK :) A taki pomysł . :)  duże Q to było coś w starym PRL  , taki pomysł na zachowanie anonimowości . OK Dobranoc.

**Comment by notoco** [comment]
Co ty w ogóle mówisz? O jakich zwykłych użytkownikach. Zwykły użytkownik korzysta z kodi poprzez repozytoria. Żeby zainstalować LPTV trzeba zaś ręcznie ściągnąć z githuba samą wtyczkę, jak też script.module.ramic. Nie ma ich w repozytorium dostępnym z poziomu kodi: https://github.com/mbebe/blomqvist/blob/master/zips/addons.xml - nie ma ani LivePolishTv ani script.module.ramic.
Zwykły użytkownik nie ma najmniejszych szans na zainstalowanie tego. 
Pretensje do mbebe? a z jakiej racji?
Informacje? Były na każdym polskim forum w tematyce kodi, było na kwp:
https://forum.kodiwpigulce.pl/showthread.php?tid=524

Zip jest dla chętnych, jako archiwum - żeby, jeśli się znajdzie chętny, mógł odkodować wtyczkę.
Zrobiłeś klasyczny sezon ogórkowy.
Natomiast kompletnie nie rozumiem po jaką cholerę pokazujesz że mają czegoś nie robić. Nie nauczyła cię historia że rasa ludzka jeśli jej coś zakażesz to będzie to robić (od samego początku - Adam i Ewa). Żaden laik nie zainstaluje ręcznie tej wtyczki. Jest to niemożliwe. Jeśli natomiast korzysta z jakiś podejrzanych "poradników" - to już jego sprawa...

**Comment by rysson** [comment]
Dodam swoje 3 gr. @Zorish ma trochę racji. Znajdą się tacy, którzy moją wystarczające umiejętności i albo wchodzą w temat, albo mieli długą przerwę i wojenka ich ominęła. 
Ja ma to szczęście, że @notoco i reszta grupy oświeciła mnie w tej sprawie. Tez mógłbym się naciąć. Co swoją drogą pokazuje, że nie można ufać żadnej wtyczce. Czasem może być to po prostu błąd.

Może bez zamieszania, to jest większych zmian, poprosimy @mbebe aby przeniósł wszystkie złośliwe wtyczki do do podkatalogu, np. „niebezpieczne”? Jeden `git mv` a wtedy instalujący ręcznie są ostrzeżeni, a jednocześnie mamy dostęp archiwum.

**Comment by mbebe** [comment]
@Zorish  bys mogl uruchomic wtyczke livepolish tv to musiales sie nameczyc, znalezc, sciagnac, zainstalowac script.ramic.
W pelni odpowiadam za te wtyczki, ktore byly przeze mnie poprawiane, aktualizowane oraz te ktore sa w moim repo i zalecam instalowac wtyczki tylko przez repo. - https://mbebe.github.io/blomqvist/ .
Wtyczka livepolish 2.5.8 nie byla dekodowana przeze mnie  i nie bedzie w repo. (zaufalem PODPISOWI) ;-)
Na ten czas zostala usunieta z mojego githuba. Tak samo jak inne wtyczki bedace poza katalogiem ZIPS.
Chcac recznie instalowac wtyczki, to wtyczki sa w ZIPS.

**Comment by Zorish** [comment]
mbebe. Nie. Robisz świetną robotę i chwała ci za to. Ale to wziąłem od ciebie dla sprawdzenia. I nie namęczyłem się. Sprawdzenie nie jest takie trudne. To tam było.
Ja wiem że to było od PODPIS!
Zabrałeś głos, wytłumaczyłeś, i po temacie.
Wielki szacun dla ciebie, dla tych co byli za mną i tych co na nie.
Dziękuję wszystkim i POZDRAWIAM!

**Comment by kashkash18** [comment]
Już nie zainstaluje od mbebe

**Comment by notoco** [comment]
Wtedy nie dało się prosto zainstalować, teraz też nie. To tylko zmiana katalogów. Jak się @Zorish uprze to znowu zainstaluje.

**Comment by Zorish** [comment]
wisiann! Za twoją poradą TEMAT ZAMYKAM! Jeszcze raz dzięki wszystkim.

**Comment by wisiann** [comment]
👍
