### ISSUE TITLE
Player.pl - dodanie możliwości cofania na kanałach live

### ISSUE THREAD

**Issue by kszaq** [mbebe/blomqvist#524]
https://github.com/kszaq/plugin.video.playermb/commit/f35ae3f59bde670f9300e8c1ee66aaf47120ecd8.patch

**Comment by kszaq** [comment]
Tutaj wersja uwzględniająca wartość time_shift zwróconą przez serwer, gdyby dostępne było mniej/więcej bufora:
https://github.com/kszaq/plugin.video.playermb/commit/b936238fdc1cff54fbd8909dc3a74a6f8504f5e6

Przetestowane na kanałach live oraz VOD.

**Comment by praspp** [comment]
Czy mógłbyś dodać funkcję Catch-up TV w dodatku CanalPLUS-VOD od @mbebe, a konkretnie do wersji 1.7.4.5 autorstwa @EuHadii1 ?
https://github.com/mbebe/blomqvist/issues/387#issuecomment-800581577

**Comment by kszaq** [comment]
Niestety nie, bo nie mam C+.

**Comment by praspp** [comment]
Mogę udostępnić na priv dane do autentykacji w C+ Online.

**Comment by EuHadii1** [comment]
@praspp @kszaq  - jak chcecie dodać funkcjonalność catch up to najlepiej na wersji z poniższego linku, bo poprawiłem jeszcze tworzenie linków w liście m3u i dodałem grupowanie dla nowych kanałów, które się pojawiły w C+ ostatnio

https://drive.google.com/file/d/1o6NsWEphupb7j8JKOlSI7vSkiKqGgq3H/view?usp=drivesdk

**Comment by mbebe** [comment]
to tez dodalem do repo.

**Comment by mkaflowski** [comment]
Są szanse na implementacje w C+?

**Comment by praspp** [comment]
> Są szanse na implementacje w C+? 

To pytanie do @kszaq .

**Comment by lbuczko** [comment]
@kszaq - Czy dodanie parametru '&dvr=....' aby osiągnąć time_shift jest to funkcjonalność dodatku inputstream.adaptive czy samego Kodi - nigdzie nie mogę znaleźć dokumentacji na temat tego parametru. Chodzi mi o to, że testuję inną wtyczkę i przyjmuje mi parametr np. '&dvr=262113200' - co jest odpowiednikiem niecałych 73 godzin, parametr np. '&dvr=263113200' już nie uruchamia w ogóle streamu i nie wywala błędu w logu, natomiast max time_shift od providera  to 7 dni więc jeszcze brakuje 5 dni. Podejrzewam, że albo kodi albo inputsream.adaptive nie obsługuje tak dużych liczb, jednak nie wiem gdzie szukać i ewentualnie zgłosić poprawkę lub jeśli będzie taka możliwość samemu poprawić.

**Comment by kszaq** [comment]
@lbuczko To jest parametr w API player.pl, wyciągnięty z analizy ruchu generowanego w przeglądarce: najpierw API zwraca maksymalną możliwą wartość, potem jest mnożona przez stałą po stronie klienta (JS) i dodawana do URL pobierającego manifest. Innymi słowy, długość dostępnego timeshift zależy w pełni od manifestu zwracanego przez serwer.

**Comment by lbuczko** [comment]
@kszaq - To co opisałeś to już wiedziałem. Chodziło mi o to, że dzięki dodaniu parametru do url'a '&dvr=jakaś liczba' Kodi pozwala cofać stream (oczywiście jeśli na to pozwala provider). Po dodaniu tego parametru Kodi pokazuje, że już jakiś czas oglądamy i możemy sobie cofnąć stream. Ta liczba to wartość podana przez API pomnożona przez dane z dasha (timescale) - u mnie provider daje 7 dni, czyli 604800 sek wstecz razy timescale = 1000, ale niestety Kodi nie przyjmuje takich wartości. Udało mi się dać 262113200 co dało niecałe 73 godziny, ale już wartości 263113200 i wyższych nie przyjmuje - stream nie uruchamia się. Stąd moje pytanie - dodanie &vdr=... to funkcjonalność KODI, czy to inputstream.adaptive. Czy może są jeszcze inne parametry - gdzie znajdę jakieś info ?

**Comment by kszaq** [comment]
A sprawdzałeś, czy przy większej wartości dvr dostajesz prawidłowy manifest?

**Comment by lbuczko** [comment]
Nie do końca mi się udaje śledzić transmisje po ssl'u (w szczególności w Kodi), ale sprawdzałem na Horizonie i teraz już wiem, że dodanie parametru '&dvr=...' nie jest uniwersalne a po porostu dodaje do URL'a z manifestem MPD parametr & vdr, a api to odpowiednio interpretuje (od razu mówię ten parametr nie działa na Horizon'a, więc w ten sposób nie doda się time_shift'a, ale dzięki temu miałem tę informację w logu). Po prostu przypadek jest, że akurat tego providera również parametr vdr działa, ale widocznie dla większych odległości czasu jest dawany parametr w inny sposób.
Dzięki za wszystko. Pozdrawiam.

**Comment by rysson** [comment]
Powtórzę wpis, bo on raczej tutaj powinien być. @DeGH w #304 wspomniał, że zrobiłeś poprawki, których nie ma w repo @mbebe. Ja też naniosłem trochę zmian (do dobra, dość brutalnie) i teraz chciałbym złączyć naszą pracę.

@kszaq, zamierzam łyknąć Twoje zmiany do tego co przekopałem. Bardzo zależy Ci na historii commitów, czy mogę sprasować do jednego? Pytam bo ze 2x jest ręczny revert, co też jest jakąś informacją.

**Comment by kszaq** [comment]
Nie widziałem #304. Zamknę ten wątek i możemy kontynuować w #304. Jak już tam pisałem, przygotuję squash dla łatwiejszego zaaplikowania pojedynczych zmian.

**Comment by rysson** [comment]
No i pięknie, dzięki.

Squasha nie musisz bo i tak mam konflikt (trochę ten kod przeorałem). Wezmę wprost z Twego repo.
