### ISSUE TITLE
CP Go - drobne poprawki i generowanie listy m3u do PVR IPTV Simple

### ISSUE THREAD

**Issue by kszaq** [mbebe/blomqvist#525]
Cześć @mbebe,

Dodałem do wtyczki CP Go generowanie listy m3u, skopiowane z wtyczki WP Pilot. Może będziesz chciał to dodać do Twojego repo:
https://github.com/kszaq/plugin.video.cpgo

**Comment by irkfine** [comment]
Generowanie listy jest super. Czy to działa z Kodi 19?

**Comment by kszaq** [comment]
Działa, używam Kodi 19.

**Comment by z0rza** [comment]
@kszaq  super sprawa z tym generatorem, mógł byś dodać takie udogodnienie do CanalPLUS-VOD jeżeli @mbebe nie będzie miał nic przeciwko?

**Comment by kszaq** [comment]
Niestety nie, bo nie mam dostępu do C+.

**Comment by michael112** [comment]
https://github.com/mbebe/blomqvist/issues/387
@z0rza Poszukaj pod koniec strony post autorstwa @EuHadii1

**Comment by z0rza** [comment]
@michael112 wielkie dzięki, połączone wszystko do kupy w 1 listę działa wyśmienicie

**Comment by michael112** [comment]
@z0rza czym łączysz listę? Ręcznie w notatniku? Bo słyszałem że jest do tego jakiś dodatek.

**Comment by praspp** [comment]
To nie do mnie, ale polecam dodatek  IPTV Merge. Używam go do zarządzania/łączenia 5 list - TV, Radio.
https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html

**Comment by z0rza** [comment]
> @z0rza czym łączysz listę? Ręcznie w notatniku? Bo słyszałem że jest do tego jakiś dodatek.

Używam Notepad++

**Comment by michael112** [comment]
No tak, to jest dobry pomysł. Można nawet poustawiać kanały według swojej kolejności, tylko to trochę żmudna praca.

**Comment by praspp** [comment]
Do ededycji list polecam PlaylistEditorTV: https://github.com/Isayso/PlaylistEditorTV
Do zarządzania listami (m. in. łączenia list) w Kodi -  IPTV Merge: https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html
