### ISSUE TITLE
Nagrywanie platnej tv

### ISSUE THREAD

**Issue by xxcriticxx** [mbebe/blomqvist#53]
Ktos mnie oświeci jak można nagrać płatne tv typu wizjetv czy hejtv?

**Comment by sky0002** [comment]
mogę ja ale na czym, jaki system jaka wersja no i jaki sprzęt ???

**Comment by xxcriticxx** [comment]
@sky0002 win10 kodi 17.6

@notoco jesteś w okolicy?

**Comment by notoco** [comment]
No jestem....

**Comment by xxcriticxx** [comment]
@notoco wiesz coś na temat nagrywania płatnej tv?

**Comment by notoco** [comment]
Nie - nie widzę takiej potrzeby - wszystko jest we wtyczkach .

**Comment by sky0002** [comment]
Witam. Dla Ciebie najszybciej i najprościej będzie instalacja wtyczki M TvGuide. W ustawieniach wtyczki Nagrywanie, Ustawić folder zapisu i pobrać aplikację do nagrywania . Wybrać pod swój system. Po restarcie wpisać EPG https://epg.ovh/pl.xml i swoje dane do wizjatv. Z heytv jest troszkę gorzej bo m tvguide jeszcze jej nie obsługuje, ale jest do obejścia.

**Comment by sky0002** [comment]
Nie. Płatne jest tylko EPG. Repo : https://www52.zippyshare.com/v/4dKZFeTw/file.html

**Comment by sky0002** [comment]
Nie sprawdzałem tego, ale wydaje mi się że 1 a jak masz jeszcze 2 go dawce goda albo listę to możesz nagrywać i oglądać jednocześnie.

**Comment by gzenio22** [comment]
Nagrywać możesz jeden kanał jednocześnie :)

**Comment by xxcriticxx** [comment]
@wisiann nie o takie nagrywanie chodziło

**Comment by wisiann** [comment]
Ahhh ,sorry

**Comment by kodiwpigulce** [comment]
Jest jeszcze aplikacja na win, która działa jako serwer i z poziomu Kodi w sieci możesz nagrywać: https://www.nextpvr.com
kolejna opcja to wtyczka IPTV Recorder: https://forum.kodi.tv/showthread.php?tid=329991

A najwygodniejsza według mnie opcja to postawić sobie Tvheadend i też można z Kodi nagrywać: https://tvheadend.org

**Comment by xxcriticxx** [comment]
@kodiwpigulce dzieki za info
