### ISSUE TITLE
Nasze-kino 

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#54]
wtyczka mimo zaznaczeniu grupuj seriale  nie robi tego

**Comment by rafalmar1981** [comment]
pozdrowienia dle mbebe i podziękowania za wielką pracę.

**Comment by wisiann** [comment]
U mnie dziala

**Comment by kendo999** [comment]
a czy okładkim filmow   ładują się

**Comment by wisiann** [comment]
Nope
