### ISSUE TITLE
Co się dzieje z mbebe?

### ISSUE THREAD

**Issue by hevet** [mbebe/blomqvist#554]
Czy coś się stało z mbebe? Od 3 tygodni nic nie napisał, ani nie uaktualnił. Czy po prostu jest zajęty innymi sprawami?

**Comment by notoco** [comment]
Może prowadzi jeszcze normalne życie poza internetem?

**Comment by rysson** [comment]
Mbebe? Niemożliwe, to jest SI nowej generacji. Inaczej nie reagowałby tak szybko :-P
Może przechodzi kalibrację?
