### ISSUE TITLE
Zaniepokojony

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#556]
Witam wszystkich @mbebeowców, mam pytanie do was czy coś się stało @mbebe? (nic nie potrzebuje), zwyczajna troska. Pozdrawiam

**Comment by lucjan76** [comment]
Mam nadzieję że wszystko okej z mbebe

**Comment by rysson** [comment]
Też mam nadzieję, że to przeciążenie, brak czasu, czy choć by )oby chwilowy) brak chęci.
Zdecydowanie nie chciałbym przeżywać tego co z MrKnow.

**Comment by rafalmar1981** [comment]
oby nic się nie stało

**Comment by mbebe** [comment]
Spokojnie. Wszystko w miare ok.
Wracam powoli do normalnosci.
:roll_eyes:

**Comment by rysson** [comment]
I całe szczęście – świetna wiadomość.
Gdyby nie aktywność przez ostatnie lata to pomyślałbym, że to nadmiar projektów do oddania przed sesją :-P

**Comment by irkfine** [comment]
Może znajdzie się trochę czasu na usprawnienie wtyczki UPC TV GO bo obecnie nie jest z nią najlepiej? Jestem gotowy podnieść priorytet tego dofinansowaniem i mam nadzieję że nie będę w tym osamotniony:).
