### ISSUE TITLE
AlanTvSport w repo.

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#56]
wersja 1.0 :-D

**Comment by kashkash18** [comment]
I te powtórki :) Rewelacja heheh

**Comment by xxcriticxx** [comment]
nazwe trzeba zmienic na hulkstream.com

**Comment by mbebe** [comment]
Na te chwile nie ma to wplywu na wtyczje.

**Comment by kashkash18** [comment]
Alan się zepsuł , przy próbie wejścia w Live wyskakuje błąd dodatku. 
![](https://i.imgur.com/iRhIPRZ.png)

Ostatnimi czasy więcej streamów odpalało się z alternatywnych źródeł niż z podstawowych , więc nie wiem czy czegoś nie pozmieniali.

**Comment by kashkash18** [comment]
Teraz jest ok . Dzięki wielkie 🙂

**Comment by kopernik1983** [comment]
@mbebe załapałeś się :) https://koditips.com/hulkstream-kodi/

**Comment by kashkash18** [comment]
Błąd przy wejściu w Live
![](https://i.imgur.com/VKd4bKT.jpg)

**Comment by krotki1** [comment]
Hulkstream nie lata, nie pokazuje linków, sprawdzałem na dwóch urzadzeniach,
pozdrawiam,

**Comment by kashkash18** [comment]
Dzięki za poprawkę :) teraz wszystko wyświetla się prawidłowo . W Java dodali nowe powtórki do wyboru które nie gadają.

**Comment by kashkash18** [comment]
Ahhh te powtórki :) Teraz jest Panie w cyc :)

**Comment by kashkash18** [comment]
A możesz w Java dodać "Następna strona" ?? Zobacz np UEFA Europa League. W SportPiece to samo , np w American-Football

**Comment by kashkash18** [comment]
Działa , aczkolwiek Hulk zaopatruje się w ogromną liczbę różnych źródeł streamów. Ogarnięcie wszystkiego i utrzymanie przy życiu jest bardzo trudne. Gdyby mbebe miał to ogarnąć na tip top to nie miał by czasu na inne wtyczki a już nie wspomnę o życiu prywatnym. Egzotykę będzie ciężko obejrzeć , a przy ważniejszych wydarzeniach musisz znaleźć działający link. Częściej trafisz coś działającego w alternatywnych źródłach.
Nie wiem czy o to Ci chodzilo bo pytanie które zadałeś jest bardzo ogólne.
