### ISSUE TITLE
IPLA - brak niektórych pozycji w VOD na Kodi19

### ISSUE THREAD

**Issue by hevet** [mbebe/blomqvist#562]
Przykładowo, gdy wejdę w VOD - SPORT - DYSCYPLINY - piłka nożna - wybiorę wyświetl materiały, nie wyświetlają się żadne materiały. Problem występuje tylko gdy wybiorę dyscyplinę, która ma w nazwie polskie znaki. Przykładowo w motoryzacja wszystko jest w porządku. To samo w innych kategoriach np. DZIECI - najmłodsi - brak materiałów.

Na Kodi 18.9 problem nie występuje.

Dzięki

**Comment by hevet** [comment]
@mbebe dałoby radę rozwiązać ten problem😁?

**Comment by mbebe** [comment]
poszla poprawka.

**Comment by hevet** [comment]
Dzięki
