### ISSUE TITLE
Nasze-kino .... .eu?

### ISSUE THREAD

**Issue by gs188** [mbebe/blomqvist#57]
Mistrzu mbebe, a czy jest szansa zeby 'odpalic' wtyczke do strony nasze-kino.eu?  (dawne nasze-kino.online) byla w kodzie u ramic'a ale juz nie dziala.  To nie to samo co naszekino.tv
Tu jest stara wersja do sciagniecia jakby mialo to pomoc:
https://kodi-addons.club/addon/plugin.video.naszekino/2.4

**Comment by mbebe** [comment]
Mam ja rozkopana od jakiegos czasu. Tylko tam chyba linki sa do sciagania filnow. Wkrotce do niej zajrze...
