### ISSUE TITLE
cda-x.pl + cdax.online = cda-tv.pl

### ISSUE THREAD

**Issue by adamibeata** [mbebe/blomqvist#58]
Witam mam nadzieje i chciałbym aby to była ostania moja demona pod tą nazwą czyli cda-tv.pl (nie wiadomo co  się stanie i wymyślą  pod nazwą  Anti-acta2 czy przejdzie czy nie? w  tej formie) mam nadzieję że  zerkniesz na to co aktualnie  znajduję się na stronie chciałbym aby moja strona odzwierciedlała aktualną nazwę i wszystko co na niej się znajduje , nie ma już cda-x.pl  czy cdax online  jest i niech tak zostanie http://cda-tv.pl
Jest błąd we wtyczce mianowicie jak nie zaktualizuje  postów nie wyświetlają się linki. brak przejścia w następną stronę 
W razie czego będę pisał

**Comment by mbebe** [comment]
W tej nowej, zaktualizowanej wtyczce 1.2.6 brak linkow i brak nastepnej strony?

**Comment by adamibeata** [comment]
tak

**Comment by mbebe** [comment]
ok. poszla poprawka - wersja 1.2.7
