### ISSUE TITLE
UPC TV GO błąd logowania

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#584]
Witam szanowne grono wyskakuje błąd logowania w UPC TV GO
Oto log https://paste.kodi.tv/ibawevebeh
Da się coś pokąbinować?? Pozdrawiam

**Comment by hevet** [comment]
U mnie loguje się normalnie.

**Comment by zuzia-dev** [comment]
Działa, loguje się. Od wczoraj są jakieś awarie, niektórym znikają kanały więc może to ma związek.

**Comment by rafalmar1981** [comment]
Właśnie nie problem od miesiąca jest na androidzie, na stronie działa

**Comment by hevet** [comment]
U mnie na androidzie również loguje się poprawnie.

**Comment by rafalmar1981** [comment]
@hevet a widziałeś w logu że wyskakuje błąd

**Comment by hevet** [comment]
Widziałem, napisałem że u mnie loguje się poprawnie, więc problem jest u Ciebie.

**Comment by rafalmar1981** [comment]
więc tak na stronie internetowej ok na win7 kodi 17.6 krypto ok na androidzie kodi 18.9 błąd błędne dane logowania, fakt po przeinstalowaniu zalogowało poprawnie i działa. Dziękuję  @hevet (lenistwo chyba wyszło, a raczej na pewno - troczę wpisywania było). Pozdrawiam

**Comment by zuzia-dev** [comment]
Właśnie maiłam to samo, wchodzę do Kodi, błąd logowania. Zamknęłam program i kilka minut ponowiłam próbę - działa.
