### ISSUE TITLE
Viaplay PL

### ISSUE THREAD

**Issue by zuzia-dev** [mbebe/blomqvist#588]
Wtyczka jest w repozytorium Kodi, autor raczej nie zaktualizuje zbyt prędko: https://github.com/emilsvennesson/kodi-viaplay
Udało mi się ją po lekkim liftingu zmusić do działania z https://viaplay.pl/ ale jest problem z napisami. Pobiera lecz nie wyświetla. Po zmianie ścieżki dźwiękowej wyświetlają się napisy, ale nieprawidłowo. Może ktoś rzucić okiem na kod i coś podpowiedzieć? @mbebe, może coś doradzisz? 

Edit:
Po długim czasie i ja mam swoją aktywnie rozwijaną wersję: https://github.com/zuzia-dev/kodi-viaplay

**Comment by hevet** [comment]
Może wrzuć tu Twój zmodyfikowany dodatek.

**Comment by zuzia-dev** [comment]
Napisy mają format .smi SAMI i nie wiem jak to ugryźć.

```
    def download_subtitles(self, suburls):
        """Download the SAMI subtitles, decode the HTML entities and save to temp directory.
        Return a list of the path to the downloaded subtitles."""
        paths = []
        for sub_data in suburls:
            sami = self.make_request(url=sub_data['href'], method='get').decode('utf-8', 'ignore').strip()
            htmlparser = HTMLParser.HTMLParser()
            subtitle = htmlparser.unescape(sami).encode('utf-8')
            path = os.path.join(self.tempdir, '{0}.sami'.format(sub_data['languageCode']))
            with open(path, 'w') as subfile:
                subfile.write(subtitle)
            paths.append(path)
        return paths
```

Pobiera, zapisuje tak:

```
<SAMI>
<HEAD>
   <STYLE TYPE="Text/css">
   <!--
      P {margin-left: 29pt; margin-right: 29pt; font-size: 12pt; text-align: center; font-family: Tahoma; font-weight: bold; color: #FFFFFF; background-color: #000000;}
      .SUBTTL {Name: 'Subtitles'; Lang: en-US; SAMIType: CC;}
   -->
   </STYLE>
</HEAD>
<BODY>
   <SYNC START=72399>
      <P CLASS=SUBTTL>ZRZESZENIE STUDENTEK &ldquor;DELTA NU”<br>CITY UNIVERSITY
   <SYNC START=75026>
      <P CLASS=SUBTTL> 
   <SYNC START=78154>
      <P CLASS=SUBTTL>ELLE WOODS<br>PRZEWODNICZ&Aogon;CA
   <SYNC START=81700>
      <P CLASS=SUBTTL> 
   <SYNC START=126870>
      <P CLASS=SUBTTL>KRÓLOWA BALU ABSOLWENTÓW
   <SYNC START=128455>
      <P CLASS=SUBTTL> 
   <SYNC START=179756>
      <P CLASS=SUBTTL>Uwielbiam t&eogon; restauracj&eogon;!<br>Podobno Madonna zacz&eogon;&lstrok;a tam rodzi&cacute;.
   <SYNC START=183134>
      <P CLASS=SUBTTL> 
   <SYNC START=183301>
      <P CLASS=SUBTTL>Kurcz&eogon;, musz&eogon; i&sacute;&cacute; na zakupy.<br>Do zobaczenia wieczorem.
   <SYNC START=186471>
      <P CLASS=SUBTTL> 
   <SYNC START=186513>
      <P CLASS=SUBTTL>Cze&sacute;&cacute;.
   <SYNC START=188056>
      <P CLASS=SUBTTL> 
   <SYNC START=188306>
      <P CLASS=SUBTTL>Bruiser, co to?
   <SYNC START=190308>
      <P CLASS=SUBTTL> 
   <SYNC START=194354>
      <P CLASS=SUBTTL>&ldquor;Powodzenia wieczorem.<br>Elle i Warner na zawsze”.
   <SYNC START=197232>
      <P CLASS=SUBTTL> 
   <SYNC START=197357>
      <P CLASS=SUBTTL>Jakie to mi&lstrok;e.
   <SYNC START=199359>
      <P CLASS=SUBTTL> 
   <SYNC START=213081>

```

Tylko ó jest prawidłowe, reszta polskich znaków jak widać.

**Comment by Mariusz89B** [comment]
Podaj jakies url z sub_data['href'] to napisze wsparcie dla polskich znakow bo nie mam logowania do viaplay.

**Comment by zuzia-dev** [comment]
@Mariusz89B odbierz maila.

**Comment by hevet** [comment]
Jakby ktoś był zainteresowany polskim Viaplay, tu zmodyfikowany dodatek. W opcjach należy wybrać viaplay.pl i zalogować się kodem przez stronę. @zuzia-dev nie potrzeba nic zmieniać w obsłudze w napisach, pokazuje normalnie polskie znaki.
[kodi-viaplay-master.zip](https://github.com/mbebe/blomqvist/files/6943370/kodi-viaplay-master.zip)

**Comment by Mariusz89B** [comment]
> Jakby ktoś był zainteresowany polskim Viaplay, tu zmodyfikowany przeze mnie dodatek. W opcjach należy wybrać viaplay.pl i zalogować się kodem przez stronę https://viaplay.pl/activate
> @zuzia-dev nie potrzeba nic zmieniać w obsłudze w napisach, pokazuje normalnie polskie znaki.
> [kodi-viaplay-master.zip](https://github.com/mbebe/blomqvist/files/6943370/kodi-viaplay-master.zip)

Problem dotyczy Kodi v18 nie v19.

Tu jest Viaplay ze wsparciem dla v18 i v19 z polskimi napisami, jednak przy przewijaniu jest bug z synchronizacja napisow:

**plugin.video.viaplay-2.1.3.zip**
https://drive.google.com/file/d/1j8wY81jOUGa5wjKOxFwZ8PpFGCX31oep/view?usp=sharing

**Comment by zuzia-dev** [comment]
@Mariusz89B @hevet 
W szwedzkiej wersji nie ma problemu z napisami, sprawadziłam. Pobierają się i wyświetlają właściwe. Nie występuje błąd napisów przy przewijaniu.

<a href='https://postimg.cc/w3jJPfr4' target='_blank'><img src='https://i.postimg.cc/w3jJPfr4/sew1.jpg' border='0' alt='sew1'/></a>

<a href='https://postimg.cc/hXLfhTw7' target='_blank'><img src='https://i.postimg.cc/hXLfhTw7/swe2.jpg' border='0' alt='swe2'/></a>

```
<SAMI>
<HEAD>
   <STYLE TYPE="Text/css">
   <!--
      P {margin-left: 29pt; margin-right: 29pt; font-size: 24pt; text-align: center; font-family: Tahoma; font-weight: bold; color: #FFFFFF; background-color: #000000;}
      .SUBTTL {Name: 'Subtitles'; Lang: en-US; SAMIType: CC;}
   -->
   </STYLE>
</HEAD>
<BODY>
   <SYNC START=0>
      <P CLASS=SUBTTL>Boden och jag har pratat<br>om att göra dig till kandidat.
   <SYNC START=2680>
      <P CLASS=SUBTTL> 
   <SYNC START=2760>
      <P CLASS=SUBTTL>Ja, det är jag verkligen!
   <SYNC START=3840>
      <P CLASS=SUBTTL> 
   <SYNC START=3920>
      <P CLASS=SUBTTL>Välkommen till bil 81, raring!
   <SYNC START=6920>
      <P CLASS=SUBTTL> 
   <SYNC START=8280>
      <P CLASS=SUBTTL>Mills!
   <SYNC START=9960>
      <P CLASS=SUBTTL> 
   <SYNC START=10200>
      <P CLASS=SUBTTL>Jag inte inte skicka ut dig i tjänst.
   <SYNC START=11680>
      <P CLASS=SUBTTL> 
   <SYNC START=11760>
      <P CLASS=SUBTTL>Om Dawson flyttar till brandbilen,<br>så finns det väl en ledig sjukvårdstjänst?
   <SYNC START=15080>
      <P CLASS=SUBTTL> 
   <SYNC START=15160>
      <P CLASS=SUBTTL>Det stämmer.
   <SYNC START=16160>
      <P CLASS=SUBTTL> 
   <SYNC START=16800>
      <P CLASS=SUBTTL>Jag har beställt! Var är groggarna?
   <SYNC START=18400>
      <P CLASS=SUBTTL> 
   <SYNC START=18480>
      <P CLASS=SUBTTL>Du ska inte dricka mer.
   <SYNC START=19520>
      <P CLASS=SUBTTL> 
   <SYNC START=19600>
      <P CLASS=SUBTTL>Och nu är det en intervention?
   <SYNC START=20880>
      <P CLASS=SUBTTL> 
   <SYNC START=20960>
      <P CLASS=SUBTTL>Du vet väl att det erbjuds sorgbearbetning?
   <SYNC START=22880>
      <P CLASS=SUBTTL> 
   <SYNC START=23000>
      <P CLASS=SUBTTL>Det behövs inte.
   <SYNC START=24040>
      <P CLASS=SUBTTL> 
   <SYNC START=25960>
      <P CLASS=SUBTTL>Klara, kör.
   <SYNC START=27240>
      <P CLASS=SUBTTL> 
   <SYNC START=27720>
      <P CLASS=SUBTTL>Kör, kör!
   <SYNC START=30280>
      <P CLASS=SUBTTL> 
   <SYNC START=32240>
      <P CLASS=SUBTTL>Jag gjorde det!
   <SYNC START=34400>
      <P CLASS=SUBTTL> 
   <SYNC START=36000>
      <P CLASS=SUBTTL>Ja! Tack, Mick.
   <SYNC START=38040>
      <P CLASS=SUBTTL> 
   <SYNC START=38120>
      <P CLASS=SUBTTL>Du betalar nästa runda.
   <SYNC START=40440>
      <P CLASS=SUBTTL> 
   <SYNC START=42880>
      <P CLASS=SUBTTL>Okej.
   <SYNC START=44120>
      <P CLASS=SUBTTL> 
   <SYNC START=47840>
      <P CLASS=SUBTTL>Kelly, du får röka utomhus.
   <SYNC START=49160>
      <P CLASS=SUBTTL> 
   <SYNC START=49240>
      <P CLASS=SUBTTL>Vad snackar du om?
   <SYNC START=51120>
      <P CLASS=SUBTTL> 
   <SYNC START=51200>
      <P CLASS=SUBTTL>Allt jag har betalat här,
   <SYNC START=52600>
      <P CLASS=SUBTTL> 
   <SYNC START=52680>
      <P CLASS=SUBTTL>-och jag får inte röka en cigarr?<br>-Ta det med borgmästaren.
   <SYNC START=54400>
      <P CLASS=SUBTTL> 
```

**Comment by Mariusz89B** [comment]
@zuzia-dev Mi sie wydaje ze to wina znaku, bo jak sprawdzisz i porownasz w kodi\userdata\addon_data\plugin.video.viaplay\tmp\ pliki np z angielskim to plik sie nie rozni.

**Comment by hevet** [comment]
Spolszczona wersja 
[plugin.video.viaplay_2.1.3_polish.zip](https://github.com/mbebe/blomqvist/files/6944640/plugin.video.viaplay_2.1.3_polish.zip)

**Comment by zuzia-dev** [comment]
@hevet nadal to samo. Uruchamiam film, napisy wyświetlają się prawidłowo. Przesuwam do przodu, a one dalej lecą od miejsca zanim przesunęłam. Nie reagują na zmianę pozycji odtwarzania filmu.

**Comment by hevet** [comment]
@zuzia-dev ja tylko spolszczyłem dodatek, nie naprawiłem napisów :)

**Comment by zuzia-dev** [comment]
@hevet OK :)

Gdyby ktoś chciał przyłączyć się do testów, aktywacja usługi na 30 dni za darmo, może być karta debetowa VISA/Mastercard z 0 zł na koncie, byle obsługiwała 3D Secure.

**Comment by Mariusz89B** [comment]
@zuzia-dev napisalem do Emila moze nam w tym pomoze.

**Comment by zuzia-dev** [comment]
@Mariusz89B Raczej nie pomoże, pisali do niego ludzie z innych państw, bo Viaplay jest nie tylko w tych skandynawskich i bez odzewu. W sumie nie dziwię się, bo skąd ma wiedzieć, czy napisy w "dziwnych" językach działają prawidłowo. Wersja szwedzka pracuje prawidłowo, przesuwanie, wznawianie nie powoduje "rozjazdu" napisów - testowałam na wtyczce z repozytorium Kodi.

**Comment by Mariusz89B** [comment]
@zuzia-dev ja do niego pisalem juz wczesniej w innych sprawach, jestem szwedem wiec moze sie cos uda wykombinowac.

**Comment by zuzia-dev** [comment]
@Mariusz89B to zmienia postać rzeczy :)
Napisy muszą być, bo tam są i będą dodawane rożne niszowe produkcje skandynawskie.

**Comment by zuzia-dev** [comment]
@Mariusz89B @hevet sprawdzaliście pod Androidem? Mnie nie działa wtyka, jeszcze nie wiem czemu.

**Comment by hevet** [comment]
U mnie na drugim komputerze z Kodi 19.1 błąd dodatku, na Kodi 18.9 działa, Poza tym teraz z tego co widzę nie rozjeżdżają się napisy.

**Comment by zuzia-dev** [comment]
Kanały TV jednak działają. @hevet już pogrubiam się z tym wersjami. W repo kodiwpigulce.pl jest wersja nie do końca spolszczona i ją zainstalowałam. Zaraz sprawdzę Twoją.

**Comment by Mariusz89B** [comment]
Poprawki. :)

**plugin.video.viaplay-2.1.3_v2.zip**
https://drive.google.com/file/d/1eOaNuzX6_RLCOH7H4fnoHE4d9I9rUkBb/view?usp=sharing

**Comment by hevet** [comment]
@Mariusz89B u mnie na Kodi 19.1 wyskakuje błąd


`Error Type: <class 'resources.lib.viaplay.Viaplay.ViaplayError'>
                                                   Error Contents: b'PersistentLoginError'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.viaplay\resources\lib\addon.py", line 22, in run
                                                       plugin.run()
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.viaplay\resources\lib\addon.py", line 37, in root
                                                       pages = helper.vp.get_root_page()
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.viaplay\resources\lib\viaplay.py", line 202, in get_root_page
                                                       raise self.ViaplayError('MissingSessionCookieError')  # raise error if user is not logged in
                                                   resources.lib.viaplay.Viaplay.ViaplayError: 'MissingSessionCookieError'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.viaplay\default.py", line 5, in <module>
                                                       addon.run()
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.viaplay\resources\lib\addon.py", line 29, in run
                                                       if helper.authorize():
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.viaplay\resources\lib\kodihelper.py", line 101, in authorize
                                                       self.vp.validate_session()
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.viaplay\resources\lib\viaplay.py", line 141, in validate_session
                                                       self.make_request(url=url, method='get', params=params)
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.viaplay\resources\lib\viaplay.py", line 99, in make_request
                                                       return self.parse_response(req.content)
                                                     File "C:\Users\jacek\AppData\Roaming\Kodi\addons\plugin.video.viaplay\resources\lib\viaplay.py", line 106, in parse_response
                                                       raise self.ViaplayError(response['name'].encode('utf-8'))
                                                   resources.lib.viaplay.Viaplay.ViaplayError: b'PersistentLoginError'
                                                   -->End of Python script error report<--`

**Comment by Mariusz89B** [comment]
@hevet pobierz plik jeszcze raz, i sie na nowo zaloguj.

**Comment by hevet** [comment]
Niestety dalej błąd. Usunąłem dodatek i jego ustawienia ponowna instalacja i nadal błąd. Strona ustawiona na viaplay.pl

**Comment by zuzia-dev** [comment]
@Mariusz89B możesz wrzucać na githuba do jakiegoś katalogu test lub coś w tym guście? Ciężko się pobiera z google.

**Comment by Mariusz89B** [comment]
@hevet Poprawka:

**plugin.video.viaplay-2.1.3_v2.zip**
https://drive.google.com/file/d/1eJI_VfO_bfjgp2pBygbNX1ALv8tN007R/view?usp=sharing

**Comment by hevet** [comment]
@Mariusz89B działa na Kodi18.9 i Kodi19.1. Dzięki
Obecnie przynajmniej u mnie napisy działają poprawnie przy przewijaniu.

**Comment by Mariusz89B** [comment]
@zuzia-dev https://github.com/Mariusz89B/kodi-viaplay/tree/2.1.3

**Comment by zuzia-dev** [comment]
@Mariusz89B @hevet nie działa v3 na 18.9, rozjazd napisów przy przesuwaniu, czasami nie wczytują się. Dzieje się to losowo.

**Comment by Mariusz89B** [comment]
@zuzia-dev  Tak, wiem problem dalej istnieje. W ostatnich wersjach byly jedynie poprawki z szyforwaniem python 2 -> 3, co do napisow to jeszcze nic nie wykombinowalem.

**Comment by mbebe** [comment]
A tak w skrocie, to o co chodzi? ;-)

**Comment by Mariusz89B** [comment]
> A tak w skrocie, to o co chodzi? ;-)

Witaj po dluszym czasie! :D

```
Zla synchronizacja napisow sami:

def download_subtitles(self, suburls, language_to_download=None):
        """Download the SAMI subtitles, decode the HTML entities and save to temp directory.
        Return a list of the path to the downloaded subtitles."""
        paths = []
        lookup_table_replace = {}

        for url in suburls:
            lang_pattern = re.search(r'[_]([a-z]+)', str(url['href']))
            if lang_pattern:
                sub_lang = lang_pattern.group(1)
            else:
                sub_lang = 'unknown'
                self.log('Failed to identify subtitle language.')

            if sys.version_info[0] < 3:
                if sub_lang == 'pl':
                    lookup_table_replace = {
                        '&aogon;': 'ą', '&Aogon;': 'Ą',
                        '&cacute;': 'ć', '&Cacute;': 'Ć',
                        '&eogon;': 'ę', '&Eogon;': 'Ę',
                        '&lstrok;': 'ł', '&Lstrok;': 'Ł',
                        '&nacute;': 'ń', '&Nacute;': 'Ń',
                        '&sacute;': 'ś', '&Sacute;': 'Ś',
                        '&zacute;': 'ź', '&Zacute;': 'Ź',
                        '&zdot;': 'ż', '&Zdot;': 'Ż'
                    }

            if language_to_download and sub_lang not in language_to_download:
                continue
            else:
                sami = self.make_request(url=url['href'], method='get').decode('utf-8', 'ignore').strip()
                try:
                    for k, v in lookup_table_replace.items():
                        sami = sami.replace(k, v.decode('utf-8'))
                except:
                    pass

                htmlparser = HTMLParser.HTMLParser()
                subtitle = htmlparser.unescape(sami).encode('utf-8')
                path = os.path.join(self.tempdir, '{0}.sami'.format(sub_lang))
                with open(path, 'wb') as subfile:
                    subfile.write(subtitle)
                paths.append(path)

        return paths
```

**Comment by hevet** [comment]
To ja wtedy mam szczęście, bo u mnie napisy czy na Kodi 18.9, czy 19.1 działają poprawnie przy przewijaniu.

**Comment by zuzia-dev** [comment]
@mbebe odbierz maila. @hevet ja mam Kodi 18.9 na Linuksie. Włączam losowy film, jest czołówka, przesuwam i napisy są źle zsynchronizowane lub nie ma ich w ogóle.

**Comment by hevet** [comment]
Być może trafiłem akurat na serial gdzie napisy działają poprawnie,

**Comment by Mariusz89B** [comment]
@mbebe masz maila.

**Comment by zuzia-dev** [comment]
@Mariusz89B na jednej z poprzednich wersji już było dobrze, ale wróciło. Można zgłupieć od tego Viaplay :)

**Comment by Mariusz89B** [comment]
@zuzia-dev chyba sie wydawalo jedynie bo czasami dziala a czasami nie, tez mnie to oszukalo wczoraj.

**Comment by Mariusz89B** [comment]
@zuzia-dev @mbebe Chyba cos mam, teraz wydaje mi sie ze synchroinizacja dziala poprawnie:

https://drive.google.com/file/d/1BYPF7Fh0ixZynqnhIzygIzaefHo7-_lz/view?usp=sharing

**Comment by zuzia-dev** [comment]
@Mariusz89B nie rozumiem tego, ale nadal jest losowo, raz działa idealnie, a drugi raz już nie. Z całą pewnością nie jest to wina Kodi, bo sprawdzam w szwedzkiej wersji wtyczki i tam idealnie, przesuwanie, wznawianie nie psuje napisów.

**Comment by Mariusz89B** [comment]
Kilka poprawek:
https://github.com/Mariusz89B/kodi-viaplay/releases/tag/2.1.4

**Comment by zuzia-dev** [comment]
@Mariusz89B odbierz maila.

**Comment by zuzia-dev** [comment]
@Mariusz89B taki mam błąd w Kodi 18.9 przy tworzeniu listy m3u:

```
2021-08-09 11:30:14.591 T:140152116864768  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
2021-08-09 11:30:16.284 T:140152007071488   ERROR: NEWADDON Unknown Video Info Key "list_title"
2021-08-09 11:30:39.248 T:140152007071488   ERROR: Previous line repeats 31 times.
2021-08-09 11:30:39.248 T:140152007071488   ERROR: EXCEPTION: argument "buffer" for "write" must be a string or a bytearray
2021-08-09 11:30:39.259 T:140152007071488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument "buffer" for "write" must be a string or a bytearray
                                            Traceback (most recent call last):
                                              File "/home/zuzia/.kodi/addons/plugin.video.viaplay/default.py", line 5, in <module>
                                                addon.run()
                                              File "/home/zuzia/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 35, in run
                                                generate_m3u()
                                              File "/home/zuzia/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 102, in generate_m3u
                                                f.write(data)
                                            TypeError: argument "buffer" for "write" must be a string or a bytearray
                                            -->End of Python script error report<--

```

**Comment by Mariusz89B** [comment]
@zuzia-dev tak zapomnialem dodac wsparcie dla python 2 w tej funkcji, poprawie, jeszcze jest inny problem:
https://forum.kodiwpigulce.pl/showthread.php?tid=3804&pid=31993#pid31993

**Comment by zuzia-dev** [comment]
@Mariusz89B kilka drobnych błędów: https://forum.kodiwpigulce.pl/showthread.php?tid=3804&pid=33113#pid33113

**Comment by zuzia-dev** [comment]
@mbebe @Mariusz89B czy możecie dodać wersję litewską https://viaplay.lt/ ?

**Comment by Masterpicons** [comment]
Viaplay na Enigma2 soft Egami 10 PY3, KODI 19.3 . Po sekundzie obraz staje i ładuje się bufor, kilka sekund ok i znów to samo. W input stream adaptive jak zaznaczy się tylko video o obraz idzie bez problemu. Jak zaznaczę "wszystko" to zaczyna się problem.

**Comment by zuzia-dev** [comment]
@Masterpicons problem wygląda na podobny z tym tu: https://github.com/Mariusz89B/kodi-viaplay/issues/9#
W skrócie - należy odinstalować wtyczkę wraz z danymi, zainstalować ponownie i dokonać aktywacji przez https://viaplay.pl/activate a po restarcie Kodi powinno ruszyć.
PS. Jeśli chodzi o samą Enigmę ponoć niektórym Viaplay działa prawidłowo, ale nie mam jak tego zweryfikować, bo nie posiadam takiego urządzenia.
