### ISSUE TITLE
anime-odcinki.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mbebe/blomqvist#59]
@mbebe na pewno chetnych znajdziesz na ta wtyczke

**Comment by mbebe** [comment]
filmy online mrknow dziala ta wtyczka.

**Comment by xxcriticxx** [comment]
@mbebe chyba myslisz strony

**Comment by mbebe** [comment]
nie.


![1onl](https://user-images.githubusercontent.com/30195202/50253441-82035d80-03ea-11e9-975e-82fe3fae752e.jpg)
![2onl](https://user-images.githubusercontent.com/30195202/50253443-82035d80-03ea-11e9-8986-ce83494245b5.jpg)
![3onl](https://user-images.githubusercontent.com/30195202/50253444-82035d80-03ea-11e9-9ae4-08222ae97518.jpg)
![4onl](https://user-images.githubusercontent.com/30195202/50253440-816ac700-03ea-11e9-9c32-f6cf2f04df1f.jpg)

**Comment by xxcriticxx** [comment]
@mbebe to sie troche spóźniliśmy sorry

**Comment by mbebe** [comment]
Chyba tak, u niego tez jest te anime.

**Comment by wombad** [comment]
To moze wtyczka do shinden.pl - jednej z najwiekszych stron z anime.

**Comment by xxcriticxx** [comment]
@wombad https://forum.kodiwpigulce.pl/showthread.php?tid=1436

**Comment by mbebe** [comment]
Jest chyba robiona j.w.
