### ISSUE TITLE
Polsat Go

### ISSUE THREAD

**Issue by mtr81** [mbebe/blomqvist#591]
Ruszył serwis [POLSAT GO](https://polsatgo.pl), który ma zastąpić Iplę w segmencie darmowych materiałów video Grupy Polsat, w tym przekazów live niektórych programów TV (obecnie Polsat i TV4).  @mbebe czy jest szansa na wtyczkę do Kodi nowego serwisu?

**Comment by xxcriticxx** [comment]
trzeba poczekac do 1 września az skoncza zmieniac wszystko

Świat zmienia się, a my wraz z nim. Polsat Box Go to marka, która od 1 września zastąpi marki Ipla i Cyfrowy Polsat Go. Wychodząc naprzeciw oczekiwaniom klientów, Polsat Box Go zapewni szeroki wybór treści i sposobów dostępu do nich - każdy będzie mógł oglądać ulubione treści i kanały - sportowe, filmowe, serialowe czy bajki w przystępnej dla niego technologii.
Dzięki harmonizacji serwisów i aplikacji ulubione treści będą dostępne online i na żądanie na różnych urządzeniach – telewizorze, smartfonie, tablecie, komputerze czy laptopie, w dowolnym miejscu i o dowolnej porze, kiedy i jak się chce. Teraz Ty rządzisz. Wybierz swoje wszystko.

**Comment by Gall-78** [comment]
Polsat Go i Polsat Box Go to dwie różne usługi. Polsat GO już działa, zastąpi bezpłatną część IPLI.
