### ISSUE TITLE
filmowo.co

### ISSUE THREAD

**Issue by Seico** [mbebe/blomqvist#61]
Witam
W tej wtyczce nie startują żadne filmy , można prosić o zerknięcie i poprawę

**Comment by mbebe** [comment]
Zaktulizowane.

**Comment by wisiann** [comment]
W Chicago dalej nie dziala, :(

**Comment by mbebe** [comment]
Tzn.? Nie odpala linkow, nie wyswietla?

**Comment by wisiann** [comment]
Nie odpala linkow
