### ISSUE TITLE
PlayerPLmb tylko 720p

### ISSUE THREAD

**Issue by picarsite** [mbebe/blomqvist#618]
Cześć, we wtyczce PlayerPLmb obraz jest stremowany tylko w 720p. Tylko raz czy dwa razy widziałem że jest 1080p stremowany. W oryginalnej aplikacji na androida istnieje wybór między obrazami. 1080p jest tam do wyboru. Pozdrawiam.

----
Hi, in the PlayerPLmb plugin the video is only streaming in 720p. Only once or twice have I seen that it is 1080p streaming. In the original android app there is a choice between streams. 1080p is available to choose from there. Greetings.

**Comment by Mariusz89B** [comment]
Zapoznaj sie z wtyczka inputstream.adaptive, jakosc obrazu jest ustawiana wedlug bandwith.

**Comment by picarsite** [comment]
Dzięki za wskazówkę. Tam faktycznie idzie ustawić "Min. Bandwith (Bit/s)". Ustawiłem na 6000000 i teraz zawsze bierze steramy w FullHD.

**Comment by DeGH** [comment]
@picarsite na czym to sprawdzałeś?
Ustawiłem min. bandwith taki jak ty, a nadal mi puszcza tylko w 720p.

**Comment by Mariusz89B** [comment]
@DeGH W inputstream.adaptive ustaw wybor strumienia na reczny dla wszystkich strumieni.

**Comment by DeGH** [comment]
@Mariusz89B ustawiłem min. przepustowość na 10000000, zaznaczyłem nawet "zignoruj rozdzielczość ekranu".
Zarówno automatyczny strumień jak i ręczny odtwarza maksymalnie 720p.
Przy ręcznym najlepsza ścieżka to: h264, 1280x720, 2800000 bps
YouTube leci normalnie w 1080p (zaznaczone używanie inputstream).

**Comment by Mariusz89B** [comment]
Może akurat wybrany kanał nie jest dostępny w wyższej jakości.

**Comment by picarsite** [comment]
Tak ja mam ustawione w Kodi 19. I na TVN HD (i na innych) jest FullHD 1080.

![IMG_20211006_100759](https://user-images.githubusercontent.com/14298624/136165513-9a86934f-a237-4826-a2a1-6a34bb6daf7a.jpg)
![IMG_20211006_100904](https://user-images.githubusercontent.com/14298624/136165571-15412535-0f44-45f9-b94d-f9968503e7c6.jpg)
