### ISSUE TITLE
Wtyczki z napisami

### ISSUE THREAD

**Issue by krecik71** [mbebe/blomqvist#63]
Witam
Czy dało by  rade zrobić wtyczkę do tych stron.
https://gostream.site/
https://www1.subsmovies.nz/watch?movie=4799066

**Comment by mbebe** [comment]
w reduxie widze, ze ich nie ma

**Comment by krecik71** [comment]
ok dzięki za fatyge

**Comment by mbebe** [comment]
to inny gostream jest w placencie, subsmovies nie ma tez.

**Comment by xxcriticxx** [comment]
@krecik71 placenta is dead!
