### ISSUE TITLE
TVP VOD

### ISSUE THREAD

**Issue by DeGH** [mbebe/blomqvist#636]
Po wejściu w VOD > Seriale wyświetla tylko jedną kategorię "seriale bez ograniczeń", a w VOD > Programy jest pusto.

Kodi 19.1
Wersja dodatku 2.2.48

**Comment by Axis963** [comment]
U mnie na Kodi 18 to samo ://

**Comment by xxcriticxx** [comment]
tak to samo u mnie na kodi 19.1

**Comment by hevet** [comment]
Dzięki, działa 🙂

**Comment by papulus** [comment]
Mam jeszcze pytanie czy można by było naprawić opcje użycia serwerów proxy? Z góry dziękuję.

**Comment by BlazejosP** [comment]
Dzieki u mnie też działa po ostatnich poprawkach na rpi2
