### ISSUE TITLE
http://segos.es

### ISSUE THREAD

**Issue by sky0002** [mbebe/blomqvist#65]
Witam Panie Mbebe . Wiem że wtyczka działa  prawidłowo w Kodi 17, ale czy jest możliwość już ją dostosować do 18. Chodzi o to że każda zakładka kończy się na pierwszej stronie, nie ma "następna strona"
Bardzo lubię tą wtyczkę i dla tego  się odezwałem. I tak wiem że jest od Phantoma, ale wolę tą zieloną ma większe możliwości. Pozdrawiam i oczywiście to tyko sugestia jak nie to nie  :)

**Comment by kashkash18** [comment]
Mbebe przez jakiś czas będzie offline. Jak wróci to pewnie pochyli się na tym i innymi zgłoszeniami. Trzeba cierpliwie czekać .

**Comment by sky0002** [comment]
Dziękuję bardzo i Pozdrawiam i  SZACUN ZA PRACĘ naprawdę doceniam

**Comment by kendo999** [comment]
niesamowicie ogarnięty gość postawił bym mu browara

**Comment by kashkash18** [comment]
@kendo999 https://github.com/mbebe/blomqvist/issues/39

**Comment by kashkash18** [comment]
@sky0002 a jaką wersje wtyczki posiadasz ?? Ja teraz używam 3.6 na Kodi 18 RC 4 i normalnie pokazuje następne strony 
![s1](https://user-images.githubusercontent.com/22107339/51216065-645ee080-1923-11e9-8fdb-88b13a4d52b7.jpg)
![s2](https://user-images.githubusercontent.com/22107339/51216074-6c1e8500-1923-11e9-9e00-b2b7057d9474.jpg)
