### ISSUE TITLE
HDSeans - nie działa logowanie

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#650]
Jak w temacie - nie działa logowanie - dane wpisane prawidłowo. W logach pusto

**Comment by notoco** [comment]
Po poprawkach powyżej loguje, ale niestety nie działa odtwarzania.
na stronie działa - ale dodali konieczność weryfikacji maila
Nie działa połówka zagłębięń (np. bajki, wyświetl filmy - w sumie działa tylko ostatnio dodane - ale nic nie odtwarza...
W sumie - na stronie też coraz mniej odtwarza. Czyżby koniec legendy?

**Comment by Kantel88** [comment]
U mnie po weryfikacji i aktualizacji dalej nie loguje, błąd dodatku, wersja 18.9.

**Comment by mbebe** [comment]
Kolejna aktualizacja poszla.
Dodalem tez odtwarzanie embedsb, bo malo ktory link cda dziala.

**Comment by mbebe** [comment]
No wlasnie, jak robilem, to widzialem, ze nigdzie nie ma resolvera.
