### ISSUE TITLE
viaplay

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#653]
Coś mi się pochrzaniło z tą wtyczką, pomoże ktoś?
Seriale działają
Tutaj log:
https://paste.kodi.tv/eturerivul

**Comment by zuzia-dev** [comment]
Drodzy Panowie, da radę zrobić aktualizację? https://github.com/mbebe/blomqvist/issues/588#issuecomment-962642143

**Comment by zuzia-dev** [comment]
W litewskiej wersji jest obecnie Liga Mistrzów (czy jakoś tak) i Formuła 1. Ja sobie dodałam u siebie obsługę, ale sądzę, że warto dodać globalnie do wtyczki.

**Comment by Mariusz89B** [comment]
X2CP


2021-11-09 19:07 skrev zuzia-dev:

**Comment by Mariusz89B** [comment]
https://github.com/Mariusz89B/kodi-viaplay/releases/tag/2.2.3

**Comment by zuzia-dev** [comment]
@Mariusz89B Jest OK, dziękuję w swoim imieniu jak też Litwinów :)

**Comment by zuzia-dev** [comment]
@Mariusz89B jeśli możesz sprawdź proszę dzisiejszą transmisję Man City - Chelsea. Raz wybiera mi stream 720p, a raz 1090p, a powinno najwyższą jakość, takie mam ustawienia w Kodi.

**Comment by Mariusz89B** [comment]
@zuzia-dev Jak wygladaja twoje ustawienia we wtyczce inputstream.adaptive?

**Comment by zuzia-dev** [comment]
> @zuzia-dev Jak wygladaja twoje ustawienia we wtyczce inputstream.adaptive?

https://i.postimg.cc/TPFp28m1/input.jpg

**Comment by Mariusz89B** [comment]
Ustaw min. przepustowosc na ile sie da, i wybor streamu na reczne.

**Comment by zuzia-dev** [comment]
@Mariusz89B dzięki za sugestię, ręcznie wybieranie działa, widzę, że dla tej pozycji jest nieco inny profil jakościowy dla 720p.
