### ISSUE TITLE
problem na xboxie

### ISSUE THREAD

**Issue by ZgredekLCD** [mbebe/blomqvist#669]
Witam wszystkich, 
Co może być powodem, że nie działa mi żadna aplikacja z pakietu mbebe? Czy ktoś tez ma taki problem?
wersja kodi na Xbox to Matrix

**Comment by notoco** [comment]
Kodi 19.3 na Xbox jest wadliwe i większość nie działa. Jakieś próby rozwiązań masz tutaj, ale czy to działa ciężko powiedzieć: https://www.reddit.com/r/Addons4Kodi/comments/qijqrr/xbox_kodi_193_workaround/

**Comment by ZgredekLCD** [comment]
Dzięki wielkie, działa!
