### ISSUE TITLE
Nie działa większość dodatków

### ISSUE THREAD

**Issue by RobinsonPL** [mbebe/blomqvist#67]
Witam, przestaly działać dodatki na moich dwóch boxach na skinie Conluence, nie działa Segos alltube szukajka i inne, jest błąd dodatków i nie można zainstalować nowych. Chwilowa awaria? :)

**Comment by kashkash18** [comment]
Jaka masz wersję resolveurl ??

**Comment by RobinsonPL** [comment]
Powiem Ci że pytanie mnie przerosło ;) Jak to sprawdzić? PS. Koledze na buildzid CM z Polish Team Wizard nie chodzi alltube i cda x z kolei

**Comment by xulek** [comment]
zaktualizuj resolver, bo pewnie korzystasz z tego od cherry a tam był problem z jedną wersją

**Comment by kashkash18** [comment]
Wtyczki o których piszesz wymagają aktualizacji. A resztę powiedział Ci @xulek :)

**Comment by RobinsonPL** [comment]
Oki dzięki za szybką interwencje ;) poszukam tego resolver'a na kodi ;)

**Comment by stalker84** [comment]
witam wszystkich zaktualizowałem PolischTeam repo do wersji 0.0.9 i wiekszosc wtyczek spowrotem działa sprawdzałem to na kodi 17.6 i kodi 18 rc pozdrawiam

**Comment by krecik71** [comment]
Kol..@mbebe
Podziękowania za aktualizacje wtyczek.

**Comment by RobinsonPL** [comment]
Chłopaki ponownie jest problem, nie działa Segos w czystym Kodi , zmiana Resolver'a też nic nie daje, w drugim Boxie na CM też nie śmiga, aktualizacje nic nie dają, skończyły mi się pomysły....nawet czerwony Segos od Phantoma nie śmiga

**Comment by kashkash18** [comment]
A sprawdziłeś czy strona działa ??

**Comment by RobinsonPL** [comment]
O widzisz i jak za dotknięciem czarodziejskiej różdżki nagle strona o wtyczka ruszyła ;)

**Comment by kashkash18** [comment]
Przez cały dzień mają dziś problem z serwerem
