### ISSUE TITLE
TVizio - propozycja

### ISSUE THREAD

**Issue by zuzia-dev** [mbebe/blomqvist#675]
Jest promocja na miesiąc, gratis pełny pakiet TV: https://www.tvizio.bg/tvlist
Wystarczy zarejestrować konto, nie trzeba podpinać karty, tylko mail i hasło. Działa w Polsce bez VPN. 
@mbebe co sądzisz?

**Comment by mtr81** [comment]
Właściwie pisałem dla własnych potrzeb, ale skoro pytasz udostępniam ->
[plugin.video.tvizio.zip](https://github.com/mbebe/blomqvist/files/7592005/plugin.video.tvizio.zip)
Wtyczka wymaga wpisania danych do logowania w ustawieniach. Na liście uwzględniłem wszystkie kanały. Te które będą dostępne po wygaśnięciu miesięcznej promocji mają dopisek [FTA]. Plugin nie obsługuje opcji 'replay', która z tego co widziałem jest dostępna na niektórych stacjach. Jest możliwość wygenerowania listy M3U (z poziomu Settings).

**Comment by zuzia-dev** [comment]
@mtr81 dziękuję! Widzę, że wszyscy oprócz mnie migrowali na Kodi 19 :)
