### ISSUE TITLE
Filman.cc

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#677]
Od długiego czasu już jest spokój przynajmniej jak ma się "premium".
Moje pytanie dotyczy opcji wyszukiwania gdy ustawiam ostatnio dodane lista się nie zmienia i pozostają cały czas te same pozycję, zapewne to samo dotyczy pozostałych opcji np. filmy z lektorem. Czy można coś z tym zrobić czy nie da rady?
Logów nie podeślę bo nie ma błędów teoretycznie.
Pozdrawiam

**Comment by wojciech679** [comment]
Witam. Jak się nie ma premium to można ogladać normalnie? Dzisiaj zainstalowałem wtyczke filman.cc w KODI i wywala błąd podczas próbie włączenia filmu, każe sprawdzić log.

**Comment by rafalmar1981** [comment]
niewiem ja mam premium jak nie miałem to waliło błędami
teraz mam premium i na stronie wszystko gra np. opcje jak pisałem wcześniej ale na wtyczce już nie z tego co pamiętam coś podobnego było na cda ale w szukaniu

**Comment by Katapulta** [comment]
> Witam. Jak się nie ma premium to można ogladać normalnie? Dzisiaj zainstalowałem wtyczke filman.cc w KODI i wywala błąd podczas próbie włączenia filmu, każe sprawdzić log.

Filman działa bez premium bez żadnego problemu. Nie trzeba mieć żadnego premium. Jeśli mowa o kodi 19.

**Comment by rafik121** [comment]
filman nie działa w kodi 19.3 z premium i bez premium

**Comment by Katapulta** [comment]
> filman nie działa w kodi 19.3 z premium i bez premium

Filman.cc działa w kodi 19.3 bez premium bez najmniejszego problemu. Nie opowiadajcie bzdur , chyba ze wtyczki używać nei umiecie. 

[https://streamable.com/ae2wql](url)
