### ISSUE TITLE
PolsatGo - propozycja

### ISSUE THREAD

**Issue by kamillopl** [mbebe/blomqvist#679]
Proponuję zmienić sortowanie odcinków tak, aby zaczynały się od najnowszych. Dla przykładu wezmę serial "Pierwsza Miłość". Po wejściu w serial pierwszy z góry odcinek to 1424 (jakiś błąd?) a zaraz po nim mamy odcinek 1, 2, 3, ... Jestem pewien że zdecydowanie lepszą opcją byłoby odwrócenie tego, ponieważ nikt nie będzie przewijał stron aż do odcinka 3300+. Poza tym większość ludzi wchodzi po to aby zobaczyć najnowszy odcinek.

**Comment by DeGH** [comment]
Ależ sortowanie od najnowszego jest od dawna.
Poprawki były zgłoszone tutaj: https://github.com/mbebe/blomqvist_srcs/tree/main/srcs/plugin.video.polsatgo
i zostały przez @mbebe zaakceptowane.
Niestety przy dodawaniu do repo, dodał starą wersję czyli 1.7 a podmienił jedynie numeracje na 1.8
Było to zgłaszana, ale brak reakcji :P
Musisz ściągnąć ręcznie i podmienić pliki.

**Comment by praspp** [comment]
> Proponuję zmienić sortowanie odcinków tak, aby zaczynały się od najnowszych. Dla przykładu wezmę serial "Pierwsza Miłość". Po wejściu w serial pierwszy z góry odcinek to 1424 (jakiś błąd?) a zaraz po nim mamy odcinek 1, 2, 3, ... Jestem pewien że zdecydowanie lepszą opcją byłoby odwrócenie tego, ponieważ nikt nie będzie przewijał stron aż do odcinka 3300+. Poza tym większość ludzi wchodzi po to aby zobaczyć najnowszy odcinek.

@kamillopl Poniżej masz plugin.video.polsatgo-1.8 z podmienionym (poprawionym plikiem main.py). Sortowanie odcinków "od najnowszego" działa.
[plugin.video.polsatgo-1.8.zip](https://github.com/mbebe/blomqvist/files/7651324/plugin.video.polsatgo-1.8.zip)

**Comment by kamillopl** [comment]
@DeGH @praspp dzięki za informację. Akurat wczoraj wyszła wersja 1.9 i udało się ją zainstalować z poziomu aktualizacji wtyczki w Kodi. Teraz są sezony do wyboru i jest wygodniej.
