### ISSUE TITLE
Wtyczka z napisami.

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#68]
@krecik71  wtyczka do subsmoviez.nz do testow :-D
W ustawieniach wtyczki grupowanie seriali w sezony.
[plugin.video.subsmovies-0.1.zip](https://github.com/mbebe/blomqvist/files/2784368/plugin.video.subsmovies-0.1.zip)

**Comment by wisiann** [comment]
Wow!!
Super jakosc :)

**Comment by xxcriticxx** [comment]
This site can’t be reached subsmoviez.nz’s server IP address could not be found.

**Comment by krecik71** [comment]
jes jes jes !!!!!
Wielkie dzieki jak narazie działa zaj.....biście

**Comment by krecik71** [comment]
Kol@mbebe  jesteś wielki jeszcze raz  Dzięki

**Comment by mbebe** [comment]
@xxcriticxx  tu adres strony - https://www1.subsmovies.nz/home

**Comment by wisiann** [comment]
Tak myslalem ze cos zle nabazgral,

**Comment by xxcriticxx** [comment]
@mbebe przydalyby sie polskie scrapery do seren albo wtyczka do real-debrid api

@wisiann google mnie tam pokierowalo

**Comment by notoco** [comment]
@xxcriticxx do rd masz wtyczkę od kwp oraz nową - realizer https://github.com/aenemapy/aenemapyrepo

**Comment by xxcriticxx** [comment]
@notoco kwp tv packow nie gra

Drugiej nie testowałem

**Comment by kodiwpigulce** [comment]
@xxcriticxx niedługo będzie aktualizacja wtyczki ale mimo braku funkcji packów to jak na stronie RD dodasz jak zwykle to można oglądać bez problemu przez wtyczkę

**Comment by xxcriticxx** [comment]
@kodiwpigulce jak bendzie nowa wersja napewno przetestuje
