### ISSUE TITLE
Eurosport we wtyczce PlayerPLmb

### ISSUE THREAD

**Issue by praspp** [mbebe/blomqvist#682]
Nowe zgloszenie na prośbę @rysson 

Mam pakiet Eurosport w Player. Kanały live tv E1 i E2 są dostepne w menu wtyczki. We wtyczce brak jakichkolwiek transmisji online, jak i materiałów VOD z pkietu Eurosport. 
@rysson Dasz radę rozwiazać ten problem?

_Originally posted by @praspp in https://github.com/mbebe/blomqvist/issues/673#issuecomment-985401561_

**Comment by rysson** [comment]
@mm1992 załatwił tę sprawę. W dodatku dodał jeszcze generację m3u.
Można przetestować kandydata na [1.12](https://github.com/kodi-pl/blomqvist_srcs/releases/tag/playermb-1.11.13).

**Comment by Pawojc** [comment]
Witam. Czy byłaby możliwość aby dodać do ustawień wtyczki Player wybór domyślnej ścieżki audio?
Obecnie gdy uruchamiam stream z Eurosportu to ustawia się język QIS i trzeba ręcznie zmieniać na POL.
