### ISSUE TITLE
Pastebin Playvid

### ISSUE THREAD

**Issue by frijerz** [mbebe/blomqvist#69]
Zaciekawila mnie ta wtyczka, ale zupełnie nie mam pojęcia jak jęj używac. Problem chyba w tym, jak ma wygladac zapis w pastebin? Podalem linka, nazwe ale widze tylko krzaczki. Kto podpowie jak sie za to zabrac?

**Comment by xxcriticxx** [comment]
prosze przeczytaj https://github.com/mbebe/blomqvist/issues/40

**Comment by Arek76** [comment]
Musisz idpowiednio ulozyc format wpisu na pastebin , tu masz przyklad 
http://vshare.io/d/7y3zoo1 |IO: Ostatnia na Ziemii |2019|film|
link |  tytul | rok produkcji | film|I tylko by wtyczka wyswietlala prawidlowy plakat i opis musisz umiescic w Pastebin prawidlowy rok produkcji i identyczny tytul ktory widnieje na stronie Filmweb. 
Jak  dla mnie rewelacyjna wtyczka , Obsluguje rowniez formaty muzyczne typu mp3 .

**Comment by frijerz** [comment]
ZRobilem taki wpis:
http://siptv.5v.pl/udrop/play-8d0d63cc0c33313f-Dywizjon.303.Historia_prawdziwa.2018.PL.WEBRip.XviD-KiT.avi.ts|IO: Dywizjon 303. Historia prawdziwa|2018|Film polski
ustawilem jako Public, niestety efektem są "krzaczki": 

[http://prntscr.com/mbr49n](url)

**Comment by Arek76** [comment]
Nie dodajesz linku do playlisty typu ts to raz tylko do filmu , dwa to czy dywizjon 303 ma z przodu w tytule IO??:) To ze film ktory podalem wyzej ma taki tytul nie oznacza ze musisz go powielac . 
Jesli chodzi o ten film ktory chcesz wrzucic to tu masz wpis 
http://vshare.io/d/ape7duc |Dywizjon 303. Historia prawdziwa|2018|film|
i tak ma wygladac wpis kompletny . Oprocz tego jesli juz masz jakies smieci w liscie po prostu ja usun i zrob wszystko od nowa

**Comment by frijerz** [comment]
Juz jest prawie dobrze, tak to ma wyglądać?
http://prntscr.com/mbtda7

Jednak nadal brak info o filmie, mimo ze tytuly i rok prod. sa takie jak w Filmweb

**Comment by frijerz** [comment]
> prosze przeczytaj #40

Dziękuję, nie znalazłem wcześniej tego wątku. Wszystko gra!
