### ISSUE TITLE
Gaia wtyczka,

### ISSUE THREAD

**Issue by Wisian** [mbebe/blomqvist#695]
Co myslicie o tej wtyczke ?
Off topic wiem,ale moze warto zeby Mbebe ja spolszczyl?

**Comment by notoco** [comment]
oj... zaczynając od początku. (@mbebe pozwolisz że będę adwokatem"?)
1. Mbebe jest twórcą wtyczek - nie tłumaczem. Spolszczyć wtyczkę może każdy - to jeden plik. Więc szkoda czasu twórcy na tłumaczenie z en.
2. Co myślimy? Cóż - wtyczka porzucona w 2019 czy nawet w 2018 przez oryginalnych twórców, potem podrzucana do różnych repozytoriów celem podpicia ich "użyteczności", często ze zmienianym numerem wersji... co by naiwni instalowali myśląc że to nowsza i lepsza wersja. 
3.  Zależność od script.module.urlresolver - czyli od syfu który robi TVAddons - niby nic, ale raz po raz zupełnie przypadkiem wrzucają jako zależność a to program Indigo, a to zmieniają jakąś wersję zależności, a to w swoim repo mają koparkę bitcoinów. Jeśli można wejść w jakieś gówno w świecie kodi - to instalacja tego na własne życzenie jest taplaniem się w basenie z odchodami.
4. Wtyczka porzucona 3 lata temu, TvAddons... co jeszcze... A! Działa tylko z kodi 18 bo nie ma żadnego developwera który by potrafił ją poprawić. 
5. No i torrenty - korzysta z torentów. W sumie trzeba by regularnie sprawdzać jej kod, bo może korzystać z dowolnej rzeczy - niestety TVAdoons bałbym się cholernie - nie wiadomo gdzi epolecą twoje hasła, listy m3u.
6. Kiedyś niezła wtyczka - obecnie - syf.

**Comment by Wisian** [comment]
Dzieki za info,
Cos przeczuwalem ale chcialem sprawdzic u najlepszych
