### ISSUE TITLE
Hejo.tv - nie widzi premium

### ISSUE THREAD

**Issue by RobinsonPL** [mbebe/blomqvist#70]
Witam, zakupiłem sobie premium na hejo, zalogowałem się w Waszej wtyczce, pokazało że jest premium do maja ale gdy wchodzę w kanały lub film wyrzuca że potrzebne jest konto premium. Czyli jest ale jakby go nie było. Na stronce wszystko działa.

Dostałem info na FB że twórca nie ma premium by to naprawić, mogę udostępnić dane do premium żeby wtyczka została naprawiona :)

PS. Jeżeli wtyczka nie będzie działać czy jest inna alternatywą na hejo.tv, jakąś apka na androida lub kodi?

**Comment by mbebe** [comment]
zaktualizowalem wtyczke w repo.

**Comment by frutak** [comment]
zip z wersja 1.9 wtyczki jest skorumpowany - wtyczka sie nie updatuje do 1.9, recznie tez sie nie da zipa otworzyc. Mozesz przebudowac?

**Comment by mbebe** [comment]
zaktualizowane

**Comment by sierscstf** [comment]
Witam,
jest problem z wczytaniem premium poprzez wtyczkę na kodi 16.1.  Wersja kodi na TV Philips niestety nie do podniesienia.  Jest szansa na aktualizację wtyczki ?! pzdr

**Comment by notoco** [comment]
Podejrzewam że nie - ta wersja nie jest wspierana od hoho i kawałek. Dostosowanie wtyczki do 16.1 wymagałoby pewnie wielu przeróbek względem obecnie istniejącej wtyczki. Rozwiązanie - takie jak zawsze przy androidzie na tv - olać andka na tv i kupić boxa za 150 zł, postawić coreelec i zapomnieć o tej pomyłce jaką jest android w tv.

**Comment by sierscstf** [comment]
Pytani do autora jaki jest nakład pracy  związany z modyfikacją wtyczki ...premium jest widziane tylko nie widziane przy rozpoczęciu streemingu. Co do boxa, mam rasbery pi podłączonego do drugiego TV i wszystko działa na kodi 18, ale jest zapewne duże grupa ludzi posiadających TV z androidem, którzy nie chcą, nie potrafią lub mają organiczny wstręt do wydawania kasy na coś co już mają w pakiecie :)
