### ISSUE TITLE
Polsat GO

### ISSUE THREAD

**Issue by cyberfreak25** [mbebe/blomqvist#710]
Po aktualizacji wtyczki do najnowszej wersji, przy próbie odtworzenia byle jakiego wideo inputstream wywala takie błędy:

> 022-02-03 19:06:56.434 T:6093    ERROR <general>: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
>2022-02-03 19:06:56.434 T:6093    ERROR <general>: CCurlFile::Open failed with code 0 for https://b2c-www.redefine.pl/rpc/drm/:
>2022-02-03` 19:06:56.435 T:6093    ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
>2022-02-03 19:06:56.435 T:6093    ERROR <general>: AddOnLog: inputstream.adaptive: License update not successful (no keys)
>2022-02-03 19:06:56.484 T:6093    ERROR <general>: AddOnLog: inputstream.adaptive: Initialize failed (SingleSampleDecrypter)

Inne serwisy DRM działają bez zarzutu. Sprawdzałem na 3 ostatnich bibliotekach widevine na wszystkich ten sam rezultat i komunikat.

OS: Coreelec 19.4

**Comment by cyberfreak25** [comment]
Prawdopodobnie to wina serwerów polsatu. Bo teraz wszystko działa tak jak powinno.

**Comment by hevet** [comment]
Raczej tak, bo wczoraj miałem ten sam problem.
