### ISSUE TITLE
CANAL + - błąd wczytywania kanałów live

### ISSUE THREAD

**Issue by Brugliii** [mbebe/blomqvist#717]
Po otworzeniu kanału live wyświetla się informacja o błędzie.

**Comment by hevet** [comment]
U mnie odtwarzają się poprawnie. Jaka wersja Kodi, system?

**Comment by Brugliii** [comment]
19.3, system Android OS i Android 10

**Comment by Brugliii** [comment]
Dziękuję za pomoc. Wszystko działa ;)
