### ISSUE TITLE
Tvn24

### ISSUE THREAD

**Issue by Poikuj** [mbebe/blomqvist#718]
Jest możliwość dodania słuchania tvn24 audio? Jak na stronie się zaloguje to dopiero wtedy można słuchać na żywo tvn24 i tvn24 bis

**Comment by mbebe** [comment]
Mozna sprawdzic - trzeba sie logowac jak w player - zalogowac sie na stronie tvn24 i przepisac kod na stronie 
https://tvn24.pl/go/zaloguj-tv
We wtyczce - w live audio - bedzie to napisane.
[plugin.video.tvn24pl-1.7.zip](https://github.com/mbebe/blomqvist/files/8127164/plugin.video.tvn24pl-1.7.zip)

**Comment by Poikuj** [comment]
Dziala, dziekuje
