### ISSUE TITLE
plugin.video.canalplusvod

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#720]
Dzień dobry wszystkim pojawił mi się  w  tej wtyczce taki  błąd tz. problem jest taki...przy próbie włączenia kanału zakręci się kółko z napisem "proszę czekać", następnie znika i tak na każdym kanale - strona działa poprawnie,, nie wyświetla żadnego błędu(nie ma logów). czy dało by się coś zrobić?? Pozdrawiam

**Comment by hevet** [comment]
@rafalmar1981 jeżeli to na androidzie, to poszukaj w tematach poniżej

**Comment by rafalmar1981** [comment]
@hevet tak na androidzie poszukam . dziękuję
