### ISSUE TITLE
Polsat Go - Do Jednaj Bramki nie działa

### ISSUE THREAD

**Issue by mkaflowski** [mbebe/blomqvist#722]
Program Do Jednaj Bramki nie działa we wtyczce Polsat Go. Jest szansa na poprawkę?

**Comment by hevet** [comment]
Nie ma takiego programu Do Jednaj Branki.

Napisz prawidłowy tytuł

**Comment by mkaflowski** [comment]
> Nie ma takiego programu Do Jednaj Branki.
> 
> Napisz prawidłowy tytuł

https://polsatgo.pl/wideo/do-jednej-bramki/5024111/autoplay

**Comment by mtr81** [comment]
Po poniższej poprawce powinno już działać.
[plugin.video.polsatgo-1.92.zip](https://github.com/mbebe/blomqvist/files/8149773/plugin.video.polsatgo-1.92.zip)

**Comment by mkaflowski** [comment]
Działa! Super. Dziękuję bardzo. Powinno zostać dodane do repo. @mbebe
