### ISSUE TITLE
Polsat news

### ISSUE THREAD

**Issue by Poikuj** [mbebe/blomqvist#728]
Na stronie polsatnews.pl/wideo pojawil sie na zywo stream polsat news.
We wtyczce jest mozliwosc dodania?

Edit, teraz 
polsatnews.pl/wideo-lista

**Comment by hevet** [comment]
@mbebe a co z tym błędem?
https://github.com/mbebe/blomqvist/issues/701

**Comment by Poikuj** [comment]
> dodalem, jest w nowej wersji wtyczki.

Dziala, dziekuje
