### ISSUE TITLE
Ekstraklasa Live

### ISSUE THREAD

**Issue by rafciu27** [mbebe/blomqvist#73]
Jako, że niedługo zaczyna się sezon, może warto pogrzebać coś w wtyczce aby na VPNie pojawiały się źródła live. W tej chwili ani bez VPN ani z nie pojawiają się. Pozdrawiam ;)

**Comment by kashkash18** [comment]
Bo na dailmotion nie ma streamu Live

**Comment by kashkash18** [comment]
https://www.dailymotion.com/video/x2yclwl

**Comment by rafciu27** [comment]
Myślałem, że tam cały czas śmiga live. W zeszłym roku tak było. Czyli jest nadzieja, że będzie działać jak się pojawią?

**Comment by kashkash18** [comment]
Jeśli się pojawi to powinno działać , pytanie tylko czy przez Proxy czy VPN. Trzeba zejść na ruch Ekstraklasy

**Comment by rafciu27** [comment]
Live jest już, a źródeł nie ma ani na vpn'ie ani przez proxy.

**Comment by kashkash18** [comment]
Możesz podesłać link do tego Live ??

**Comment by kashkash18** [comment]
Info z oficjalnego kont Ekstraklasy "Dzień dobry, kanał dalej istnieje, od jutra zapraszamy na transmisje." Więc zobaczymy jutro jak to będzie wyglądać

**Comment by kashkash18** [comment]
Live odpalony , działa przez Proxy :) Aczkolwiek są jakieś problemy z obrazem. Zresztą nie tylko tutaj
