### ISSUE TITLE
New Source To Fix Goojara.to "supernova.to"

### ISSUE THREAD

**Issue by crak3rjack** [mbebe/blomqvist#733]
@mbebe Found source to replace goojara does open menus but link don't work and don't has cloudflare can you please take look & thanks!
**** Look at the image 
![go](https://user-images.githubusercontent.com/59179646/156943276-15e5d7d5-c421-46e9-b0f6-0292c455a081.jpg)
****
https://supernova.to/

**Comment by mbebe** [comment]
supernova has cloudflare protection, but i hope - goojara -  should work again .
[plugin.video.goojara-0.4.zip](https://github.com/mbebe/blomqvist/files/8257004/plugin.video.goojara-0.4.zip)

**Comment by crak3rjack** [comment]
@mbebe Sorry for bothering too much... really appreciate it, working fine again and super thanks m8!😊💪
