### ISSUE TITLE
USTV GO not working

### ISSUE THREAD

**Issue by crak3rjack** [mbebe/blomqvist#737]
Sorry to bother can't find the the post... can't remember who helped me out hopefully he can take a look something changed and it's not loading and thanks!🙏

**Comment by mtr81** [comment]
Hi, I checked a moment ago ( channels: ABC, Cinemax, NBC, Boomerang) and plugin works (maybe too slow, but works).

**Comment by crak3rjack** [comment]
@mtr81 OK I'll check again & thanks👍

**Comment by crak3rjack** [comment]
@mbebe You can close this!
