### ISSUE TITLE
informacja

### ISSUE THREAD

**Issue by leonzawodowiec12** [mbebe/blomqvist#74]
DarmowaTV:
internetowa.ws - usunąć jest osobna wtyczka
tele-wizja.ru - usunąć strona już nie istnieje 
tvmaniak.com - na razie nie działa 

filmowo.co - nie działają linki 
filman.cc - błąd dodatku nie działa również tv
serialnet.pl - błąd dodatku 
kresfilm.tv to teraz filmbit.ws można również dodać tv 

ekranik.tv można dodać

**Comment by Zorish** [comment]
filmbit.ws. Aby oglądać bez limitów wykup Konto Premium. No to już bez sensu.

**Comment by xxcriticxx** [comment]
ekranik.tv = Zarejestruj darmowe konto oraz wykup premium aby móc swobodnie oglądać materiały w naszym serwisie.

**Comment by adamibeata** [comment]
a czy jest jakaś wtyczka na tv która działa i tv też ?

**Comment by kashkash18** [comment]
Cierpliwości

**Comment by adamibeata** [comment]
może się doczekamy za rok może dwa :)

**Comment by kashkash18** [comment]
A może wcale ;)

**Comment by adamibeata** [comment]
co gdzie kiedy ?  dajcie linka  xd

**Comment by mbebe** [comment]
filmbit.ws - pojawila sie juz w repo. czasami darmowa tv nie chodzi.
https://github.com/mbebe/blomqvist/issues/76

**Comment by leonzawodowiec12** [comment]
@mbebe mam prośbę naprawisz filman.cc pisze błąd dodatku na stronie jak się zaloguje to jest dostęp do darmowej tv i jak byś umiał również zobaczyć serialnet.pl, filmowo.co i wtyczka darmowa tv

**Comment by kashkash18** [comment]
Co do serialenet i filmowo to wtyczki działają poprawnie , a to że streamy się nie odpalają to już wina serwisy. Stream umiera a serwis go nie aktualizuje.

**Comment by Zorish** [comment]
@mbebe czasami darmowa tv nie chodzi. Fakt. A tak dla informacji. VAVOO też korzysta z filmbit.ws.
To chyba długo nie pociągnie.

**Comment by leonzawodowiec12** [comment]
Działa wam wtyczka Sport365?

**Comment by mbebe** [comment]
darmowatv zaktualizowana - usuniety sport. te co dzialaja na stronie - dzialaja we wtyczce.

**Comment by leonzawodowiec12** [comment]
Dzięki dobra robota

**Comment by adamibeata** [comment]
może napisze tak działa bez zarzutów to >brak działającego streama< 
zobacz .ws działa   coś  tam działa a reszta tak więc to jedyne jest ok

**Comment by wisiann** [comment]
@adamibeata,
prosze zmien ton swoich postow z roszczeniowych na proszace,
mbebe i inni programisci robia to za free i niebardzo chce im sie to czytac jak ktos wymaga zeby bylo,i coraz mniej zagladaja,
jak chcesz zeby bylo right  now to se wykup platna tv i wymagaj,
troche to sie robi annoying, 

pozdro!

**Comment by Zorish** [comment]
@wisiann! Całkowicie cię popieram. Ale tak jest. Czasami trzeba komuś coś napisać aby się opamiętał.
Dzięki dla wszystkich PROGRAMISTÓW za wspanialą pracę!!!

**Comment by adamibeata** [comment]
Ja nie pisze hej ty to nie działa zrób coś z tym aby działało,   ja po prostu napisałem tylko że coś nie jest tak 
podziwiam informatyków i programistów co się tym zajmują bo mnie by się nie chciało i nie ważne czy było by to za darmochę czy za kasę.
Jak ktoś został urażony to sorki
