### ISSUE TITLE
KimCartoon addon errors when searching for cartoon

### ISSUE THREAD

**Issue by AceKiron** [mbebe/blomqvist#753]
![image](https://user-images.githubusercontent.com/39498818/162568905-7eb9487c-796d-42fc-a7e1-cb09ddaae836.png)

**Comment by mbebe** [comment]
Fixed.
New version - 0.3 in my repo.

**Comment by AceKiron** [comment]
Thanks, but now it doesn't work on my Xbox

**Comment by mbebe** [comment]
Any logs, any errors?

**Comment by AceKiron** [comment]
Just that one push notification as in the picture a few comments above. I don't think I can find logs anywhere on Xbox, lmk if I'm wrong tho.

**Comment by mbebe** [comment]
I can't see any problems with version 0.3.
Please install Kodi Logfile Uploader from Kodi repo (programs) and click upload.
You will get link for your log.

**Comment by AceKiron** [comment]
https://paste.kodi.tv/nocovevife

**Comment by AceKiron** [comment]
Seems like it could not find kernel32, nor the cffi module needed by Cryptodome.
What do you use Cryptodome for anyway? Last time I wrote a client to download videos from kimcartoon it didn't require any cryptography , and that client still works too.

**Comment by mbebe** [comment]
To get (to decrypt) 2 streams - beta, and probably p2p.

**Comment by AceKiron** [comment]
I don't think you need to. My client may only support the default stream service, which I thought was Beta, but it manages to download episodes and doesn't use any cryptography.
Maybe take a look for yourself? I've uploaded it to https://github.com/AceKiron/kim.

**Comment by mbebe** [comment]
luxubu is default stream and ends with 'fe' , others need crypto, so You have only "fe" in your code.

**Comment by mbebe** [comment]
I hope it will work.
[plugin.video.kimcartoon-0.4.zip](https://github.com/mbebe/blomqvist/files/8500313/plugin.video.kimcartoon-0.4.zip)

**Comment by AceKiron** [comment]
Could you upload that to this repo or some sort of testing repo?

**Comment by mbebe** [comment]
added to my repo.

**Comment by AceKiron** [comment]
Still the same: http://paste.kodi.tv/zihosihipa

**Comment by AceKiron** [comment]
Bump
