### ISSUE TITLE
kraisfilm->filmbitws

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#76]
Kraisfilm zmienil sie w filmbitws.
w repo wtyczka - kraisfilm 1.4.1

**Comment by wisiann** [comment]
Super!!

**Comment by wisiann** [comment]
Super!!

**Comment by wisiann** [comment]
#mbebe,zerknij jak bedziesz mial czas,


W zakladce seriale nie ma przechodzenia na nastepna strone,
Takze czy mozna zrobic zeby lista seriali byla alfabetycznie ustawiona ?

**Comment by kashkash18** [comment]
Nie ma przechodzenia na następna stronę bo zakladka pokazuje wszystkie 88 seriali jakie są dostępne w serwisie . 
A co do ustawienia alfabetycznego to jestem za :)

**Comment by wisiann** [comment]
No to kicha😜

**Comment by wisiann** [comment]
@mbebe,
chyba telewizja sie spsula ,
zuc okiem jak bedziesz mial chwile,
tylko na niej moge ogladac natgeowild,

dzieki!
