### ISSUE TITLE
Problem z odtwarzaniem materiałów w niektórych wtyczkach :-(

### ISSUE THREAD

**Issue by toso-7** [mbebe/blomqvist#760]
Witam.
Precyzując to we wtyczkach:
CDA.pl
hdseans.pl
Nie odpala filmów ze źródeł CDA. Kręci się cały czas kółko ładowania i próbując wyjść zawiesza się Kodi. I tak samo jest we wtyczkach:
govod.pl
ekranik.tv
hejo.tv
Kodi 19.3 zainstalowany na AndroidzieTV 11 na Nvidii SHIELD :-(
Będzie może jakaś poprawa tego? Czy w czym może tkwić ten błąd? :-( Przed aktualizacją Nvidii wszystko działało.
Pozdrawiam

**Comment by hevet** [comment]
Bez loga za dużo się nie wymyśli. Ale jak piszesz, że przed aktualizacją było dobrze to sam sobie odpowiedziałeś.

**Comment by toso-7** [comment]
Downgrade’a w Nvidii nie zrobię bo aktualizację zrobiła oficjalnie ze swojego kanału :-/ Więc Android 11 będzie teraz standardem. Gdzie znajdę loga do wglądu?

**Comment by hevet** [comment]
https://kodiwpigulce.pl/jak-zainstalowac-wtyczke-log-viewer-na-kodi-17-poradnik/

**Comment by notoco** [comment]
@hevet - tym to tylko podglądnie - ale do analizy nie wiele się zda - bo pokaże tylko zrzuty ekranu - nie wyśle całości - a tu zapewne o jakąś zależność chodzi.
- lepiej tą metodą: https://kodiwpigulce.pl/logi

**Comment by hevet** [comment]
@notoco masz rację, szukałem tego poradnika na stronie, a on jest przecież na forum 😉

**Comment by toso-7** [comment]
@hevet @notoco Dzięki wielkie. Jak tylko „pozyskam” :-D loga to go tu wtrynię.

**Comment by mbebe** [comment]
Na niektorych systemach nie odtwarza plikow MP4 - wlasnie m.in. cda
Tu byl watek - https://github.com/mbebe/blomqvist/issues/738 - trzeba do tych wtyczek pododawac proxy i przez niego puszczac odtwarzanie.

**Comment by mbebe** [comment]
Dalem te aktualizacja cdamb - po aktualizacji trzeba wylaczyc i wlaczyc kodi od nowa.

**Comment by toso-7** [comment]
Jak wrócę to spróbuję to ogarnąć o ile mnie to nie przerośnie 😅

**Comment by mbebe** [comment]
Sam nie zrobisz raczej. Musze wtyczki poaktualizowac.

**Comment by toso-7** [comment]
Pewnie jak mówisz. Szybciej to bym zapewne zapaści dostał, opalenizny koloru czerwonego na fejsie i niezbyt spokojnego podejścia do tego hehe

**Comment by toso-7** [comment]
@mbebe CDA działa 😃 Raz jeszcze dzięki, a co do wtyczki możliwe będzie w niedalekiej przyszłości po zalogowaniu się mieć dostęp do swoich materiałów? I miałeś rację, VOD w Beta TV też nie odpala jak w tych wtyczkach powyżej opisanych 😅 Nawet jak się uda co jest rzadkością to tylko na 10 sec. i znowu ładowanie 100% i się wiesza Kodi.

**Comment by mbebe** [comment]
@toso-7 Nie mam tego android 11, wiec jak mozesz to sprawdz te wersje z pliku:
Nie wiem, czy to zmienia, czy faktycznie trzeba proxy.
[plugin.video.darmowatv-1.8.12.zip](https://github.com/mbebe/blomqvist/files/8546574/plugin.video.darmowatv-1.8.12.zip)

**Comment by toso-7** [comment]
@mbebe Właśnie sprawdziłem. Też jest tak samo. Ładuje materiał i stoi. :-(
