### ISSUE TITLE
CDA - poprawka dla odtwarzania filmów spoza wtyczki

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#762]
@mbebe 
Było - ale znikło w ostatniej wersji:
https://github.com/mbebe/blomqvist_srcs/pull/3 coś musiało ci umknąć - zrób mały upgrade z tą poprawką :)

**Comment by mbebe** [comment]
Ok. poszlo.

**Comment by notoco** [comment]
Dzięki wielkie
:smile: :rocket:
