### ISSUE TITLE
canalplusonline

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#767]
Witam magów. Nie wiem co się stało ale każdy kanał zaczyna się ładować "proszę czekać", a następnie wyłącza się ładowanie i nic się nie dzieje. można to coś  z tym zrobić?? Pozdrawiam

**Comment by hevet** [comment]
U mnie kanały poprawnie się odtwarzają na androidzie z Kodi, czy Libreelec.

**Comment by rafalmar1981** [comment]
dzięki za info na kodi 18.9 na androidzie kilka wersji  sprawdzonych i nadal tak samo, przeinstalowałem zrestartowałem i tutaj log:
https://paste.kodi.tv/mavilusisa

**Comment by rafalmar1981** [comment]
@hevet generalnie to posypało mi się kilka wtyczek...upc i viaplay jeśli chodzi o viaplay to już wysłałem i log i zapytanie do @[Mariusz89B

**Comment by mtr81** [comment]
@rafalmar1981 przejdź na K19. Wsparcie dla K18 definitywnie się kończy.

**Comment by rafalmar1981** [comment]
@mtr81 na kodi 19  na win 7 to samo

**Comment by mtr81** [comment]
W takim razie wrzuć pełnego debug-loga z K19 dotyczącego wtyczki UPC (ale najnowszej ver.), bo piszesz, że z nią też masz jakiś problem

**Comment by rafalmar1981** [comment]
@mtr81 upc 2.5 na 19 chodzi elegancko....dziękuję za pomoc

**Comment by zuzia-dev** [comment]
> @hevet generalnie to posypało mi się kilka wtyczek...upc i viaplay jeśli chodzi o viaplay to już wysłałem i log i zapytanie do @[Mariusz89B

@rafalmar1981 tak się składa, że wtyczka Viaplay, czy Canal+ jak najbardziej działają pod Kodi 18.9. Zrób sobie nowy profil jeśli oczywiście samo odinstalowanie wtyczki (razem z danymi) i ponowne zainstalowanie nie pomoże.

**Comment by rafalmar1981** [comment]
@zuzia-dev sorenseb, że tak późno, zrobiłem jak napisałaś i bez efektu niestety, ale spoko i tak jest taki wybór we wtyczkach, że czymś zastąpie. Pozdrawiam.

**Comment by rafalmar1981** [comment]
Poprzenosili hejo.tv, ekranik.tv i internetowa.tv do tego vodmax.tv - lipa.

Ponowię zapytanie/pomoc nie odtwarzają mi się programy na androidzie w TV Smart kodi 19.3 wtyczka 1.7.5.3 przy instalacji  prosi o zainstalowanie  InputStream Helper i tyle. Przy próbie odtworzenia chwilę się pokręci i koniec vod działa bez problemu, podam może bardziej pomoże log:
https://paste.kodi.tv/xaxewokidu

Podam jak to wygląda na win7 bo tam działają programy i vod -  kodi 19.4 ale działa też na 19.3 wtyczka 1.7.5.3 przy instalacji  prosi o zainstalowanie InputStream Helper gdy chę włączyć  program to InputStream Adaptive, a następnie "This add-on relies on the proprietary decryption module widevin cdm for playback" zgadzam się i potem  komunikat o akceptację  "widevine cdm eula" oczywiście akceptuję i pięknie działa podam log:
https://paste.kodi.tv/atizomabib


Może dlatego nie działa na androidzie, że nie woła tego widevin?
Pozdrawiam. Proszę o rozwiązanie problemu jeżeli się da

**Comment by rafalmar1981** [comment]
Cały TV Smart zresetowany do ustawień fabrycznych czyste kodi na androidzie oraz win7. Pozdrawiam.

**Comment by hevet** [comment]
@rafalmar1981 włacz w opcjach wtyczki ""Sprawdzanie certyfikatu serwera licencji".

**Comment by rafalmar1981** [comment]
Niestety nie pomogło nic

**Comment by rafalmar1981** [comment]
teraz taki log:
https://paste.kodi.tv/oyehuzewup
vod działa

**Comment by mtr81** [comment]
Czy po zmianie ustawienia ''Sprawdzanie certyfikatu serwera licencji" zrestartowałeś Kodi?

**Comment by rafalmar1981** [comment]
tak oczywiście
i nmawet tv wyłączyłem na chwilę
