### ISSUE TITLE
Filman i vizjer.pl na MB filmy

### ISSUE THREAD

**Issue by rekin65** [mbebe/blomqvist#769]
Witam, wiadomo coś na temat tego, że od pewnego czasu vizjer.pl we wtyczce MB filmy, a dziś filman.cc padło? 
Android, Kodi 18.5 😉

**Comment by zaganiacz** [comment]
> Witam, wiadomo coś na temat tego, że od pewnego czasu vizjer.pl we wtyczce MB filmy, a dziś filman.cc padło? Android, Kodi 18.5 😉

Pomijajac jakąś zabytkową wersje kodi, to vizjer pl schowany za Cloudflare. Filman dziś też się schował za Cloudflare, co mozna łatwo sprawdzić otwierajac w przeglądarce.

**Comment by rekin65** [comment]
A wiadomo coś na temat kolejnego dodatku, który padł, a mianowicie ekranik.tv?
