### ISSUE TITLE
SopcastHD.tv

### ISSUE THREAD

**Issue by marsaad** [mbebe/blomqvist#77]
Panie mbebe i Mirki. Mam pytanie. Czy istnieje możliwość stworzenia wtyki Kodi dla w/w strony? Oczywiście z możliwością logowania. Dziękuję i pozdrawiam.

**Comment by Zorish** [comment]
Następny! Wtyczka do płatnej strony PREMIUM. A to chyba na twój prywatny użytek. A z przeglądarki nie można oglądać.. Oj mbebe ciężkie masz życie. Odpocznij trochę!

**Comment by kashkash18** [comment]
Gdyby ten serwis dawał jeszcze coś za free to można by pomyśleć , ale tak to nie ma sensu.

**Comment by wisiann** [comment]
A kto to jest "Mirki"

**Comment by sky0002** [comment]
Mirki to Panowie, Mirabelki to Panie. Slang z wykop.pl, było nawet w TVN. Gra o Milion. Pozdrawiam.

**Comment by wisiann** [comment]
Troche zacofany jestem ;) 
Ale @sopcastHD.tv w swietnej formie ,👍

**Comment by mbebe** [comment]
Zawsze na takich serwisach smieszy mnie taki fragment
'Wlasciciele nie biora odpowiedzialnosci za tresci udostepniane przez osoby trzecie.'
Wlasciciel nic nie robi tylko bierze kase :-)

**Comment by Zorish** [comment]
mbebe! BRAWO!!! Ale nie wszyscy to rozumieją. Za chwilę będą chcieć wtyczkę do konta na Allegro. HE,HE,HE.
