### ISSUE TITLE
segos - mała poprawka

### ISSUE THREAD

**Issue by notoco** [mbebe/blomqvist#78]
Mała poprawka dla zalogowanych - po kliknięciu w nazwę zalogowanego użytkownika przenosi do filmów które zostały dodane na stronie do obejrzenia:
http://segos.es/?page=needtosee

Poprawka:
```
def login():
    u = my_addon.getSetting('user')
    p = my_addon.getSetting('pass')
    logged=False
    if u and p:
        logged =  segos.getLogin(u,p)
    if logged:
		addDir('[B]Segos.es (%s)[/B]'%u,ex_link='http://segos.es/?page=needtosee', mode='ListMovies',page=1,iconImage='DefaultFolder.png',fanart=FANART)
    else:
        addLinkItem('[B]Zaloguj[/B]','',mode='settings',iconimage='',IsPlayable=False)
segos.COOKIEFILE=os.path.join(DATAPATH,'segos.cookie')
```

Warto by było tez jakoś rozegrać problem przy korzystaniu np z video favorites czy simple favorites - ustawienie skrótu do np. filmów ostatnio dodanych pokazuje czystą kartę (podejrzewam że obija się o cookie, ponieważ przejście w poziom wyżej powoduje już prawidłowe wyświetlenie zawarotści i zalogowanie) - skrót którego używam:
plugin://plugin.video.segos/?ex_link=http%3a%2f%2fsegos.es%2f%3fpage%3dbajki&foldername=Bajki&mode=ListMovies&page=1&trickToReload=$INFO[System.Time(hh:mm:ss)]
Na szybko sprawdziłem - jeśli cookie utraci ważnośc lub go nie ma - to wejście przez skrót bezpośrednio powoduje wyświetlenie pustej strony. Wejście przez wtyczkę już jest ok. tego problemu nie ma w alltube np.

**Comment by notoco** [comment]
Udało mi się to rozwiązać dla zalogowanego użytkownika - w pliku main.py dodałem funkcję:
```
def start():
    u = my_addon.getSetting('user')
    p = my_addon.getSetting('pass')
    logged=False
    if u and p:
        logged =  segos.getLogin(u,p)
```

a następnie odpowiednio zmieniłem 
```
elif mode[0] == 'ListMovies':
    start()
    ListMovies(ex_link+fsortv,page)
elif mode[0] == 'ListMoviesKat':
    start()
    ListMoviesKAT(ex_link,page)
elif mode[0] == 'ListSerials':
    start()
    ListSerials(ex_link+fsortv,page)
elif mode[0] == 'epizody':
    start()
```

Dla użytkownika który podał login i hasło w ustawieniach przechodzi bez problemu w podkatalogi wtyczki przez korzystanie z funkcji opartych na "Ulubione" w kodi czy przez dodatek simple favorites/simple video...

**Comment by notoco** [comment]
```
def start():
    u = my_addon.getSetting('user')
    p = my_addon.getSetting('pass')
    logged=False
    logged =  segos.getLogin(u,p)
```
Taka wersja działa zarówno dla zalogowanych jak i nie zalogowanych
Trzeba by to chyba inaczej na logikę rozegrać, ale ja za słaby jestem w pythonie... 
Wersja z naniesioną poprawką z postu inicjującego + zmiany powyżej
[main.py.txt](https://github.com/mbebe/blomqvist/files/2844237/main.py.txt)

**Comment by mbebe** [comment]
wrzucilem Twoje poprawki w wersji 4.0.1. 
Pozniej na to spokojnie popatrze.

**Comment by notoco** [comment]
Moja poprawka troszkę spowalnia wtyczkę w związku z czym... troszkę pomęczyłem i wymodziłem coś takiego...
segos.py - dodajemy funkcje start
```
def start():
    s.headers.update({'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0'})
    url ='http://segos.es/'
    check = s.get(url)
    cf = cloudflare3.Cloudflare(url,check)
    if cf.is_cloudflare:
        authUrl = cf.get_url()
        makeAuth = s.get(authUrl)
        result = s.get(url).content
        s.cookies.save()			
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0','Referer': 'http://segos.es/'}
        s.get(BASEURL)
```
Zaś w mainy.py wywalamy tę funkcję i zamaist wywołania start() wywołujemy segos.start()

I tu się moja znajomość pythona kończy.... Oczywiście trzeba to troszkę oczyścić i poprawić...
[main.py.txt](https://github.com/mbebe/blomqvist/files/2845901/main.py.txt)
[segos.py.txt](https://github.com/mbebe/blomqvist/files/2845903/segos.py.txt)
