### ISSUE TITLE
Polsat Box Go

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#787]
Dzień dobry mam taki problem...gdy wybieram "Kanały TV" wyświetlają mi się tylko trzy pozycję tj. POLSAT, TV 4, UKRAINA 24 HD, przy pakiecie "Polsat Box Go Sport". Dało by się coś zrobić z tym zrobić? nie występują błędy...kodi18.9 - android. Pozdrawiam

**Comment by hevet** [comment]
https://github.com/mbebe/blomqvist/issues/750#issuecomment-1101525771

**Comment by rafalmar1981** [comment]
@hevet dziękuję
