### ISSUE TITLE
Hejo tv 

### ISSUE THREAD

**Issue by Jzppstr** [mbebe/blomqvist#79]
Po aktualizacji kodi nie działa konto premium

**Comment by Jzppstr** [comment]
Jak byś dał radę coś z tym zrobić to wielkie dzieki

**Comment by mbebe** [comment]
tzn. co nie dziala, czego nie odtwarza, nie loguje?

**Comment by mbebe** [comment]
Na stronie nic nie startuje. :-)

**Comment by mbebe** [comment]
wtyczka zaktualizowana - wersja 1.9.3

**Comment by Huero23** [comment]
@mbebe Wtyczka Wizja.Tv nie ładuje żadnego kanału? Ostatnie 2 dni nie działa.
