### ISSUE TITLE
Polsat Box Go

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#790]
Dzień dobry mam taki problem...tz. nie wiem jaki. wyskakuje mi błąd na wersji plugin.video.pgobox-1.98.zip, gdy cofnę się do wersji plugin.video.pgobox-1.97.zip mam dostępne tylko dwa kanały(polsat i tv4). Taki jest log prz wejściu w kanały tv na wersji plugin.video.pgobox-1.98.zip m- kodi 18.9
https://paste.kodi.tv/uwuzawikor
Da się coś z tym zrobić. Pozdrawiam. I z góry dziękuję.

**Comment by rafalmar1981** [comment]
Ktoś ma jakiś pomysł?

**Comment by sky0002** [comment]
Przejdź na kodi 19. A jak się upierasz przy 18, to masz tu liste.m3u dla tej wtyczki. plugin.video.pgobox-1.97.zip 
https://forum.kodiwpigulce.pl/showthread.php?tid=4451&pid=39175#pid39175
Pozdrawiam

**Comment by rafalmar1981** [comment]
@sky0002 o wielkie dzięki....masz rację przejdę na tę 19 jednak. Pozdrawiam
