### ISSUE TITLE
wtyczka sportowaTV w repo

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#80]
- sport365live
- livelooker
- livetv.sx
- tvpsport
- canalesportivo
- cricstream

kodi 18
wymaga inputstreamadaptive dla tvp sport
mozna wlaczyc rtmp input
\o/

**Comment by kashkash18** [comment]
Oooo proszę , i działający Sport 365 :)
Super robota :)

**Comment by rafalmar1981** [comment]
kashkash18 mam pytanie, korzystam z kdi 17.6 krypto, jak włączam jakikolwiek mecz z sport365live non stop sie zacina nieda się ogladac obraz mija sie z dzwiekiem , moze jakiś pmysł

**Comment by kashkash18** [comment]
Jaka masz wersję wtyczki ??

**Comment by rafalmar1981** [comment]
tą która jest w repo mbebe sportowaTV, ale wcześniej też tak miałem, straciłem cierpliwość więc postanowiłem zapytać. Masz może jakąś wtyczke do telewizji korzystam z wizja tv od cherry, ale niema w jakości hd tylko sd

**Comment by kashkash18** [comment]
RTMP Input masz zainstalowany ??

**Comment by rafalmar1981** [comment]
no to juz magia dla mnie

**Comment by rafalmar1981** [comment]
dobra znalazłem w kodi i mam nieaktywny aktywuję go i dam znać jak działa

**Comment by kashkash18** [comment]
Dodatki -> Pobierz -> Wtyczki strumieniowe

**Comment by rafalmar1981** [comment]
jeżeli chodzi o  sport365live to ładnie leci jak na razie Napoli- Torino 
dzięki za odpowiedź i podpowiedź

**Comment by rafalmar1981** [comment]
kashkash18 witam ponownie  i jeszcze raz dziękuję za pomoc, ale jeszcze mam pytanie odnośnie tv oprócz wizja tv. znasz  może jakąś wtyczkę czy coś.

**Comment by kashkash18** [comment]
Nie znam , TV mam od operatora kablowego więc nie moja bajka . 
Po aktywacji RTMP sport365 chodzi lepiej ??

**Comment by rafalmar1981** [comment]
tak przynajmniej wczorajszy mecz

**Comment by xulek** [comment]
troche to mało prawdopodobne, że rtmp coś poprawiło. RTMP działa tylko dla streamów rtmp a tych jest tak mało w tej wtyczce o ile w ogóle jakieś są, że pewnie odczułeś efekt placebo :P

**Comment by kashkash18** [comment]
@xulek u mnie bez RTMP sport365 działa tak że nie da się tego oglądać. Po odpaleniu działa idealnie. A używam tego dodatku od bardzo dawna.

**Comment by xulek** [comment]
> @xulek u mnie bez RTMP sport365 działa tak że nie da się tego oglądać. Po odpaleniu działa idealnie. A używam tego dodatku od bardzo dawna.

to bardzo interesująca informacja, będę się musiał temu przyjrzeć

**Comment by kashkash18** [comment]
Dlatego użytkownikowi rafalmar1981 napisałem by odpalił RTMP i pomogło. Nie wiem jaki ma wpływ jedno na drugie ale działa :)

**Comment by xulek** [comment]
z kodu skryptu wynika, że wcale nie wpływa i obsługuje tylko protokoły "rtmp|rtmpt|rtmpe|rtmpte|rtmps" i tylko na nich zostaje wywoływana więc można to uznać za cud lub cudowny zbieg okoliczności :D No chyba, że odpalony stream był streamem rtmp :P

**Comment by kashkash18** [comment]
Więc może te streamy latają z RTMP 😉

**Comment by rafalmar1981** [comment]
o widzę że poruszyłem temat. Fajnie że koś oprócz twórcy wtyczki ktoś coś pomaga doradza, dziękuję wam. Pozdawiam

**Comment by rafciu27** [comment]
Działa komuś sport365live od Bugatasinho która jest dostępny w wtyczce?

**Comment by kashkash18** [comment]
U mnie działa normalnie , odpaliłem teraz BRA-PAN i lata

**Comment by kashkash18** [comment]
Masz zainstalowany f4mTester ??

**Comment by vijayk416** [comment]
Livelooker errors today with typertv hockey streams

**Comment by kisiel999** [comment]
Działają Wam wszystkie streamy ze Strims.World? Bo ja w niektóre nie mogę wejść i wyskakuje error: this link is not working.

**Comment by kashkash18** [comment]
Problem znany , przy kolejnej aktualizacji powinien zostać rozwiązany.

**Comment by kisiel999** [comment]
Dzięki za info, cierpliwie czekam. Dajcie znać, kiedy będzie aktualizacja.

**Comment by kisiel999** [comment]
Widzę, że poszedł update, ale nadal mi coś streamy ze flashem nie chcą działać. Po prostu nic się nie dzieje po włączeniu takiego streama (próbuje go wczytać, ale nawet nie mam komunikatu o błędzie).
Poza tym na jednym z dzisiejszych streamów z ATP Barcelona jest ochrona anty-DDoS.

**Comment by kashkash18** [comment]
Jeśli możesz to opisuje dokładnie jakie wydarzenie , nr streamu , i jak masz umiejętności to więcej informacji o nim :) 
To zdecydowanie pomoże gdyz nie zawsze jest czas na sprawdzenie wszystkiego .
Im więcej dokładnych informacji , tym łatwiej zrobić poprawki :)

**Comment by kisiel999** [comment]
ATP Barcelona, stream 2 i 3 nie działa w KODI http://strims.world/ATPBARCELONA.php stream trzeci na bank działa jak wchodzę przez stronę, nie wiem jak z drugim.

**Comment by kisiel999** [comment]
Sorki, że post pod postem, ale będzie we wtyczce https://www.laola1.tv ? Ktoś też pisał, aby dodać https://www.soccerstreams100.com/

**Comment by kisiel999** [comment]
![IMG_20190426_122232](https://user-images.githubusercontent.com/49946524/56801700-65ef4d00-681e-11e9-962f-3690edaf11c3.jpg)
Mam czasem takiego buga, jak wejdę w streamy z unblocked.is
