### ISSUE TITLE
Wtyczka Arte.tv PL - problem z odtwarzaniem

### ISSUE THREAD

**Issue by praspp** [mbebe/blomqvist#809]
addon id="plugin.video.artetvpl" name="Arte.tv PL" version="0.1" provider-name="mbebe"

nie odtwarza filmów z sekcji Strona główna-->ArteKino Classic

Log z próby odtworzenia 2 filmów w załączeniu. Wygląda na problem z obsługą certyfikatu serwera. Prośba o naprawę.
[kodi.log](https://github.com/mbebe/blomqvist/files/9168657/kodi.log)

**Comment by mtr81** [comment]
Spróbuj tej wersji:
[plugin.video.artetvpl.zip](https://github.com/mbebe/blomqvist/files/9169203/plugin.video.artetvpl.zip)

**Comment by praspp** [comment]
Sprawdziłem. Odtwarzenie wymienionych materiałów w tej wersji wtyczki działa prawidłowo. Dziękuję. 
Mógłbyś jeszcze spojrzeć na wybór napisów przy rozpoczynaniu odtwarzania? Pomimo wybrania konkretnego języka napisów z listy, po kliknięciu na wybrany material i zatwierdzeniu wyboru napisy nie są wyświetlane. Trzeba je i tak później włączyć podczas odtwarzania.

**Comment by mtr81** [comment]
Co do automatycznej aktywacji napisów, to wymagana jest następująca zależność - wybrany język napisów powinien być zbieżny z wskazanym w ustawieniach Kodi: Settings->Player->Language->Preferred sublitle language. Przykładowo jeśli preferowany język ustawisz na polski i wybierzesz stream z polskimi napisami ruszą one automatycznie, ale przy wyborze pozostałych wersji napisy będziesz je musiał włączyć ręcznie.

**Comment by praspp** [comment]
Mam takie ustawienia jak opisałeś, ale to nie działa. Wybór języka napisów przy odpaleniu materiału powoduje tylko załadowanie tych (i tylko tych) wybranych do odtwarzania, ale nie włącza ich widoczności.

**Comment by mtr81** [comment]
Hmm dziwne u mnie to działa. Dla pewności wrzucam screeny ustawień, przy których polskie napisy powinny uruchamiać się automatycznie [przy wyborze streamu oznaczonego jako "Polski (napisy)]":

![sub1](https://user-images.githubusercontent.com/86961563/181059653-b30a5030-ba4f-4989-8315-927b8e8b7a62.png)
![sub2](https://user-images.githubusercontent.com/86961563/181059671-4235cb2b-f605-459a-8a41-f68f8edfa7e6.png)

**Comment by praspp** [comment]
Mam identyczne ustawienia. Żeby po wybraniu "Polski (napisy)" pokazały się od razu napisy muszę mieć włączoną opcję "Pokazuj napisy" w ustawieniach napisów jako domyślne dla wszystkich mediów.

![firetv_2022-07-27_02_54_33](https://user-images.githubusercontent.com/62591068/181137607-0336c905-6f7b-440a-ac17-3bdcf73aefc8.jpg)

Chciałbym, żeby wybranie opcji "Polski (napisy)" automatyczie rozpoczęło wyświetlanie napisów tylko dla materiału oglądanego aktualnie bez włączonej opcję "Pokazuj napisy" jako domyślnej dla wszystkich mediów. Ale to już kwestia przebudowy wtyczki i dodania nowej funkcjonalności.

**Comment by mtr81** [comment]
W wersji poniżej zaimplementowałem wyodrębnienie z listy M3U pliku z napisami i podanie go do procesowania za pomocą 'setSubtitles', co powinno rozwiązać sprawę. Prośba o weryfikację na większej ilości materiałów (sprawdzałem zasadniczo tylko na filmach na ścieżkach innych niż polskie)
[plugin.video.artetvpl_subt.zip](https://github.com/mbebe/blomqvist/files/9194596/plugin.video.artetvpl_subt.zip)

**Comment by praspp** [comment]
Napisy są wyodrębniane i dodawane do listy napisów jako dodatkowe (zewnętrzne), ale wtyczka ich nie włącza automatycznie. Trzeba je aktywować ręcznie w menu napisów.

![firetv_2022-07-28_11_17_11](https://user-images.githubusercontent.com/62591068/181471070-098b36ce-6d64-49d6-b441-89d471f4f68a.jpg)

![firetv_2022-07-28_11_18_35](https://user-images.githubusercontent.com/62591068/181471169-e3a6a1f2-242b-48d2-9e10-3a1eeec9ac86.jpg)

**Comment by mtr81** [comment]
Ja drążę temat do oporu :-) 
[plugin.video.artetvpl.zip](https://github.com/mbebe/blomqvist/files/9214309/plugin.video.artetvpl.zip)

**Comment by praspp** [comment]
Teraz jest perfekt. Dziękuję. Może puścisz commit z tymi poprawkami do blomqvist_srcs? Użytkownicy dostaliby aktualizację z repo. W przyszłości.😉
