### ISSUE TITLE
MeczReplay

### ISSUE THREAD

**Issue by rafciu27** [mbebe/blomqvist#81]
Witam. Wtyczka MeczReplay nie otwiera źródeł. Przydałby się jakiś fixik. Pozdrawiam

**Comment by kashkash18** [comment]
Masz na myśli MeczReplay który jest w wtyczce Ekstraklasa ??

**Comment by rafciu27** [comment]
Uaaa ale wtopa, mbebe nie jest autorem tej wtyczki. Pomyliłem się bo było w jego repo. Usuwam temat :)

**Comment by kashkash18** [comment]
Dobrze się tam komponuje ;)
