### ISSUE TITLE
Intel Atom - PlayerPLmb

### ISSUE THREAD

**Issue by martiinezz** [mbebe/blomqvist#822]
Cześć,
Kodi 18.9 - wtyczka się zainstalowała - logowanie działa - ale jakikolwiek materiał uruchamiam - mam głos - ale obraz to pixeloza.
Zakładam, że to nie problem wtyczki, ale wolę zapytać :)

**Comment by hevet** [comment]
Wyłącz w ustawieniach Kodi akcelerację sprzętową.

**Comment by martiinezz** [comment]
Po wyłączeniu akceleracji mam tylko fotkę z odcinka i dźwięk - podciągnąłem Kodi do 19.3 - jest lepiej - piksele przy większym ruchu, ale da się oglądać :) dzięki zamykam
