### ISSUE TITLE
Wizja.Tv Premium- Nie Działa.

### ISSUE THREAD

**Issue by Huero23** [mbebe/blomqvist#83]
Nie ładuje żadnego kanału od dwóch dni.

**Comment by kashkash18** [comment]
Mbebe nie jest twórcą wtyczki Wizja TV

**Comment by Huero23** [comment]
@kashkash18 Czy wiesz kto jest? Czy Cherry TV ? Dzięki...

**Comment by kashkash18** [comment]
Nie mam pojęcia jaka masz wtyczkę

**Comment by Huero23** [comment]
@kashkash18 Mam builda z PolishTeam to jest chyba wtyczka CherryTv... Nie jestem pewny.

**Comment by notoco** [comment]
Wtyczka wizja tv nie jest autorstwa cherry. Autorem jest kodiver. 
https://kodiwpigulce.pl/jak-zainstalowac-wtyczke-wizjatv-od-kodiver-na-kodi-17-poradnik/

**Comment by Huero23** [comment]
@notoco Chyba ktoś inny ją przejął? Widzę ją Cherry TV Zip ale nie pisze od kogo...

**Comment by notoco** [comment]
Nie możesz jej widzieć w repozytorium cherry bo jej nie ma i nie było: https://github.com/CherryKodi/CHERRY
To że jest w buildzie nie oznacza że jest ich autorstwa. Dostałeś linka do poradnika instalacji w którym mowa jest o autorze wtyczki.

**Comment by sky0002** [comment]
plugin.video.wizjatv-2018.08.15.0.zip : https://www106.zippyshare.com/v/00t0aZng/file.html
Wyłącz RTMP Input jak masz włączoną, wtyczka będzie Ci chodzić stabilniej. Pozdrawiam.

**Comment by stalker84** [comment]
serwus wszystkim pytanie do sky0002 twoja rada pomogła i wtyczki wizji tv chodza stabilniej ale po dezaktywacji RTMP imput po kilku minutach aktywuje się sama masz jakas rade na to? pozdro.

**Comment by sky0002** [comment]
Witaj. Więc ja odinstaluj. Masz pewnie zainstalowaną także wtyczkę sportowaTV i ona wymusza aktywację RTMP imput. Jak odinstalujesz a potem będziesz uruchamiał sportowaTV to się zapyta czy z powrotem zainstalować RTMP imput. Zatwierdzasz nie a wtyczka i tak się uruchomi i  będzie prawidłowo działać. Pozdrawiam.

**Comment by stalker84** [comment]
serwus dzięki za rade sky0002 nie mogę jej odinstalować ale po dezaktywacji wtyczki sportowaTV RTMP imput nie aktywuje się sam jesteś wielki! pozdro
