### ISSUE TITLE
CDA.pl+CDA TV

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#837]
Witam szanowne grono coś się popsuło we wtyczce nie da się zalogować bez żadnego błędu tylko w kółko zaloguj się...czy jest szansa na naprawienie. pozdrawiam serdecznie.

**Comment by praspp** [comment]
Jako Login użyj nazwy użytkownika (aliasu), a nie adresu email. Taki sposób logowania działa u mnie bez problemu.

**Comment by Cinek77** [comment]
Z ciekawości sprawdziłem i loguje się bez problemu przez email jak i nazwę użytkownika (alias).
Kodi 19.3 System Windows/Android. Wersja wtyczki 1.8.
Może dane logowanie nieprawidłowo wpisane lub nie aktywne.

**Comment by rafalmar1981** [comment]
@Cinek77 na kodi 19.4 na win 7 loguje się bez problemu, a na androidzie kodi19.3  już lipa, przejdę na kodi 19.4 w androidzie i zobaczę, to dam znać. Pozdrawiam i dziękuję za pomoc
