### ISSUE TITLE
wtyczka Vectra - App Check token is required

### ISSUE THREAD

**Issue by isillo** [mbebe/blomqvist#838]
Od paru dni nie dziala wtyczka Vectra. Nie mozna sie zalogowac, od razu jest komunikat jak w temacie. Odinstalowanie i zainstalowanie od nowa nie pomaga.

**Comment by isillo** [comment]
To prawdopodobnie dlatego, ze na stronce dolozyli teraz wyskakujace jedno nowe okno chwile po zalogowaniu: 
![ss_0001_2022-09-18-1003](https://user-images.githubusercontent.com/77502952/190894421-9dc568a8-46ac-4ead-b15b-3f0159447ccc.png)

**Comment by isillo** [comment]
jest jakas wersja 0.7 wtyczki w produkcji naprawiajaca ten blad?

**Comment by zuzia-dev** [comment]
@mbebe  @isillo Nie chodzi o to okienko logowania, zresztą nie u wszystkich ono wyskakuje. Token zmienia się dla każdej sesji logowania.

**Comment by isillo** [comment]
Zatem jest jakis sposob by obejsc to?

**Comment by mbebe** [comment]
Zgadza sie. Zmiana na stronie.
Sprobuj te wersje >>> 
[plugin.video.vectrapl-0.7.zip](https://github.com/mbebe/blomqvist/files/9641768/plugin.video.vectrapl-0.7.zip)
Moze byc potrzeba wymiany(usuniecia i dodania) nowego urzadzenia.

**Comment by zuzia-dev** [comment]
Wersja 0.7 jest OK. Sprawdziłam specjalnie dla użytkowników na dwóch kontach Vectry i działa bez zarzutu. W obydwu przypadkach wymagane było dodanie nowego urządzenia.

**Comment by isillo** [comment]
0.7 dziala elegancko
