### ISSUE TITLE
Player, Polsat go error

### ISSUE THREAD

**Issue by PeQuS** [mbebe/blomqvist#840]
Cześć, mam problem z uruchomieniem playera na kodi na android TV box. Mam pakiet z reklamami. Loguje się na konto, ale przy uruchamianiu jakiejkolwiek pozycji pojawia mi się komunikat "Nieudane odtwarzanie pozycji...". Załączam log. Może ktoś jest w stanie pomóc? Z góry dzięki.Podobna rzecz jest na Polsat go.
[kodi.log](https://github.com/mbebe/blomqvist/files/9639623/kodi.log)

**Comment by mtr81** [comment]
Wygląda na jakiś problem z pluginem InputStream. Spróbuj przeinstalować tą wtyczkę. Znajdziesz ją w sekcji Program add-ons->inputStream Helper.
Sprawdź też sekcję My Add-Ons -> VideoPlayer Inputstream. Powinieneś zobaczyć coś takiego:
![ISA](https://user-images.githubusercontent.com/86961563/192121201-a564d5c7-e642-47ff-97dc-12c62ab4716b.png)

**Comment by PeQuS** [comment]
Dzięki za odpowiedź. Przeinstalowałem tą wtyczkę i dodatkowo odinstalowałem wtyczkę InputStream Helper. Zainstalowałem wszystko ponownie od zera. Niestety efekt ten sam. Co ciekawe na laptopie z windowsem 10 wideo z playera się uruchamia.

**Comment by mtr81** [comment]
Z logu wynika, że jest jakiś problem na etapie pobierania licencji Videwine DRM. Czy oficjalne apki playera i Polsatu GO działają na tym urządzeniu poprawnie? Jak możesz wrzuć log Kodi po uruchomieniu wtyczki Polsat GO, żeby zweryfikować, że to jest ten sam problem co z playerem. Dodatkowo sprawdź zawartość plików z rozszerzeniami challenge, init i postdata, które znajdziesz w katalogu .kodi/cdm/widevine

**Comment by PeQuS** [comment]
Oficjalna apka Polsat go działa na tym urządzeniu. Wideo się odpala bez problemu. Playera nie jestem w stanie sprawdzić - brak apki do ściągnięcia. Wrzucam log z playerem i Polsatem z kodi. Czy we wskazanych plikach powinienem zwrócić uwagę na coś konkretnego?
[kodi.log](https://github.com/mbebe/blomqvist/files/9641470/kodi.log)

**Comment by mtr81** [comment]
To samo, co przy player.pl - problem z pobraniem licencji. W pliku o rozszerzeniu .response powinieneś mieć rodzaj błędu.

**Comment by PeQuS** [comment]
Poniżej zawartość pliku .response 

{"id":1,"jsonrpc":"2.0","result":{"accessPolicy":{"id":"246"},"id":"858342103","object":{"client_info":[],"content_owner":"cyfrowypolsat","content_provider":"cyfrowypolsat","internal_status":127,"service_version_info":{"license_sdk_version":"17.1.0 Built on Jun 1 2022 21:32:31 (1654144333)","license_service_version":"widevine_license_wls_20220601_212461-RC00"},"status":"ACCESS_DENIED","supported_tracks":[]},"reporting":{"redevents":{"sellModel":"AVOD"}},"validFrom":"2022-09-25T13:45:10Z","validTo":"2022-09-26T13:45:10Z"}}

**Comment by mtr81** [comment]
Sprawdź jeszcze jedną rzecz - dodaj do listy M3U w IPTV Simple Client następujący materiał zabezpieczony DRM. Używasz jakiegoś proxy czy VPN-u z tym Kodi?
'
#EXTINF:-1,TEST
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://play.tv3.lv/api/products/3188946/drm/widevine?platform=BROWSER&type=MOVIE&tenant=AVOD_LV|Content-Type=|R{SSM}|
#KODIPROP:inputstream.adaptive.manifest_type=mpd
https://cdnlb.tvplayhome.lt/vod/eds/go3_svod/20210802T1001/80080244/_/GO3_SVOD_DASH/80080244.mpd`
`

**Comment by aprof28** [comment]
Tylko podpowiem . Polsat Go poza granicami PL wymaga VPN inaczej nie odpali🤔😏👍

**Comment by PeQuS** [comment]
Nie używam VPN ani proxy. Mieszkam w PL. Nie wiem czy dobrze to ustawiłem, ale próba odpalenia listy m3u skutkuje podobnym komunikatem. Szczegóły w logach. 
[kodi.log](https://github.com/mbebe/blomqvist/files/9649687/kodi.log)

**Comment by mtr81** [comment]
OK. Jeśli jesteś zdeterminowany postaram się pomóc, ale może to zająć trochę czasu... Przede wszystkim prośba o przeinstalowanie całego Kodi tj. wykonanie deinstalacji starej wersji i wgranie Kodi 19.4. Następnie dodaj jedynie Inputstream Helper i jedną z wtyczek, z którymi masz problem. Póki co nie wyrywaj żadnych innych addons-ów.

**Comment by PeQuS** [comment]
Usunąłem wszystko. Zainstalowałem tylko to co pisałeś plus playera. Nic innego. Efekt ten sam.
[kodi.log](https://github.com/mbebe/blomqvist/files/9691190/kodi.log)

**Comment by mtr81** [comment]
Wygeneruj pełny debug log. Ustawienia->System->Logging->Enable debug logging

**Comment by PeQuS** [comment]
Log w załączeniu.
[kodi.log](https://github.com/mbebe/blomqvist/files/9691984/kodi.log)

**Comment by mtr81** [comment]
Nie widać nagłówków, które lecą w zapytaniach. Zaznacz jeszcze w opcjach logu "Enable component-specific logging" oraz w oknie dialogowym, które uaktywni się po kliknięciu "Specify component-specific logging" wybierz "verbose logging for the libCURL library".

**Comment by PeQuS** [comment]
Zrobione. Log w załączeniu.
[kodi.log](https://github.com/mbebe/blomqvist/files/9692901/kodi.log)

**Comment by mtr81** [comment]
To jeszcze jedna prośba. żebym mógł porównać logi z odtwarzania materiału, do którego mam dostęp. Doinstaluj IPTV Simple Client i dodaj na listę M3U poniższy stream. Odpal go i wrzuć pełny debug-log. Sorry, że tak męczę ale to wysypywanie się Kodi na etapie pobierania licencji jest nietypowe.
```
#EXTINF:-1,TEST
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://play.tv3.lv/api/products/3188946/drm/widevine?platform=BROWSER&type=MOVIE&tenant=AVOD_LV|Content-Type=|R{SSM}|
#KODIPROP:inputstream.adaptive.manifest_type=mpd
https://cdnlb.tvplayhome.lt/vod/eds/go3_svod/20210802T1001/80080244/_/GO3_SVOD_DASH/80080244.mpd
```

**Comment by Cinek77** [comment]
Hejka
Sprawdzałem wcześniej w Kodi 19.3 Polsat Go i Player na  boxie bez certyfikatu (X88King), na telewizorze z Android TV(TCL) i na kompie z windows. 
Wtyczki działają poprawnie i Telewizja i materiały video.

Teraz sprawdziłem robiąć czystą instalacje Kodi ze sklepu google (Zainstalowało Kodi 19.3) na  boxie bez certyfikatu (X88King).
Na wtyczce Polsat Go działa poprawnie.
Zainstalowałem Kodi 19.4 i też wszystko dobrze.
Może to wina boxa ?

Jaki to box? 
Moja sugestia to wywalić cały folder Kodi z Android/Data/org.xbmc.kodi
Odinstalować Kodi i zainstalować na nowo Kodi i wtyczki.

**Comment by PeQuS** [comment]
Logi w załączeniu. Mam boxa mecool m8s pro l. Jak odinstalowałem kodi to katalogu nie było. Mogę jeszcze raz spróbować jak coś i najpierw usunąć katalog a potem odinstalować.
[kodi.log](https://github.com/mbebe/blomqvist/files/9698593/kodi.log)

**Comment by aprof28** [comment]
Tv box xgody t95z plus  działa perfekt android 7.0. Oraz tv box t95 plus android 11.0 też działa należy wybrać miejsce wygenerowanej listy np.download lub inny plik. Na tym drugim był mały problem z logowaniem bez vpn ale po włączeniu vpn jestem zalogowany i mam listę.

**Comment by mtr81** [comment]
@aprof28  problem dotyczy prawdopodobnie certyfikacji DRM.
@PeQuS spróbuj zrobić to co sugeruje się w tym miejscu ->[https://forum.kodiwpigulce.pl/showthread.php?tid=1373&pid=8817#pid8817]( https://forum.kodiwpigulce.pl/showthread.php?tid=1373&pid=8817#pid8817)

**Comment by Cinek77** [comment]
@aprof28 nie chodzi o to że nie odtwarza z wygenerowanej listy tylko wszystkiego z wtyczki Polsat Go i Player na boxie mecool m8s pro l.
Chyba że ja źle zrozumiałem to co opisał @PeQuS
A my możemy pisać (jak ja wyżej) że na takim czy innym urządzeniu działa. Na tym raczej nie zadziała jak nie zrobi się tego o czym pisze wyżej mtr81.
Mam taki zabytek z 2017 roku mecool m8s pro W. Który leżał w szufladzie od trzech lat.
Podłączyłem go sprawdziłem i też te wtyczki nie działają.
Więc wylądował z powrotem w szufladzie raczej już dożywotnio :) :P

**Comment by PeQuS** [comment]
Zmodyfikowałem nazwę pliku jak sugerował @mtr81 i Polsat go ruszył! I to nawet w dobrej jakości :) Playera aktualnie nie jestem w stanie sprawdzić bo mają jakąś przerwę techniczną lub awarię. Jak tylko zacznie działać to sprawdzę i dam znać czy z playerem też poszło. Jeżeli zmiana nazwy tego pliku nie wpłynie negatywnie na nic innego to będzie dobrze.

**Comment by PeQuS** [comment]
Player też działa bez problemu! :) Dzięki wielkie! Żona się ucieszy :D Wielkie dzięki za pomoc!

**Comment by Mrexel55** [comment]
Sent from Yahoo Mail for iPhone


On Sunday, September 25, 2022, 11:16 AM, PeQuS ***@***.***> wrote:




Oficjalna apka Polsat go działa na tym urządzeniu. Wideo się odpala bez problemu. Playera nie jestem w stanie sprawdzić - brak apki do ściągnięcia. Wrzucam log z playerem i Polsatem z kodi. Czy we wskazanych plikach powinienem zwrócić uwagę na coś konkretnego?
kodi.log
