### ISSUE TITLE
Generator listy m3u

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#842]
Witam mam pytanie chciałem wygenerować listę z upc w wersji 2.5 niestety wywalił za przeproszeniem błąd podam logi może to pomoże:
https://paste.kodi.tv/ivihunabiv
Dodatkowo udało mi się wygenerować listę m3u z polsatboxgo niestety nie mogę odpalić ani vlc czy potplayerem..
tak w skrócie wygląda lista m3u wygenerowana z polsatboxgo i nie wiem czy tak ma to wyglądać:
#EXTM3U
#EXTINF:-1,POLSAT PL
plugin://plugin.video.pgobox/?mode=playtvs&url=1445662&page=0&moviescount=0&movie=True&name=POLSAT&image=https://ipla.pluscdn.pl/p/cms_thumbnails/96/96c7znf842w8spf1ui973hcyb36igs6b.jpeg
#EXTINF:-1,TV4 PL
plugin://plugin.video.pgobox/?mode=playtvs&url=1443260&page=0&moviescount=0&movie=True&name=TV4&image=https://ipla.pluscdn.pl/p/cms_thumbnails/j5/j5mk747m5amytwah7ue54jwdxp9g8v6h.jpeg
#EXTINF:-1,POLSAT NEWS HD PL
plugin://plugin.video.pgobox/?mode=playtvs&url=1456330&page=0&moviescount=0&movie=True&name=POLSAT NEWS HD&image=https://ipla.pluscdn.pl/p/cms_thumbnails/bn/bnwk2b98j3epxjmwyx1fbpxkc1k7ecct.jpeg
Pozdrawiam i dziękuję za jakie kolwiek wskazówki czy porady. I jeszcze jedno pytanie czy ktoś z was panowie i panie potrafią wygenerować pojedyńcze linki ze stron takich jak upc, polsatboxgo czy viaplay/ chciałbym zrobić własną listę tylko z kanałami sportowymi, udało mi się to zrobić z elewnesports.pl(ale to było proste). jeszcze raz pozdrawiam i jeżeli nie za bardzo trafiłem z pytaniami to bardzo przepraszam.

**Comment by mtr81** [comment]
Witam
Sprawdzałem generowanie listy M3U we wtyczce UPC 2.5 - działa bez zarzutu. Pytanie czy byłeś zalogowany we wtyczce w momencie generowania listy?
Co do generowania list z wtyczek - one działają tylko i wyłącznie w Kodi i to pod warunkiem posiadania zainstalowanej wtyczki .

**Comment by rafalmar1981** [comment]
@mtr81 dzieki za info
