### ISSUE TITLE
MB filmy błąd

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#853]
Dzień dobry/dobry wieczór.
Coś porobiło się z zalukaj.vip
android kodi 19.4
win7 kodi 19.4
wyskakuje błąd i na win7 oraz androidzie
log z win7:
https://paste.kodi.tv/buqoboruba
Gdyby ktoś w wolnym czasie zerkną, będę wdzięczny. Pozdrawiam.

**Comment by rafalmar1981** [comment]
Chyba cała wtyczka padła...oglądaj.to też "błąd logowania" a vizjer działa tylko szkoda, że nie wyszukuje :)

**Comment by kashkash18** [comment]
Sprawdź czy masz premium w oglądaj.to.
Zauważyłem że jak się skończy premium to wtyczka wywala błąd dodatku.

**Comment by mbebe** [comment]
Dobra. Wersja 1.3.40 powinna juz byc ok. ;-)

**Comment by rafalmar1981** [comment]
@kashkash18 tak mam premium(dziękuję za zainteresowanie).
@mbebe elegancko, bomba zalukaj.vip śmiga, vizjer - wyszukiwarka działa, oglądaj.to(premium) -"niepoprawne dane logowania".
Zależało mi na zalukaj.vip i vizjerze najbardziej, jest super::) Dziękuję bardzo. To z innej bajki - muszę podłączyć się do wątku w sprawie filmann.cc. Jeszcze raz . Pozdrawiam.

**Comment by Bogdan16** [comment]
witam
vizjer - wyszukiwarka nie działa
Pozdrawiam

**Comment by Bogdan16** [comment]
witam
mam wykupione Zalukaj Vip na stronie wszystko dziala a na Kodi 19.4 Matrix Niepoprawne dane logowania co musze zrobic

Pozdrawiam
