### ISSUE TITLE
Android tv problemy z wtyczkami upc, polsatbox go

### ISSUE THREAD

**Issue by Kamqtny** [mbebe/blomqvist#855]
Witam,

ma problem na moim urządzeniu PLAY NOW TV BOX 2 - android tv z niektórymi wtyczkami na kodi od mbebe.
niestety nie wiem czemu, ale upc ani polsat box mi nie działa, mówimy oczywiście po zalogowaniu na konto.
jestem świeżakiem z kodi.
na boxie mam fabrycznie zainstalowaną wersję 19.3
mam nadzieję że dobre logi zgrałem, dodaje link
proszę o pomoc i z góry dziękuję
 https://drive.google.com/file/d/1G2xwEMDrUxZE0ZW3xSuyzLfwuMrRTS2h/view?usp=sharing

**Comment by hevet** [comment]
Co do upc, to obecnie stara wtyczka nie działa w ogóle, spróbuj nowej z tego wątku https://github.com/mbebe/blomqvist/issues/851

**Comment by FXcodi** [comment]
Faktycznie jest problem "polsatbox Go" - przy próbie wejścia w zakładkę **KanałyTV** wyskakuje taki błąd!
![PolsatBoxGO](https://user-images.githubusercontent.com/39464253/197037091-82733ed9-148c-4215-b830-0705cef4cde9.jpg)

**Comment by batorencjusz** [comment]
Również w ogóle nie moge uruchomić kanałów TV

**Comment by hevet** [comment]
Spróbujcie tej wersji PGB, po poprawkach @mtr81
[plugin.video.pgobox-1.99.zip](https://github.com/mbebe/blomqvist/files/9836721/plugin.video.pgobox-1.99.zip)

**Comment by mtr81** [comment]
To musiał być jakiś błąd po stronie serwera, bo obecnie wtyczka z repo działa bez zarzutu. W wersji, którą wrzucił wyżej @hevet przywrócono EPG (tylko dla bieżącej i kolejnej pozycji programowej) oraz zablokowano odtwarzanie kanałów, których nie ma w pakiecie (z wyświetleniem stosownego komunikatu).

**Comment by Kamqtny** [comment]
> To musiał być jakiś błąd po stronie serwera, bo obecnie wtyczka z repo działa bez zarzutu. W wersji, którą wrzucił wyżej @hevet przywrócono EPG (tylko dla bieżącej i kolejnej pozycji programowej) oraz zablokowano odtwarzanie kanałów, których nie ma w pakiecie (z wyświetleniem stosownego komunikatu). Ale uwaga - ta wersja powstała przed wersją 1.99, która jest w repo !

**Comment by Kamqtny** [comment]
Niestety, u mnie dalej ten sam error na polsatbox go 1.99. I to nie tylko kanaly tv, ale nic nie uruchamia, ani vod...
Mam wykupiony pakiet hbo i jego treści też nie działają

**Comment by FXcodi** [comment]
U mnie po aktualizacji polsatbox go śmiga treści/zakładka HBO także, chociaż wcześniej problem był tylko z kanałami tv ze streamingu.

**Comment by Kamqtny** [comment]
> Co do upc, to obecnie stara wtyczka nie działa w ogóle, spróbuj nowej z tego wątku #851

Dziękuję, ta wtyczka działa aż miło. 
Jednak dalej z polsatboxem jest problem

**Comment by Kamqtny** [comment]
> Wrzuć debuglog z Kodi. Logujesz się dobrymi danymi?
Mam nadzieję, że o to chodzi:
https://paste.kodi.tv/obijazelow.kodi

wylogowałem się, zalogowałem, wyłączyłem i załączyłem DRM, ale w żadnej z tych opcji nic się nie zmieniło... dalej nie działa na POLSATBOXgo, zwykłe PolsatGO śmiga, nawet polsat i tv4 na żywo...

**Comment by mtr81** [comment]
Czy na tej wersji z linka dzieje się to samo? https://github.com/mbebe/blomqvist/issues/855#issuecomment-1286575256 (musisz ściągnąć i zainstalować z ZIP-a a nie z repo)

**Comment by Kamqtny** [comment]
Na wersji z zipa wyswietla sie lista kanałów, ale po kliknięciu w dowolny wyswietla komunikat kodi (na srodku ekranu okienko) w stylu" nieudane otwarcie jednej lub wiecej pozycji....

**Comment by mtr81** [comment]
To poproszę jeszcze log Kodi z tej ostatniej wersji.

**Comment by mtr81** [comment]
OK. Dzięki. Wygląda na jakiś problem na etapie pobierania licencji. W katalogu /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/cdm znajdziesz plik o rozszerzeniu .response. Możesz zrzucić jego zawartość?

**Comment by Kamqtny** [comment]
Nie, to jest nowy box i na nim po zainstalowaniu wtyczki od mbebe nigdy nie działało. Czyli dobrze rozumiem, włączam kodi, uruchamiam wtyczk pbg nastepnie minimalizuje kodi i ide do menadżera plików i kopiuję w/w plik, tak?

**Comment by mtr81** [comment]
Dokładnie. Powinna być tam informacja o rodzaju błędu, który wystąpił przy pobieraniu licencji.

**Comment by Kamqtny** [comment]
https://paste.kodi.tv/emuqocofus
mam nadzieję że o to chodzi ;)

**Comment by mtr81** [comment]
Tak. Dzięki. Dziwna sprawa, bo licencja 'wjeżdza' prawidłowo. No to jeszcze trzeba zobaczyć bardziej szczegółowy log z ruchem pakietów. Zaznacz w opcjach logu "Enable component-specific logging' i wrzuć jeszcze raz log.

**Comment by Kamqtny** [comment]
Kurcze, nie bardzo wiem coo mam teraz zmienić...
Wchodzę w ustawienia, system, dianostyka i to co mmam na zrzucie ekranu???
![Screenshot_20221026-231855_TeamViewer](https://user-images.githubusercontent.com/116280053/198140554-bf9ff9e7-d99b-4173-9b31-2514fb01f92e.jpg)
Bo przy wybierz komponent nie mam nic do logowania... chyba ze to nie to.

**Comment by mtr81** [comment]
W komponentach powinieneś mieć zaznaczone Verbose Logging for the libCURL library (listę wywołasz po kliknięciu trzeciego wiersza)

**Comment by Kamqtny** [comment]
https://paste.kodi.tv/fazoyoviru.kodi
mam nadzieję, że jest dobrze

**Comment by mtr81** [comment]
W ustawieniach wtyczki jest zakładka DRM. Włącz weryfikację certyfikatu.

**Comment by Kamqtny** [comment]
> > Wrzuć debuglog z Kodi. Logujesz się dobrymi danymi?
> > Mam nadzieję, że o to chodzi:
> > https://paste.kodi.tv/obijazelow.kodi
> 
> wylogowałem się, zalogowałem, wyłączyłem i załączyłem DRM, ale w żadnej z tych opcji nic się nie zmieniło... dalej nie działa na POLSATBOXgo, zwykłe PolsatGO śmiga, nawet polsat i tv4 na żywo...

o tutaj o tym pisałem

**Comment by mtr81** [comment]
Tylko u ciebie dzieją się dziwne rzeczy. Z ostatniego logu wynika, że nie ruszyła nawet procedura pozyskania licencji DRM. Z drugiej strony przesyłasz plik, z którego wynika, że licencja została pobrana. To się nie trzyma kupy.

**Comment by Kamqtny** [comment]
na innym boxie z androidem 9 nie mam problemu.
tutaj zmieniłem na android TV i nie działa, choć mam dokładnie takie same ustawienia wtyczki i KODI, zanim tu napisałem próbowałem samodzielnie skontrolować ustawienia. 
Myślałem że problemem jest tylko środowisko ANDROID TV...

Tylko w ostatnim logu są 2 części o 23:30, a potem 23:42
w tej pierwszej części przeinstalowywałem wtyczkę na mbebe z repo i jeszcze nie było domyślnie włączonego DRM,
ale o 23:42 już to zmieniłem i też bez efektu.

**Comment by mtr81** [comment]
OK. sprawdziłem na swoim boxie - sprawdzanie certyfikatu ma być **wyłączone**. Sprawdzaj na tej wersji wtyczki, którą wrzuciłem, bo z tą z repo jest coś nie tak.

**Comment by Kamqtny** [comment]
dobra, o 17 będę w domu, przeinstaluję na tą zmodyfikowaną i wyłączę drm, dam znać za godzinkę czy w końcu ruszyło. 
dzięki za cierpliwość i pomoc

**Comment by mtr81** [comment]
To od razu wrzucę wtyczkę z poprawioną sekcją HBO, bo tam też sypało błędami
[plugin.video.pgobox-1.99.zip](https://github.com/mbebe/blomqvist/files/9880221/plugin.video.pgobox-1.99.zip)

**Comment by Kamqtny** [comment]
> To od razu wrzucę wtyczkę z poprawioną sekcją HBO, bo tam też sypało błędami [plugin.video.pgobox-1.99.zip](https://github.com/mbebe/blomqvist/files/9880221/plugin.video.pgobox-1.99.zip)

Dziękuję serdecznie. DZIAŁA :)
na tym zipie zmodyfikowanym i wyłączonym DRM.
Dzięki raz jeszcze, mam jeszcze drobny problem z samym KODI, w ustawieniach wyświetlacza mam 1080p, choć cały box jest 4k i hdmi 2.2 ... to 1920x1080 mam wyszarzone i nie idzie niczego zmienić, czy coś z tym jestem w stanie zrobić?
wieczorem zamknę jako rozwiązane :)

**Comment by mtr81** [comment]
A jaką rozdzielczość masz przy odtwarzaniu np. Wydarzeń 24 na wtyczce PBG (do sprawdzenia na odtwarzaczu Settings->Video Settings)?

**Comment by Kamqtny** [comment]
![Screenshot_20221027-180633_TeamViewer](https://user-images.githubusercontent.com/116280053/198342252-d04d1cf8-69fc-4dc3-9603-cd788ed29389.jpg)
Niestety tylko 1080p mi wyswietla

**Comment by mtr81** [comment]
I to jest max co możesz mieć.

**Comment by Kamqtny** [comment]
oki. no nic, dzięki. bardzo mi pomogłeś. pozdr
