### ISSUE TITLE
Sweet.tv

### ISSUE THREAD

**Issue by UncleHoSzczecin** [mbebe/blomqvist#857]
I znów podrzucam nową usługę.
Mam nadzieję że skończy się równie dobrze jak w przypadku telewizjionline.
Wystartowała w Polsce https://sweet.tv/pl

**Comment by FXcodi** [comment]
Gdzie znajdę wtyczkę do telewizjionline?

**Comment by mtr81** [comment]
@UncleHoSzczecin to jest serwis płatny. Jak ktoś ma napisać wtyczkę bez danych dostępowych?

**Comment by UncleHoSzczecin** [comment]
> @UncleHoSzczecin to jest serwis płatny. Jak ktoś ma napisać wtyczkę bez danych dostępowych?

Nie mam nic przeciwko temu by opłacić na miesiąc "premium" komuś kto stworzy wtyczkę.
Swojego niestety nie udostępnię bo popełniłem błąd zakładając konto poprzez dane logowania Google ale służę 5 zł.
W razie czego daj jedynie znać.

**Comment by UncleHoSzczecin** [comment]
Moim zdaniem warto bo jakkolwiek kanałów telewizyjnych mają bardzo mało to jednak są w nich takie które bardzo rzadko występują u tak tanich operatorów.

**Comment by mbebe** [comment]
https://github.com/mbebe/blomqvist/issues/867
