### ISSUE TITLE
vod.tvp.pl

### ISSUE THREAD

**Issue by Huero23** [mbebe/blomqvist#86]
Czy działa wam VOD na TVP ? NP: SERIAL  WIECZNA MIŁOŚCI straszenie buffering robi albo staje... inne też jak Elif.

**Comment by mbebe** [comment]
Sprobuj zmniejszyc jakosc wideo w ustawieniach wtyczki.

**Comment by Huero23** [comment]
@mbebe dziękuje sprawdzę tak dzisiaj... Zauważyłem że w ustawieniach jest opcje INPUTSTREAM ADAPTIVE czy włączyć czy nie czy to robi różnice w vod ?

**Comment by Huero23** [comment]
@mbebe jeszcze jeden dziwny problem od dwóch dni jak włączyłem VPN to dalej pokazuje "Ograniczenia Licencyjne, materiał niedostępny " albo Wiadomość i Teleexpress nie mam takie problemu?

**Comment by Huero23** [comment]
*ale Wiadomość i Teleexpress nie

**Comment by mbebe** [comment]
INPUTSTREAM ADAPTIVE moze byc wlaczony do tego co leci LIVE, ale nie musi i tak powinno ruszyc.
Przy jakim programie, pozycji, pokazuje ograniczenia licencyjne?

**Comment by Huero23** [comment]
@mbebe... Tylko jak chce wejść na jakiś SERIAL na vod.TVP.pl - Elif i Wieczna Miłości serial... Ale jak wchodzę na Wiadomość, Teleexpress albo Panorama nie ma żadnego problemu...dziwne trochę bo zawsze jak nie działało to wszędzie była blokada.

**Comment by Huero23** [comment]
@mbebe... Jak klikniesz na odcinek wtedy wskakuje PROBLEM OKIENKO. Masz opcje pisze Spróbować użyć serwera proxy i na dole pisze W OPCJACH DOSTĘPNA ALTERNATYWA OPCJA! TAK NIE

**Comment by mbebe** [comment]
Wylacz vpn i to samo sie bedzie pojawiac. Uzywasz zlego vpn PL.

**Comment by Huero23** [comment]
@mbebe używam IPVANISH VPN... Wszystko działało ok ostatnie 2-3 tygodnie ale ostatnie 3 dni tylko na seriale VPN nie działa ale także jak mówiłem Teleexpress odblokuj bez problemu to jest dziwne.

**Comment by Huero23** [comment]
@mbebe czy to jest możliwe że działa na WIADOMOŚĆ, PANORAMA I TELEXPRESS ALE NIE NA SERIALE?

**Comment by Huero23** [comment]
@mbebe przepraszam miałeś rację. Miałem  ustawione na "Best Server Available" ręcznie ustawiłem na inny server aż trafiłem na który działa to same z jakość video z powrotem wziąłem NAILEPSZE DO RĘCZNIE USTAWIENIE. DZIAŁA ! DZIĘKUJE BARDZO. POZDRAWIAM Z LOS ANGELES.

**Comment by BondasH** [comment]
Witam

mam pytanie ,mianowicie dziś chciałem obejrzeć 2 odcinki  Korona królów 200 i 201 (w sumie to nie ja tylko zona) i nie udało mi się ich odpalić, musiałem sie zalogowac na stronie www wyciągnąć stream i dodać do listy w kodi 

czy istnieje możliwość dodania logowania do premium w tym ze dodatku oraz odblokowania tych i podobnych pozycji.

pogrzebałem sam chcialem dodac weblogin.py do dodatku ale nadal nie działaja te pozycje i inne które sa odplatne , używam openvpn do zmiany ip działa na innych to na tym też nie to jest problemem
jakos nie widze nic w dodadku strefa ABO z tych pozycji 

sa jakieś szanse 

ps. ogólnie dzięki za prace

**Comment by kashkash18** [comment]
Odcinek nr 200 się odpala
![](https://i.imgur.com/RAJu3NG.jpg)
![](https://i.imgur.com/1rxdN0a.jpg)
A na 201 trzeba zaczekać

**Comment by BondasH** [comment]
dzięki za odpowiedź,

pytałem o coś innego / bez czekania tak jak pisałem mogę stream wyciągnąc nie musze czekać / 
odcinek 200 sie pojawił bo pewnie w tv był rano go nie było

**Pytałem czy jest możliwość zrobienia logowania i odblokowania płatnych źródeł...............**

http://images2.imagebam.com/7d/41/4f/9b4ee61183605134.png

**Comment by kashkash18** [comment]
A czy przypadkiem to co chcesz odpalić to nie DRM ??
Z tego co kojarzę to ta wtyczka nie jest przystosowana do odpalania DRM

**Comment by BondasH** [comment]
Dla tego zadałem pytanie: **### czy jest możliwość zrobienia logowania i odblokowania płatnych źródeł**

**skoro odpala odcinek 200 to dla czego nie miał by odpalić odcinka 201**

**Comment by kashkash18** [comment]
Wydaje mi się że wszystko co jest w strefie abo to DRM

**Comment by mbebe** [comment]
@BondasH 
[plugin.video.TVP.pl-2.2.zip](https://github.com/mbebe/blomqvist/files/3050299/plugin.video.TVP.pl-2.2.zip)
tu wersja wtyczka, gdzie sie zalogujesz (w ustawieniach wtyczki). Zapewne nie bedzie dzialac bez polskiego IP. Te seriale beda odtwarzane. Nie wiem, co wiecej, bo nie sprawdzalem. :-))))))))))))))))))

**Comment by BondasH** [comment]
@mbebe 
Dziękuję ci bardzo!!! dałeś mi bardzo dużo świętego spokoju...
* tak używam **service.vpn.manager** i też szukałem rozwiązania tak aby to wszystko działało przyzwoicie i samo bez ingerencji wielkiej ogólnie polecam wszystkim ten dodatek ma w ustawieniach które dodatki maja korzystać z vpn a które nie po odpaleniu np. tvp vod automatycznie sie odpala vpn i juz jest polska lokalizacja a jak przełącze na Netflix to automatycznie się wyłacza vpn

z tego co zauważyłem to już nie działa np. Wiktoria komunikat brzmi Strumień DASH  Materiał DRM  i nie pali, reszty dowiem sie wieczorem jak zasiądzie druga połowa na swoich gniotach

**Comment by mbebe** [comment]
Ok, tu wersja, ktora odpala drm.
[plugin.video.TVP.pl-2.2.1.zip](https://github.com/mbebe/blomqvist/files/3050471/plugin.video.TVP.pl-2.2.1.zip)

**Comment by kashkash18** [comment]
W tej wersji DRMy się odpalają i komunikat Strumień DASH Materiał DRM też się pojawia. 
Ale to już chyba w ramach informacji .

**Comment by mbebe** [comment]
Tak, nie usunalem tej informacji. ;-)

**Comment by BondasH** [comment]
Jeszcze raz wielkie dzięki już obadana wtyczka działa poprawnie co do info o drm
 to chyba to  **xbmc.executebuiltin('Notification(Strumień DASH, ' + 'KODI 18 - materiał z DRM' + ', 1200)')** wystarczy przykasować ,prawda?

**Comment by BondasH** [comment]
@mbebe 

Witaj ,znów pojawił się problem chyba trwa już więcej nic tydzień ,nie pisałem nic myślałem ze ktoś napisze ale widocznie nikt z premium nie korzysta ,mianowicie problem jest taki jak poprzednio jest pozycja na liście ale jak ją odpalam to woła o login a jestem zalogowany i znów przeglądarka i wyciąganie .m3u 

możesz zerknąć?
dzięki pozdrawiam.

**Comment by mbebe** [comment]
a probowales tej wtyczki? https://github.com/mbebe/blomqvist/blob/master/zips/plugin.video.tvpABON/plugin.video.tvpABON-1.4.zip

**Comment by BondasH** [comment]
nie bo ta działała dobrze sprawdze ,THX

**Comment by BondasH** [comment]
działa!, muszę zacząć to wszystko śledzić za dużo zmian ciągle no i repo nie zawsze pokazuje update w sumie to prawie nigdy.

**Comment by Huero23** [comment]
@mbebe Hey... Znowu nie mogę wejść na Wiadomość, Teleexpress i Panorama... Mam zdjęcie problem ale tutaj chyba nie mogę zrobić paste zdjęcia .. Pokazuję błędy.

**Comment by Huero23** [comment]
![15567728359862706621002200249692](https://user-images.githubusercontent.com/19337836/57057178-d0a7ea80-6c5b-11e9-9a36-c8b2f0bf2b0d.jpg)
@mbebe

**Comment by robbcio1983** [comment]
I
