### ISSUE TITLE
iitv.info

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#862]
Witam czcigodnego @mbebe, czy jest możliwość dodania/ reaktywacji wtyczki?
[plugin.video.iitv](https://github.com/mbebe/blomqvist/tree/master/zips/plugin.video.iitv)
Pozdrawiam.

**Comment by mbebe** [comment]
Ale tam nic nie ma. To nie jest strona z filmami, ktore mozna ogladac.

**Comment by rafalmar1981** [comment]
@mbebe qurde  przepraszam stronę pomyliłem
