### ISSUE TITLE
Player PL -  Problemy z Video

### ISSUE THREAD

**Issue by deco1640** [mbebe/blomqvist#866]
Obraz przycina tak jak pokaz slajdów inne wtyczki działają prawidłowo.
Kodi 19.4 
Android TV 9.0
TV Sharp 40CI1EA

Jakby miał ktoś okazję looknąć dorzucam pełne logi z kodi :
https://pastebin.pl/view/raw/21fcc0f8
https://megawrzuta.pl/download/7d79122d0fdf273a47dc23679a5a7073.html

**Comment by Cinek77** [comment]
A może by tak przejrzeć  wcześniejsze tematy odnośnie Playera zanim założy się nowy.
https://github.com/mbebe/blomqvist/issues/834#issuecomment-1241866356

**Comment by deco1640** [comment]
Przeglądałem i nawet tej opcji nie mam w ustawieniach, dlatego dałem logi bo już wszystkie opcje o których tu czytałem nie pomogły. Dlatego założyłem NOWY TEMAT

**Comment by hevet** [comment]
W ogóle nie masz opcji akceleracji sprzętowej jakiejkolwiek?

**Comment by deco1640** [comment]
Mam tylko :

- Zezwalaj na sprzętową akcelerację - MediaCodec (powierzchniowy)
- Zezwalaj na sprzętową akcelerację
- i nic więcej nie ma.

**Comment by Cinek77** [comment]
Świeża instalacja Kodi ze sklepu na Telewizorze TCL
Instaluje się Kodi 19.3 a nie Kodi 19.4
Player działa i nic nie przycina. Sprawdzone kilka seriali i programów.
Proponuję zainstalować Kodi 19.3 ze Sklepu Play google czy jak tam masz.

**Comment by deco1640** [comment]
Instalowałem już wszystkie wersje kodi i 19.0 aż do 4 i nawet Kodi 20. Wszędzie ten sam błąd, robiłem ustawienia fabryczne i nic to nie dało. Tylko ciekawi mnie dlaczego Polsat Box Go działa na full HD a na player nawet przy najmniejszej rozdzielczości jest dokładnie ten sam błąd.

**Comment by Axis963** [comment]
Nie wiem czy to to, ale kiedyś kiedyś na podobny problem mi to pomoglo:

https://forum.kodiwpigulce.pl/showthread.php?tid=4174&pid=36608#pid36608

**Comment by deco1640** [comment]
To nic nie daje. Ja mam Widevine wbudowane w Android TV, nie mam żadnych opcji przewracania itp.

**Comment by deco1640** [comment]
![FB_IMG_1667860091994](https://user-images.githubusercontent.com/114484853/200428998-33aba2ef-f09e-4f1e-b121-38abdee9a4d5.jpg)

**Comment by deco1640** [comment]
![FB_IMG_1667860098132](https://user-images.githubusercontent.com/114484853/200429044-7d92ad14-6ecd-459c-8c41-9634d68ad017.jpg)

**Comment by deco1640** [comment]
Stare zdjęcia ale dalej pisze dokładnie to samo.

**Comment by Cinek77** [comment]
Sprawdź jeszcze czy aplikacja Player działa poprawnie i odtwarza materiały.(Filmy/Seriale/Programy)

**Comment by Cinek77** [comment]
To pozostaje korzystanie z aplikacji.

**Comment by deco1640** [comment]
Jakby ktoś chciał się przyjrzeć jak to wygląda w praktyce nagrałem wideo z tym klatkowaniem
https://files.fm/f/d6g7kyysc

**Comment by deco1640** [comment]
Zacinanie wideo w moim przypadku ustępuje w aplikacji Player po zaznaczeniu tej opcji w ustawieniach aplikacji 
Dało by radę żeby ktoś to mógł sprawdzić czy idzie to wprowadzić znaczy tą opcję do wtyczki Playera w Kodi?
![20221213_115959-1](https://user-images.githubusercontent.com/114484853/207300370-60ff3e92-bd41-4043-8612-e040fff09433.jpg)
