### ISSUE TITLE
Internetowa ws

### ISSUE THREAD

**Issue by Katrin241081** [mbebe/blomqvist#87]
Witam. Zakupiłam konto premium na internetowa tv ale na kodi wyskakuje  mi błąd logowania i brak konta premium. Na telefonie aplikacja działa. Kodi 17,6 urządzenie Amazon Stick.
Pozdrawiam

**Comment by mbebe** [comment]
jakiej uzywasz wtyczki i skad ja wzielas?
Uzywasz pewnie oryginalnej z ich strony. Na ich wtyczce pojawia sie taki komunikat j.w.

**Comment by Katrin241081** [comment]
Tzn wtyczkę mam z repozytorium mbebe. Urządzenie to Amazon Stick na który wgrany jest kodi 17,6

**Comment by mbebe** [comment]
ok. :-)

**Comment by mbebe** [comment]
poszla poprawka - mozesz sprawdzic.

**Comment by Katrin241081** [comment]
Działa!!! Wielkie dzięki!!!! 👌👌👌

**Comment by mbebe** [comment]
Moze wyciszone? Albo akurat lecial "Krzyk ciszy"?

**Comment by Katrin241081** [comment]
Załapało!!!

**Comment by Katrin241081** [comment]
Czy odbierania programów za granicą na darmowa tv potrzebne jest VPN???

**Comment by mbebe** [comment]
Nie. Powinny dzialac bez vpnu.

**Comment by Katrin241081** [comment]
To u mnie na darmowa telewizja. online wyskakuje brak działającego stream.

**Comment by mbebe** [comment]
W kazdej tv? w zobacz.ws, w supersportowo itd.?

**Comment by Katrin241081** [comment]
Supersportowo odbiera ale reszta albo wyrzuca co chwilę albo w ogóle nie działa
