### ISSUE TITLE
fili.cc

### ISSUE THREAD

**Issue by gzenio22** [mbebe/blomqvist#88]
Hej może dało by radę we wtyczce fili zrobić podział na sezony? było by sporo szybciej biegać po wtyczce niż pocinac scrollem w doł bo serial ma np 15 sezonow po 22 odcinki i pocinaj na sam dol listy Xd

**Comment by kashkash18** [comment]
Wejdź w ustawienia wtyczki , seriale  i zaznacz grupuj epizody w sezonach.

**Comment by gzenio22** [comment]
Dzięki zamykam
