### ISSUE TITLE
HDseans, filmowoclub

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#882]
HDseans oraz filmowoclub(znalazłem i spodobało misię) jako alternatywa zamiast jak wiem filman.cc oraz CDA.pl + CDA TV nie działają na razie(Cloudflare). 
Kodi 19.4 win7 i android.
HDseans - nie działa opcja ustawienia gatunku w filmach oraz serialach, po wybraniu filmu/serialu często zdarza się, że po wybraniu jakiego kolwiek źródła - kręci się przez chwilę kółko w prawym dolnym rogu i przestaje, na stronie działa.

filmowoclub - wszystko jest oki poza ustawianiem filtrów np. "ostatnio dodane" itp. wyświetla pierwszą stronę z https://filmowo.club/

log z win7:
https://paste.kodi.tv/najawiyiso

Pytanie czy dało, by się to naprawić. Pozdrawiam.

**Comment by praspp** [comment]
CDA.pl + CDA TV od @mbebe można naprawić: https://github.com/mbebe/blomqvist/issues/880#issuecomment-1330517797

**Comment by hevet** [comment]
Ą
