### ISSUE TITLE
Propozycja nowej wtyczki 

### ISSUE THREAD

**Issue by Kara55k** [mbebe/blomqvist#883]
Witam, składam propozycje stworzenia wtyczki polskiej Magenty TV w internecie jest wiele wtyczek ale wszystkie z nich dotyczą Magenty niemieckiej :/

**Comment by mbebe** [comment]
A podeslalbys dane logowania? ;-)

**Comment by Kara55k** [comment]
Podaj jakiś szybszy kontakt do ciebie :)

**Comment by mbebe** [comment]
mbebeGIT (at) protonmail.com

**Comment by aprof28** [comment]
Witam. Czy dało by się coś zrobić że stroną https://resetoff.pl/  działa na zasadzie freedisc posiada filmy i seriale . Z górki dzięki.
