### ISSUE TITLE
VODPanel

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#888]
Witam czy jest możliwość stworzenia wtyczki Vodpanel?
Pozdrawiam.

**Comment by notoco** [comment]
Ale przecież oni mają swoją wtyczkę. Ta ich apka to tak naprawdę zmodyfikowane kodi + wtyczka. Wystarczy ją wyciągnąć

**Comment by rafalmar1981** [comment]
pobrałem z googleplay i na telefonie huawei zainstalowana ale zawiesza się nic nie da się zrobić nawet wrowadzić  danych do logowania

**Comment by rafalmar1981** [comment]
OKI ale apka ze strony hula elegancko

**Comment by notoco** [comment]
No to z apki pewnie da się wyciągnąć ich wtyczkę. Tylko podejrzewam że to jest tak mocno przerobione kodi że samo wyciągnięcie wtyczki niewiele da.

**Comment by rafalmar1981** [comment]
To już niech sobie hula poza kodim(na tv smart), nie zajmuję czasu mistrzom w okresie przed świątecznym.Pozdrawiam.

**Comment by notoco** [comment]
W przypadku tego typu aplikacji obawiam się że hulają nie tylko poza kodim dane z twojego urządzenia... No ale każdy ma wybór...
