### ISSUE TITLE
Pytanie do/dla znawców

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#89]
Mam pytanie...mam konto premium Wizja.tv wywala mnie z każdego kanału, czy mam coś zainstalować, włączyć, wyłączyć...jakaś rada,porada będę wdzięczny kodi17.6

**Comment by sky0002** [comment]
https://github.com/mbebe/blomqvist/issues/83 Tu masz odpowiedz na swoje pytanie. A jak Cię co chwilę wywala to znaczy że nie tylko Ty korzystasz z tego konta . Przewala po Ip, a i Wizja jest ostro do tył. To nawet Gold dziś aktualizował swoją wtyczkę do 18 a wizja sama nic nie wydała . I Mbebe nie pisał tej wtyczki z której korzystasz to czemu tu zadajesz pytanie ? Nie gniewaj się ale nie ten adres ;) Pozdrawiam.

**Comment by rafalmar1981** [comment]
sky0002 spoko nie gniewam się. Dziękuję za odpowiedź oraz radę. Wiem, że nie ten adres ale wiedziałem,iż to tu dostanę odpowiedź w miarę szybko, "nie tylko Ty korzystasz z tego konta" - rozumiem przez to tak ktoś zna moje dane do konta? Czy jest możliwość podesłania linku gdzie gold jest w miarę stabilny? Dziękuję i również pozdrawiam.

**Comment by sky0002** [comment]
No Kolego ale jakiego linku? Chcesz moje dane do konta Gold ? Owszem gold jest mniej wymagający ale czy to nie przesada ? Proszę http://goldvod.tv/ zaloguj się wykup i będzie działać . Serdecznie pozdrawiam.

**Comment by rafalmar1981** [comment]
Nie nie źle mnie zrozumiałeś, nie chcę Twoich danych, zarejestrowałem się i pewnie około dziewiątej wykupię konto, a jeśli chodzi o link to miałem na myśli wtyczkę do kodi ale przecież jest na stronie. Czy RMPT ma być włączony?

**Comment by sky0002** [comment]
Na Goldzie tak, tylko wtyczka Wizji ma z nią problem i Przepraszam bo pomyślałem o Tobie następna  pijawka ;) a  jak już odwaliliśmy takiego off topa to polecam. M-Tvgude http://64.79.96.137/repository.mods-kodi/  i epg od KWP https://epg.ovh/pl.gz
i nie będą potrzebne Ci jakieś inne wtyczki. Darmowe konto WP Twój gold i zaczynasz przygodę z Kodi . Idę spać :)

**Comment by rafalmar1981** [comment]
Dziękuję

**Comment by rafalmar1981** [comment]
sky0002 hej witam wyskakuje mi błąd na tv guaid błąd wczytywania pliku epg

**Comment by rafalmar1981** [comment]
epg od KWP https://epg.ovh/pl.gz rozpakowałem go i ten plik dałem do ustawień epg zmieniając na xml

**Comment by sky0002** [comment]
Wita. Nic nie kombinuj tylko wpisz adres http://epg.ovh/pl.gz bez 's' lub http://epg.ovh/pl.xml . Wtyczka 
M-TvGuide nie ogarnia adresów szyfrowanych wiec zwykłe http. Pozdrawiam.

**Comment by rafalmar1981** [comment]
już zrobiłem ten plik rozpakowany dodałem xml i śmiga

**Comment by rafalmar1981** [comment]
ale dziękuję za zainteresowanie i szybką odpowiedź

**Comment by notoco** [comment]
Jak rozpakujesz ten plik to epg będziesz miał na maks 3 dni... więc zupełnie bez sensu - samo się nie zaktualizuje. Posłuchaj sky0002 - on ci prawdę prawi.

**Comment by rafalmar1981** [comment]
oki czyli ten adres wpisać http://epg.ovh/pl.gz lub te dwa pozostałe http://epg.ovh/pl.xm, https://epg.ovh/pl.gz

**Comment by rafalmar1981** [comment]
sky0002 jest jakiś sposób aby nie zacinały się kanały, zrobiłem tak jak kazałeś. Może jakiś program, zmienić ustawienia np. serwer z Holandii na jakiś inny albo zmienić priorytet na wyższy choć nie wiem co to znaczy. Pozdrawiam

**Comment by sky0002** [comment]
Witaj. Priorytety są po to by ustalić kolejność dawców 11 jest najwyższym priorytetem i jak na goldzie go ustawisz to jaka pierwszy dostawca wyświetli ci kanał. A jeśli Ci zacina to zmieni serwer z Holandia na inny bliżej Twojej lokalizacji. Pozdrawiam.

**Comment by rafalmar1981** [comment]
sky0002 dobra dziękuję bardzo za pomoc
