### ISSUE TITLE
CanalPlus-vod: logowanie, "Access Denied"

### ISSUE THREAD

**Issue by SBPrime** [mbebe/blomqvist#899]
Mam problem z logowaniem się do serwisu.
Zrobiłem szybką analizę co się dzieje i błąd pojawia się tutaj:

https://github.com/mbebe/blomqvist_srcs/blob/main/srcs/plugin.video.canalplusvod/main.py#L776
```
774					data = 'username=' + quote(self.LOGIN) + '&password=' + quote(self.PASSWORD) + '&execution=' + execution + '&_eventId=submit&geolocation='
775					
776					response = sess.post(self.mainLOGINurl, headers=headers, data=data, verify=False)
778					av = response.text
```

Odpowiedź z serwera (response.text):
```
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
                                                    
You don't have permission to access "http&#58;&#47;&#47;logowanie&#46;pl&#46;canalplus&#46;com&#47;login" on this server.<P>
Reference&#32;&#35;18&#46;44645e68&#46;1673017979&#46;96a61ac1
</BODY>
</HTML>
```

Co sprawdzałem:
1. zweryfikowałem zawartość `data` w oparciu co wysyła przeglądarka podczas logowania - username, password i execution ustawione poprawnie (hasło oczywiście zweryfikowałem jako pierwsze ;) )
2. zweryfikowałem zawartość `headers` - porównałem je z tym co wysyła przeglądarka, były małe różnice, ale nawet po podmianie headrów (mała aktualizacja + dodanie kilku których nie było) to samo
3. wreszcie próbowałem to odpalić cały proces logowania w postmanie, efekt ten sam.

Kodi odpalam pod linuxem 64bit, najnowsza wersja wtyczki z repo.

**Comment by kopernik1983** [comment]
https://github.com/mbebe/blomqvist/issues/886
