### ISSUE TITLE
Prosba o wlaczenie GitHub Pages i wystawienie linku do file managera

### ISSUE THREAD

**Issue by meserak86** [mbebe/blomqvist#9]
Jak w  temacie bylo by latwiej dla mniej kumatych userw wystawic repo na linku sciagalnym z file managera... to minuta roboty dla Ciebie a dla niektorych userow 15 min rozkminy mniej

**Comment by meserak86** [comment]
wklep link z github page do pliku readme to bdzie widoczny na dole pod repo:D

**Comment by wisiann** [comment]
@mbebe,
Bedziesz mial chwile zeby to zrobic?

**Comment by xulek** [comment]
@wisiann https://mbebe.github.io/blomqvist/
