### ISSUE TITLE
Olpair

### ISSUE THREAD

**Issue by frijerz** [mbebe/blomqvist#90]
Niektore filmy wymagają potwierdzenia na stronie Olpair. Jak z tym radzicie sobie na Kodi?

**Comment by notoco** [comment]
Potwierdzamy w olpair. Najprościej przez komórkę w tej samej sieci wifi (żeby było jedno IP).

**Comment by frijerz** [comment]
Taki trick :) nie wpadlem na to. Szkoda, ze to sie nie dzieje automatycznie.
Dzięki.

**Comment by wisiann** [comment]
nie mozna miec wszystkiego ;)

**Comment by frijerz** [comment]
A jednak można miec więcej!  Dostalem wiecej niz tylko zalogowanie:
otrzymałem jako "bonus" mnóstwo reklam w stylu: "zerznij mnie", "spotkaj sie ze mną", no i oczywiście "powieksz swojego penisa"  :)

**Comment by kashkash18** [comment]
Reklamy targetowane :D Jakiś bloker reklam pomoże :)

**Comment by notoco** [comment]
@frijerz - od lat nie widziałem w openload żadnych reklam - wystarczy uBlock i ewentualnie pihole ;) co by komórkę ładnie wychwyciło...

**Comment by frijerz** [comment]
> Reklamy targetowane :D Jakiś bloker reklam pomoże :)
Hmmm... nigdy nikomu nie skarżyłem sie na wielkość, żona też nie narzekała... xD
@notoco te reklamy to z olpair. 
Sytuacja z parowaniem troche sie komplikuje, gdy na boxie mam VPN, a na telefonie nie.

**Comment by kashkash18** [comment]
@frijerz widocznie openload wie lepiej :-P

**Comment by notoco** [comment]
@frijerz - olpair to nic innego niż strona openload służąca do parowania - kiedyś było openload.com/pair, teraz jest olpair
Jeśli jesteś w PL i nie korzystasz z p2p to VPN na boxie nie jest ci potrzebny. Jeśli w innym kraju to owszem - się przydaje...

**Comment by Janasek** [comment]
@notoco dobrze prawi ale zapomniał dodać ze na android tylko i wyłacznie przegladarka firefoxa posiada możliwość instalacji Roszerzeń, ale uzywam już bardzo długo i reklam nie ma rosszerzenie nazywa się ublock origin niestety firefox do najlepszych nie nalezy no ale zawsze to jakieś rozwiązanie dobrze radzi sobie również **Blokada** aplikacje nie wymaga root https://blokada.org/pl/index.html

kolejna to Host file nie wymaga root powinna załatwic wiekszość problemów z reklamami w aplikacja takich jak ipla,tvp vod etc. host file https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/4499fa0cd50afff265682e144b51f10c10c01838/polish-pihole-filters/hostfile.txt

Autorstwa : https://github.com/MajkiIT/polish-ads-filter , przy okazji można zapodać kilka dobrych regół do ublocka
