### ISSUE TITLE
Kodi 20 Nexus...no update for plugin.video.wrestlingwatch available

### ISSUE THREAD

**Issue by TitanME** [mbebe/blomqvist#902]
By using Kodi 20 Nexus, there's no update available!
Last version for Nexus is 0.3. Newer versions (0.4 and 0.5) are not available from your repo.

Installing 0.5 per zip is possible without any problems. But the repo shows only 0.3 as possible Version.

Additional:
In version 0.5 ONLY the category "WatchProWrestling.live" works! The second category does not work.

**Comment by mbebe** [comment]
New version 0.6 is available in repo.
Probably you should install again my repo.
https://github.com/mbebe/blomqvist/raw/master/repository.mbebe.zip

**Comment by TitanME** [comment]
Thank you...it work's fine now
