### ISSUE TITLE
TVP VOD nie działa cześć materiału (v. 1.1.1)

### ISSUE THREAD

**Issue by MariuCh007** [mbebe/blomqvist#924]
Właśnie wykryłem że nie działają np. nowe odcinki/najnowszy sezon Ojca Mateusza.
Używam wersji 1.1.1 z https://mtr81.github.io/kodi_addons/repository.mtr81.zip

**Comment by mtr81** [comment]
Temat do zamknięcia. Bo raz to nie wtyczka z repo Mbebe, a dwa wyjaśnienie masz tu ->https://github.com/mbebe/blomqvist/issues/861#issuecomment-1462883427

**Comment by MariuCh007** [comment]
> Temat do zamknięcia. Bo raz to nie wtyczka z repo Mbebe, a dwa wyjaśnienie masz tu ->[#861 (comment)](https://github.com/mbebe/blomqvist/issues/861#issuecomment-1462883427)

OK, wyjaśnienia pomogły w uruchomieniu.
