### ISSUE TITLE
hdseans.pl OSZUST

### ISSUE THREAD

**Issue by Bogdan16** [mbebe/blomqvist#925]
Prosze wykasowac post

**Comment by Cinek77** [comment]
To trzeba mieć siano w głowie zamiast mózgu by za takie coś co jutro może zniknąć płacić za cały rok.
Brawo!!!

**Comment by mtr81** [comment]
@Bogdan16 a czytałeś regulamin? Np. punkt 6.3. jest ciekawy (pisownia oryginalna); "**Usługa Premium w żadnym wypadku nie gwarantuje dostępności do nowych bądź specialnych matariałów(...)**" Wychodzi więc na to że wpłaciłeś darowiznę...

**Comment by notoco** [comment]
Problem Bogdana polega na tym że część linków jest na serwerach CDA. Jeśli CDA usunie zawartość to przenosi automatycznie do strony o wykupie premium. Hdseans nie ma tu nic do rzeczy i nie ma na to wpływu że linki padły. To się dzieje w każdym tego typu serwisie premium. Obok każdego linka masz taki wykrzyknik - po jego kliknięciu możesz zgłosić że dany link nie działa.
