### ISSUE TITLE
Oglądaj.to

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#931]
Witam magików znalazłem sobie taki serial świat gliniarzy ale za cho... erę nie może go wyszukać okazał się, że niczego nie wyszukuje... niestety na innych wtyczkach niema tylko vizjer  kiepska jakość napisy i czasem cloudflare wskakuje. Czy da się to naprawić? Pozdrawiam

**Comment by mbebe** [comment]
@rafalmar1981 na filser sprawdz. ;-)

**Comment by rafalmar1981** [comment]
@mbebe dziękuję faktycznie jest(ale wtyczki brak:() już ogarnąłem to na oglodaj.to - by wyszukało mi "świat gliniarzy" musiałem wpisać 'gliniarzy' i wskoczyło. Jest coś dziwnego zauważyłem na wtyczce oglodaj.to jakieś przesunięcie dźwięku względem obrazu(sprawdzałem na kilku filmach - na stronie działa bez przesunięć). Pozdrawiam i dziękuję za konkretną informację na temat serialu.
