### ISSUE TITLE
Kim Cartoon is down

### ISSUE THREAD

**Issue by bjgood** [mbebe/blomqvist#935]
Hi,
Kim Cartoon is down (at least on my end).
Thank you.

**Comment by mbebe** [comment]
@bjgood updated and fixed.
Only hx streams won't work.
added captcha, and fixed crypto.
added new dependecies - js2py and pyjsparser
ver - 0.6 in my repo.

**Comment by bjgood** [comment]
Thank you mbebe for the fix.

**Comment by frankies4frankies** [comment]
Hi @mbebe live sports ( Cricfree ) doesn’t work at my end. Thanks
