### ISSUE TITLE
Wtyczka Flixclassic.pl - problem

### ISSUE THREAD

**Issue by praspp** [mbebe/blomqvist#939]
@mbebe 
Nie działa odtwarzanie treści video we wtyczce 
plugin.video.flixclassic v0.1
ATV 9.0, K19.5
Log w załączeniu.
Możesz na to spojrzeć?
[kodi.log](https://github.com/mbebe/blomqvist/files/11239474/kodi.log)

**Comment by hevet** [comment]
https://github.com/mbebe/blomqvist/issues/755#issuecomment-1106585178

**Comment by praspp** [comment]
@hevet 
Ale, że co? W tym issue jest rozwiązanie problemu? v.0.2 również nie działa. Sprawdziłem przed wysłaniem tego zgłoszenia.

**Comment by hevet** [comment]
Podałem link do tej wersji, ale nie mam subskrypcji, więc nie wiem czy działa.

**Comment by praspp** [comment]
Tak, jak pisałem wcześniej v0.2 z https://github.com/mbebe/blomqvist/issues/755#issuecomment-1106585178 również nie działa.

**Comment by praspp** [comment]
> @praspp
> Tam coś nie działa ze sprawdzaniem dostępności produktów...
> Wymień w funkcji playvid linijkę ```if int(id) in avail:``` na ```if True:``` w pliku \resources\lib\flix.py i powinno ruszyć. Ale to tylko proteza...

@mtr81 
Proteza działa. Dziękuję za ppmoc.
