### ISSUE TITLE
Segos - nie loguje do konta

### ISSUE THREAD

**Issue by RobinsonPL** [mbebe/blomqvist#94]
Pojawił się problem, mimo premium nie chce logować do konta. Strona internetowa segosa działa/ Wtyczka z repo Phantom ma ten sam problem.

**Comment by sky0002** [comment]
No fakt moja najlepsiejsza wtyczka nie funka ale się nie martw segos od Phantom ma ten sam problem. Znaczy zmiany na strone fajnie że funka strona i nie podzieliła żywota jak https://www.wykop.pl/wpis/39534539/nasze-kino-tv-padlo-zamkneli-czy-usuwac-konto-film/
Pozdrawiam i trzeba czekać na czary mary od Mbebe  bo strona jako strona dalej działa

**Comment by mbebe** [comment]
Na ten moment poprawka logowania. 
Do poprawienia jeszcze wybor zrodla. Ale to juz pozniej. ;-)
