### ISSUE TITLE
UPC brak pakietów

### ISSUE THREAD

**Issue by rafalmar1981** [mbebe/blomqvist#948]
Witam mam problem nie są widoczne kanały z pakietu "Pakiet Polsat Sport Premium" na stronie www wszystko prawidłowo działa, dodam, że pakiet "Pakiet Premium MEGA SPORT" na www również działa i na kodi też. Android Kodi 19.4 oraz win7 kodi 19.4 nie widać tego pakietu tz. kanałów z "Pakiet Polsat Sport Premium". nie ma żadnych błędów, wersja wtyczki 2.7(mbebe, mtr81). Da się coś z tym zrobić??. Pozdrawiam.

**Comment by hevet** [comment]
Zainstaluj upc2 z tego repozytorium.

**Comment by mtr81** [comment]
@rafalmar1981 było wyjaśniane tutaj -> https://github.com/mbebe/blomqvist/issues/874#issuecomment-1331586914

**Comment by isio831** [comment]
Witam nie wiem czy tylko u mnie ale we wtyczce upc2 kanaly dzialaja tylko chwile i potem obraz staje. Moze ktos sprawdzic czy ktos jeszcze tak ma.

**Comment by mtr81** [comment]
@isio831 problem zdiagnozowany i poprawione wersje wtyczek **upc2** trafiły do repozytoriów: KWP (1.4) i mojego (1.5). Z kolei w wersji 2.7 wtyczki **horizongo** 'wiszącej' tutaj -> https://github.com/mbebe/blomqvist/pull/890/commits/9b89930e19cdb081398849b000b43c96ab2508f3 należy w ustawieniach włączyć opcję 'Odświeżanie tokena - LiveTV'

**Comment by isio831** [comment]
Ok dzieki za szybko reacje. Pozdrawiam
