### ISSUE TITLE
plusfilm.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mbebe/blomqvist#95]
slucham opinii klientow

bedzie wtyczka czy nie bedzie?

**Comment by mbebe** [comment]
Dlugo nie pociagnie na polskiej domenie. :-)

**Comment by xxcriticxx** [comment]
@mbebe pozyjemy zobaczymy

**Comment by mbebe** [comment]
tu pierwsza wersja do testow.
[plugin.video.plusfilm-1.0.zip](https://github.com/mbebe/blomqvist/files/2957684/plugin.video.plusfilm-1.0.zip)

:-D

**Comment by notoco** [comment]
Bym powiedział - a gdzie moja recenzja??? Jak to możliwe że w 20 godzin machnąłeś wtyczkę?

**Comment by kodiwpigulce** [comment]
mbebe szybki jak strzała ;)

**Comment by xulek** [comment]
> Bym powiedział - a gdzie moja recenzja??? Jak to możliwe że w 20 godzin machnąłeś wtyczkę?

na szablonie takie wtyczki robi się w godzinę :P

**Comment by notoco** [comment]
No muszę się temu przyjrzeć... :)

**Comment by xxcriticxx** [comment]
@mbebe thanks

**Comment by Seico** [comment]
W kategorii seriale każdy serial posiada tylko jedną stronę z odcinkami , nie ma możliwości przejścia na kolejne strony z następnymi odcinkami , może dało by radę aby każdy sezon serialu był osobno
