### ISSUE TITLE
Mb filmy

### ISSUE THREAD

**Issue by Nazcakx** [mbebe/blomqvist#950]
Problem z wtyczką mb filmy - wtyczka wysypuję się po wybraniu ogladaj.to z danymi logowania i bez nich ten sam rezultat.

Podrzucam logi z kodi:

[https://pastebin.com/FsY12GDE](url)

**Comment by Cinek77** [comment]
A dane logowanie aktywne? Wpisane prawidłowo w oglądaj ? Jak tak to powinno działać.

**Comment by Nazcakx** [comment]
Dane wpisane prawidłowo - aktywne, sprawdzałem na przeglądarce i kilkukrotnie w ustawieniach wtyczki.
