### ISSUE TITLE
E-kino.tv

### ISSUE THREAD

**Issue by Nazcakx** [mbebe/blomqvist#951]
Wtyczka pokazuje kategorie bez podania danych logowania, po wpisaniu danych i zalogowaniu wyłącza się.

Log:
[https://pastebin.com/FsY12GDE](url)

Problem wystąpił jednocześnie z inna wtyczką(Mb filmy - moje poprzednie zgłoszenie), możliwe że przyczyna jest ta sama.
Jednak w odróżnieniu od tamtego przypadku tutaj bez logowania da się podejrzeć kategorie.

**Comment by Cinek77** [comment]
Z tego co mi wiadomo to E-kino.tv ma swoją wtyczkę. Więc jak masz swoje konto to zaloguj się na stronie pobierz wtyczkę i zaloguj kodem.

**Comment by Nazcakx** [comment]
Masz racje, przeoczyłem ten fakt. Dziękuje za informacje.
