### ISSUE TITLE
Videopenny.net

### ISSUE THREAD

**Issue by gadom92** [mbebe/blomqvist#96]
Nie wiem czy robię coś się, ale w filmach i serialach nie wyświetla się nic. Kodi 18.1

**Comment by mbebe** [comment]
Jaka masz wersje wtyczki?

**Comment by mbebe** [comment]
Masz nowa wersje wtyczki?

**Comment by kopernik1983** [comment]
strona sobie poszła , lecz nie wiadomo gdzie  :P 
![ice_screenshot_20190312-172013](https://user-images.githubusercontent.com/33724908/54217041-2af1be00-44eb-11e9-8358-a59c2f826b6e.jpeg)

**Comment by timtumturutumtum** [comment]
Chyba Ci się jedno N zapomniało

**Comment by kopernik1983** [comment]
A faktycznie :) więc sobie nie poszła jak tak. A wtyk po aktualizacji działa...

**Comment by gadom92** [comment]
a no działa, pojawiła się aktualizacja do 1.2 i wszystko elegancko się wyświetla
