### ISSUE TITLE
No streams working at plugin.video.wrestlingwatch-0.6

### ISSUE THREAD

**Issue by TitanME** [mbebe/blomqvist#966]
Both categories

- WatchWrestling.cam
- WatchProWrestling.live

are not working.

Perhaps you can fix it.

THX for your time, support and addon.

**Comment by mbebe** [comment]
watchwrestling.cam - fixed,
watchprowrestling - website dead.
update in my repo.

**Comment by TitanME** [comment]
Thank you for fix and support
