### ISSUE TITLE
tefaupe strefa abo

### ISSUE THREAD

**Issue by mbebe** [mbebe/blomqvist#97]
[plugin.video.plugin.video.tvpABON-1.0.zip](https://github.com/mbebe/blomqvist/files/2963374/plugin.video.plugin.video.tvpABON-1.0.zip)
dane w ustawieniach wtyczki
wymaga inputstream adaptive.

**Comment by kopernik1983** [comment]
Śmiga elegancko. Przydał by się podział na kategorie i jakaś szukajka :) Trochę trzeba się umordować żeby po opisach coś znaleźć co nas interesuje :)

**Comment by leonzawodowiec12** [comment]
NIE DZIAŁA:
- Boxfilm brak linków na stronie są
- Polsat News pusto 
- Nasze-Kino strona padła
-Filmlink strona padła
- Hulkstream/all events błąd dodatku 

STRONY jak byś chciał coś dodać:
rodzinnekino.com
- allbox.tv
- cda.pl
- fonline.pl
- movieneo.com
- filmosy.tv
- kino123.pl 
TV
- telewizja-internetowa.pl
- televhs.com

**Comment by notoco** [comment]
Ale czemu wstawiasz to w tym wątku który dotyczy wtyczki tefaupe strefa abo? Zauważyłeś że to nie jest Facebook gdzie wpisuje się byle co i byle gdzie?
Jak ma działać nasz-kino czy filmlink skoro strony padły?
Do cda jest wtyczka od phantoma... po co robić kolejną?
Co twój post wniósł do tematu tej wtyczki?

**Comment by xxcriticxx** [comment]
@notoco ostro! patrze `contributora` sie dorobiles

**Comment by notoco** [comment]
@xxcriticxx no a ile można. Gość wszędzie wrzuca czego mu brakuje. 
Nie zauważyłem nawet że mbebe mnie awansował.... Nieźle...
Btw. W repo kodiwpigulce jest coś co cię ucieszy. Fanfilm. Sprawdź filmy-nagrody

**Comment by xxcriticxx** [comment]
@notoco tank you

**Comment by leonzawodowiec12** [comment]
@mbabe dzięki za Polsat news i boxfilm

**Comment by mbebe** [comment]
dodane do repo. 
dodano kategorie i szukanie.
zalogujcie sie na poczatku, by pozniej nie bylo klopotow. :-)
