### ISSUE TITLE
a moze pierwsza polska wtyczka XXX

### ISSUE THREAD

**Issue by meserak86** [mbebe/blomqvist#98]
Jak wiemy wtyczek xxx jest malo, a stron z dobra iloscia linkow do pelnych filmikow tez jest malo... proponuje https://yourporn.sexy/ jest sporo materialow, i w hus reklam, wiec az sie prosi o wtyczke:D

**Comment by mbebe** [comment]
Skad Wy takie strony znajdujecie?
Bo mi to kolega podrzuca. :-)

**Comment by kodiwpigulce** [comment]
Przecież masz 2 duże wtyczki xxx wciąż działające czyli: 
1. Ultimate Whitecream
2. Adulthideout

**Comment by notoco** [comment]
To przecież nie dla niego tylko dla kolegi. 
@kodiwpigulce - ale na tych stronach kolega nie ma żadnych znajomych twarzy...

**Comment by mbebe** [comment]
Sprawdzalem na telefonie. Odtwarza sie tam wogole cos? Czy tylko torrenty sa?

**Comment by kendo999** [comment]
zapodajcie wtyczkie xxl  w 4k  chętnie taką przytule

**Comment by anon2018** [comment]
> Przecież masz 2 duże wtyczki xxx wciąż działające czyli:
> 
> 1. Ultimate Whitecream
> 2. Adulthideout
  jest jeszcze pare innych, ale slabo dzialaja albo sa to kopie ...molochy z 1 i 2maja sporo amterialow LQ
poza tym nie mamy wtyczki xxx w polskich repo, nie ma co traktowac tematu jak rozowego slonia w pokoju:D


> To przecież nie dla niego tylko dla kolegi.
> @kodiwpigulce - ale na tych stronach kolega nie ma żadnych znajomych twarzy...

ile mozna ogladac te same oczy i usta:D dobre strony ktore maja w hus reklam zasluguja na oprawienie we wtyczke:D

wystarcza karegosie szukaj trendy :D

**Comment by meserak86** [comment]
stronka ma kategorie szukaj i trendy, to by wystarczylo, miniaturki tez sa do linkow i w hus reklam przy odpalaniu linkow, ale strona dosc dobra bo ma mnustwo linkow z platnymi pelnymi filmami i wszystko online, idealny material na wtyczke jesli nie ma jakichs zabezpieczen

**Comment by kendo999** [comment]
eporner .com  w necie lata

**Comment by mbebe** [comment]
yourporn.sexy jest w UWC.

**Comment by sky0002** [comment]
Witam Panie Meserak86 . Fajnie że Pan wraca do nas, Już AKTA 2 nie jest tak straszna ;) Dla niewtajemniczonych to Pan Mazerak86 wyniósł nasze wersje pl w numeracji pod niebiosa. Owszem wiem jak to się zaczęło walka z M-TvGude  jak zaczeli szyfrować i to było OK. Ale zastanawia mnie po co resztę. Nie wierzyłeś w swoich użytkowników? Ok fajnie że wróciłeś ale od razu tak ostro hehe. Przepraszam musiałem ;) A teraz poważnie ;? Wracasz do PTW ? A może samodzielny projekt ? I sory wiem że mam strasznie durne poczucie humoru, ale to prawie rok i się cieszę :)))    A powiem prawdę że przez tą numeracje nie raz na Tobie psy wieszałem.

**Comment by meserak86** [comment]
Do ptw nie wracam bo nie ma po co, ptw osiagnelo punkt optymalnego rozwoju a reszcie teamu zachcialo se zrobic znow z calego pomyslu klike z podzialem na vip i nie vip, a moja koncepcja forum poszla w strone wareza i bede trzymal sie z dala od tego niebezpiecznego wykonania, swoj projekt tez nie mam zamiaru robic bo nie ma po co,moja walka z hujowoscia sceny polskiego kodi zaczela sie od ramica a incydent z mods nie jest za interesujacy bo sami sobie strzelili w stope miernie wykonanym skokiem na kase... Dymow zadnych nie bedzie bo nie ma z kim, po co i o co jak narazie nikt nie chce zagrodzic dostepu do wtyczek za kase wiec jest ok... Cala scena kodi stoi teraz na mbebe i wtyczkach gala bo tylko oni wtyczkami moga posunac do przodu sytuacje bo nie da sie juz nic zrobic bez programowania albo wielkich nakladow pracy wielu ludzi...dlatego ptw jest potrzebne ale nie mi

**Comment by notoco** [comment]
@meserak86 - chyba nie zauważyłeś że FanFilm tworzy nie tylko Gal, grupa osób wnoszących poprawki rozrosła się i z tego co widzę w kilku miejscach to jeszcze nie koniec. I te osoby zgromadziły się dzięki PTW - i pracują nad FanFilmem dzięki PTW. 
Nie zauważyłeś chyba że mamy takie wtyczki jak HBO GO i inne od c0d34fun, że i tam coraz więcej jest wsparcia od innych osób. 
Że osoby z PTW i powiązane z kodiwpigulce biorą na warsztat wtyczki zachodnie i dodają do nich swój wkład.
Także nie mów że tylko mbebe i gal, bo odbierasz wielu osobom ich wkład w rozwój polskiej sceny kodi.
I nie. Dodanie wtyczki porno nie jest "rozwojem" kodi...

**Comment by maxxwell87** [comment]
https://xopenload.me
http://fullxxxmovies.net
http://fullmoviesporn1.blogspot.com
https://adult-channels.com/adult-movies-online/

Strony z pełnymi filmami.
