### ISSUE TITLE
Fmovies addon not working

### ISSUE THREAD

**Issue by jferreira93-web** [mbebe/blomqvist#988]
Hi,  it gives an error on everything that is searched, i think it has to do with the change on the address.

The new address: https://fmoviesz.to/

Hope you fix it, thanks.

**Comment by Shoninzo** [comment]
I hope it gets fixed soon

**Comment by mbebe** [comment]
updated. New version in repo.

**Comment by jferreira93-web** [comment]
Thanks man!

**Comment by Shoninzo** [comment]
Awesome, thanks!
