### ISSUE TITLE
Nasze-Kino.tv

### ISSUE THREAD

**Issue by dmxcasper2** [mbebe/blomqvist#99]
Zauważyłem że nie mogę uzyskać dostępu do żadnych filmów i seriali w wtycze Nasze-Kino.tv? Sprawdziłem z kilku różnych boxas androidach i dwóch różnych IP addresses i nic. Pokazuje mi się błąd "nasze-kino.tv error". Sprawdziłem odpalanie tej wtyczki z Łodzi 17.6 i 18. Ten sam błąd wyskakuje. Czy to sprawa strony nasze-kino.tv?

**Comment by dmxcasper2** [comment]
Chyba sobie sam odpowiedziałem na pytanie.

https://www.wykop.pl/wpis/39534539/nasze-kino-tv-padlo-zamkneli-czy-usuwac-konto-film/

**Comment by xxcriticxx** [comment]
@notoco z nasz taka ver Łodzi 17.6 i 18?

**Comment by wisiann** [comment]
Łodz torpedowa?!
