### ISSUE TITLE
Request Live TV addon

### ISSUE THREAD

**Issue by jferreira93-web** [mbebe/blomqvist#992]
Can an addon be made from this site? 

https://tv0800.com/

Thanks.

**Comment by mbebe** [comment]
Streams have clearkeys encryption, and it's not possibly to play this in KODI. Maybe soon.

**Comment by jferreira93-web** [comment]
Ok, thanks.

**Comment by jferreira93-web** [comment]
And this one?

https://wiziwig1.org/
