### ISSUE TITLE
*Request*, Fmovies addon with subtitles?

### ISSUE THREAD

**Issue by jferreira93-web** [mbebe/blomqvist#993]
Is it possible to add the subtitles that are on the fmovies website to the addon as well? (similiar to what you did with lookmovie)

Sure, i can download the subtitles myself manually, sure, just by searching on the player "movie title (year)" or "tv show title s00e00" using this method and it works.

But i'm asking this because:

1- It would help some people who don't know much about kodi, so an autosub would help those people.
2- The subs on the site are in sync like 95% of the time, so would be great if they are available. (like you use to have on older versions of the addon as well or the recent lookmovie)
3- Lookmovie has this function but most of those aren't in sync (websites fault ofcourse) specially tvshows.

Cheers.

If you could do it i would be very glad, if you can't it's all good anyways. I know i'm making to many requests, sorry about that lol, you've been very helpful

Thanks for all the work you put on these, your addons are the most stable. Thanks

**Comment by mbebe** [comment]
fmovies and lookmovie updates are available in repo.
;-)
