### ISSUE TITLE
Lookmovie not working

### ISSUE THREAD

**Issue by jferreira93-web** [mbebe/blomqvist#994]
All content gives an error when i try to play anything and won't play

The content appers listed when searched but won't open.

Please fix it. 

Thanks!

**Comment by kolekan** [comment]
I'm sure that's the reason
![tempsnip](https://github.com/mbebe/blomqvist/assets/35860760/3db81564-b5fd-44bb-bec2-59a0d4f1f73b)

**Comment by mbebe** [comment]
fmovies and lookmovie updates are available in repo.
;-)

**Comment by jferreira93-web** [comment]
Thanks man!

Fmovies is all good.

Lookmovies asks for a captcha for movies and works after completing it but the tvshows don't work.

I try to open the folder of any tv shows at it gives an error and does not open.

Fix it with your talent if you can :)

These f... who own the websites put a lot of protections lol

**Comment by mbebe** [comment]
Ok, there's another captcha. I will fix it soon.

**Comment by jferreira93-web** [comment]
Thanks!

There's another problem, Categories don't open after you click on the genres folders, on movies and tvshows, gives an error.

The rest i tested and it's fine!

Thanks again.

**Comment by mbebe** [comment]
ok. Fixed.

**Comment by jferreira93-web** [comment]
Thanks ;)
