### ISSUE TITLE
TVN24 nie działa

### ISSUE THREAD

**Issue by boe666** [mbebe/blomqvist#995]
Nie działa LIVE dla tego kanału. Generalnie po kliknięciu nic się nie dzieje. Jakiś błąd ?

**Comment by mtr81** [comment]
Jakiej wtyczki to dotyczy?

**Comment by boe666** [comment]
TVN24.pl.
Fakty TVN działają, Live Audio - po  zalogowaniu - też działa, a TVN24.pl nie działa w ogóle. Żadnego komunikatu. LibreELEC 11.0.3 na RPI4.

**Comment by mtr81** [comment]
Ta pozycja w menu miała przenosić na główną stronę. To nie jest przekaz live video.

**Comment by boe666** [comment]
Ok. Rozumiem. A będzie kiedyś możliwość żeby TVN24 działało ? Pytam, bo działa tvn24 Audio.

**Comment by mtr81** [comment]
TVN 24 jest dostępny w TVN24 GO dla subskrybentów, a tego serwisu wtyczka nie obejmuje.

**Comment by boe666** [comment]
ok, rozumiem bo przez stronkę mogę oglądać TVN24. Myślałem że skoro działa AUDIO TVN24 to będzie też z VIDEO... Są plany żeby była wtyczka do TVN24 GO ?

**Comment by mtr81** [comment]
Jak zależy ci na TVN24 na żywo, to sprawdź tą wersję. Nie mam co prawda dostępu do tvn24go, ale dodałem ten kanał w zakładce liveAudio. Jak masz aktywną subskrypcję, to jest cień szansy, że to zadziała. Tyle mogę zrobić bez logowania...
[plugin.video.tvn24pl_test.zip](https://github.com/mbebe/blomqvist/files/12838902/plugin.video.tvn24pl_test.zip)

**Comment by boe666** [comment]
Tzn nie wiem jak do tego wejść. W zakłądce Live Audio mam tylko TVN24 i TVN24BIS - oba streamują tylko audio. Zalogowałem się na Live Audio, działa to tak że muszę wpisać kod na stronie tvn24.pl który generuje wtyczka - i to działa (audio). Nigdzie nie znalazłem możliwości wejścia na tvn24 ... gdzie mam szukać ? Chyba że mam się gdzieś zalogować w tej wtyczce (login hasło z tvn24go).

**Comment by mtr81** [comment]
Musisz wgrać z zipa wtyczkę, którą zamieściłem powyżej (z zipa - nie z repo) i w zakładce live audio będziesz miał też TVN24, TVN24 Bis oraz Espreso.TV

**Comment by boe666** [comment]
wgrałem wtyczkę z ZIPa a następnie z repozytorium mbebe wtyczkę wideo (najpierw odinstalwałem tą co byłą a potem zainstalowałem). Nie mam w live video espreso.tv a jedynie tvn24 i tvn24bis. Wchodzę na tvn24, loguję się kodem i działa ale audio - czyli tak jak było.

**Comment by mtr81** [comment]
Żle robisz... Masz wgrać tylko i wyłącznie wtyczkę z ZIP-a. Z repo już po tym nic nie wgrywasz, bo nadpisujesz w ten sposób tą poprawkę z ZIP-a

**Comment by boe666** [comment]
ok. Jest na liście. ESPRESO.TV działa, ale TVN24 i BIS nie działa (pozycje AUDIO działają) - kręci się kółeczko ale po chwili jest powrót do menu.

**Comment by boe666** [comment]
Może trzeba dorzucić takie logowanie jak jest przy audio - które podaje kod.

**Comment by mtr81** [comment]
Nie, bo logowanie jest jedno. Jak masz na koncie dostęp do TVN24 video żadne inne logowanie nie jest potrzebne. Pewnie coś jeszcze trzeba dorzucić typu tokeny, czy nagłówki..., ale bez dostępu nie jestem w stanie tego stwierdzić.

**Comment by boe666** [comment]
Może Ci wyślę mailem login i hasło (potem mogę przecież zmienić).

**Comment by mtr81** [comment]
OK. mtr81@proton.me

**Comment by boe666** [comment]
Nie znaleziono adresu..... na pewno dobry email podales?

niedz., 8 paź 2023, 00:00 użytkownik mtr81 ***@***.***>
napisał:

**Comment by mtr81** [comment]
Dodałem TVN24 i TVN24 BiS na żywo oraz 7 dniowe archiwum programów oparte na EPG - dostępne jedynie dla użytkowników posiadających subskrypcję TVN24go
[plugin.video.tvn24pl-1.9.zip](https://github.com/mbebe/blomqvist/files/12840316/plugin.video.tvn24pl-1.9.zip)

**Comment by boe666** [comment]
Dzięki za uruchomienie zarówno LIVE TVN24 jak i archiwum. Wszystko działa wyśmienicie (jeśli ktoś ma aktywną subskrypcję TVN24go). Pozdrawiam. wszystkich,

**Comment by Dannniello** [comment]
> Dodałem TVN24 i TVN24 BiS na żywo oraz 7 dniowe archiwum programów oparte na EPG - dostępne jedynie dla użytkowników posiadających subskrypcję TVN24go [plugin.video.tvn24pl-1.9.zip](https://github.com/mbebe/blomqvist/files/12840316/plugin.video.tvn24pl-1.9.zip)

Mega dzięki za ten dodatek! Już traciłem nadzieję, że znajdę wtyczkę i zastanawiałem się na anulowaniu subskrypcji (dostęp przez stronę tvn24.pl jest dość upierdliwy).

BTW, dlaczego plugin.video.tvn24pl-1.9.zip nie jest zintegrowany z repo blomqvist (tam dalej jest wersja 1.8 bez obsługi wideo TVN24 i TVN24 BiS)?

**Comment by boe666** [comment]
Cześć, zainstalowałem w końcu wtyczkę. Na Żywo wszystko ok, ale archiwum
tvn24 nie ma - jest błąd - każe sprawdzić logi podczas kliknięcia na
konkretny dzień. Nie wiem gdzie tych logów szukać :)

sob., 22 lut 2025 o 21:59 Dannniello ***@***.***> napisał(a):

**Comment by boe666** [comment]
Wcześniejszy mail nieaktualny - pomyliłem stary wątek z nowym. Za
zamieszanie przepraszam.

niedz., 23 lut 2025 o 10:14 Marcin Kapski ***@***.***> napisał(a):
